### ISSUE TITLE
Failed to send attachments to provider when using thrift RPC protocol.

### ISSUE THREAD

**Issue by cderlearner** [apache/incubator-dubbo#1048]
thrift协议发送消息，编码RpcInvocation的attachments对象，只取interface的value值，其他key/value没有取，导致attachments对象有其他值无法从消费端发送到生产端。

**Comment by chickenlj** [comment]
#1095

**Comment by diecui1202** [comment]
@lovepoem please consider this in native-thrift protocol. Thanks

**Comment by lovepoem** [comment]
hi, I will close it now,  we discuss it in https://github.com/dubbo/dubbo-rpc-native-thrift/issues/2
