### ISSUE TITLE
dispatcher:execution

### ISSUE THREAD

**Issue by DoubleSmile** [apache/incubator-dubbo#1089]
Dubbo官方的说法是：dispatcher配置为execution时候 只请求消息派发到线程池，不含响应，响应和其它连接断开事件，心跳等消息，直接在IO线程上执行。
但是我在源码中却没有发现其处理逻辑，相反其与all几乎一样，除了在默认的executor找不到时候会去找另外executor和捕捉了异常。

所以具体的execution到底是怎么生效的呢

**Comment by chickenlj** [comment]
Yes, i think your are right, it's the same with `all dispatcher`, we may fix the execution dispatcher policy to meet the description in docs in the next version.

**Comment by chickenlj** [comment]
We will track this issue with PR #1449.  Remove from milestone and close this issue.
