### ISSUE TITLE
When i configure two beans for async callback, i got a reflection exception.

### ISSUE THREAD

**Issue by yanhao57** [apache/incubator-dubbo#1090]
问题描述：模块A有两个服务a1、a2需要异步调用模块B中两个服务b1、b2，因此在模块A中定义了两个bean，每个bean中定义一个onReturn方法来处理异步回调，结果只有1个bean的onReturn生效，另一个在回调时报反射异常。这种只能定义一个bean来处理回调的设置是故意为之还是隐藏的bug呢？？

**Comment by chickenlj** [comment]
Can you post the detailed exception and your configuration here?  I can not reproduce this problem.

**Comment by diecui1202** [comment]
Feel free to reopen if necessary.
