### ISSUE TITLE
dubbo2.5.3注解方式无效

### ISSUE THREAD

**Issue by xuzunyuan** [apache/incubator-dubbo#117]
参照了dubbo用户指南，按照上面说的做了注解配置。
本想采用自动扫描，减少开发的工作量，但是无效。

有配置注解成功的吗？讲解一下吧

**Comment by love61v** [comment]
用@Autowired注解

**Comment by enson16855** [comment]
@Autowired
	private DemoService demoService;
	
	public void say() {
		String hello = demoService.sayHello("world"); // 执行远程方法

		System.out.println(hello); // 显示调用结果
	}

还是一样出现：
Exception in thread "main" java.lang.NullPointerException
	at com.alibaba.dubbo.demo.Say.say(Say.java:11)

**Comment by enson16855** [comment]
@Reference(version="1.0.0")
	private DemoService demoService;
	
	public void say() {
		String hello = demoService.sayHello("world"); // 执行远程方法

		System.out.println(hello); // 显示调用结果
	}

这种方式也出现了空指针

**Comment by usc** [comment]
spring配置文件需要加上 <context:component-scan base-package="xxx" />
dubbo consumer 配置文件 dubbo:reference 正常配置，

**Comment by love61v** [comment]
1<context:component-scan base-package="xxx" />你配置了；如果能正常扫到@service就能注入； 
注意:  @service是 dubbo包中的@service不是spring的哟、
2.你不能注入报空指针，那么你可用原始的<bean id="demoServiceImpl" class="xxxx"/> 这种方法测试还报空否咯， 不然就是@service生效
3.祝好运

**Comment by love61v** [comment]
context:component-scan扫包
原始的:   <bean id="demoServiceImpl" class=""/>   上面这2行都掉了

**Comment by love61v** [comment]
bean id="demoServiceImpl"  class="xxxxxx"

**Comment by enson16855** [comment]
XML方式没有任何问题，@Service也没有问题，在dubbo控制台可以看到接口注册生效了，但就是在@Reference(version="1.0.0") 这边，注入不进来，拿到的是null

**Comment by enson16855** [comment]
因为项目之前使用的是annotation的方式 如果切换回XML方式 会比较麻烦，所以想继续使用annotation的方式

**Comment by Benjamin2086** [comment]
@enson16855 我也遇到相同的问题，请问解决了吗

**Comment by zuochi** [comment]
我成功了，出现空指针的原因是：spring mvc扫描的时候根本无法识别@Reference，同一方面，dubbo的扫描也无法识别Spring @Controller,所以两个扫描的顺序要排列好，如果先扫了controller，这时候把控制器都实例化好了，再扫dubbo的服务，就会出现空指针。

下面是我成功的代码：

<mvc:annotation-driven />

<dubbo:annotation package="XXX.XXX.XXX.controller" />
<context:component-scan base-package="XXX.XXX.XXX.controller"/>

祝成功

**Comment by justein** [comment]
你们都集成了Spring3了么？还有，每个服务的数据源怎么配置？

**Comment by enson16855** [comment]
@zuochi  成功的代码呢？分享一下 好不

**Comment by zuochi** [comment]
@enson16855 分享了，就是这么简单。。。搞了一个早上，尼玛

**Comment by zuochi** [comment]
@justein 我集成了4.x的

**Comment by justein** [comment]
@zuochi 我刚集成了3.2，现在想搞一个实际的业务发布成服务试一试

**Comment by enson16855** [comment]
@justein  我也是集成4.x

**Comment by justein** [comment]
@enson16855 就修改了一下dubbo的pom.xml。主要是我们上个项目用的S3，所以就集成到3了。

**Comment by love61v** [comment]
https://github.com/love61v/dubbo-demo    我这有个  小demo,     doc下有小说明，  如有需要可小看，请拍砖

**Comment by jiezhiz** [comment]
1. consumer spring xml中配置: 
<context:component-scan base-package="xx">
		<context:exclude-filter type="annotation" expression="org.springframework.stereotype.Controller"/>
	</context:component-scan>

2. consumer springmvc xml中配置: 
<context:component-scan base-package="xx" use-default-filters="false">
		<context:include-filter type="annotation" expression="org.springframework.stereotype.Controller"/>
	</context:component-scan>

3. consumer dubbo xml中配置: 

	<dubbo:annotation package="xx" />

4. provider dubbo xml 中配置
<dubbo:annotation package="xx" />

我用的spring4, dubbo2.5.3, 按照上述配置可实现dubbo annotation.

**Comment by jiezhiz** [comment]
1. consumer spring xml中配置: 
<context:component-scan base-package="xx">
		<context:exclude-filter type="annotation" expression="org.springframework.stereotype.Controller"/>
	</context:component-scan>
2. consumer springmvc xml中配置: 
<context:component-scan base-package="xx" use-default-filters="false">
		<context:include-filter type="annotation" expression="org.springframework.stereotype.Controller"/>
	</context:component-scan>
3. consumer dubbo xml中配置: 
	<dubbo:annotation package="xx" />
4. provider dubbo xml 中配置
<dubbo:annotation package="xx" />

我用的spring4, dubbo2.5.3, 按照上述配置可实现dubbo annotation.

**Comment by wangjingfei** [comment]
谢谢提供workaround方案

**Comment by zhilongxia** [comment]
@Referenceh和@Autowired均需要在spring mvc的DispatcherServlet配置中显式配置dubbo consumer的配置.如/WEB-INF/applicationContext-dubbo-consumer.xml 否则在Controller中服务报NullPointException

<dubbo:annotation/>
<context:component-scan base-package="net.aimeizi.dubbo.controller">
    <context:include-filter type="annotation" expression="com.alibaba.dubbo.config.annotation.Reference"/>
</context:component-scan>

**Comment by genghaizhou** [comment]
用 @Reference @Service 和注解
先启动 consumer 再启动 provider, 调用就会空指针，但是反过来却正常
按照 dubbo + zk 的 notify 机制 应该是可以更新的
实际上： consumer 确实收到 zk notify 了，但还是调用 @Reference 还是 null
感觉上 notify 应该没有更新 Reference 的 remote serice
还有遇到这个问题了吗？
。。求解决

**Comment by wangdm0824** [comment]
@love61v  写的很垃圾，也好意思拿出来！！！

**Comment by zouchunhui** [comment]
备注一下。

**Comment by chenjinying1988** [comment]
检查两个地方试试吧：

**Comment by ralf0131** [comment]
The latest Dubbo should support annotation configuration very well, please checkout this latest code! I am closing this issue.

**Comment by smartwjw** [comment]
@genghaizhou 我们碰到了相同问题，provider 先启动没有问题，后启动旧 null.

```xml
        <dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>dubbo-spring-boot-starter</artifactId>
            <version>0.2.0</version>
        </dependency>
```

dubbo version 2.6.2.

**Comment by smartwjw** [comment]
配置 ` dubbo.consumer.check=false` 解决问题

**Comment by TrillStones** [comment]
如果运行在sping-boot中，并且使用yml配置文件，则这个路径要能扫到你的“@Reference”注解。
![image](https://user-images.githubusercontent.com/32927876/54341271-708dc280-4674-11e9-9b60-54acf2af238e.png)

**Comment by voyagertanyao** [comment]
@wangjunwei87  方案可行
