### ISSUE TITLE
How to use ACL authorisation mechanism of Zookeeper on dubbo

### ISSUE THREAD

**Issue by coolspring1293** [apache/incubator-dubbo#1179]
- For servers exposed on the public network, using registry centre of `zookeeper` without fitters, it exists the security issues that `zookeeper` can be registered by any sever. 
- Actually, third party agency also discovered the vulnerability via IP and port scanning. Using `iptable` can not be approved.  
- ACL authorisation mechanism of `zookeeper` (username: passwd) can deal with it, but I have no idea about how to use it on `dubbo`.
- I have searched on Google and tried it (read source code and tried to make it), I got nothing useful and did not complete it. How can I deal with this issue by username and password? Thx~

***

- References:

  * [掃文資訊：分佈式服務Dubbo+Zookeeper安全認證](https://hk.saowen.com/a/b6faf5cac136f036726aef3dae5608eb1c90d5b201916cdeec7a7897f50ed07a)
  * [知乎：Zookeeper+dubbo，怎么设置安全认证？](https://www.zhihu.com/question/45720203/answer/140188334)

**Comment by 89zhulin** [comment]
目前无解 只能防火墙了

**Comment by chickenlj** [comment]
Currently, dubbo support `digest` ACL provided by zookeeper. 
And you must use `curator`, because `zkclient` don't support zookeeper's ACL.

**Comment by 89zhulin** [comment]
@chickenlj  尝试一下

**Comment by coolspring1293** [comment]
See [zdubbo](http://www.ztesoft.com/cn/content/details_281_2775.html) maybe help.

**Comment by carryxyh** [comment]
Hi,@coolspring1293 
Is there still sth about this issue? Why reopen it.

**Comment by carryxyh** [comment]
Close it now.
no more feedback

&READY-TO-CLOSE&
