### ISSUE TITLE
消费者端能支持node吗？

### ISSUE THREAD

**Issue by honchy** [apache/incubator-dubbo#118]
消费者端能支持node吗？

**Comment by kazaff** [comment]
貌似群里有人正在完成node版的dubbo客户端，并且考虑开源~

**Comment by kazaff** [comment]
貌似群里有人正在完成node版的dubbo客户端，并且考虑开源~

**Comment by kazaff** [comment]
貌似群里有人正在完成node版的dubbo客户端，并且考虑开源~

**Comment by wuwen5** [comment]
jsonrpc
https://github.com/ofpay/dubbo-rpc-jsonrpc

node-client
https://github.com/ofpay/dubbo-node-client

python-client
https://github.com/ofpay/dubbo-client-py

**Comment by fantaxy025025** [comment]
怎么没有人写ruby的client呢

**Comment by ralf0131** [comment]
Please check this awesome project: https://github.com/dubbo/dubbo2.js
