### ISSUE TITLE
@Reference can't specify protocol？

### ISSUE THREAD

**Issue by artoruis** [apache/incubator-dubbo#1182]
xml 可以指定，但是 annotation 无法指定
 like [#615](https://github.com/alibaba/dubbo/issues/615)

**Comment by chickenlj** [comment]
Currently, we don't support specify protocol on `@Reference`.
I recommend you use different group or version  as a workaround if you have the same service exported on multiple protocols.

We'll try to improve the annotation configuration continuously.

**Comment by ralf0131** [comment]
Hi, please check the latest code, it is already supported.
