### ISSUE TITLE
请问提供方与消费方与注册中的问题

### ISSUE THREAD

**Issue by ksh033** [apache/incubator-dubbo#119]
1.我现在有个项目即是消费方也是提供方这样可以吗，还是提供方需要单独剥离。如果放一起是不是也只能存在一个dubbo:registry节点
2.我通过maven做模块集成的时候是不是项目中只能存在一个dubbo:registry配置节点

**Comment by vistier** [comment]
1. 如果放在一起干还要用这个了...直接使用不就可以了
2.正常一个提供方对应一个节点
3.dubbo:registry可以有多个节点

**Comment by ksh033** [comment]
因为现在的项目正好有提供给别人的服务也有引用别人的服务，所以想确认一下是否可以放一起注册中心是否只能使用同一个。
例如a.war，b.war包，如果a.war提供也服务，同时还引用了b.war的服务，这种时候是a.war，如果只有一个注册中心，是不是消费方与提供方都是同一个注册中心，还是可以分别使用不同的注册中心。

**Comment by ksh033** [comment]
因为现在的项目正好有提供给别人的服务也有引用别人的服务，所以想确认一下是否可以放一起注册中心是否只能使用同一个。
例如a.war，b.war包，如果a.war提供也服务，同时还引用了b.war的服务，这种时候是a.war，如果只有一个注册中心，是不是消费方与提供方都是同一个注册中心，还是可以分别使用不同的注册中心。

**Comment by ksh033** [comment]
因为现在的项目正好有提供给别人的服务也有引用别人的服务，所以想确认一下是否可以放一起注册中心是否只能使用同一个。
例如a.war，b.war包，如果a.war提供也服务，同时还引用了b.war的服务，这种时候是a.war，如果只有一个注册中心，是不是消费方与提供方都是同一个注册中心，还是可以分别使用不同的注册中心。

**Comment by ksh033** [comment]
因为现在的项目正好有提供给别人的服务也有引用别人的服务，所以想确认一下是否可以放一起注册中心是否只能使用同一个。
例如a.war，b.war包，如果a.war提供也服务，同时还引用了b.war的服务，这种时候是a.war，如果只有一个注册中心，是不是消费方与提供方都是同一个注册中心，还是可以分别使用不同的注册中心。

**Comment by zhiying8710** [comment]
a, b两个war包提供的服务可以不往同一个注册中心注册, 但是如果a引用了b的服务, 那a引用的时候的注册中心就要写b服务的注册中心

**Comment by javahongxi** [comment]
你提供的服务依赖于别人的服务，必须放一起，这还用怀疑？注册中心当然可以有多个，不过难道一个不够用吗，可以把注册中心做好，只提供一个唯一的域名地址

**Comment by ralf0131** [comment]
Yes, you can choose single registry, or you can choose multiple registries. It is up to you to decide.
