### ISSUE TITLE
A method level cache implementation for dubbo.

### ISSUE THREAD

**Issue by skykong1981** [apache/incubator-dubbo#1227]
2016年基于当当版dubbox 2.8.4版本开发了接口方法级的缓存。下面是服务提供方Provider的配置

```
<dubbo:cacheServer id="userCache" protocol="memcached" address="192.168.1.101:11211" prefix="user_" user="cacheuser" password="cachepasswd" timeout="3600"/>
<dubbo:cacheServer id="accountCache" protocol="redis" address="192.168.1.102:6379" prefix="act_" user="cacheuser" password="cachepasswd" timeout="3600"/>
<!-- prefix=为统一的key前缀，timeout默认的缓存失效时间 -->
 <dubbo:cache service="com.xxx.qo.UserQo" server="userCache">
    <dubbo:buffer key="user_{openid}_{shopid}" method="getUserByOpenid" command="get" timeout="600"/>
    <dubbo:buffer key="userOpenid_{userid}_{shopid}" method="getUserOpenid" command="get"/>
 </dubbo:cache>
 <dubbo:cache service="com.xxx.aggregate.UserAggregate" server="userCache">
    <dubbo:buffer key="user_{userid}" method="getUser" command="get" timeout="600"/>
    <dubbo:buffer key="user_{user.userid}" method="updateUser" command="delete"/>
    <dubbo:buffer key="user_{userid}" method="upgradeUserFlag" command="delete"/>
    <dubbo:buffer key="userShop_{userid}_{shopid}" method="getUserShop" command="get" timeout="600"/>
    <dubbo:buffer key="userShop_{userid}_{shopid}" method="updateQrcode" command="delete"/>
    <dubbo:buffer key="userShop_{userid}_{shopid}" method="updateFollow" command="delete"/>  
    <dubbo:buffer key="user_{userid},account_{userid}" method="updateBalance" command="delete"/>   <!--支持同时失效多个缓存对象--> 	
 </dubbo:cache>
```

服务消费方Consumer不需任何改动。

上述xml配置，在Provider启动后会写入Zookeeper，写在service的node节点里，Consumer启动会获取依赖服务的信息。
当Consumer调用Provider的服务时，Consumer判断该方法是否配置了缓存，如果配置了，会直接去缓存去get，如果缓存没有，再调用Provider，同时把结果放在缓存中。

Consumer在invoke方法时判断该method是否配置了缓存，入配置了get，会先去cacheServer查询，存在，直接返回，不存在调用Provider，得到结果put到缓存，并返回；入配置了delete，先去删除cacheServer的缓存对象，再调用Provider
。

缓存对于高并发的应用系统很重要，在使用“微服务”的架构中，缓存是做在Provider侧，只有Provider的开发者熟悉其业务逻辑，对什么对象进行缓存。缓存的使用流程是 Consumer -> Provider -> CacheServer。
Consumer -> Provider -> CacheServer，多了一个环节，多一个环节就多了一个环节的网络开销，同时无谓的增加了Provider的访问压力。

二次开发代码侵入性强，使用侵入性小，使用时仅在Provider侧配置xml。

“方法级”缓存不能cover所有的缓存应用场景，需要搭配“业务级”缓存，一起完成缓存功能。
在“微服务”架构中，如果服务的粒度过大，方法级缓存会使用的比较吃力。

17年9月份很高兴看到dubbo重启维护。现在把这个思路抛出来，希望能看到大家的评论。

**Comment by chickenlj** [comment]
Good idea, i have some basic questions here:
* Will all the configuration registered to registry and passed to consumer? 
* Caches only at consumer and no caches at provider?

**Comment by chickenlj** [comment]
Would you like to make a contribution and make a pull request?

**Comment by skykong1981** [comment]
@chickenlj 1，缓存配置注册到zookeeper(目前仅支持zookeeper作为注册中心)，Consumer启动时获取缓存配置信息，运行过程中如Provider有变更，会同步到Consumer。
2，缓存的get，delete操作都是在Consumer端，Provider仅提供配置。

**Comment by chickenlj** [comment]
@skykong1981  Can you give a typical provider url example when use the above cache configuration?

**Comment by skykong1981** [comment]
@chickenlj 不知道你说的typical provider url是什么意思，是在zookeeper里面的 /dubbo/com.xxx.TestService/providers 里展示的节点url？我没有把缓存配置写在这个url里，而是写在了这个node的data里。

**Comment by chickenlj** [comment]
@skykong1981 Thanks for your kindness and sorry for the late reply. 
I think we'd better discuss here, so people in community can join us, i think your work is of great value. You send a PR, and we can discuss the implementation details.

**Comment by skykong1981** [comment]
@chickenlj I had created a PR, pls check it. Thanks.

**Comment by diecui1202** [comment]
@skykong1981 I have reviewed your PR, please submit a new PR if necessary. Thanks.
