### ISSUE TITLE
suggest add the annotation @override to the interface method

### ISSUE THREAD

**Issue by akun2014** [apache/incubator-dubbo#1229]
for example:
com.alibaba.dubbo.container.log4j.Log4jContainer
most of class not add the @override annotation.

**Comment by ralf0131** [comment]
Hi, would you mind sending a pull request? Thanks!

**Comment by chickenlj** [comment]
I have noticed that the PR #1239 being closed? Can you create a new one please?

**Comment by chickenlj** [comment]
Merged
