### ISSUE TITLE
linux 运行dubbo-provider-assembly 脚本启动出错

### ISSUE THREAD

**Issue by kucoll** [apache/incubator-dubbo#123]
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 1879048192 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /opt/dubbo-provider/scrm-user-provider/hs_err_pid12621.log

**Comment by kucoll** [comment]
这是linux交换内存不够吗？ 为什么提示要1.8G的交换内存？

**Comment by ralf0131** [comment]
Please check your machine's physical memory.
