### ISSUE TITLE
Dubbo Spring Boot 1.0.0-SNAPSHOT will be released

### ISSUE THREAD

**Issue by mercyblitz** [apache/incubator-dubbo#1251]
It includes following modules :

* [dubbo-spring-boot-parent](https://github.com/dubbo/dubbo-spring-boot-project#dubbo-spring-boot-parent)
* [dubbo-spring-boot-autoconfigure](https://github.com/dubbo/dubbo-spring-boot-project#dubbo-spring-boot-autoconfigure)
* [dubbo-spring-boot-actuator](https://github.com/dubbo/dubbo-spring-boot-project#dubbo-spring-boot-actuator)
* [dubbo-spring-boot-starter](https://github.com/dubbo/dubbo-spring-boot-project#dubbo-spring-boot-starter)
* [dubbo-spring-boot-samples](https://github.com/dubbo/dubbo-spring-boot-project#dubbo-spring-boot-samples)

More details : https://github.com/dubbo/dubbo-spring-boot-project

If you like it , please do *star* it , thank you!

**Comment by ralf0131** [comment]
Awesome work!

**Comment by leyou240** [comment]
Good job!

**Comment by lovepoem** [comment]
now 1.0.0 have been released
