### ISSUE TITLE
Upgrade tomcat version to 8.5.x

### ISSUE THREAD

**Issue by ralf0131** [apache/incubator-dubbo#1254]
The current dependency to tomcat is 8.0.x, which has been announced as [End of Life](http://tomcat.apache.org/tomcat-80-eol.html) on 30 June 2018.

So we should upgrade tomcat to 8.5.x.

**Comment by chickenlj** [comment]
Can 8.5.x works on JDK 1.7 or lower?

**Comment by mercyblitz** [comment]
It's not a question, Clients can choose which version that they want, Dubbo did not depend on Tomcat API

**Comment by ralf0131** [comment]
8.5.x is designed to replace 8.0.x, so it is compatible in terms of both running on Java 7+.

**Comment by ralf0131** [comment]
I think this issue has low priority, let's do it in the next release.
