### ISSUE TITLE
Lack of UT for ConsistentHashLoadBalance in LoadBalanceTest.

### ISSUE THREAD

**Issue by dchack** [apache/incubator-dubbo#1262]
com.alibaba.dubbo.rpc.cluster.loadbalance.LoadBalanceTest中缺少ConsistentHashLoadBalance的测试用例。

**Comment by dchack** [comment]
@chickenlj can you review this [PR](https://github.com/alibaba/dubbo/pull/1267)

**Comment by chickenlj** [comment]
Close this one, track with #1267
