### ISSUE TITLE
dubbo admin前端路径bug

### ISSUE THREAD

**Issue by dengly** [apache/incubator-dubbo#128]
最近使用dubbo admin，发现sysinfo下有不少bug，目前发现都是路径有问题

**Comment by zhangmengpl** [comment]
如果你使用tomcat  部署在ROOT目录下 就好了

**Comment by lyjohn** [comment]
自己改下吧，都不见更新了... $rootContextPath.getURI("")

**Comment by justein** [comment]
目前admin只能放在tomcat的Root下执行，admin用的WebX，路径都是从后台过来的，文档里有说将admin部署在ROOT下的。路径问题确实存在

**Comment by ralf0131** [comment]
The dubbo admin is being refactored to a spring-boot application. Stay tuned!

**Comment by ralf0131** [comment]
Dubbo admin has been refactored to a spring-boot application, please check again!
