### ISSUE TITLE
dubbo.application.qosEnable=false don't work

### ISSUE THREAD

**Issue by ayhero** [apache/incubator-dubbo#1280]
dubbo版本：2.9.0，2.6.0
配置:
>
        dubbo.application.qosPort=33333
        dubbo.application.qosEnable=false
        dubbo.application.qosAcceptForeignIp=false
使用注解注入spring

> 
	@Bean
	public ApplicationConfig requestApplicationConfig() {
		ApplicationConfig applicationConfig = dubboProperties.getApplication();
		if (applicationConfig == null) {
			applicationConfig = new ApplicationConfig();
		}
		return applicationConfig;
        }
debug显示注入成功
![run-properties](https://user-images.githubusercontent.com/4559497/35424816-2d846c32-0291-11e8-8243-b5890bba3d6a.png)

本机IP：192.168.162.30
内网远程IP：192.168.4.214
远程机器Telnet本机结果
![telnet](https://user-images.githubusercontent.com/4559497/35424851-66ef2746-0291-11e8-8705-c48c190cd204.png)
另外，jvm参数加入了qos相关，依然不起作用
![telnet-setting](https://user-images.githubusercontent.com/4559497/35424887-c1d013be-0291-11e8-8c36-c4acf4cc87fd.png)

**Comment by chickenlj** [comment]
dubbo.application.qos.port=33333
dubbo.application.qos.enable=true/false

Please use the demo configuration above, i will update the docs later.

**Comment by ayhero** [comment]
@chickenlj thx ,but this issue is here,I find the protocol configuration in the docs and see "telnet"
![qq 20180130171413](https://user-images.githubusercontent.com/4559497/35558027-e72409a6-05e1-11e8-9173-cf31624c1332.png)
then I change my setting to below pic
![qq 20180130171807](https://user-images.githubusercontent.com/4559497/35558083-0ed1211e-05e2-11e8-8745-58bd18915eb0.png)
but,it just not working like what I configure,so maybe anything I am missing?
![qq 20180130172539](https://user-images.githubusercontent.com/4559497/35558534-422418f4-05e3-11e8-9513-c4556d2df458.png)

I want to shutdown all telnet in the prod environment,so thx~

**Comment by ayhero** [comment]
@chickenlj and something else
in version 2.5.9,use confs  
`dubbo.application.qos.port=33333
dubbo.application.qos.enable=true`
I still can not open the qos
![qq 20180130174435](https://user-images.githubusercontent.com/4559497/35559594-0f464472-05e6-11e8-9373-2b5d5d0f5946.png)
however,the token of service can reject unsafe invoking,so this is my only solution:)

**Comment by chickenlj** [comment]
The `old telnet` can't be closed, though the `telnet` property is designed for user to configure, it is never used. 

I am not sure whether we will continue working on `old telnet`, because we plan to replace it with the `qos` module.

**Comment by chickenlj** [comment]
> in version 2.5.9,use confs
> dubbo.application.qos.port=33333 dubbo.application.qos.enable=true
> I still can not open the qos

Where do you configure these properties?

**Comment by ralf0131** [comment]
As @chickenlj suggested, please use the following properties to disable qos:

```
dubbo.application.qos.port=33333
dubbo.application.qos.enable=true/false
```

I am closing this issue now.
