### ISSUE TITLE
We encourage everyone to use English when sending pull request

### ISSUE THREAD

**Issue by ralf0131** [apache/incubator-dubbo#1287]
Because Dubbo wants to be a global community, we encourage everyone to use English to describe the enhancement when sending pull request. 
And we are going to add it to the check list of pull request template.

**Comment by web1992** [comment]
Yes

**Comment by ralf0131** [comment]
Another thing worth mentioning is the commit message. Please use English. A pull request that contains non-English commit messages might not pass code review in the future.
