### ISSUE TITLE
能否加一个 dubbo-rpc-hprose

### ISSUE THREAD

**Issue by andot** [apache/incubator-dubbo#130]
https://github.com/andot/hprose 这个项目支持的语言众多，在常用语言支持上比 thrift、hessian 还要多，性能也比它们更强劲，支持的底层协议绑定也更多（目前支持HTTP、TCP和WebSocket底层协议绑定）。当然它也支持 Java 语言：https://github.com/hprose/hprose-java ，所以 dubbo 官方能否加一个 dubbo-rpc-hprose 的实现，让 hprose 的用户也能享受一下 dubbo 带来的强大功能呢？

**Comment by elespec** [comment]
I'm coming for give this a rate;

**Comment by myxingke** [comment]
重庆人必须支持的顶一个，打到缅甸鬼子！信hprose得永生！

**Comment by lscgzwd** [comment]
四川人民发来要约

**Comment by myxingke** [comment]
以前不知道有RPC 知道有RPC后又知道了hprose 再然后知道是国人开发的，虽然我只用PHP版，但是给我带了大大的方便，很棒很支持，最后来我又知道这个东西除了C++（好像）版外是andot一个人开发，而且没有商业支持，我突然觉得andot好累，完全是一个人在搞在开发呢！

**Comment by myxingke** [comment]
小马哥加油，努力！我们会为你打气的！他的墓志铭一样：就像编程语言一样，世界上只有两种，一种天天被人骂，另一种无人问津。

**Comment by foreversmart** [comment]
不管怎么样，顶一个～

**Comment by cenwei** [comment]
让 hprose 的用户也能享受一下 dubbo 带来的强大功能

**Comment by ralf0131** [comment]
Hi, would you please send a pull request for this?

**Comment by diecui1202** [comment]
No more feedback ? I'll close it. Reopen if necessary.
