### ISSUE TITLE
When refer the same service with more than one @References(with different configs) on consumer side, only one take effect.

### ISSUE THREAD

**Issue by zzl1521** [apache/incubator-dubbo#1306]
消费端使用注解方式引用服务端接口，如果一个服务中存在多处引用同一个接口但配置不同，比如重试次数不一样，消费端服务初始化时只会生效第一个加载的引用，而后的其他配置也就不生效，会导致服务失败重试等问题

**Comment by zzl1521** [comment]
AnnotationBean    private Object refer(Reference reference, Class<?> referenceClass)

**Comment by roc-cn** [comment]
I think this problem needs to be fixed: `com.alibaba.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor#generateReferenceBeanCacheKey`

**Comment by haiyang1985** [comment]
mark.

**Comment by mercyblitz** [comment]
Will be fixed on Dubbo `2.5.11`

**Comment by luyuanwan** [comment]
Has this problem fixed ?

**Comment by beiwei30** [comment]
this issue is no longer valid, has been fixed.
