### ISSUE TITLE
zk没有启动时，provider启动无响应

### ISSUE THREAD

**Issue by xuhengfei** [apache/incubator-dubbo#133]
我把zk关闭，启动provider的服务器(Main方法启动)
直接无响应，也不报错。

请问是bug吗？
这个预期应该是启动报错，提示zk不可用吧

**Comment by feihuwang** [comment]
dubbo中连接zookeeper没有设置连接默认连接超时时间，自己改下吧！

**Comment by htynkn** [comment]
refer to https://github.com/apache/incubator-dubbo/issues/287
Fixed since v2.5.7.

**Comment by ralf0131** [comment]
This issue has been fixed.
