### ISSUE TITLE
An idea to refactor dubbo spring config mechanism.

### ISSUE THREAD

**Issue by kimmking** [apache/incubator-dubbo#1364]
Hello, everyone,
   Now dubbo spring config is built by defining some parser, handler, xsd .etc.
   I thought about refactoring it by xmlbeans-spring several years ago.
   When we do it, we will:
   1. cut 90% codes for parser, handler,
   2. config dubbo by every bean object structure directly.，
   3. generate xsd file automaticly,
   4. modify and maintain schema easily.
   
how about this idea,guys?

**Comment by beiwei30** [comment]
As far as I know, xmlbeans is quite old technology. I am not sure we should approach toward this way, pls. shine more light on this, by providing more impl details :)

**Comment by kimmking** [comment]
@beiwei30 ok, I will make a demo for dubbo recently.

**Comment by chickenlj** [comment]
sth. new for this issue?

**Comment by diecui1202** [comment]
reopen if necessary.
