### ISSUE TITLE
[Announcement] Dubbo has entered Apache Incubator

### ISSUE THREAD

**Issue by ralf0131** [apache/incubator-dubbo#1373]
The [proposal](https://wiki.apache.org/incubator/DubboProposal) for Dubbo to join Apache Incubator has passed the vote conducted by the Apache Incubator community with 5 binding "+1" votes,  9 non-binding "+1" votes,  no "0" and no "-1" votes.

Details: https://lists.apache.org/thread.html/b3f8e62bf077519a2c6bfa26835e833aa2e32a80f0632a0789bb086a@%3Cgeneral.incubator.apache.org%3E

**Comment by kimmking** [comment]
congratulations

**Comment by zonghaishang** [comment]
great!

**Comment by Authorlove** [comment]
cheers！

**Comment by chickenlj** [comment]
Good to hear this news in The Spring Festival.

**Comment by DeadLion** [comment]
Congratulations！

**Comment by CFshuming** [comment]
Wonderful!

**Comment by javahongxi** [comment]
REALLY NICE

**Comment by qct** [comment]
Great Job

**Comment by dongxuwang** [comment]
Congrats!

**Comment by leyou240** [comment]
good!
