### ISSUE TITLE
Can dubbo have a real communtiy ?

### ISSUE THREAD

**Issue by LINGLUOJUN** [apache/incubator-dubbo#1379]
In my opinion,the dubbo should have its real community,not only contains issues and answers,but also contains excellent articles everyone who has good idea to share in there。

**Comment by kimmking** [comment]
If you want a resources collection, here is:  https://github.com/dubbo/dubbo-resources

If you want a discussion board, Here are issues.

If you want a good place for an assembly of them, it's a good idea, can you describe more details for building a real community?

**Comment by LINGLUOJUN** [comment]
@kimmking  like the springForAll,I think it's great

**Comment by kimmking** [comment]
OK, I got it.

**Comment by LINGLUOJUN** [comment]
@kimmking cooperating with spring4all seems a good idea

**Comment by ralf0131** [comment]
@LINGLUOJUN   I like this idea of building a community that any one can share or post articles about Dubbo, springForAll is a good example, but I think we can do more, documentation, learning course, article, conference, meetup, hackathon, etc.  Any suggestion is welcome!

**Comment by chickenlj** [comment]
BTW, you can send email to dev@dubbo.apache.org or subscribe it, which is preferred way for discussing questions like this.
