### ISSUE TITLE
Consumer annotation config actually unnecessary set basePackages for @DubboComponentScan

### ISSUE THREAD

**Issue by Sunshow** [apache/incubator-dubbo#1385]
from [document](http://dubbo.io/books/dubbo-user-book-en/configuration/annotation.html):
consumer side should set path to scan:
`@DubboComponentScan(basePackages = "com.alibaba.dubbo.test.service")`

but at source code [DubboComponentScanRegistrar](https://github.com/alibaba/dubbo/blob/master/dubbo-config/dubbo-config-spring/src/main/java/com/alibaba/dubbo/config/spring/context/annotation/DubboComponentScanRegistrar.java):
`registerReferenceAnnotationBeanPostProcessor(registry);`

so that no packagesToScan is pass to reference annotation regsiter,
the document should be fixed.

I found this after a wrong package configuration.

**Comment by chickenlj** [comment]
Hi, welcome to Dubbo community!

Please consider using English, Dubbo is a global community, and all the issues may be viewed and discussed by people all over the world.

Meanwhile, you can send email to dev@dubbo.apache.org or subscribe it, which is preferred way for discussing questions like this. And we will make sure that every email will receive a reply.

Github issues should be a pure place for tracking determined features, enhancements or  bugs.

**Comment by chickenlj** [comment]
@mercyblitz, who is an expert on spring, has subscribed to dev@dubbo.apache.org, i think you will get  the answer there from him.

**Comment by Sunshow** [comment]
@mercyblitz Yes, I know that. I just suggested to write more clearly to eliminate possible misunderstandings. Thanks for your reply.

**Comment by zonghaishang** [comment]
@Sunshow 
consumer side @DubboComponentScan  support set path to scan, see pr: https://github.com/apache/incubator-dubbo/pull/1550

**Comment by beiwei30** [comment]
this issue is no longer valid.

**Comment by mercyblitz** [comment]
`@DubboComponentScan` is used in the server side, thus, you could use `@EnableDubbo`.
