### ISSUE TITLE
Consumer side Validation SPI is wrongly activated while setting validation=true for provider

### ISSUE THREAD

**Issue by Sunshow** [apache/incubator-dubbo#1386]
ATT.

this case consumer leads to throw

`Caused by: java.lang.NoClassDefFoundError: javax/validation/Validation`

even while calling no validation method, unless add all validation dependencies to consumer,

that's not awesome.

one more question about ValidationFilter:

why the condition check is `isNotEmpty`:
`ConfigUtils.isNotEmpty(invoker.getUrl().getMethodParameter(invocation.getMethodName(), Constants.VALIDATION_KEY))`

and previous version check true or false:
`if (invoker.getUrl().getMethodParameter(invocation.getMethodName(), Constants.VALIDATION_KEY, false))`

**Comment by beiwei30** [comment]
@Sunshow can you provide a small sample to demo how to reproduce?

**Comment by chickenlj** [comment]
> ATT.
> 
> this case consumer leads to throw
> 
> Caused by: java.lang.NoClassDefFoundError: javax/validation/Validation
> 
> even while calling no validation method, unless add all validation dependencies to consumer,
> 
> that's not awesome.
> 

I think it is reasonable to check validation conditions on consumer side before params passed to provider side as this can be more efficient. If we keep it this way, we will meet the problem in your case: all consumers have to be aware of provider side validation configurations, for example when provider opened validation check, consumer side have to add necessary dependencies.

Please, send this problem to dev@dubbo.apache.org, and [subscribe to this email address](https://github.com/alibaba/dubbo/issues/1393). We can decide which way to go after a full discussion.

**Comment by Sunshow** [comment]
@chickenlj 
thanks, just sent the mail.

**Comment by chickenlj** [comment]
@nzomkxia I think your suggestion works, would you please submit a pull request?

https://github.com/apache/incubator-dubbo/blob/300f9c9fe1e4de8f14b494d8bf835b4e1ac6d5d6/dubbo-registry/dubbo-registry-api/src/main/java/com/alibaba/dubbo/registry/integration/RegistryProtocol.java#L230
