### ISSUE TITLE
Combine these two spring boot starter projects?

### ISSUE THREAD

**Issue by kimmking** [apache/incubator-dubbo#1427]
hello, everyone.
two spring-boot-starter for dubbo users is confusing and redundant. so can we combine two to an official one?

- https://github.com/dubbo/dubbo-spring-boot-project
- https://github.com/alibaba/dubbo-spring-boot-starter 

I found @xionghuiCoder is a developer of the non official one, can you resolve this issue with @mercyblitz ?

**Comment by mercyblitz** [comment]
It's working in process...
