### ISSUE TITLE
Dose dubbo3.0 have a plan to support gRPC

### ISSUE THREAD

**Issue by healerkx** [apache/incubator-dubbo#1428]
Dose dubbo 3.0 or later versions have a plan to support gRPC

**Comment by ralf0131** [comment]
Please ask it by sending email to dev@dubbo.apache.org. Issues are for bug tracking purpose. It is expected that question like this will be closed immediately in the near future.

**Comment by chickenlj** [comment]
Hi, 

I think supporting gRPC is on our long-term roadmap. Please send mails to dev@dubbo.apache.org <mailto:dev@dubbo.apache.org> for further discussion.

**Comment by ralf0131** [comment]
Hi, please checkout the our Qcon talk which covers gRPC talk: https://github.com/apache/incubator-dubbo/wiki#news
