### ISSUE TITLE
How to use "rest" protocol in dubbo, any demo？

### ISSUE THREAD

**Issue by luzhzhsoft** [apache/incubator-dubbo#1434]
how to use rest protocol in dubbo？

**Comment by chickenlj** [comment]
Hi, 

We recommend you send email to dev@dubbo.apache.org or subscribe it, which is preferred way for discussing questions like this.

We'd like github issues to be a pure place for tracking determined features, enhancements or bugs.

Thank you.

**Comment by lovepoem** [comment]
https://github.com/apache/incubator-dubbo-docs/pull/14 the dubbox's documents will be merged,hope it can help you

**Comment by nmyphp** [comment]
可以参考这个CSDN博客：https://blog.csdn.net/nmyphp/article/details/79174225

**Comment by ralf0131** [comment]
Please check this doc: http://dubbo.apache.org/#!/docs/user/references/protocol/rest.md?lang=zh-cn
