### ISSUE TITLE
[Announcement]Dubbo dev@list mails web page

### ISSUE THREAD

**Issue by kimmking** [apache/incubator-dubbo#1437]
Hi, everyone, we can use this page to view all dev@list mails online now:
[https://lists.apache.org/list.html?dev@dubbo.apache.org](https://lists.apache.org/list.html?dev@dubbo.apache.org)

**Comment by chickenlj** [comment]
Well done. Where did you find it?

**Comment by kimmking** [comment]
I am in ActiveMQ mail list so I found dubbo also have  a web page.
And mentor show a apache remail page in gitter channel, I update the links above.

**Comment by ralf0131** [comment]
That's great!
