### ISSUE TITLE
Url overwrite between protocol and service

### ISSUE THREAD

**Issue by xkaifei** [apache/incubator-dubbo#1440]
<dubbo:protocol port="${producer.port}" name="dubbo" serialization="kryo"/>
    <dubbo:service interface="aaa.bbb.XXservice" registry="common" ref="xxService" serialization="fastjson"/>
Provider will fill the header[2] with kryo id(8)  when encoding the response , and consumer uses kryo instead of fastJson.

**Comment by xkaifei** [comment]
http://dubbo.io/books/dubbo-user-book/references/xml/dubbo-service.html
这上面说service没有serialization，能否说明一下protocol和provider的serialization的覆盖原因?

**Comment by chickenlj** [comment]
> ```xml
> <dubbo:protocol port="${producer.port}" name="dubbo" serialization="kryo"/>
> <dubbo:service interface="aaa.bbb.XXservice" registry="common" ref="xxService" serialization="fastjson"/>
> ```

I think `fastjson` will take effect. What do you mean by 

> and consumer uses kryo instead of fastJson.

Do you have other additional configuration? 

Please send more detailed info to the apache @dev mailing list dev@dubbo.apache.org for further discussions.

**Comment by xkaifei** [comment]
@chickenlj There is'nt any additional configuration.
For this: 

> I think fastjson will take effect

 I checked the source ,it's probably may be a bug in 2.6.x.
Consumer will choose serialization class while decoding response at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCodec::decodeBody(), it's the "header[2]" decides the serialization class, which is decided by provider.
Then I checked source code of encoding:
`Serialization serialization = getSerialization(channel);`
`
protected Serialization getSerialization(Channel channel) {
       return CodecSupport.getSerialization(channel.getUrl());
}
`
That url in channel will not be changed by configuration in <dubbo:service> or <dubbo:provider>

**Comment by beiwei30** [comment]
@chickenlj is correct, in this case **fastjson** will be used. @xkaifei You can verify it by debug it. Yes, it is true that the sender will decided the serializer for the receiver, otherwise, how could you decode the message correctly?

**Comment by wangwei-ying** [comment]
> @chickenlj is correct, in this case **fastjson** will be used. @xkaifei You can verify it by debug it. Yes, it is true that the sender will decided the serializer for the receiver, otherwise, how could you decode the message correctly?

hi,  Which pr solved this problem ,thx for much.

**Comment by wangwei-ying** [comment]
> @chickenlj is correct, in this case **fastjson** will be used. @xkaifei You can verify it by debug it. Yes, it is true that the sender will decided the serializer for the receiver, otherwise, how could you decode the message correctly?

hi,  Which pr solved this problem ,thx for much.
