### ISSUE TITLE
Can not invoke "$echo" of remote service through a dubbo proxy get by  SpringContext.getBean？

### ISSUE THREAD

**Issue by shiqingshun** [apache/incubator-dubbo#1446]
在使用xml配置
<dubbo:reference group="${node.group.name}" interface="com.sqs.interfaces.XXService" version="1.0" />
然后通过ApplicationContext.getBean(com.sqs.interfaces.XXService.class); 获取到的服务引用在使用EchoService测试服务可用性时，出现异常

Caused by: com.alibaba.dubbo.common.bytecode.NoSuchMethodException: Not found method "$echo"

**Comment by chickenlj** [comment]
Hi shiqingshun,

Firstly, please consider using English, Dubbo is a global community, and all the issues may be viewed and discussed by people all over the world.

> Caused by: com.alibaba.dubbo.common.bytecode.NoSuchMethodException: Not found method "$echo"

Did you get this exception on provider side? I doubt that for some reason the `EchoFilter` didn't take effect in the invocation chain. 

Can you send an email to the apache @dev mailing list dev@dubbo.apache.org for further discussion?

Thanks

**Comment by shiqingshun** [comment]
Hi chickenlj 

I get this exceprion is on consumer side.

Exception stack:
Exception in thread "main" com.alibaba.dubbo.rpc.RpcException: Failed to invoke the method $echo in the service com.sqs.interfaces.XXService. cause: Not found method "$echo" in class com.sqs.interfaces.XXService.
       at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:101)
       at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:229)
       at com.alibaba.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:72)
       at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:52)
       at com.alibaba.dubbo.common.bytecode.proxy0.$echo(proxy0.java)
       at com.sqs.javatest.health.TestApp.main(TestApp.java:34)
Caused by: com.alibaba.dubbo.common.bytecode.NoSuchMethodException: Not found method "$echo" in class com.sqs.interfaces.XXService.
       at com.alibaba.dubbo.common.bytecode.Wrapper0.invokeMethod(Wrapper0.java)
       at com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:46)
       at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:72)
       at com.alibaba.dubbo.rpc.protocol.AbstractProxyProtocol$2.doInvoke(AbstractProxyProtocol.java:94)
       at com.alibaba.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:144)
       at com.alibaba.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:74)
       at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75)
       at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:69)
       at com.alibaba.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:54)
       at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:69)
       at com.alibaba.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:48)
       at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:69)
       at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53)
       at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:77)
       ... 5 more

**Comment by kimmking** [comment]
can you provide your codes to show how to invoke echoService? @shiqingshun

**Comment by shiqingshun** [comment]
This is my test code:

    public static void main(String[] args) throws Exception {
        String[] xmlFiles = new String[]{
                "classpath:applicationContext-config.xml",
                "classpath:applicationContext.xml",
                "classpath:applicationContext-dubbo-consumer.xml",
        };
        ApplicationContext moduleContext = new ClassPathXmlApplicationContext(xmlFiles);
        Object imService = moduleContext.getBean(com.sqs.interfaces.XXService.class);
        EchoService echoService = (EchoService) imService;
        if (echoService != null) {
            echoService.$echo("Hello");
        }
    }

**Comment by shiqingshun** [comment]
I guess the problem is in Wrapper.java,
Wrapper.java generates the function in the invokeMethod that iterates over the method list of the provider 
 interface. When the method name is not included in the provider interface, it throws com.alibaba.dubbo.common.bytecode.NoSuchMethodException

c3=
    public Object invokeMethod(Object o, String n, Class[] p, Object[] v) throws java.lang.reflect.InvocationTargetException {
        com.sqs.javatest.health.interfaces.ImService w;
        try {
            w = ((com.sqs.javatest.health.interfaces.ImService) $1);
        } catch (Throwable e) {
            throw new IllegalArgumentException(e);
        }
        try {
            if ("getMsg".equals($2) && $3.length == 1) {
                return ($w) w.getMsg((java.lang.String) $4[0]);
            }
            if ("getMsg2".equals($2) && $3.length == 1) {
                return ($w) w.getMsg2((java.lang.String) $4[0]);
            }
        } catch (Throwable e) {
            throw new java.lang.reflect.InvocationTargetException(e);
        }
        throw new com.alibaba.dubbo.common.bytecode.NoSuchMethodException("Not found method \"" + $2 + "\" in class com.sqs.javatest.health.interfaces.ImService.");
    }

**Comment by qinliujie** [comment]
@shiqingshun hi,I have try and work well,please make sure that your program load EchoFilter.you can confirm that by set a breakpoint in com.alibaba.dubbo.rpc.filter.EchoFilter

**Comment by shiqingshun** [comment]
@qinliujie Hi, how do I modify my config file.

**Comment by shiqingshun** [comment]
@qinliujie hi, Can you tell me how you tested it?
Providers and consumers are in the same JVM and there is no problem.
However, providers and consumers are not in the same JVM and an exception occurs. Neither provider nor consumer can enter EchoFilter breakpoints.

**Comment by kimmking** [comment]
can you show dubbo config xml?

**Comment by shiqingshun** [comment]
provider config xml

<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:dubbo="http://code.alibabatech.com/schema/dubbo"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-2.5.xsd
	http://code.alibabatech.com/schema/dubbo http://code.alibabatech.com/schema/dubbo/dubbo.xsd">

    
    <dubbo:application name="health-test" />

    
    <dubbo:registry  client="curator"  protocol="${dubbo.registry.protocol}" address="${dubbo.registry.address}" username="${dubbo.registry.username}" password="${dubbo.registry.password}" timeout="100000">
        <dubbo:parameter key="qos.enable" value="false"/>
        <dubbo:parameter key="qos.port" value="22224"/>
    </dubbo:registry>

    <dubbo:protocol name="rmi" port="1099" threads="10" />

    <bean id="imServiceImpl" class="com.sqs.javatest.health.service.ImServiceImpl"></bean>

    <dubbo:service group="${node.group.name}" ref="imServiceImpl" interface="com.sqs.javatest.health.interfaces.ImService" version="1.0" />
    
</beans>

consumer config xml

<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:dubbo="http://code.alibabatech.com/schema/dubbo"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-2.5.xsd
	http://code.alibabatech.com/schema/dubbo http://code.alibabatech.com/schema/dubbo/dubbo.xsd">

    
    <dubbo:application name="health-test" />

    
    <dubbo:registry  client="curator"  protocol="${dubbo.registry.protocol}" address="${dubbo.registry.address}" username="${dubbo.registry.username}" password="${dubbo.registry.password}" timeout="100000">
        <dubbo:parameter key="qos.enable" value="false"/>
        <dubbo:parameter key="qos.port" value="22224"/>
    </dubbo:registry>

    <dubbo:protocol name="rmi" port="1010" threads="10" />

    <bean id="imServiceImpl" class="com.sqs.javatest.health.service.ImServiceImpl"></bean>

    <dubbo:reference id="imserver" group="${node.group.name}" interface="com.sqs.javatest.health.interfaces.ImService" version="1.0" />

</beans>

**Comment by chickenlj** [comment]
Please provide your demo code that can reproduce your problem and reopen this issue, if necessary.

**Comment by gangzi828** [comment]
I encounter the same question? Caused by: com.alibaba.dubbo.common.bytecode.NoSuchMethodException: Not found method "$echo" in class XXXService.This is caused by Dubbo Provider's EchoFilter has no effect?

**Comment by kingStart** [comment]
springboot actuator  服务正常可启动，并且能访问到 /health 抓取状态，但{"status":"DOWN"}, 将详情访问出来，发现是hession协议的服务影响了health的检查状态  在所有的环境中均可用，并且中可用的。

/health结果如下 ：

`{
  "status": "DOWN",
  "dubbo": {
    "status": "DOWN",
    "ClassIdBean [interfaceClass=interface com.test.robot.serviceapi.DoctorInfoServiceAPI, group=null, version=null]": "UP",
    "ClassIdBean [interfaceClass=interface com.test.robot.serviceapi.warnmessage.WarnMessageServiceApi, group=null, version=null]": "UP",
    "ClassIdBean [interfaceClass=interface com.test.robot.serviceapi.PersonArchivesServiceAPI, group=null, version=null]": "UP",
    "ClassIdBean [interfaceClass=interface com.test.robot.serviceapi.organization.user.OrganizationUserServiceApi, group=null, version=null]": "UP",
    "ClassIdBean [interfaceClass=interface com.test.api.fileservice.UploadServiceAPI, group=null, version=null]": "DOWN, message: Failed to invoke the method $echo in the service com.test.api.fileservice.UploadServiceAPI. Tried 1 times of the providers [10.1.1.68:8383] (1/1) from the registry 10.1.1.68:2181 on the consumer 10.1.3.118 using the dubbo version 2.6.0. Last error is: Failed to invoke remote proxy method $echo to hessian://10.1.1.68:8383/com.test.api.fileservice.UploadServiceAPI?anyhost=true&application=data-provider-pad&check=false&default.retries=0&default.timeout=10000&dubbo=2.5.8&generic=false&interface=com.test.api.fileservice.UploadServiceAPI&lazy=true&methods=download,upload&pid=21836&register.ip=10.1.3.118&remote.timestamp=1557036450072&side=consumer&timestamp=1557305248082, cause: Not found method \"$echo\" in class com.test.api.fileservice.UploadServiceAPI.",
    "ClassIdBean [interfaceClass=interface com.test.robot.serviceapi.monitor.BloodPressureMonitorApi, group=null, version=null]": "UP"
  },
  "jms": {
    "status": "UP",
    "provider": "ActiveMQ"
  },
  "diskSpace": {
    "status": "UP",
    "total": 126981165056,
    "free": 24086355968,
    "threshold": 10485760
  },
  "redis": {
    "status": "UP",
    "version": "5.0.3"
  },
  "db": {
    "status": "UP",
    "database": "MySQL",
    "hello": 1
  }
}`

**Comment by auroraMR921** [comment]
I also encountered the same problem: com.alibaba.dubbo.rpc.RpcException: Failed to invoke the method $echo in the service com.keystar.eprdms.service.file.LoadFileService.
The protocol of my interface is hessian, and there will be some methods of transferring file streams. Where is the method of $echo? How to find?
