### ISSUE TITLE
NettyHelper in netty extension populated Logger "InternalLogger" in netty.

### ISSUE THREAD

**Issue by teclxl** [apache/incubator-dubbo#1447]
系统中有自己的Netty服务器，同时指定Dubbo用Netty，然后LoggingHandler就没法用了。下面的代码回导致我的Netty服务器无法使用Netty自带的日志体系。如果我强制自己的Netty服务器晚于Dubbo加载，那么Dubbo也是无法使用到DubboLogger的。
```
public class NettyHelper {

    public static void setNettyLoggerFactory() {
        InternalLoggerFactory factory = InternalLoggerFactory.getDefaultFactory();
        if (factory == null || !(factory instanceof DubboLoggerFactory)) {
            InternalLoggerFactory.setDefaultFactory(new DubboLoggerFactory());
        }
    }
```
# Added content in English. Help with Google Translate
System is TCP server using Netty4, and Dubbo is specified to use Netty4. When I add LoggingHandler to ChannelPipeline of my System, The log is not expected. 
Like this:
![image](https://user-images.githubusercontent.com/11850956/37442060-5a02eabc-283f-11e8-939a-68255f8912b2.png)

I tracked the code and found the Logger is `com.alibaba.dubbo.remoting.transport.netty4.logging.NettyHelper.DubboLogger` instead of `io.netty.util.internal.logging.Slf4JLogger`.  DubboLogger added other content arount the original log. The NeetyHelper replace the InternalLoggerFactory when Dubbo loading, like the code block above shows.
# By the way.
My system build by Spring Boot, use default logging framework which is Slf4j + Logback.
Dubbo's logger is not extend default logger, but replace it.
![image](https://user-images.githubusercontent.com/11850956/37442386-0585c494-2841-11e8-8f8f-354e7f226726.png)

**Comment by chickenlj** [comment]
Hi,

Please consider using English, Dubbo is a global community, and all the issues may be viewed and discussed by people all over the world.

Can not work? Is there any detailed error recorded? I think LoggingHandler will also use the DubboLogger specified by Dubbo, and it will finally depend on the real logger implementation, e.g. log4j, slf4j, etc. 

Please send more details to @dev@dubbo.apache.org for in-depth discussion.

Thanks

**Comment by kimmking** [comment]
I think you can send a mail to dev@dubbo.apache.org about keeping default logger mechanism in netty for further discussion.  @teclxl

**Comment by teclxl** [comment]
Sorry, the message mail is classified by Outlook as other without push notification.

**Comment by teclxl** [comment]
Press wrong button to close.

**Comment by beiwei30** [comment]
@teclxl That's true `com.alibaba.dubbo.remoting.transport.netty4.logging.NettyHelper.DubboLogger` will be used if dubbo boots ahead of your netty, but if you look into `com.alibaba.dubbo.common.logger.LoggerFactory`, you will find DubboLogger will eventually delegate to the real logging framework your app relies on:

```java
    // search common-used logging frameworks
    static {
        String logger = System.getProperty("dubbo.application.logger");
        if ("slf4j".equals(logger)) {
            setLoggerAdapter(new Slf4jLoggerAdapter());
        } else if ("jcl".equals(logger)) {
            setLoggerAdapter(new JclLoggerAdapter());
        } else if ("log4j".equals(logger)) {
            setLoggerAdapter(new Log4jLoggerAdapter());
        } else if ("jdk".equals(logger)) {
            setLoggerAdapter(new JdkLoggerAdapter());
        } else {
            try {
                setLoggerAdapter(new Log4jLoggerAdapter());
            } catch (Throwable e1) {
                try {
                    setLoggerAdapter(new Slf4jLoggerAdapter());
                } catch (Throwable e2) {
                    try {
                        setLoggerAdapter(new JclLoggerAdapter());
                    } catch (Throwable e3) {
                        setLoggerAdapter(new JdkLoggerAdapter());
                    }
                }
            }
        }
    }
```

I am not sure if it satisfies what you demands. In order to help clarify this issue better, I push a same code at https://github.com/beiwei30/netty-dubbo-logging-test, pls. modify it further in order to help me understand your issue better.

**Comment by chickenlj** [comment]
I think beiwei30 and me both have clarified this issue. It shouldn't be caused by dubbo's NettyHelper.

**Comment by beiwei30** [comment]
@teclxl @chickenlj would you mind to take a look at https://github.com/beiwei30/incubator-dubbo/commit/030ebcea51603b955330059814fa95601f5dd1f6? I made an experimental change to solve this issue.

**Comment by teclxl** [comment]
@beiwei30 I think your change can solve this issue. I think the reason is that FailsafeLogger changed all msg, too.
I saw you have already begun to slove this issue. I don't know if it is appropriate to close the issue now. Please close this issue, if you think it is appropriate.

**Comment by ralf0131** [comment]
@beiwei30 Can this issue be closed?

**Comment by ralf0131** [comment]
This issue has been fixed.
