### ISSUE TITLE
JavassistProxyFactory 类中的 wrapper.invokeMethod 性能差问题。

### ISSUE THREAD

**Issue by hone-liu** [apache/incubator-dubbo#1457]
wrapper.invokeMethod 在不同服务器（相同配置，centos6，8核cpu，64G内存，jdk1.7）里面表现耗时差别很大，知道是什么原因么？（getLocalTimeByUTC 方法体没有任何业务逻辑，直接new 对象返回）
日志如下：
>>>>>>>>getLocalTimeByUTC,spend:520 ms

`public <T> Invoker<T> getInvoker(T proxy, Class<T> type, URL url) {
		// TODO Wrapper类不能正确处理带$的类名
		final Wrapper wrapper = Wrapper.getWrapper(proxy.getClass().getName().indexOf('$') < 0 ? proxy.getClass() : type);
		return new AbstractProxyInvoker<T>(proxy, type, url) {
			@Override
			protected Object doInvoke(T proxy, String methodName,
					Class<?>[] parameterTypes, Object[] arguments)
					throws Throwable {
				long start = System.currentTimeMillis();
				Object obj = wrapper.invokeMethod(proxy, methodName,parameterTypes, arguments);
				long end = System.currentTimeMillis();
				logger.info(">>>>>>>>" + methodName+ ",spend:" + (end - start) + "ms");
				return obj;
			}
		};
	}`

**Comment by qinliujie** [comment]
Maybe you can use jstack to locate this problem, just use it to print thread stack every second when you run your application and see where it blocked

**Comment by qinliujie** [comment]
#!/bin/bash


iteration=100
interval=2
pid=36293

for (( i=1; i<=$iteration; i++ )); do
    echo "================Begin iteration ${i}====================="
     jstack $pid > jstack.${i}.txt
    echo "================End iteration ${i}====================="
    if [ $i -lt $iteration ]; then
       echo "Sleeping $interval seconds..."
       sleep $interval;
    fi
done

**Comment by qinliujie** [comment]
it is a demo, you can change it to adjust for yourself

**Comment by zhaojigang** [comment]
原则上这个方法性能不会差，因为他是做了硬编码直接调用服务实现类的 @hone-liu

**Comment by chickenlj** [comment]
Generally, this method shouldn't be the performance bootle neck.

You can follow qinliujie's advice to check the detailed jstack to locate real problems
