### ISSUE TITLE
Can not stop retry with `retries=0`

### ISSUE THREAD

**Issue by SuperstarSage** [apache/incubator-dubbo#1463]
![qq 20180313184422](https://user-images.githubusercontent.com/18466015/37337230-9527d460-26ee-11e8-80ff-e0d6b6473cfb.png)
我这样配置了之后，为什么还会有失败重试？

**Comment by sofay** [comment]
看源码好像只有cluster为failover这个参数才有用

**Comment by zonghaishang** [comment]
@SuperstarSage

if you use failfast cluster, retries does't work.
if you use failover cluser, the minimum number of retries is "retries + 1 ".

refer from : com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker#doInvoke

``` java
        int len = getUrl().getMethodParameter(invocation.getMethodName(), Constants.RETRIES_KEY, Constants.DEFAULT_RETRIES) + 1;
        if (len <= 0) {
            len = 1;
        }
```

**Comment by chickenlj** [comment]
Hi,

Please consider using English, Dubbo is a global community, and all the issues may be viewed and discussed by people all over the world.

Please send mail to dev@dubbo.apache.org to discuss questions like this. We'd like github issues to track bugs, features or at least high suspicious bugs. We guarantee that the questions send to the mailing list can get a quicker reply.

How to send and subscrite to dev@dubbo.apache.org: #1393 

Thanks
