### ISSUE TITLE
[Announcement]Release notification of 2.5.10 and 2.6.1

### ISSUE THREAD

**Issue by chickenlj** [apache/incubator-dubbo#1465]
Hi, community

[2.5.10](https://github.com/alibaba/dubbo/releases/tag/dubbo-2.5.10) has been released, contains some bugs reported by community.

2.6.1 is expected also to be released very soon, in this version, we will refactor the project structure so each module in dubbo can be deployed to repository separately,  and will add some enhancements.

Currently, dubbo keeps two versions evolve in parallel: 2.5.x, 2.6.x, check #1208 for detailed version management plan. 
* For contributors, please make sure all changes on the right base branch, that is, only use 2.5.x branch for bugfixes, otherwise use master.
* For committers, make sure select the right label and target branch for every PR, make sure 2.5.x merge to master as soon as possible.

**Comment by nobodyiam** [comment]
Good to know, thanks!
