### ISSUE TITLE
com.alibaba.dubbo.common.URL不能使用邮箱作为用户名

### ISSUE THREAD

**Issue by CandleFlower** [apache/incubator-dubbo#1470]
com.alibaba.dubbo.common.URL.valueof()中如果用户名或密码中包含@字段，导致解析错误
i = url.indexOf("@");需要将此字段改为i = url.lastIndexOf("@");

**Comment by vangoleo** [comment]
We will improve the URL interpreting logic, thanks a lot.

**Comment by ralf0131** [comment]
Hi, thanks for reporting, could you please send a pull request to fix it?

**Comment by markt-asf** [comment]
I'm not convinced that this bug report is valid.
From RFC 3986
authority      = [ userinfo "@" ] host [ ":" port ]
userinfo    = *( unreserved / pct-encoded / sub-delims / ":" )
unreserved     = ALPHA / DIGIT / "-" / "." / "_" / "~"
sub-delims     = "!" / "$" / "&" / "'" / "(" / ")" / "*" / "+" / "," / ";" / "="

The '@' character is not a valid character for the userinfo. If use of a '@' is required then it would need to be %nn encoded. Multiple '@' before those host looks to be invalid and should probably be rejected.

**Comment by chickenlj** [comment]
We can refer what java.lang.URL does. 
I think change to `lastIndexOf()` brings no harm,  there's also no need to add error promotion. But we should remove the '@' use cases in UT.
