### ISSUE TITLE
durid配置durid sql  监控后dubbo无法启动

### ISSUE THREAD

**Issue by liaoqianlin999** [apache/incubator-dubbo#1480]
项目中同时使用durid+dubbo时，加载duridsql 监控后dubbo配置无法启动，注释掉durid sql 监控后正常启动。
<bean id="dataSource" class="com.alibaba.druid.pool.DruidDataSource"
		init-method="init" destroy-method="close">
		<property name="url" value="${jdbc.url}" />
		<property name="username" value="${jdbc.username}" />
		<property name="password" value="${jdbc.password}" />
		<property name="initialSize" value="5" />
		<property name="minIdle" value="5" />
		<property name="maxActive" value="30" />
		<property name="maxWait" value="60000" />
		<property name="timeBetweenEvictionRunsMillis" value="60000" />
		<property name="minEvictableIdleTimeMillis" value="300000" />
		<property name="removeAbandoned" value="true" />
		<property name="removeAbandonedTimeout" value="1800" />
		<property name="validationQuery" value="SELECT 'x'" />
		<property name="testWhileIdle" value="true" />
		<property name="testOnBorrow" value="false" />
		<property name="testOnReturn" value="false" />
		<property name="poolPreparedStatements" value="true" />
		<property name="maxPoolPreparedStatementPerConnectionSize"
			value="20" />
		<property name="filters" value="stat" />
	</bean>
****

 	<bean id="transactionManager"
		class="org.springframework.jdbc.datasource.DataSourceTransactionManager">
		<property name="dataSource" ref="dataSource" />
	</bean> 

	<bean id="sqlSessionFactory" class="org.mybatis.spring.SqlSessionFactoryBean">
		<property name="dataSource" ref="dataSource" />
		<property name="mapperLocations" value="classpath:orm/*.xml" />
	</bean>

	<bean class="org.mybatis.spring.mapper.MapperScannerConfigurer">
		<property name="annotationClass" value="org.springframework.stereotype.Repository" />
		<property name="basePackage" value="com.jhqf.user.mapper" />
		<property name="sqlSessionFactoryBeanName" value="sqlSessionFactory" />
	</bean>
	<bean id="snowIdUtil" class="com.jhqf.commons.idproducer.SnowIdUtil">
		<constructor-arg index="0" value="${workerId}"/>
		<constructor-arg index="1" value="${datacenterId}"/>
	</bean>

     <import resource="dubbo-service-provider.xml" />

dubbo配置
	<dubbo:application name="dubbo_provider" />
	<dubbo:registry address="${zookeeper.url}" />
	<dubbo:protocol name="dubbo" port="${dubbo.port}" />
	<dubbo:annotation package="com.jhqf.user.remoteimpl" />

**Comment by chickenlj** [comment]
```xml
<dubbo:annotation package="com.jhqf.user.remoteimpl" />
```
This configuration is deprecated since 2.5.7 or higher, please upgrade to the latest version and use the recommended configuration: https://github.com/apache/incubator-dubbo/tree/master/dubbo-test/dubbo-test-examples/src/main/java/com/alibaba/dubbo/examples/annotation
