### ISSUE TITLE
Typo on chapter 6.27 in user book.

### ISSUE THREAD

**Issue by zhuyuehao** [apache/incubator-dubbo#1483]
<dubbo:provider deplay=”-1” />  中deplay应该是delay；

位置在：
规避办法的第3节

**Comment by chickenlj** [comment]
Please report to dev@dubbo.apache.org for this kind of problem.

And you can create a PR directly to https://github.com/apache/incubator-dubbo-docs

**Comment by chickenlj** [comment]
Done
