### ISSUE TITLE
Serialization exception when there's List type in DTO 

### ISSUE THREAD

**Issue by learndockering** [apache/incubator-dubbo#1484]
dubbox以前遗留的老问题，一个模型存在List这类变量在调用过程中出现调用失败的情况，必须使用数组传输才行
比如：List<String> 改成 String[]，否则调用会报一下错误
![0c71a29a-dc6d-43c4-ae93-0bbbbbff9981](https://user-images.githubusercontent.com/35672310/37629234-99c32216-2c18-11e8-9964-babc7fec3721.png)

**Comment by chickenlj** [comment]
Hi,

Please consider using English, Dubbo is a global community, and all the issues may be viewed and discussed by people all over the world.

Seems to be a serialization problem, have you tried use other serialization framework, say hessian2, fastjson?

Please send more details to @dev@dubbo.apache.org for in-depth discussion.

Thanks

**Comment by vangoleo** [comment]
As @chickenlj mentioned, does this issue only occur while using kryo serialization? It maybe a serialization problem.

**Comment by zonghaishang** [comment]
@learndockering 
Please provide the object structure that List contains or your unit test code, thanks.

**Comment by chickenlj** [comment]
Closed. Reopen if necessary.
