### ISSUE TITLE
Remove deprecated annotation implementation in v2.6.2 to avoid misuse.

### ISSUE THREAD

**Issue by chickenlj** [apache/incubator-dubbo#1485]

**Comment by diecui1202** [comment]
@chickenlj Could u describe it with more details ?

**Comment by chickenlj** [comment]
There's a completely new implementation, which is located in [dubbo-spring-boot-project](https://github.com/apache/incubator-dubbo-spring-boot-project), to replace the deprecated [AnnotationBean](https://github.com/apache/incubator-dubbo/blob/master/dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/AnnotationBean.java) since 2.5.7.

With the new implementation, you can use, 
```xml
@DubboComponentScan(basePackages="org.apache.dubbo.demo")
```
or
```properties
## application.properties
# Base packages to scan Dubbo Components (e.g., @Service, @Reference)
dubbo.scan.basePackages  = com.alibaba.boot.dubbo.demo.provider.service
```
to do the same thing.
