### ISSUE TITLE
2.5.7 之后，dubbo增加了qos-server，然后打印日志出来的版本号是 2.0.1

### ISSUE THREAD

**Issue by cnhans** [apache/incubator-dubbo#1492]
虽然是日志打印不对，但具体里面有没其他bug不清楚，麻烦检查下是否是版本号弄错了，非常感谢，2.5.7及之前的日志都是正确的。

**Comment by vangoleo** [comment]
Could you provide the content of log?

**Comment by ralf0131** [comment]
Can you check whether it is duplicate of #1524 ?

**Comment by ralf0131** [comment]
Confirmed duplicate of #1524
