### ISSUE TITLE
How to build a new route rule in version 2.5.3+

### ISSUE THREAD

**Issue by LijyCasey** [apache/incubator-dubbo#1493]
I saw the guide of Dubbo [dubbo-user-guide](http://dubbo.apache.org/books/dubbo-user-book-en/demos/routing-rule.html) that if I want to build a route rule I should build URL like `"condition://0.0.0.0/com.foo.BarService?category=routers&dynamic=false&rule=" + URL.encode("host = 10.20.153.10 => host = 10.20.153.11") + "` 
but I saw the resource of dubbo-admin or dubbokeeper the URL was built like `route://0.0.0.0/com.alibaba.dubbo.monitor.MonitorService?category=routers&dynamic=false&enabled=false&force=false&name=1&priority=1&router=condition&rule=consumer.host=10.20.153.10+=>+provider.host=10.20.153.11&runtime=false` 
it starts with 'route' instead of 'condition' ,so I confused if the guide version too old or dubbo-admin's version is outdated

**Comment by vangoleo** [comment]
Thanks for your feedback, and we will look into this issue and keep you updated.

**Comment by nzomkxia** [comment]
try the current version of dubbo ops：https://github.com/apache/incubator-dubbo-ops, just create a new rule in Route Rule page
