### ISSUE TITLE
dubbo

### ISSUE THREAD

**Issue by zhangwei850428** [apache/incubator-dubbo#1494]
公司：国美金融
地址：中国北京
联系方式： zhangwei_227@126.com
业务场景：理财网贷系统服务化

**Comment by vangoleo** [comment]
Below is the right place to provide your info to Dubbo team:
[ issue#1012: Wanted: who's using dubbo](https://github.com/apache/incubator-dubbo/issues/1012)

**Comment by vangoleo** [comment]
Dubbo team, this is not a issue, just close it.
