### ISSUE TITLE
move  JettyContainer and PageHandler's impls classes

### ISSUE THREAD

**Issue by wannshan** [apache/incubator-dubbo#1499]
JettyContainer and PageHandler's impls classes should move to dubbo-ops/dubbo-monitor-simple from dubbo.jar

**Comment by ralf0131** [comment]
Hi, Welcome!

Would you mind send a PR?

**Comment by wannshan** [comment]
oh ,this work have bean done in apache/incubator-dubbo
my code is old  dubbo,my mistake.

**Comment by chickenlj** [comment]
closed.
