### ISSUE TITLE
 java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by dengly** [apache/incubator-dubbo#150]
我使用的是dubbo-2.5.4-SNAPSHOT.jar，放在Tomcat的lib下，而且所有的jar都放在Tomcat的lib下。启动时没有报任何错误，在dubbo admin后台看到提供者和消费者都正常。但是在打开使用时报了如下错误:

``` java
java.lang.IllegalArgumentException: java.lang.NoClassDefFoundError: com/pointercn/community/service/impl/DBServiceImpl
 at com.alibaba.dubbo.common.bytecode.Wrapper47.invokeMethod(Wrapper47.java)
 at com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:46)
 at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:72) ... 
25 more 
Caused by: java.lang.NoClassDefFoundError: com/pointercn/community/service/impl/DBServiceImpl ...
28 more
```

我查看了，该类是存在的，在提供者下的。
我爬了网，根据这个http://blog.csdn.net/achilles12345/article/details/41958713 修改也不行。
另外想问，那个dubbo版本才是最新的

**Comment by all4future** [comment]
我同样地遇到了这个问题，不过我的情况比较奇怪。  

1. 在IntelliJ IDEA中启动provider工程，一切正常。
2. 使用sh脚本启动工程，无法连接服务，同时consumer那边出现了以上的报错

这个错误我这里是从consumer那边报出来的，反而provider并没有任何的报错日志，尝试了很多方法，甚至更换了一个impl类都出现了一样的问题。也对比了配置，并确认没有配置错误。

搜了半天发现了[这篇文章](http://ju.outofmemory.cn/entry/185058)，也没有帮助。

PS：我的dubbo版本为2.5.3

**Comment by sunshineasbefore** [comment]
这个问题有人解决了吗?

**Comment by yinjinquan** [comment]
我也遇到这个问题了
1、在idea启动provider和customer是没有问题的，而且消费者能正常调用生产者，但是当maven打包成jar包，当customer 访问 provider的时候，provider 报错NoClassDefFoundError。 
我的dubbo版本是：2.5.5 jdk：1.8.40

**Comment by ralf0131** [comment]
1. Don't put Dubbo to Tomcat's CATALINA_HOME/lib directory.
2. Please check the latest Dubbo version.
3. If it still have this issue, please provide a description on how to reproduce the issue.
4. I am closing this issue now, feel free to reopen it.

**Comment by lastboy1228** [comment]
javassist 3.18及以下版本与java8不兼容，注意排除旧的javassist(有javassist和org.javassist两个group)
