### ISSUE TITLE
local mock not work according by the user manual

### ISSUE THREAD

**Issue by apel-apel** [apache/incubator-dubbo#1501]
the user manual describe the usage about mock like this：
```xml
<dubbo:service interface="com.foo.BarService" mock="true" />
```
or
```xml
<dubbo:service interface="com.foo.BarService" mock="com.foo.BarServiceMock" />
```

but, this config is not work, the correct way is insteading `<dubbo:service` with `<dubbo:reference`,
just like this:
```xml
<dubbo:reference interface="com.foo.BarService" mock="true" />
```
or
```xml
<dubbo:reference interface="com.foo.BarService" mock="com.foo.BarServiceMock" />
```
I think should edit the user manual like above;

**Comment by vangoleo** [comment]
I have already reproduced this issue on my machine, and Dubbo team will fix this in the official user manual document:

- http://dubbo.apache.org/books/dubbo-user-book/demos/local-mock.html
- http://dubbo.apache.org/books/dubbo-user-book-en/demos/local-mock.html

Thanks a lot for your feedback ^_^

**Comment by vangoleo** [comment]
@diecui1202 Finished.

**Comment by ralf0131** [comment]
This has been fixed by https://github.com/apache/incubator-dubbo-docs/pull/12
