### ISSUE TITLE
kryo's ClassLoader Exception

### ISSUE THREAD

**Issue by tosilu** [apache/incubator-dubbo#1502]
Unable to load class path with kryo's ClassLoader. Retrying with current.

**Comment by vangoleo** [comment]
Hi, could you provide more details about this issue, for example, the code snippet and the detailed exception.

**Comment by diecui1202** [comment]
@tosilu 

We will be appreciated if you could stick the exception stack trace. Without details, we can't repeat the problem.

**Comment by chickenlj** [comment]
Feel free to reopen this issue if necessary
