### ISSUE TITLE
 ServiceBean.getSpringContext()  is null

### ISSUE THREAD

**Issue by windywang** [apache/incubator-dubbo#1503]
when I  use   ServiceBean.getSpringContext() in filter  ，I found  the object is  null。I use springboot integrated dubbo。 
I used to have debug,But it was found that the breakpoint did not come in when springboot started.
On the other question, I want to ask what API can get all the registered services
thank u。

**Comment by linghushaoxia** [comment]
show your code，please ,let's solve the probem  together ~

**Comment by vangoleo** [comment]
Please show your code for further diagnosis.

**Comment by diecui1202** [comment]
@duanling will check this problem in his hands-on working.

**Comment by chickenlj** [comment]
#1674

**Comment by whanice** [comment]
Seems can use a static method,  ApplicationModel.allProviderModels()

**Comment by Marthevin** [comment]
not resolved yet?

**Comment by beiwei30** [comment]
not valid any longer, we don't provide static method to get context from ServiceBean. The original impl is incorrect.
