### ISSUE TITLE
[Suggestion] What about migrating from Javassist to Byte Buddy

### ISSUE THREAD

**Issue by vangoleo** [apache/incubator-dubbo#1504]
Byte Buddy has better performance, below is a benchmark testing report, and as I known, Hibernate already changed to use Byte buddy. 
[https://zeroturnaround.com/rebellabs/testing-the-performance-of-4-java-runtime-code-generators-cglib-javassist-jdk-proxy-byte-buddy/](https://zeroturnaround.com/rebellabs/testing-the-performance-of-4-java-runtime-code-generators-cglib-javassist-jdk-proxy-byte-buddy/)

**Comment by zonghaishang** [comment]
I already have an idea to replace the bytecode implementation in dubbo, I will continue to pay attention to this issue

**Comment by chickenlj** [comment]
Instead of replacement, how about add a new extension with Byte Buddy using Dubbo's SPI. 

@vangoleo Let's bring this awesome idea to dev@dubbo.apache.org for further discussion.

**Comment by vangoleo** [comment]
We already changed to discuss this via dev@dubbo.apache.org, please close this issue.

**Comment by diecui1202** [comment]
Since the discussion has transmitted to the dev mail list, so this issue can be closed. 

@chickenlj @ralf0131 @beiwei30 please help to close it.
