### ISSUE TITLE
[Suggestion] Add checkstyle for CI

### ISSUE THREAD

**Issue by htynkn** [apache/incubator-dubbo#1513]
hey team,

I notice there is some unused code (for example: https://github.com/apache/incubator-dubbo/blob/master/hessian-lite/src/main/java/com/alibaba/com/caucho/hessian/io/Hessian2Input.java#L88)

Looks like dubbo doesn't have checkstyle in maven configuration or it doesn't have correct rule.

do we have any plan to add checkstyle check in CI?

**Comment by ralf0131** [comment]
Strongly +1. Static analysis might produce false positives, but overall I think it is better than not having it.

**Comment by ralf0131** [comment]
Suggestions are expected to be reported to the mailing list dev@incubator.dubbo.apache.org.  Issues are used to track bugs.

**Comment by htynkn** [comment]
@ralf0131 sure thing. next time I will send suggestion to maillist

**Comment by justinmclean** [comment]
Apache runs SonarQube if you want to use that. See https://builds.apache.org/analysis/

**Comment by htynkn** [comment]
I did a quick try. I only apply one basic rule.
According to dubbo [code-conventions](https://github.com/apache/incubator-dubbo/blob/master/CONTRIBUTING.md#code-conventions). 

> If there are more than 120 characters in current line, start a new line.

Checkstyle find more than 6000 Checkstyle violations :(
