### ISSUE TITLE
HTTP协议不像文档描述的那样可以从浏览器，JS中使用呀

### ISSUE THREAD

**Issue by caohenghui** [apache/incubator-dubbo#1515]
HTTP协议不像文档描述的那样可以从浏览器，JS中使用呀，
使用POSTMAN，和各类浏览器，各种水土不服。。。

**Comment by limingwei** [comment]
原本的http协议，似乎不怎么成熟
合进来的dubbox的，可能更好

**Comment by kimmking** [comment]
@caohenghui  which document describe the http protocol can be used in webbrowser？

**Comment by chickenlj** [comment]
We need to figure out the way of using http in browser. Support or not, how to use if support.

**Comment by beiwei30** [comment]
need a blog to explain how http works in dubbo.

**Comment by beiwei30** [comment]
close it for now since I file a new doc bug here: https://github.com/apache/incubator-dubbo-website/issues/298

**Comment by everythingbest** [comment]
hava a look at this : https://github.com/everythingbest/dubbo-postman
