### ISSUE TITLE
请求解决序列化问题

### ISSUE THREAD

**Issue by miaoyinjun** [apache/incubator-dubbo#1516]
服务接口返回List，首个对象是null，输出为：[null]，请问有什么序列化全局配置可以将[null]转换为[]，谢谢

**Comment by zonghaishang** [comment]
@miaoyinjun
Please attach your demo code or unit tests.

**Comment by zonghaishang** [comment]
Would you please consider ask in English? Since this project is moved to ASF repo, we hope it is understandable by people all over the world so that everyone can join to discuss.

  Also, please try to ask by sending an email to dev@dubbo.incubator.apache.org , issues is used to track bugs.

**Comment by kimmking** [comment]
generally it should return null instead of  [] or [null]
@zonghaishang

**Comment by zonghaishang** [comment]
My understanding is that if an empty object, the service provider is free to choose whether to save it in the list.

**Comment by chickenlj** [comment]
Seems to be a project-related problem, feel free to reopen this issue if you have more information
