### ISSUE TITLE
Add java9 in CI build

### ISSUE THREAD

**Issue by htynkn** [apache/incubator-dubbo#1521]
Currently dubbo support java6, java7 and java8.

All unit test pass in java9, we should consider add official support for java9 and even java10.
Currently travis support java9. java10 is in progress (https://github.com/travis-ci/travis-ci/issues/9368)

As discussed in mail list, the first step is to add java9 in travis ci.

**Comment by htynkn** [comment]
Additional informaiton:
[x]All unit test can pass in java9
[x]All javadoc generate pass in java9
[] cobertura-maven-plugin doesn't work with java9

Refer to build logs: https://api.travis-ci.org/v3/job/359231113/log.txt

**Comment by lovepoem** [comment]
Now cobertura-maven-plugin is used to count the unit test  coverage，we should ensure it can work

**Comment by htynkn** [comment]
@lovepoem cobertura reply on com.sun:tools:jar which java9 removed (http://openjdk.java.net/jeps/220).

I don't think cobertura is in maintain any more. Latest release is at 2015 (http://mvnrepository.com/artifact/net.sourceforge.cobertura/cobertura)

**Comment by lovepoem** [comment]
>I don't think cobertura is in maintain any more. Latest release is at 2015 

If so, we can consider other tools:such as coverails……

**Comment by lovepoem** [comment]
Now the java9  ci faild: https://github.com/apache/incubator-dubbo/pull/1611

**Comment by htynkn** [comment]
@lovepoem hey Xin, I figure out the reason for issue 1611. Please refer to my comment for that PR.
The issue for PR 1611 is not related to java9 travis configuration and maven-javadoc-plugin is latest version. I couldn't see much we can improve for travis CI configuration.
Could you close this issue now or after 1611 merged?

**Comment by lovepoem** [comment]
https://github.com/apache/maven-javadoc-plugin has resoled the issue in snapshot version, so we should pay attention to  https://issues.apache.org/jira/projects/MJAVADOC/issues
