### ISSUE TITLE
启动时检查依赖,无论我check设为true或者false，它都不检测直接启动成功

### ISSUE THREAD

**Issue by zeng54088** [apache/incubator-dubbo#1522]

**Comment by ralf0131** [comment]
Hi, welcome!

It's better to ask question via mailing list dev@incubator.dubbo.apache.org. Issues are used to track bugs.

**Comment by zeng54088** [comment]
@zonghaishang 还是不行啊 
dubbo版本为2.6.0
项目A依赖于项目B
==========================================
项目A configuration 如下
@Configuration
public class DubboConfiguration {
    @Bean
    public ApplicationConfig applicationConfig() {
        ApplicationConfig applicationConfig = new ApplicationConfig();
        applicationConfig.setName("provider-test");
        return applicationConfig;
    }

    @Bean
    public RegistryConfig registryConfig() {
        RegistryConfig registryConfig = new RegistryConfig();
        registryConfig.setAddress("zookeeper://192.168.93.87:2182");
        registryConfig.setClient("curator");
        return registryConfig;
    }

    @Bean
    public ProtocolConfig protocolConfig(){
        ProtocolConfig protocolConfig=new ProtocolConfig();
        protocolConfig.setPort(20881);
        protocolConfig.setName("dubbo");
        return protocolConfig;
    }
}
======================================
项目B configuration 如下
@Configuration
public class DubboConfiguration {
    @Bean
    public ApplicationConfig applicationConfig() {
        ApplicationConfig applicationConfig = new ApplicationConfig();
        applicationConfig.setName("provider-test1");
        return applicationConfig;
    }

    @Bean
    public RegistryConfig registryConfig() {
        RegistryConfig registryConfig = new RegistryConfig();
        registryConfig.setAddress("zookeeper://192.168.93.87:2182");
        registryConfig.setClient("curator");
        return registryConfig;
    }

    @Bean
    public ProtocolConfig protocolConfig(){
        ProtocolConfig protocolConfig=new ProtocolConfig();
        protocolConfig.setPort(20880);
        protocolConfig.setName("dubbo");
        return protocolConfig;
    }
}

**Comment by zonghaishang** [comment]
very sorry for the late reply， I think there are other services already started, so 'check' is correct.

You can add breakpoints at the following line of code to determine if invoice.isAvailable() should return true.

com.alibaba.dubbo.config.ReferenceConfig#createProxy:

if (c && !invoker.isAvailable()) {
    throw new IllegalStateException("Failed to check the status of the service " + interfaceName + ". No provider available for the service " + (group == null ? "" : group + "/") + interfaceName + (version == null ? "" : ":" + version) + " from the url " + invoker.getUrl() + " to the consumer " + NetUtils.getLocalHost() + " use dubbo version " + Version.getVersion());
}

yiji

在 2018年3月29日，20:42，zeng54088 <notifications@github.com<mailto:notifications@github.com>> 写道：

@zonghaishang<https://github.com/zonghaishang> 还是不行啊
dubbo版本为2.6.0
项目A依赖于项目B

项目A configuration 如下
@configuration<https://github.com/configuration>
public class DubboConfiguration {
@bean<https://github.com/bean>
public ApplicationConfig applicationConfig() {
ApplicationConfig applicationConfig = new ApplicationConfig();
applicationConfig.setName("provider-test");
return applicationConfig;
}

@Bean
public RegistryConfig registryConfig() {
    RegistryConfig registryConfig = new RegistryConfig();
    registryConfig.setAddress("zookeeper://192.168.93.87:2182");
    registryConfig.setClient("curator");
    return registryConfig;
}

@Bean
public ProtocolConfig protocolConfig(){
    ProtocolConfig protocolConfig=new ProtocolConfig();
    protocolConfig.setPort(20881);
    protocolConfig.setName("dubbo");
    return protocolConfig;
}


}

项目B configuration 如下
@configuration<https://github.com/configuration>
public class DubboConfiguration {
@bean<https://github.com/bean>
public ApplicationConfig applicationConfig() {
ApplicationConfig applicationConfig = new ApplicationConfig();
applicationConfig.setName("provider-test1");
return applicationConfig;
}

@Bean
public RegistryConfig registryConfig() {
    RegistryConfig registryConfig = new RegistryConfig();
    registryConfig.setAddress("zookeeper://192.168.93.87:2182");
    registryConfig.setClient("curator");
    return registryConfig;
}

@Bean
public ProtocolConfig protocolConfig(){
    ProtocolConfig protocolConfig=new ProtocolConfig();
    protocolConfig.setPort(20880);
    protocolConfig.setName("dubbo");
    return protocolConfig;
}


}

**Comment by cvictory** [comment]
@zeng54088  Is the issue ok ? And what is the reason?

**Comment by chickenlj** [comment]
Maybe you already has an existing provider in your registry?? that is to say, check passed??

Feel free to reopen if necessary.
