### ISSUE TITLE
dubbo monitor?

### ISSUE THREAD

**Issue by zhangwanly** [apache/incubator-dubbo#1528]
where is dubbo monitor? how to deploy it? is there some docs for guide? still this one: http://code.alibabatech.com/mvn/releases/com/alibaba/dubbo-monitor-simple/2.4.1/dubbo-monitor-simple-2.4.1-assembly.tar.gz  but i can not access.

**Comment by Nickolas-Evans** [comment]
I have the same question.

同问

**Comment by kimmking** [comment]
@zhangwanly @Nickolas-Evans 
You can get a release of dubbo monitor in two steps:
- Step 1: git clone https://github.com/apache/incubator-dubbo-ops
- Step 2: cd incubator-dubbo-ops && mvn package

Then you will find dubbo-monitor-simple-2.0.0-assembly.tar.gz  in incubator-dubbo-ops\dubbo-monitor-simple\target directory. Unzip it you will find the shell scripts for starting or stopping monitor.

**Comment by zhangwanly** [comment]
@kimmking thank you very much, you are so cool !

**Comment by kimmking** [comment]
[dubbo-registry-simple-2.0.0-assembly.tar.gz](https://github.com/apache/incubator-dubbo/files/1862876/dubbo-registry-simple-2.0.0-assembly.tar.gz)

**Comment by cvictory** [comment]
It is usage question. Please close it.
