### ISSUE TITLE
"dubbo.qos.port" property in dubbo.properties is useless when using dubbo-2.5.10.jar

### ISSUE THREAD

**Issue by hans0v0** [apache/incubator-dubbo#1529]
I want change dubbo.qos.port,and I change "dubbo.qos.port" property in dubbo.properties and add "-Ddubbo.qos.port" TO JAVA_OPT ,but it's useless when I use dubbo-2.5.10.jar.And change to dubbo-2.5.8.jar works fine.Sorry,It's first time I commit issue,I dont know if it's a BUG?

**Comment by ralf0131** [comment]
Hi, welcome!

Would you please update the title and description using English? Dubbo is a global community and we would like the issue to be reviewed by people all over the world.

**Comment by chickenlj** [comment]
Actually, the key is `dubbo.application.qos.port`,  not `dubbo.application.qos.port`.  I have tried and it works.
