### ISSUE TITLE
dubbo admin manual isn't newest

### ISSUE THREAD

**Issue by Itdotaer** [apache/incubator-dubbo#1530]
Hello, I find dubbo has be updated recently. But I found there are some problems,  dubbo admin manual isn't newest. So I couldn't install "demo provider", "demo consumer", "simple configuration center", "simple monitor center".

**install demo provider** [http://dubbo.io/books/dubbo-admin-book-en/install/provider-demo.html](url)
**install demo consumer** [http://dubbo.io/books/dubbo-admin-book-en/install/consumer-demo.html](url)
**install simple configuration center** [http://dubbo.io/dubbo-admin-book-en/install/simple-registry-center.html](url)
**install simple monitor center** [http://dubbo.io/dubbo-admin-book-en/install/simple-monitor-center.html](url)

Please update these files, we suppose we could use mvn command to build sub projects, and then in target files to use these demo functions.

**Comment by ralf0131** [comment]
Hi, welcome!

Would you please update the title and description using English? Dubbo is a global community and we would like the issue to be reviewed by people all over the world.

Yes, this is a known issue. If you have a solution, would you mind send a pr?

**Comment by Itdotaer** [comment]
Updated~

**Comment by nzomkxia** [comment]
the address above have been updated, please visit: http://dubbo.apache.org/books/dubbo-admin-book-en/install/provider-demo.html
