### ISSUE TITLE
在Dubbo的Filter里面无法拿到隐式传参的参数（I can't get the attachment in Dubbo Filter）？

### ISSUE THREAD

**Issue by CoderDade** [apache/incubator-dubbo#1533]
你好，我在 `com.alibaba.dubbo.rpc.Filter` 里面无法拿到 `RpcContext.getContext().getAttachment(key)` 的值，是不是一定只有在提供者方法里面才能拿到？有什么方法吗？
Hello, I just found out that, in `com.alibaba.dubbo.rpc.Filter` I can't get the value of `RpcContext.getContext().getAttachment(key)`  which I can get in the service provider.So is there any way to get value in Filter.Thinks for your reading, and hoping for you answer.

**Comment by kimmking** [comment]
which protocol you used?

**Comment by kimmking** [comment]
If you use rest protocol, you can add a RpcContextFilter as the first filter.

**Comment by techyang** [comment]
I have the same problem 。 I add a traceId param to  invocation.getAttachments  at TraceClientFilter， but i can’t get the param at  TraceServerFilter。Is it a bug to pass a param from client to server?

**Comment by kimmking** [comment]
@techyang @CoderDade you can contact me for more details with weixin id:kimmking
I guess you both use some http-based protocols like rest, then the http body which represent request data can't contains RpcContext.Attachments, then you can add RpcContextFilter  to your potocol, and RpcContextFilter will add/get attachments key-value pairs by http headers.

**Comment by CoderDade** [comment]
@kimmking Well,thanks for @techyang .I found out that the way I got value of the attachment was wrong.I used to get attachments by `RpcContext.getContext().getAttachment(key)`  in the Filter#invoke, but the right way seems to be using `invocation.getAttachment(key)`.And I make it.So it seems to be that I make a mistake.Thanks for your kindly support.

**Comment by techyang** [comment]
@CoderDade , which dubbo version do you use? I used dubbo 2.5.8 and I found both RpcContext.getContext().getAttachment(key)  and invocation.getAttachment(key) methods were not work.

**Comment by CoderDade** [comment]
@techyang 2.5.7

**Comment by chickenlj** [comment]
@CoderDade If you want to use `RpcContext.getContext().getAttachment(key)` , make suer your filter being executed behind `ContextFilter`.

**Comment by chickenlj** [comment]
@techyang Maybe you are facing the problem kimmking mentioned, some protocols: hessian, http, rest don't support passing attachments through RpcContext.attachments. We already have some issue tracking this problem.

If necessary, feel free reopen this issue.
