### ISSUE TITLE
zookeeper 提供者问题？

### ISSUE THREAD

**Issue by erstens** [apache/incubator-dubbo#1536]
zookpeeper 地址是0.22
`provider 是0.33`
请问为什么启动0.33上的dubbo时，在zkcli上看，`provider的地址是0.22?`

**Comment by kimmking** [comment]
what address do you find in zkcli?

**Comment by erstens** [comment]
Thanks very much .
It is work .


I find my hostname is ‘abc’ , and ‘abc’ is already in /etc/hosts ,it is get my hostname ? 
‘abc’ is my zk host .

Original Message
Sender:kimmkingnotifications@github.com
Recipient:apache/incubator-dubboincubator-dubbo@noreply.github.com
Cc:erstenswangao351@sina.com; Authorauthor@noreply.github.com
Date:Monday, Apr 2, 2018 15:38
Subject:Re: [apache/incubator-dubbo] zookeeper 提供者问题？ (#1536)


what address do you find in zkcli?

**Comment by erstens** [comment]
I find :
[dubbo://192.168.0.`22`:9408/xxxxxxxxxxxtimestamp=1522421683855]

[consumer://192.168.0.`22`/xxxxxxxxxxxtimestamp=1522412820653]
But the provider ip is `192.168.0.33` .

**Comment by kimmking** [comment]
you can see more details in provider's log, there you can find which address registering to zk.

**Comment by erstens** [comment]
Ok.Thanks .
