### ISSUE TITLE
Add new contributor guide

### ISSUE THREAD

**Issue by ralf0131** [apache/incubator-dubbo#1537]
Need to add documentation for new contributor to startup, including

1. join to dev mailing list
2. track issue/pr changes
3. how to fix issue, how to merge code, how to add comments
4. how to commit pull request
5. ...

**Comment by ralf0131** [comment]
Updated part 1 in wiki [1]:

https://github.com/apache/incubator-dubbo/wiki/New-contributor-guide

**Comment by kimmking** [comment]
there is not only one way to contribute by issue or pr, join to discuss, provide some  ideas, write  a  blog, review some  codes,dev some tools for dubbo  ecosystem etc

**Comment by ralf0131** [comment]
@kimmking patches welcome
