### ISSUE TITLE
cannot register to zookeeper when use curator version 3.1.0

### ISSUE THREAD

**Issue by deif2005** [apache/incubator-dubbo#1542]
zookeeper服务经客户端连接，可用，使用Curator端，经java调试，可以访问服务。使用multicast可以正常广播和调用服务，唯独使用spring配置dubbo就是无法注册至zookeeper服务。提示KeeperErrorCode = Unimplemented for /dubbo

**Comment by kimmking** [comment]
Can you submit a test case to reproduce this issue?

**Comment by deif2005** [comment]
我发现，能脸上zk服务，但是无法注册服务（可以检测到节点，但是不能注册新节点），后来我添加了zk客户端的引用“<dubbo:registry client="curator" />” 现在出现如下异常提示：Failed to subscribe consumer://192.168.1.69/com.alibaba.dubbo.registry.RegistryService?application=dubbodemo-provider&callbacks=10000&client=curator&connect.timeout=10000&dubbo=2.6.1&interface=com.alibaba.dubbo.registry.RegistryService&lazy=true&methods=lookup,subscribe,unsubscribe,unregister,register&pid=6064&reconnect=false&sticky=true&subscribe.1.callback=true&timeout=10000&timestamp=1522746885823&unsubscribe.1.callback=false, cause: Failed to invoke the method subscribe in the service com.alibaba.dubbo.registry.RegistryService. No provider available for the service com.alibaba.dubbo.registry.RegistryService from registry 0.0.0.0:9090 on the consumer 192.168.1.69 using the dubbo version 2.6.1. Please check if the providers have been started and registered.

**Comment by deif2005** [comment]
问题的原因找到了，由于项目之前在其它模块使用了curator的包，版本号是3.1.0，引用了该模块后导致了无法创建节点的问题，现在使用了2.7.1，现在一切都正常了。谢谢！

**Comment by lovepoem** [comment]
Can you use curator v3.1.0 and exclude 2.7.1, try to verify whether your project run well？ @deif2005

**Comment by ralf0131** [comment]
Hi, welcome!

Would you please update the title and description using English? Dubbo is a global community and we would like the issue to be seen by people all over the world.

Questions like this are expected to be asked in the mailing list, you can [subscribe](https://github.com/apache/incubator-dubbo/issues/1393) and ask there.

**Comment by chickenlj** [comment]
> cause: Failed to invoke the method subscribe in the service com.alibaba.dubbo.registry.RegistryService. No provider available for the service com.alibaba.dubbo.registry.RegistryService from registry 0.0.0.0:9090 

Seems like you have an internal Registry (RegistryService) implementation inside your Org.
Please make sure your registry on 0.0.0.0:9090  works fine.
