### ISSUE TITLE
multiple registry centers or one registry center cluster?

### ISSUE THREAD

**Issue by deidei** [apache/incubator-dubbo#1546]
I use zookeeper as my registry center and I have three servers. Now I have two choices to deploy zookeeper registry center:
1. three in standalone mode
 <dubbo:registry address="10.20.141.150:9090|10.20.154.177:9010|10.20.153.157:9050" />
2. one in leader mode, the other two in follower mode
 <dubbo:registry address="10.20.141.150:9090,10.20.154.177:9010,10.20.153.157:9050" />

Which one is the best practice?

**Comment by lovepoem** [comment]
Agree with @johnament

**Comment by deidei** [comment]
@zonghaishang  thank you
