### ISSUE TITLE
centos7 start.sh启动 报 Ncat: Connection refused

### ISSUE THREAD

**Issue by XiaoDongJi** [apache/incubator-dubbo#1547]
使用2.5.4打包dubbo-demo-provider-2.5.4-SNAPSHOT，在centos7中start.sh启动报错。
./start.sh
Starting the demo-provider ....Ncat: Connection refused.
.Ncat: Connection refused.
.Ncat: Connection refused.
.Ncat: Connection refused.

请问是不兼容吗

**Comment by YFCoder2** [comment]
求问 start.sh 脚本您是从哪里获得的

**Comment by foreveryang321** [comment]
https://github.com/apache/incubator-dubbo/blob/master/dubbo-container/dubbo-container-api/src/main/resources/META-INF/assembly/bin/start.sh

**Comment by XiaoDongJi** [comment]
@YFCoder2 maven直接打包会放bin目录里面，放的是 dubbo-container-api里面得脚本，楼上贴得目录

**Comment by ralf0131** [comment]
Hi, welcome!

Would you please update the title and description using English? Dubbo is a global community and we would like the issue to be seen by people all over the world.

Questions like this are expected to be asked in the mailing list, you can [subscribe](https://github.com/apache/incubator-dubbo/issues/1393) and ask there.

**Comment by chickenlj** [comment]
Where do you get the source code of 2.5.4?

I remember there are log files generated in a specific directory, check logs to find more details of the exception.
