### ISSUE TITLE
Two question about "thrift" protocol in dubbo ,may be bugs？check it please

### ISSUE THREAD

**Issue by celesky** [apache/incubator-dubbo#1559]
## **Question 1：**
when the "protocol" of provider is thrift, the "version" attribute is not work well.
You can easily reproduce this problem like this 
eg:
**provider：**
 _<dubbo:service interface="com.hola.myrpc.dubbo.api.dthrift.HelloDthriftApi$Iface" ref="helloThriftServiceImpl"  protocol="thrift" loadbalance="consistenthash" **version="1.0.0"**>
    </dubbo:service>_
**consumer：**
_<dubbo:reference id="helloThriftService" interface="com.hola.myrpc.dubbo.api.dthrift.HelloDthriftApi$Iface" retries="0" check="false"
**version="1.0.0"** />_

I traced the code ,the keys in the **ThriftProtocol.exporterMap** is "com.xxxx.ThriftApi$Iface:1.0.0:33032",but the serviceKey is "com.xxxx.ThriftApi$Iface:33032", there is not version attribute in the invocation object,so it can't match.

## **Question 2:**
when the "protocol" of provider is thrift, the parameters of method can not be boolean，even just one of them is a bool type.
You can easily reproduce this problem like this ：

eg： 
**thrift file:**
_namespace java com.hola.myrpc.dubbo.api.dthrift
 service HelloDthriftApi{
     string hello(1:string name),
     string helloBool(1:bool boo)
 }_

     @Test
    public  void testHelloThriftApi() {
        try{
            ClassPathXmlApplicationContext context = new ClassPathXmlApplicationContext(new String[] {"dubbo-test.xml"});
            final HelloDthriftApi.Iface helloService = (HelloDthriftApi.Iface)context.getBean("helloThriftService"); 
            String msg  = helloService.hello("tom");
            System.out.println("msg = " + msg);//work well
            **String msg2  = helloService.helloBool(true); //does not work ,and throw exception of timeout**
            System.out.println("msg2 = " + msg2);
        }catch (Exception e){
            e.printStackTrace();
        }
    }

dependency like this:

		<dependency>
			<groupId>org.apache.thrift</groupId>
			<artifactId>libthrift</artifactId>
			<version>0.11.0</version>
		</dependency>

		<dependency>
			<groupId>com.alibaba</groupId>
			<artifactId>dubbo</artifactId>
			<version>2.6.1</version>
			<exclusions>
				<exclusion>
					<groupId>org.apache.thrift</groupId>
					<artifactId>libthrift</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

--------------
**exception info** 
com.alibaba.dubbo.rpc.RpcException: Failed to invoke the method helloBool in the service com.hola.myrpc.dubbo.api.dthrift.HelloDthriftApi$Iface. Tried 1 times of the providers [192.168.0.106:33032] (1/1) from the registry 127.0.0.1:2181 on the consumer 192.168.0.106 using the dubbo version 2.6.1. Last error is: Waiting server-side response timeout by scan timer. start time: 2018-04-07 20:38:26.827, end time: 2018-04-07 20:38:27.835, client elapsed: 6 ms, server elapsed: 1002 ms, timeout: 1000 ms, request: Request [id=1, version=2.0.0, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=helloBool, parameterTypes=[boolean], arguments=[true], attachments={path=com.hola.myrpc.dubbo.api.dthrift.HelloDthriftApi$Iface, class.name.generator=dubbo, interface=com.hola.myrpc.dubbo.api.dthrift.HelloDthriftApi$Iface, version=0.0.0}]], channel: /192.168.0.106:56228 -> /192.168.0.106:33032
	at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:101)
	at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:233)
	at com.alibaba.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:70)

-------------------------------------------
1.provider 协议为thrift时，consumer端version设置无效。
即假设provider端设置了version=“1.0.0”，consumer端设置version也无效。
exporterMap里面为的com.xxxx.thriftApi$Iface:1.0.0:33032
而接收到的serviceKey永远都是com.xxxx.thriftApi$Iface:33032

2.当provider协议为thrift时，provider提供的方法参数里面不能用boolean，一旦有一个参数为boolean值就会调用失败。报的是超时错误，看了下代码，似乎provider端根本就没收到请求

dubbo版本2.6.1
libthrift 0.11.0
帮忙了解一下
--------------------------------

**Comment by lovepoem** [comment]
Hi, Welcome!

Would you please consider ask in English? Since this project is moved to ASF repo, we hope it is understandable by people all over the world so that everyone can join to discuss.

Also, please try to ask by sending an email to dev@dubbo.incubator.apache.org-->[Subscribe guide](https://github.com/ApacheInfra/dubbo/issues/1393) , issues is used to track bugs.

**Comment by lovepoem** [comment]
What's the version of your dubbo.jar? now the version of  libthrift in dubbo is low. Please paste some error logs.

Now a patch：https://github.com/apache/incubator-dubbo/pull/1380 is in progress

**Comment by diecui1202** [comment]
Feel free to reopen.
