### ISSUE TITLE
Dubbo best practice case application, fully automatic open source framework Emsite.

### ISSUE THREAD

**Issue by empireaaron** [apache/incubator-dubbo#1565]
We hope that Dubbo team can quickly upgrade to Apache top projects, apply for the best use demonstration project of Dubbo.      https://gitee.com/hackempire/emsite-parent

**Comment by ralf0131** [comment]
Hi, welcome!

Would you please update the title and description using English? Dubbo is a global community and we would like the issue to be seen by people all over the world.

Questions like this are expected to be asked in the mailing list, you can [subscribe](https://github.com/apache/incubator-dubbo/issues/1393) and ask there.

**Comment by kimmking** [comment]
Thanks for a wonderful integration framework.
But I guess the "best practices" were some principals from many production biz system, those contained experience of using dubbo to design, development, testing, deployment and maintainance.

**Comment by beiwei30** [comment]
thanks for ur best wish, let's close this issue for now.
