### ISSUE TITLE
Is there any deadline to release a version?

### ISSUE THREAD

**Issue by litttlefisher** [apache/incubator-dubbo#1571]

**Comment by litttlefisher** [comment]
Which can be used in dubbo-spring-boot

**Comment by wzlee** [comment]
@litttlefisher  https://github.com/apache/incubator-dubbo-spring-boot-project

**Comment by litttlefisher** [comment]
[issue91](https://github.com/apache/incubator-dubbo-spring-boot-project/issues/91)
It's said that dubbo-spring-boot is waiting dubbo 2.5.11

**Comment by kimmking** [comment]
@mercyblitz

**Comment by ralf0131** [comment]
Hi, we are going to discuss the release schedule in the mailing list this week. Please [subscribe](https://github.com/apache/incubator-dubbo/issues/1393) and you will get notified.

Since this is the first Apache release, it will take some time to follow the Apache release policy.
