### ISSUE TITLE
load balance question after new provider member joins.

### ISSUE THREAD

**Issue by shinestarwang** [apache/incubator-dubbo#1586]
遇到的情况是这样的：
新增8台服务器(provider)，旧的8台服务器的被请求次数明显比新增的服务器被调用次数多很多
(new 8 providers,but old 8 providers be requested more than new providers )
策略使用的roundrobin
dubbo version：2.5.3
容错机制：failover
weight权重都是100

**Comment by chickenlj** [comment]
Are the weight value of all providers the same?

**Comment by chickenlj** [comment]
Please subscribe to dev@dubbo.apache.org to discuss questions like this, just send your questions to this mail address, and we will guarantee a better and quicker reply there.

How to subscribe, see #1393.

**Comment by shinestarwang** [comment]
provider interface throws business Exceptions,  affect load balance?

**Comment by chickenlj** [comment]
> provider interface throws business Exceptions, affect load balance?

Nope!

**Comment by chickenlj** [comment]
Everything works fine now?

**Comment by shinestarwang** [comment]
not balanced

**Comment by chickenlj** [comment]
Weird, Roundrobin turns out to be simple and stable enough. Have you tried restart all providers? still the same traffic distribution?

**Comment by shinestarwang** [comment]
restart all providers? yes
but server never restart

**Comment by beiwei30** [comment]
let's close it for now.
