### ISSUE TITLE
How to get Session info using dubbo Filter?

### ISSUE THREAD

**Issue by CoderDade** [apache/incubator-dubbo#1590]
我正在做dubbo的权限认证，现在发现我没有办法在dubbo filter里面获取当前用户的session信息。系统是通过HttpServletRequest实时获取用户信息的，但是在filter里面我无法注入HttpServletRequest，请问有什么方案或者建议吗？

**Comment by chickenlj** [comment]
Please subscribe to dev@dubbo.apache.org to discuss questions like this, just send your questions to this mail address, and we will guarantee a better and quicker reply there.

**Comment by CoderDade** [comment]
@chickenlj OK，thx.

**Comment by chickenlj** [comment]
I don't think you can mix a dubbo service with Servlet, unless you choose to use `rest` or some other http based protocols in dubbo. 

Also, i think if your session was customized and stored in a centralized remote center, you can easily get your the cache from the dubbo filter.
