### ISSUE TITLE
Monitor stats not accurate

### ISSUE THREAD

**Issue by jpzhang1230** [apache/incubator-dubbo#1592]
发现一个问题，在启用simple-monitor时，发现第一次调用rpc时，触发MonitorFilter的collect方法时，
Monitor monitor = monitorFactory.getMonitor(url);
            if (monitor == null) {
                return;
            }
此时的monitor为空。后续接着调用rpc时，monitor又不为空。所以怀疑是MonitorFactory延迟加载导致。这里会导致一个问题，就是Collect的数量总是比实际少几条。

**Comment by beiwei30** [comment]
it's relevant to https://github.com/apache/incubator-dubbo/pull/777

**Comment by chickenlj** [comment]
We think monitoring data don't need to be accurate, though we will try to record every RPC statistics, it should not block the RPC process.

**Comment by chickenlj** [comment]
Feel free to reopen this issue if necessary.

Next time, please use english, also, you can subscribe to dev@dubbo.apache.org to discuss questions like this, just send your questions to this mail address, and we will guarantee a better and quicker reply there.

How to subscribe, see #1393.
