### ISSUE TITLE
dubbox 2.6.1版本fst序列化，provider端新增字段，consumer端报错

### ISSUE THREAD

**Issue by runformydream** [apache/incubator-dubbo#1596]
dubbox 2.6.1版本，使用fst序列化，provider端返回对象新增字段时，consumer端代码不变，consumer端反序列化报错。现在只能用version来解决，这种解决方式不优雅，有更好的方式吗？

**Comment by chickenlj** [comment]
Please use english for a global community, also, we suggest send to dev@dubbo.apache.org for any questions like this.

**Comment by chickenlj** [comment]
What do you mean by "without consumer side code change" and "version"?  The version mechanism provided by fst?

With infos provided, it's like limits of fst itself.

**Comment by chickenlj** [comment]
Feel free to reopen this issue if necessary.
