### ISSUE TITLE
示例提供者安装链接无法访问404

### ISSUE THREAD

**Issue by Leon-YSL** [apache/incubator-dubbo#1600]
Dubbo用户手册(中文)  > 2 快速启动
示例提供者安装 链接http://dubbo.io/books/dubbo-admin-book/install/provider-demo.html 无法访问404

**Comment by lovepoem** [comment]
The new url is http://dubbo.apache.org/books/dubbo-admin-book/install/provider-demo.html

I think https://github.com/apache/incubator-dubbo-docs/pull/15 will fix it

**Comment by nzomkxia** [comment]
the address has been updated
