### ISSUE TITLE
dubbo v2.6.1 @Service(retries=0)

### ISSUE THREAD

**Issue by rambosir** [apache/incubator-dubbo#1602]
retries=0不生效，请问是因为retries默认也是0的原因吗？

**Comment by zonghaishang** [comment]
duplicate with https://github.com/apache/incubator-dubbo/issues/1421

**Comment by rambosir** [comment]
@zonghaishang thanks!

**Comment by stoneapple** [comment]
@zonghaishang when using failover cluster with service annotation, retries =0 , retry option also happens if first time invoke failes, is this a bug to fix

**Comment by rambosir** [comment]
@stoneapple you need set retries=-1
