### ISSUE TITLE
typo in architecture graph

### ISSUE THREAD

**Issue by DayuZhu** [apache/incubator-dubbo#1625]
1，Dubbo的开发文档中文版中的框架设计 整体设计图的 ExchangeExchangeSerever 是不是拼写错误？！
2，DubboHandler这个handler还有么？尴尬的是我没有搜到！
[
![qq 20180418175356](https://user-images.githubusercontent.com/18682988/38925416-22795fbe-4332-11e8-8d13-6b0b8e3addc1.png)
](url)

**Comment by chickenlj** [comment]
1. `ExchangeSerever` seems to be a typo. Would you please file an issue in the doc [apache/incubator-dubbo-docs](https://github.com/apache/incubator-dubbo-docs)

2. Good for you to notice the absent of `DubboHandler` in code base. I think `DubboHandler` in architecture refer to [DubboProtocol/requestHandler](https://github.com/apache/incubator-dubbo/blob/6742d1cd0f47bf609d320474d9639324f54769f6/dubbo-rpc/dubbo-rpc-dubbo/src/main/java/com/alibaba/dubbo/rpc/protocol/dubbo/DubboProtocol.java#L72), requestHandler doesn't need to be an `ExchangeHandler`, maybe 'HttpHandler' in WebserviceProtocol we should define a 'DubboHandler'. What do you guys think?

**Comment by ralf0131** [comment]
This issue has been tracked in https://github.com/apache/incubator-dubbo-docs/issues/24
