### ISSUE TITLE
dubbo 进程状态资讯

### ISSUE THREAD

**Issue by goal578** [apache/incubator-dubbo#1628]
生产系统有个dubbo服务偶尔出现客户端连不上了，但是telnet Ip 端口是可以通。然后用 telnet 命令 看相关状态，请问有些参数什么意思？如 max,total,task
+------------+--------+--------------------------------------------------------+
| resource   | status | message                                                |
+------------+--------+--------------------------------------------------------+
| spring     | OK     | applicationContext.xml                                 |
| memory     | OK     | max:8122M,total:8122M,used:2996M,free:5126M            |
| threadpool | OK     | Pool status:OK, max:100, core:100, largest:100, active:2, task:2821428, service port: 
| load       | OK     | load:0.99,cpu:4                                        |
| summary    | OK     |                                                        |
+------------+--------+--------------------------------------------------------+

**Comment by kimmking** [comment]
nice work

**Comment by mercyblitz** [comment]
Please reference this : http://dubbo.apache.org/books/dubbo-dev-book/impls/status-checker.html
