### ISSUE TITLE
How to stress test Dubbo RPC in Jmeter?

### ISSUE THREAD

**Issue by ningyu1** [apache/incubator-dubbo#1632]
"Dubbo Plugin for Apache JMeter" is a plug-in developed for testing Dubbo interfaces in Jmeter.

[github: jmeter-plugin-dubbo](https://github.com/ningyu1/jmeter-plugins-dubbo) 
[gitee: jmeter-plugin-dubbo](https://gitee.com/ningyu/jmeter-plugins-dubbo)

<a href="https://github.com/ningyu1/jmeter-plugins-dubbo/releases"><img src="https://img.shields.io/github/release/ningyu1/jmeter-plugins-dubbo.svg?style=social&amp;label=Release"></a>&nbsp;<a href="https://github.com/ningyu1/jmeter-plugins-dubbo/stargazers"><img src="https://img.shields.io/github/stars/ningyu1/jmeter-plugins-dubbo.svg?style=social&amp;label=Star"></a>&nbsp;<a href="https://github.com/ningyu1/jmeter-plugins-dubbo/fork"><img src="https://img.shields.io/github/forks/ningyu1/jmeter-plugins-dubbo.svg?style=social&amp;label=Fork"></a>&nbsp;<a href="https://github.com/ningyu1/jmeter-plugins-dubbo/watchers"><img src="https://img.shields.io/github/watchers/ningyu1/jmeter-plugins-dubbo.svg?style=social&amp;label=Watch"></a> <a href="https://opensource.org/licenses/MIT"><img src="https://img.shields.io/badge/license-MIT-blue.svg"></a>

[how to use？](https://ningyu1.github.io/site/post/60-jmeter-plugins-dubbo-support/)

**Comment by chickenlj** [comment]
Great plugin.

I think this plugin can be a great complement for the upcoming dubbo benchmark project. 
Please send an email to dev@dubbo.apache.org, i think @diecui1202 and some other guys will follow up there.

**Comment by ralf0131** [comment]
Would you please update the title and description using English? Dubbo is a global community and we would like the issue to be seen by people all over the world.

**Comment by diecui1202** [comment]
Congratulations. Welcome to Dubbo eco-system.

**Comment by diecui1202** [comment]
It seems that this issue can be closed.

**Comment by lovepoem** [comment]
Now the project is transferred to dubbo group : https://github.com/dubbo/jmeter-plugins-dubbo
Congratulations!
