### ISSUE TITLE
Issue about the provider side parameter validation

### ISSUE THREAD

**Issue by stefli** [apache/incubator-dubbo#1637]
**Background**
We use JSR303 validation protocol, and use hibernate as implementation of JSR303 protocol.

**Version**
Dubbo version 2.5.3
 
**Problem Description**
Recently, we want to use the validation on the provider side(No issue on the consumer side). But we can't get the validation errors on the consumer side after configured the validation="true" to the service on the provider side. We try to use the ExceptionHandler to parse the exception returned,but we can't get the validation errors. The exception returned is RpcException with RemotingException clause, but we need RpcException with ConstraintViolationException clause. Because we can get the failed property name and the validation error from ConstraintViolationException directly.

We have analysised the ValidationFilter, it throws new RpcException when validation failed.
```
} catch (Throwable t) {
                throw new RpcException(t.getMessage(), t);
            }
```

 And the exception will be wrapped with RemotingException when result status is not equal to OK and SERVER_TIMEOUT in another class.

The recent version of ValidationFilter has been upgrade to return RpcResult, but it seems not completely.
```
} catch (Throwable t) {
                return new RpcResult(t);
            }
```

**Candidate Solution**
To fix this issue, we add two more files to wrap the property name and validation error from the hibernate validator, and return to client. 

The code snippet:

```
Set<CustomConstraintViolation> set = rewriteFromConstraintViolationException();
return new RpcResult(new RpcException(new CustomConstraintViolationException(set)));

// Replace javax.validation.ConstraintViolation with CustomConstraintViolation
// Replace javax.validation.ConstraintViolationException with CustomConstraintViolationException

```

We have tried to return javax.validation.ConstraintViolationException directly
```
return new RpcResult(new RpcException(new ConstraintViolationException(set)));
```

But failed with ConstraintDescriptorImpl deserialization with some error likes "ConstraintDescriptorImpl could not be instantiated.". Because the ConstraintDescriptorImpl has no empty constructor and can't be instantiated when deserialization. So create above two custom classes to rewrite the exception.

Then the ExceptionHandler can handle the RpcException, and retrieve the property name & validation error from CustomConstraintViolationException.

**Comment by ralf0131** [comment]
Hi, welcome!

Would you mind send a pull request?

**Comment by stefli** [comment]
@ralf0131 My colleague will contact the developer later and send th PR to the developer team.

**Comment by chickenlj** [comment]
Thanks for your report. I have got some questions:

1. What do you exactly mean by `The recent version of ValidationFilter has been upgrade to return RpcResult, but it seems not completely.`? I don't fully understand.
```java
} catch (Throwable t) {
      return new RpcResult(t);
}
```

2. I don't think `new RpcResult(new RpcException(new ConstraintViolationException(set)));` is a good practice, mixing RpcResult with RpcException.

3. 
> But failed with ConstraintDescriptorImpl deserialization with some error likes "ConstraintDescriptorImpl could not be instantiated."

Isn't this caused by dependency absent or version mismatch? At least, i don't understand the difference of extending ConstraintViolationException with a customized class.

**Comment by stefli** [comment]
@chickenlj The issue might happen in a certain environment, i need more test later. I found that the default implementation works in pure dubbo application without web environment.
So, i'll give more details about the process later.

**Comment by stefli** [comment]
@cthistle @ralf0131 
Latest news:
After some tests, we found that this issue only occured when using url="dubbo://xxx" in local environment. 

- **Scene (Use url property, such as url="dubbo://localhost:20880")**

Invoker -> ExceptionFilter -> ValidationFilter -> Vadation Failed -> DefaultFuture

The method returnFromResponse  of the class DefaultFurture will wrap the ConstraintViolationException to RemotingException when RpcResult status is not equal to OK/TIMEOUT, and return to consumer side. Then we can't convert RemotingExceptioin to ConstraitViolationException to get all the validation errors.
1. return new RpcExeption(t.getMessage(), t) - old version
Just wrap the ConstraintViolationException to RemotingException, unfriendly to consumer side.
2. return new RpcResult(t) - latest version
Throw a hession serialization issue as mentioned before, **seems the validation happened on the provider side.**

Code snippet of DefaultFuture.class:
```
private Object returnFromResponse() throws RemotingException {
        Response res = response;
        if (res == null) {
            throw new IllegalStateException("response cannot be null");
        }
        if (res.getStatus() == Response.OK) {
            return res.getResult();
        }
        if (res.getStatus() == Response.CLIENT_TIMEOUT || res.getStatus() == Response.SERVER_TIMEOUT) {
            throw new TimeoutException(res.getStatus() == Response.SERVER_TIMEOUT, channel, res.getErrorMessage());
        }
        throw new RemotingException(channel, res.getErrorMessage()); 
    }
```

**Conclusion: Only the customization might fix the issue or DO NOT use this configuration when using validation.**

- **Scene (without url property)**

Works fine. But, it **seems the validation happened on the consumer side, not really on the provider side.**

**Conclusion: Works fine, but can't solve the validation issue when debug in local environment.**

Pls help confirm.
