### ISSUE TITLE
[Codecov configuration] PR failing if test coverage went down

### ISSUE THREAD

**Issue by htynkn** [apache/incubator-dubbo#1638]
As discuss in mail list: https://lists.apache.org/thread.html/cf55ed71de3ebeaa7db3a6a81ee1a6dc86ceeac2c2b185ea56e6391d@%3Cdev.dubbo.apache.org%3E

For pull request, we ask every pull request has necessary unit test. 
Codecov has a feature to fail PR if test coverage went down. Which means for any pull request, if it add some code without any unit test, the PR will fail.
This can help to increase test coverage.

Considering tiny change, we need a threshold value which allow the coverage to drop by X%, and posting a success status. Please find more detail in mail list link

Related links:
https://docs.codecov.io/docs/commit-status
https://github.com/codecov/support/issues/351

**Comment by ralf0131** [comment]
Done.
