### ISSUE TITLE
dubbo 中文文档瑕疵

### ISSUE THREAD

**Issue by Sidneyxt** [apache/incubator-dubbo#1639]
![image](https://user-images.githubusercontent.com/20471875/39027393-400e1eea-4484-11e8-9714-fa624d14a590.png)

**Comment by ralf0131** [comment]
Hi, welcome!

Would you please send a pull request? The documentation is hosted in: https://github.com/apache/incubator-dubbo-docs

**Comment by Sidneyxt** [comment]
Sure

**Comment by chickenlj** [comment]
Should be tracked with the the new ticket. Close this one.
