### ISSUE TITLE
dubbo app is shown in running status on dubbo admin even after it stops already.

### ISSUE THREAD

**Issue by eatnoodlenosoup** [apache/incubator-dubbo#1640]
为什么我的dubbo应用都停了，admin界面还显示在运行

**Comment by chickenlj** [comment]
Do you use [the latest dubbo-admin source code](https://github.com/apache/incubator-dubbo-ops/tree/master/dubbo-admin), i remember this problem have been fixed. Can you reproduce by start -> stop your application? If you restart the admin ops, will the services gone?

Also, we suggest a more meaningful title clarifying your question, english for a global community.

**Comment by diecui1202** [comment]
Feel free to reopen if necessary.
