### ISSUE TITLE
[Enhancement] the algorithm of load issue on Windows

### ISSUE THREAD

**Issue by mercyblitz** [apache/incubator-dubbo#1641]
@alphatan 

---
My research of this problem.

According to [this answer](https://stackoverflow.com/a/28751028/5671078) of the question "Alternate of getSystemLoadAverage() for Windows?", the method  `getSystemLoadAverage`  of java.lang.management.OperatingSystemMXBean would return `-1` in `Windows`.

It'd be suggested to use `com.sun.management.OperatingSystemMXBean` and its `getSystemCpuLoad()` and `getProcessCpuLoad()` instead.

**Comment by diecui1202** [comment]
@mercyblitz Any progress with this ?
