### ISSUE TITLE
After the dubbox merge, can we integrate the swagger UI to generate the API documentation for the rest protocol?

### ISSUE THREAD

**Issue by li-keli** [apache/incubator-dubbo#1642]
dubbo version: `2.6.1`

> dubbox 合并进来后，如何使用swagger来生成rest协议的api文档？或者说，集成swagger UI进来的大致思路是什么呢？

> After the dubbox merge, how do you use the swagger to generate the API documentation for the rest protocol? Or, what's the general idea of integrating the swagger UI?

**Comment by chickenlj** [comment]
That's a good point, we are planning this as part of our eco-system.

Would you please translate into English? So more people can get involved.

**Comment by li-keli** [comment]
Has the authorities already had plans? I've also been working on this recently, hoping to contribute code based on official design.

**Comment by ralf0131** [comment]
Hi, any contribution is welcome!

**Comment by kimmking** [comment]
@All, I had achieve the integration with dubbo-rest and swaggerUI in last year.
And then, I will merge it to dubbo soon.

**Comment by li-keli** [comment]
@kimmking Is it true? That's very kind of you, thanks for your contribution.
