### ISSUE TITLE
message can not send,becaues channel is closed

### ISSUE THREAD

**Issue by thanks0rf** [apache/incubator-dubbo#1649]
消费者和服务提供方不在一个机房，进行网络调整，比如机房间网络专线调整，消费端产生message can not send 报错，消费端无法进行自动恢复，每次重启消费端服务才能恢复？

**Comment by carryxyh** [comment]
I am afraid this is the case now. Because the Provider address registered on zk is wrong (due to network adjustment).

**Comment by carryxyh** [comment]
@thanks0rf 
I will close this issue.
Reopen if still have problems with it.
