### ISSUE TITLE
dubbo.protocol.port 不配置或-1 会自动选择端口，但是启动抱错

### ISSUE THREAD

**Issue by Dreampie** [apache/incubator-dubbo#165]
sudo ./bin/restart.sh
ERROR: The security-provider does not started!
Starting the xxxx ....nc: invalid option -- '1'
usage: nc [-46DdhklnrStUuvzC] [-i interval] [-p source_port]
      [-s source_ip_address] [-T ToS] [-w timeout] [-X proxy_version]
      [-x proxy_address[:port]] [hostname] [port[s]]

**Comment by Dreampie** [comment]
dubbo.container=logback,spring
dubbo.application.name=xxx
dubbo.application.owner=Dreampie

dubbo.registry.protocol=zookeeper
dubbo.registry.address=xxx

dubbo.monitor.protocol=registry

dubbo.protocol.name=dubbo
dubbo.protocol.accesslog=true
dubbo.protocol.accepts=1000

dubbo.service.loadbalance=roundrobin

**Comment by diecui1202** [comment]
@Dreampie Could you provide a demo to reproduce this problem? Also, please check your restart.sh.

**Comment by diecui1202** [comment]
This issue is too old to track. Feel free to reopen if necessary.
