### ISSUE TITLE
[Release] Sync 2.6.2-SNAPSHOT to master branch

### ISSUE THREAD

**Issue by mercyblitz** [apache/incubator-dubbo#1656]

**Comment by mercyblitz** [comment]
@ralf0131 Ok

**Comment by chickenlj** [comment]
Good suggestion to keep master a SNAPSHOT version.

How about doing this when release of v2.6.2 finished.

**Comment by mercyblitz** [comment]
@chickenlj  Keeping 2.6.2-SNAPSHOT before 2.6.2 release, and Update 2.6.3-SNAPSHOT after 2.6.2

**Comment by ralf0131** [comment]
Done.
