### ISSUE TITLE
hessian-lite  performance

### ISSUE THREAD

**Issue by whanice** [apache/incubator-dubbo#1659]
I made a simply performance test in my mac to messure hessian.
the result is 
```
Benchmark                      Mode  Cnt     Score     Error  Units
Hessian4PerfTest.deserial     thrpt   30  4068.415 ± 189.925  ops/s
HessianLitePerfTest.deserial  thrpt   30  1941.054 ±  77.005  ops/s
```
We can see hessian4(4.0.37) performs much better than hessian-lite(3.2.2) in deserialization.

So here comes the question 
- What is the difference between hessian-lite(3.2.2) and hessian3?
- Can sync with hessian4?

**Comment by lovepoem** [comment]
I think you should send a mail to dev@dubbo.apache.org to discuss the relation between  hesssian-lite and origin hessian

**Comment by whanice** [comment]
@lovepoem  ok.  I will try to use the mail.

**Comment by beiwei30** [comment]
@whanice it's nice if you could provide how you perform the test.

**Comment by whanice** [comment]
@beiwei30 you can see at [here](https://github.com/whanice/examples/tree/master/src/main/java/com/whanice/code/examples/hessian)

**Comment by whanice** [comment]
fixed  and close it

**Comment by lovepoem** [comment]
Related to https://github.com/apache/incubator-dubbo/issues/2508
