### ISSUE TITLE
dubbo2.5.11 in your incubator-dubbo-spring-boot-project-0.2.0  miss

### ISSUE THREAD

**Issue by 595979101** [apache/incubator-dubbo#1660]
![1524486542 1](https://user-images.githubusercontent.com/38642570/39126659-88cbc250-4735-11e8-9ee2-7bd91d138c4e.jpg)

**Comment by kimmking** [comment]
the latest release version is 2.5.10

**Comment by ralf0131** [comment]
Please try the latest version 2.6.1, if you still have the problem, please re-open this issue.
