### ISSUE TITLE
dubbo-test 这个下面的测试用例哇,都报一样的错误

### ISSUE THREAD

**Issue by dlhf** [apache/incubator-dubbo#1661]
![image](https://user-images.githubusercontent.com/26599669/39129572-6c44011c-473d-11e8-81e0-2d0d3e5ca2ab.png)

**Comment by beiwei30** [comment]
cannot reproduce. it works on my laptop. there's one thing you may need to pay attention to, which is, you need to specify `-Djava.net.preferIPv4Stack=true` before you launch the application.
