### ISSUE TITLE
服务提供方能主动通知消费方么？

### ISSUE THREAD

**Issue by penweizgx** [apache/incubator-dubbo#167]
比如消费端要监控服务端用户登录情况（当用户登录的时候，将消息发送给消费方监控平台），现在好像都是消费端主动去调用服务端，有没有服务端主动推送给消费方的方法？

**Comment by justein** [comment]
服务端的推送可以尝试下websocket。

**Comment by 545923664** [comment]
呵呵

**Comment by zhiying8710** [comment]
参见: http://dubbo.io/User+Guide-zh.htm#UserGuide-zh-%E5%8F%82%E6%95%B0%E5%9B%9E%E8%B0%83

**Comment by lovepoem** [comment]
The dubbo is a rpc framewok. I think you can use mq to implement this business logic
