### ISSUE TITLE
Monitor Bug : could cause memory leak

### ISSUE THREAD

**Issue by caisirius** [apache/incubator-dubbo#1670]
When DNS Server error happened, dubbo monitor could cause memory leak and FullGC:

https://blog.csdn.net/caisirius/article/details/78558666

**Comment by ralf0131** [comment]
Hello, welcome to the community!

I've read about your well written article analyzing this issue, would you mind send pull request to fix this issue?

**Comment by ralf0131** [comment]
Thanks for reporting, I will close this issue.
