### ISSUE TITLE
Enhance the test coverage part-1 : dubbo-cluster module

### ISSUE THREAD

**Issue by lovepoem** [apache/incubator-dubbo#1679]
Add test case: dubbo-cluster module

**Comment by ralf0131** [comment]
Lets's add them to [project](https://github.com/apache/incubator-dubbo/projects/1) when finished.

**Comment by lovepoem** [comment]
>Lets's add them to project when finished.

Added

**Comment by lovepoem** [comment]
Claim

**Comment by lovepoem** [comment]
close via #1885
