### ISSUE TITLE
被代理过的Spring bean 无法使用@Service(version="1.0")

### ISSUE THREAD

**Issue by xtea** [apache/incubator-dubbo#168]
一般使用事务(AOP)的被代理的bean里，没法使用@Service(version="1.0") 来进行服务发布。只能通过xml的配置方式.

**Comment by lpn520** [comment]
Dubbo最好还是用xml比较好

**Comment by surpass1990** [comment]
今天碰到同样问题，xtea你解决了吗？

**Comment by xtea** [comment]
只能用xml 来进行配置，不要用注解。 @surpass1990

**Comment by mercyblitz** [comment]
Please use `@DubboComponentScan`

**Comment by mercyblitz** [comment]
Please use https://github.com/apache/incubator-dubbo-spring-boot-project/
