### ISSUE TITLE
Enhance the test coverage part-2  : dubbo-common/src/main/java/com/alibaba/dubbo/common/beanutil(bytecode|compiler|extension)

### ISSUE THREAD

**Issue by lovepoem** [apache/incubator-dubbo#1680]
add  unit test: modules  
 dubbo-common/src/main/java/com/alibaba/dubbo/common/beanutil
  dubbo-common/src/main/java/com/alibaba/dubbo/common/bytecode
  dubbo-common/src/main/java/com/alibaba/dubbo/common/compiler
  dubbo-common/src/main/java/com/alibaba/dubbo/common/extension

**Comment by zonghaishang** [comment]
Please assign to me

**Comment by lovepoem** [comment]
Ok ,it's yours

**Comment by lovepoem** [comment]
This issue has been around for a while. What is the progress now? Please give me a feedback.

**Comment by zonghaishang** [comment]
Planned to submit on July 15， because in the development of http2 and middleware contests, I didn't spend time on unit tests.
