### ISSUE TITLE
Enhance the test coverage part-3 : dubbo-common/src/main/java/com/alibaba/dubbo/common/concurrent(io|json|logger) modules 

### ISSUE THREAD

**Issue by lovepoem** [apache/incubator-dubbo#1681]
Add unit test,modules:
  dubbo-common/src/main/java/com/alibaba/dubbo/common/concurrent
  dubbo-common/src/main/java/com/alibaba/dubbo/common/io
  dubbo-common/src/main/java/com/alibaba/dubbo/common/json
  dubbo-common/src/main/java/com/alibaba/dubbo/common/logger

**Comment by htynkn** [comment]
@lovepoem I would like to pick up this task

**Comment by htynkn** [comment]
All files under `dubbo-common/src/main/java/com/alibaba/dubbo/common/json` are deprecate. will skip them when adding unit test
