### ISSUE TITLE
Enhance the test coverage part-7 : dubbo-container module

### ISSUE THREAD

**Issue by lovepoem** [apache/incubator-dubbo#1685]
Add unit test to dubbo-container  module

**Comment by lovepoem** [comment]
ok

**Comment by lovepoem** [comment]
This issue has been around for a while. What is the progress now? Please give me a feedback.

**Comment by luyuanwan** [comment]
I  can try it

**Comment by stoneapple** [comment]
@lovepoem  i have finished it ,but commit failed

**Comment by lovepoem** [comment]
Now the github is not available , I think we should have a wait

**Comment by lovepoem** [comment]
@stoneapple , Is this pr ?  https://github.com/apache/incubator-dubbo/pull/2406

**Comment by stoneapple** [comment]
@lovepoem  yes #2406
