### ISSUE TITLE
Enhance the test coverage part-8 : dubbo-filter module

### ISSUE THREAD

**Issue by lovepoem** [apache/incubator-dubbo#1687]
Add unit test to dubbo-filter module

**Comment by qinnnyul** [comment]
@lovepoem hey, I would like to increase test coverages for dubbo-filter module.

**Comment by lovepoem** [comment]
ok，the base goal：60%，you can see in the page： https://github.com/apache/incubator-dubbo/wiki/Test-coverage-guide。

The more enough,the better

**Comment by htynkn** [comment]
PR #1715 add unit test for dubbo-filter-cache. we still need unit test for dubbo-filter-validation

**Comment by qinnnyul** [comment]
good eye!  I will work on it, thanks

**Comment by lovepoem** [comment]
close via #1715 and #1736
