### ISSUE TITLE
Enhance the test coverage part-11 :  dubbo-registry/dubbo-registry-api and dubbo-registry/dubbo-registry-default modules

### ISSUE THREAD

**Issue by lovepoem** [apache/incubator-dubbo#1690]
Add unit test to 
dubbo-registry/dubbo-registry-api and dubbo-registry/dubbo-registry-default modules

**Comment by ralf0131** [comment]
Hi, I am willing to take this.

**Comment by lovepoem** [comment]
This issue has been around for a while. What is the progress now? Please give me a feedback.

**Comment by ralf0131** [comment]
Hi, I do not have enough time to do this recently... My plan is start to work on this in July...

**Comment by lovepoem** [comment]
Ok ,It's yours

**Comment by lixiaojiee** [comment]
The unit test under this issue are all finished, if there's no problem, please close this issue. @lovepoem
