### ISSUE TITLE
 Enhance the test coverage part-12: dubbo-registry/dubbo-registry-multicast(dubbo-registry-redis|dubbo-registry-zookeeper)

### ISSUE THREAD

**Issue by lovepoem** [apache/incubator-dubbo#1691]
Add unit test to the modules: 
dubbo-registry/dubbo-registry-multicast
   dubbo-registry/dubbo-registry-redis
  dubbo-registry/dubbo-registry-zookeeper

**Comment by satansk** [comment]
Let me try this :)
