### ISSUE TITLE
 Enhance the test coverage part-13 :    dubbo-remoting/dubbo-remoting-api(dubbo-remoting-grizzly|dubbo-remoting-http) modules

### ISSUE THREAD

**Issue by lovepoem** [apache/incubator-dubbo#1692]
add unit test to the modules  
 dubbo-remoting/dubbo-remoting-api
   dubbo-remoting/dubbo-remoting-grizzly/
   dubbo-remoting/dubbo-remoting-http/

**Comment by lovepoem** [comment]
This issue has been around for a while. What is the progress now? Please give me a feedback.

**Comment by htynkn** [comment]
for module `dubbo-remoting-http`, the test coverage is 73.59%
for module `dubbo-remoting-api`, the test coverage is 57.22%
but for module `dubbo-remoting-grizzly`, it's zero. 

so we still need someone working on this task, but let's focus on module `dubbo-remoting-grizzly`

**Comment by satansk** [comment]
I will do that.
