### ISSUE TITLE
 Enhance the test coverage part-14 : dubbo-remoting/dubbo-remoting-mina(dubbo-remoting-netty/dubbo-remoting-netty4) modules

### ISSUE THREAD

**Issue by lovepoem** [apache/incubator-dubbo#1693]
add unit to the modules
dubbo-remoting/dubbo-remoting-mina
   dubbo-remoting/dubbo-remoting-netty
   dubbo-remoting/dubbo-remoting-netty4

**Comment by DeadLion** [comment]
i'd like to handle this issue, do we have a deadline?

**Comment by lovepoem** [comment]
ok，the quality of test code has the highest priority。Deadline ：before the end of May
