### ISSUE TITLE
Enhance the test coverage part-15 :    dubbo-remoting/dubbo-remoting-p2p(dubbo-remoting-zookeeper) module

### ISSUE THREAD

**Issue by lovepoem** [apache/incubator-dubbo#1694]
Add unit test to the modules:
   dubbo-remoting/dubbo-remoting-p2p
   dubbo-remoting/dubbo-remoting-zookeeper

**Comment by htynkn** [comment]
@lovepoem I will pick up this

**Comment by lovepoem** [comment]
close via #1958
