### ISSUE TITLE
Enhance the test coverage part-17 : dubbo-rpc/dubbo-rpc-hessian(dubbo-rpc-http|dubbo-rpc-injvm) module

### ISSUE THREAD

**Issue by lovepoem** [apache/incubator-dubbo#1696]
Add unit to the modules  
 dubbo-rpc/dubbo-rpc-hessian
   dubbo-rpc/dubbo-rpc-http
   dubbo-rpc/dubbo-rpc-injvm

**Comment by kimmking** [comment]
and this.

**Comment by lovepoem** [comment]
This issue has been around for a while. What is the progress now? Please give me a feedback.

**Comment by kimmking** [comment]
@lovepoem  #2041
