### ISSUE TITLE
Enhance the test coverage part-18 : dubbo-rpc/dubbo-rpc-memcached(dubbo-rpc-redis|dubbo-rpc-rest) modules

### ISSUE THREAD

**Issue by lovepoem** [apache/incubator-dubbo#1697]
Add test to the modules: 
  dubbo-rpc/dubbo-rpc-memcached
   dubbo-rpc/dubbo-rpc-redis
   dubbo-rpc/dubbo-rpc-rest

**Comment by htynkn** [comment]
@lovepoem I would like to work on this card

**Comment by lovepoem** [comment]
ok it's yours
