### ISSUE TITLE
Enhance the test coverage part-20 :  dubbo-serialization/dubbo-serialization-api(dubbo-serialization-fastjson|dubbo-serialization-fst) module

### ISSUE THREAD

**Issue by lovepoem** [apache/incubator-dubbo#1699]
Add unit test to the modules:

dubbo-serialization/dubbo-serialization-api
dubbo-serialization/dubbo-serialization-fastjson
dubbo-serialization/dubbo-serialization-fst

**Comment by htynkn** [comment]
@lovepoem i would like to pick up this task.
