### ISSUE TITLE
方法级别的缓存写死为LRU？

### ISSUE THREAD

**Issue by zhuchao941** [apache/incubator-dubbo#170]
定义在method级别上，不管cache=“xxx”，最后都只会变成lru
同样的定义在reference级别上就是可以的，是否是bug？

**Comment by Mechanic-huang** [comment]
> 定义在method级别上，不管cache=“xxx”，最后都只会变成lru
同样的定义在reference级别上就是可以的，是否是bug？

我也遇到了

**Comment by whanice** [comment]
already fixed by #1396

**Comment by ralf0131** [comment]
@whanice Thanks!
