### ISSUE TITLE
Enhance the test coverage part-21 : dubbo-serialization/dubbo-serialization-hessian2(dubbo-serialization-jdk|dubbo-serialization-kryo) modules

### ISSUE THREAD

**Issue by lovepoem** [apache/incubator-dubbo#1700]
Add unit test to the modules:

dubbo-serialization/dubbo-serialization-hessian2
dubbo-serialization/dubbo-serialization-jdk
dubbo-serialization/dubbo-serialization-kryo

**Comment by diecui1202** [comment]
Please transfer it to me, thanks.

**Comment by lovepoem** [comment]
ok

**Comment by diecui1202** [comment]
PR has been merged, please close it. Thanks.
