### ISSUE TITLE
Failback Cluster失败后只会定时重新调用一次，如此次再失败则不会调用

### ISSUE THREAD

**Issue by zhuchao941** [apache/incubator-dubbo#171]
看了源码，失败后只会定时重新调用一次，如此次再失败并不会再定时调用

是否初衷如此？

**Comment by patternman** [comment]
try {
		invoker.invoke(invocation);
		this.failed.remove(invocation);
} catch (Throwable e) {
		logger.error(
		"Failed retry to invoke method "
		+ invocation.getMethodName()
		+ ", waiting again.", e);
}

要invoke不抛Throwable才remove，没调用成功就仍然在 failed里，延时过后仍然会调用。

**Comment by zhuchao941** [comment]
关键是

    protected Result doInvoke(Invocation invocation, List<Invoker<T>> invokers, LoadBalance loadbalance) throws RpcException {
        try {
            checkInvokers(invokers, invocation);
            Invoker<T> invoker = select(loadbalance, invocation, invokers, null);
            return invoker.invoke(invocation);
        } catch (Throwable e) {
            logger.error("Failback to invoke method " + invocation.getMethodName() + ", wait for retry in background. Ignored exception: "
                                 + e.getMessage() + ", ", e);
            addFailed(invocation, this);
            return new RpcResult(); // ignore
        }
    }

这段代码里已经有try..catch了，所以无论如何都会remove掉

**Comment by carryxyh** [comment]
The invoke will not over if invoke always failed like @patternman said.
DoInvoke method will only be called once. If failed, retry until the invoke success.

@ralf0131 
close this issue,pls.
