### ISSUE TITLE
annotation @Active is inconsistent with it's document

### ISSUE THREAD

**Issue by darknesstm** [apache/incubator-dubbo#1710]
source code：

> /dubbo-common/src/main/java/com/alibaba/dubbo/common/extension/ExtensionLoader.java

```java
private boolean isMatchGroup(String group, String[] groups) {
        if (group == null || group.length() == 0) {
            return true;
        }
        if (groups != null && groups.length > 0) {
            for (String g : groups) {
                if (group.equals(g)) {
                    return true;
                }
            }
        }
        return false;
    }
```
by the code, `@Activate` without property `group` can not be matched, also can not be activated.

but document say yes.

> https://dubbo.incubator.apache.org/books/dubbo-dev-book-en/SPI.html#fn_1

```java
import com.alibaba.dubbo.common.extension.Activate;
import com.alibaba.dubbo.rpc.Filter;

@Activate // Active for any condition
public class XxxFilter implements Filter {
    // ...
}
}
```

**Comment by diecui1202** [comment]
@darknesstm As the code shown, it will be activated when group is not set. 

```
        if (group == null || group.length() == 0) {
            return true;
        }
```

Feel free to reopen it if it also confuse u.

**Comment by linweizhen** [comment]
I have just been confused about this issue, and I understand that "Active for any condition" is available to both providers and consumers, but the following configuration should be what I want:
`@Activate(group = {Constants.CONSUMER, Constants.PROVIDER})`

**Comment by linweizhen** [comment]
I have just been confused about this issue, and I understand that "Active for any condition" is available to both providers and consumers, but the following configuration should be what I want:
`@Activate(group = {Constants.CONSUMER, Constants.PROVIDER})`

Your reply is inaccurate, the condition of filtering is the second groups，So I think the document annotation should explain the problem more clearly.
`if (groups != null && groups.length > 0) {
            for (String g : groups) {
                if (group.equals(g)) {
                    return true;
                }
            }
        }`

![active](https://user-images.githubusercontent.com/9344329/53802977-3c344b00-3f7e-11e9-9f21-322db1431f52.png)

**Comment by linweizhen** [comment]
@darknesstm

**Comment by linweizhen** [comment]
@diecui1202
