### ISSUE TITLE
Replace Jedis with Redisson 

### ISSUE THREAD

**Issue by the3rd** [apache/incubator-dubbo#1714]
[RedissonRegistry.zip](https://github.com/apache/incubator-dubbo/files/1953952/RedissonRegistry.zip)

This attachment is without RedissonRegistryFactory. Just like this.

```java
public class RedissonRegistryFactory implements RegistryFactory {

	public Registry getRegistry(URL url) {
		return new RedissonRegistry(url);
	}

}
```

And you should edit the file "com.alibaba.dubbo.registry.RegistryFactory" in META-INF/dubbo.

```
redisson=com.alibaba.dubbo.registry.RedissonRegistryFactory
```

The config of redisson is in a standalone file. And dubbo config like this.

```xml
<dubbo:registry protocol="redisson" address="?configFile=./config/redisson.yml" />
```

**Comment by ralf0131** [comment]
Hi,

I noticed the two alternative for Redis Client: Jedis and Redisson, they are both recommended on the official Java client for Redis [1]. They both have their advantages.

Do you have any performance evaluation for these two clients?

Unless you have provided enough information, we can't make the decision  to replace Jedis with Redisson.

p.s. Uploading a zip file is not recommended, please use pull request instead. see https://github.com/apache/incubator-dubbo/blob/master/CONTRIBUTING.md for more details.


[1] https://redis.io/clients#java

**Comment by cvictory** [comment]
As @ralf0131  said, this two clients are both recommended on https://redis.io/clients#java . And we found the spring make the jedis as default way.

So if you need use the Redisson for some condition,  you can create a project at github and share this project with as. 

Please close this issue. @diecui1202
