### ISSUE TITLE
dubbo demo start failure

### ISSUE THREAD

**Issue by z626994** [apache/incubator-dubbo#1723]
![image](https://user-images.githubusercontent.com/22947725/39461218-ce18e0e8-4d3b-11e8-9a65-eade28835b14.png)
![image](https://user-images.githubusercontent.com/22947725/39461237-ed670e8e-4d3b-11e8-8a8b-185fc29b234d.png)

as the picture shows

**Comment by kimmking** [comment]
I think the references dubbo project in your demo project is missing.

**Comment by z626994** [comment]
this download in https://github.com/apache/incubator-dubbo/tree/master/dubbo-demo ,missing?

**Comment by z626994** [comment]
I use 2.5.10 demo ,Can start
![image](https://user-images.githubusercontent.com/22947725/39461825-124b7704-4d40-11e8-937d-1902c62314ad.png)

**Comment by daanhan** [comment]
2.6.1 demo, got same error message.  My issue #1739

**Comment by ralf0131** [comment]
The latest dubbo-demo codes should work with 2.6.2-SNAPSHOT, if you are using latest demo with 2.6.1, you need to register a name space handler manually in the demo code:

You can manually register the NamespaceHandler by adding META-INF/spring.handlers with the following content:

```
http\://dubbo.apache.org/schema/dubbo=com.alibaba.dubbo.config.spring.schema.DubboNamespaceHandler
```
