### ISSUE TITLE
dubbo registry check=false is not work?

### ISSUE THREAD

**Issue by yiwugou** [apache/incubator-dubbo#1724]
when i set `<dubbo:registry check="false" />` 
and zookeeper is not setup
i can not setup dubbo-consumer project
console just circulatory print 

2018-05-02 10:44:26,708 INFO  [org.apache.zookeeper.ClientCnxn] - Opening socket connection to server 127.0.0.1/127.0.0.1:2181
2018-05-02 10:44:27,711 WARN  [org.apache.zookeeper.ClientCnxn] - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1119)

**Comment by yiwugou** [comment]
when i search in source code, i can not find which class or method invoke  `com.alibaba.dubbo.config.RegistryConfig.isCheck()`

**Comment by yiwugou** [comment]
![image](https://user-images.githubusercontent.com/28729808/39503130-bae80f24-4df6-11e8-8a23-f33984c1e70c.png)

**Comment by yiwugou** [comment]
![image](https://user-images.githubusercontent.com/28729808/39503267-9e884564-4df7-11e8-9ec6-85e04df94da9.png)

**Comment by xt8469** [comment]
check="true/false" means check if the service provider exists when started , rather than check if  the registration center (like zookeeper) exists.

**Comment by yiwugou** [comment]
no body?

**Comment by carryxyh** [comment]
Hi, there are sth wrong with doc.
Check = false in <dubbo:registry> means not throw an exception when the registration fails. 
Rather than throwing an exception when the registry doesn't exist

**Comment by carryxyh** [comment]
Hi, @yiwugou 
Would you like to submit an issue to dubbo-website? 
Of course, it is better to submit a pr together to fix it.

**Comment by carryxyh** [comment]
Since this issue has not been feedback for a long time, I will temporarily close it.

**Comment by startjava** [comment]
@carryxyh

**Comment by startjava** [comment]
carryxyh，如何重现注册失败的效果呢？感谢
