### ISSUE TITLE
采用zookeeper集群配置，把所有zookeeper都停掉以后为什么还能调用服务

### ISSUE THREAD

**Issue by renoxiang** [apache/incubator-dubbo#1735]

**Comment by renoxiang** [comment]
用的是spring-boot
            <dependency>
                <groupId>com.alibaba.boot</groupId>
                <artifactId>dubbo-spring-boot-starter</artifactId>
                <version>0.1.0</version>
            </dependency>

**Comment by ralf0131** [comment]
Thanks @feelwing1314 for the explanation.
