### ISSUE TITLE
failover重试机制（默认）且只有两个Invoker时，invoker选择有问题

### ISSUE THREAD

**Issue by feelwing1314** [apache/incubator-dubbo#1737]
当采用failover重试机制（默认）且只有两个Invoker（Provider）时，不论配置了什么负载均衡loadbalance策略，都会退化成轮询策略。但是retry重试时选择Invoker的逻辑有问题，源码在AbstractClusterInvoker.java的doSelect()方法中：
if (invokers.size() == 2 && selected != null && !selected.isEmpty()) {
    return selected.get(0) == invokers.get(0) ? invokers.get(1) : invokers.get(0);
}
假设有两个可选invoke，分别为：
10.0.0.1:20884，10.0.0.1:20886；
那么N次选择的invoke如下：
10.0.0.1:20884
10.0.0.1:20886
10.0.0.1:20886
10.0.0.1:20886
10.0.0.1:20886
... ...
即除了第1次，其他N-1次都是选择第二个Invoker。

修改建议：
将
return selected.get(0) == invokers.get(0) ?
改为
return selected.get(selected.size()-1) == invokers.get(0) ?
即每次重新选择时与前一次选择的Invoker比较，而不是与第一次选择的Invoker比较；

**Comment by mzorro** [comment]
经过测试，确实是有这个问题

**Comment by carryxyh** [comment]
@ralf0131 
Fixed, able to close.

**Comment by ralf0131** [comment]
@carryxyh Thanks, I checked the latest code, I has been fixed by https://github.com/apache/incubator-dubbo/pull/1759

**Comment by carryxyh** [comment]
: )
u are welcome
