### ISSUE TITLE
2.6.1的demo程序报错

### ISSUE THREAD

**Issue by daanhan** [apache/incubator-dubbo#1739]
2.6.1版本的dubbo-demo，在eclipse中运行dubbo-demo-provider里的Provider，得到以下错误，请解决，谢谢！
由于是dubbo新手，暂时猜测是xmlns:dubbo的路径问题。
> [04/05/18 23:49:42:042 CST] main  INFO support.ClassPathXmlApplicationContext: Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@4d49af10: startup date [Fri May 04 23:49:42 CST 2018]; root of context hierarchy
[04/05/18 23:49:42:042 CST] main  INFO xml.XmlBeanDefinitionReader: Loading XML bean definitions from class path resource [META-INF/spring/dubbo-demo-provider.xml]
Exception in thread "main" org.springframework.beans.factory.parsing.BeanDefinitionParsingException: **Configuration problem: Unable to locate Spring NamespaceHandler for XML schema namespace [http://dubbo.apache.org/schema/dubbo]**
Offending resource: class path resource [META-INF/spring/dubbo-demo-provider.xml]
	at org.springframework.beans.factory.parsing.FailFastProblemReporter.error(FailFastProblemReporter.java:70)

**Comment by daanhan** [comment]
It goes normal when change 
`<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:dubbo="http://dubbo.apache.org/schema/dubbo"
       xmlns="http://www.springframework.org/schema/beans"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-4.3.xsd
       http://dubbo.apache.org/schema/dubbo http://dubbo.apache.org/schema/dubbo/dubbo.xsd">
`
to
`<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:dubbo="http://code.alibabatech.com/schema/dubbo"
       xmlns="http://www.springframework.org/schema/beans"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-4.3.xsd
       http://code.alibabatech.com/schema/dubbo http://code.alibabatech.com/schema/dubbo/dubbo.xsd">
`
😆

**Comment by ralf0131** [comment]
The latest dubbo-demo codes should work with 2.6.2+, if you are using latest demo with 2.6.1, you need to register a name space handler manually in the demo code:

You can manually register the NamespaceHandler by adding `META-INF/spring.handlers` with the following content:

```
http\://dubbo.apache.org/schema/dubbo=com.alibaba.dubbo.config.spring.schema.DubboNamespaceHandler
```

**Comment by Brave-Andy** [comment]
我是直接下的 incubator-dubbo-ops,但是在idea中启动还是报错Unable to locate Spring NamespaceHandler for XML schema namespace [http://dubbo.apache.org/schema/dubbo]
Offending resource: URL [file:/home/ubuntu-xjg/IdeaProjects/incubator-dubbo-ops/dubbo-admin/target/classes/dubbo-admin.xml]
