### ISSUE TITLE
dubbo调用中，bean反序列化后属性丢失

### ISSUE THREAD

**Issue by qingfengpu** [apache/incubator-dubbo#174]
如题，eg：

``` java
int age;
String name;
```

调用dubbo插入数据库中 name 为 空字符串，其实是赋过值的

**Comment by lvpingWoo** [comment]
自定义异常在dubbo客户端调用中大家是怎么弄的？
除了这种方式，还有没有别的办法？改Dubbo源码？




only2004@foxmail.com
 
发件人： qingfengpu
发送时间： 2015-11-17 10:57
收件人： alibaba/dubbo
主题： [dubbo] dubbo调用中，bean反序列化后属性丢失 (#174)
如题，eg：
...
int age;
String name;
...
调用dubbo插入数据库中 name 为 空字符串，其实是赋过值的

**Comment by teaey** [comment]
贴下完整的bean类，方便定位问题。

**Comment by justein** [comment]
确认bean是否已经实现serializable接口，dubbo默认hessian序列化方式，可以换种试试。

**Comment by xy8864** [comment]
所有地方的bean类要一样的

**Comment by dczz** [comment]
子类继承父类有相同名称属性会被忽略
参考一下这个连接 http://tech.dianwoda.com/2017/06/29/liang-ge-dubbocai-guo-de-keng/

**Comment by zonghaishang** [comment]
@qingfengpu

I have tested the problem without you saying， Here is my test code:

``` java
public class Father implements Serializable {
    public int age;
    public String name;
}
public class Son extends Father {
    public String name;
}
    @Test
    public void serialize_inherited_model_then_deserialize() throws Exception {

        Son son = new Son();
        son.age = 40;
        son.name = "jason";

        ByteArrayOutputStream bout = new ByteArrayOutputStream();
        Hessian2Output out = new Hessian2Output(bout);

        out.writeObject(son);
        out.flush();

        ByteArrayInputStream bin = new ByteArrayInputStream(bout.toByteArray());
        Hessian2Input input = new Hessian2Input(bin);
        Son deserializeSon = (Son)input.readObject(Son.class);
        assertTrue(deserializeSon != null);
        assertEquals(40, deserializeSon.age);
        assertEquals("jason", deserializeSon.name);
    }
```
![image](https://user-images.githubusercontent.com/15549777/37950930-245ea4b8-31cd-11e8-9c76-a7f190b018ba.png)

I'm using dubbo 2.6.1, please attach your code and dubbo version, thanks.

**Comment by lovepoem** [comment]
This issue os opened two years ago, I think now it not exist
