### ISSUE TITLE
use CuratorFrameworkFactory.DEFAULT_CONNECTION_TIMEOUT_MS

### ISSUE THREAD

**Issue by gMan1990** [apache/incubator-dubbo#1743]
https://github.com/apache/incubator-dubbo/blob/04c93e8b98250230c4d22423372acd1c29e2c770/dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/com/alibaba/dubbo/remoting/zookeeper/curator/CuratorZookeeperClient.java#L49

rt

**Comment by carryxyh** [comment]
will fix soon by this pr:
https://github.com/apache/incubator-dubbo/pull/2217
