### ISSUE TITLE
dubbo-demo 

### ISSUE THREAD

**Issue by coder-PengWenHao** [apache/incubator-dubbo#1747]
dubbo -demo hava a bug , Unable to locate Spring NamespaceHandler for XML schema namespace [http://dubbo.apache.org/schema/dubbo]
Offending resource: class path resource [META-INF/spring/dubbo-demo-provider.xml]

**Comment by ralf0131** [comment]
This feature requires 2.6.2. If you are using lower version, please refer to my answer in #1545
