### ISSUE TITLE
provider如何异步处理请求

### ISSUE THREAD

**Issue by Spectrumleeee** [apache/incubator-dubbo#177]
provider端实现接口的时候，能否获取客户端连接的channel呢？这样服务端就可以异步处理客户端请求了，似乎channel已经被封装到了dubbo架构的底层了，服务端只能同步处理完请求就返回。

最近看到可以通过参数回调的方式实现服务端异步处理客户端请求，但是还是想知道能否有
RpcContext.getContext().getRemoteAddressString()的类似的api在服务端获取与客户端的channel，从而实现异步处理请求。

**Comment by luoyan35714** [comment]
Dubbo支持Future和Callback两种类型的异步调用
http://dubbo.io/User+Guide-zh.htm#UserGuide-zh-%E5%8F%82%E6%95%B0%E5%9B%9E%E8%B0%83

**Comment by afredlyj** [comment]
dubbo 处理异步时，会把异步的标志位往下传输，导致获取处理结果失败。

**Comment by diecui1202** [comment]
@Spectrumleeee We have provided a new async invoke implementation in 2.7.x

check https://github.com/apache/incubator-dubbo/pull/1957 for more infos.

Feel free to reopen it. &READY-TO-CLOSE&
