### ISSUE TITLE
[Enhancement] @EnableDubboConfigBinding annotates @Repeatable

### ISSUE THREAD

**Issue by mercyblitz** [apache/incubator-dubbo#1770]
`@Repeatable` should be annotated `@EnableDubboConfigBinding` .

**Comment by cvictory** [comment]
I think we can add this annotation at both 2.7.x version.  
@Repeatable is effcient after jdk1.8.

**Comment by mercyblitz** [comment]
@cvictory it both works Dubbo 2.6.x and 2.7.x, and may do later
