### ISSUE TITLE
在spring配置文件中如何修改dubbo.qos.port 

### ISSUE THREAD

**Issue by superzwd** [apache/incubator-dubbo#1774]
文档中说 可以通过以下方式修改。

> 新版本的 telnet 端口 与 dubbo 协议的端口是不同的端口，默认为 22222，可通过配置文件dubbo.properties 修改:dubbo.qos.port=33333或者通过设置 JVM 参数:-Ddubbo.qos.port=33333

在spring配置文件里面如何设置呢？

**Comment by ralf0131** [comment]
I am closing this issue because it is solved.
