### ISSUE TITLE
deprecated hessian1 and move hessian-lite to dubbo group

### ISSUE THREAD

**Issue by diecui1202** [apache/incubator-dubbo#1778]
As dubbo does not use hessian1, we need to delete it in hessian-lite.

But consider compatibility, it's recommended to deprecated it, and in next major release version, delete it.

In addition, hessian-lite is a single module, it's also recommended to move it to dubbo group from dubbo codebase.

**Comment by diecui1202** [comment]
We're considering move hessian-lite to dubbo eco-system in 2.7.x which is the next major version.

**Comment by ralf0131** [comment]
This issue has been done.
