### ISSUE TITLE
@Reference @Autowired(required = false)无法同时存在

### ISSUE THREAD

**Issue by angelovevil** [apache/incubator-dubbo#1782]
@Reference(version = "1.0.0")
@Autowired(required = false)
@Qualifier("accountProvider")
private IAccountProvider provider;
注解无法同时存在
InjectionMetadata.checkConfigMembers() 中 checkedElements会是空的

**Comment by duxingzhe1150** [comment]
@reference和@Autowired没必要同时存在吧，用纯注解方式的话，使用@reference就好了，用配置方式引入dubbo bean，只用@Autowired就可以吧。。。还有就是使用@reference的时候，由于spring和dubbo的扫描顺序原因，有时候会导致注入的对象为空，要先使用dubbo扫描才可以。。。

**Comment by angelovevil** [comment]
同时存在的话可以随时转换，构建不使用dubbo方式的工程

**Comment by beiwei30** [comment]
not a bug.
