### ISSUE TITLE
你好，有关nodejs调用dubbo服务的问题

### ISSUE THREAD

**Issue by guoxiangwen** [apache/incubator-dubbo#179]
nodejs如果直接调用Java的dubbo服务呢？有没有例子啊？谢谢了

**Comment by justein** [comment]
双方约定好接口，可以调用。

**Comment by kimmking** [comment]
dubbox用rest

**Comment by 247687009** [comment]
https://github.com/goudai/dubbo-nodejs 
dubbo nodejs support 
auto get dubbo exported service url and auto load balance
support nodejs (co||async/await)

**Comment by ralf0131** [comment]
Please check out this awesome project: https://github.com/dubbo/dubbo2.js
