### ISSUE TITLE
自己改了源码，dubbo的代码里有对降级方式配置throw  Exceptiond的支持。为何不对外开放呢

### ISSUE THREAD

**Issue by kivenhu** [apache/incubator-dubbo#1798]
请较一个问题,dubbo的代码里有对降级方式配置throw  Exceptiond的支持。为何不对外开放呢，在参数效验阶段没有做开放。 然后我这边自己改了源码，作支持。请问是否有性能或者其他问题。
主要修改类：com.alibaba.dubbo.config.AbstractInterfaceConfig
else if (mock.startsWith(Constants.THROW_PREFIX)) {
                /**
                 * 201805 hushichao增加else if (mock.startsWith(Constants.THROW_PREFIX))
                 * 让其支持配置throw 异常，这里验证配置的异常类可以加载
                 */
                String mockException = mock.substring(Constants.THROW_PREFIX.length()).trim();
                ReflectUtils.forName(mockException);
            }
主要修改类：com.alibaba.dubbo.rpc.support.MockInvoker
else if (mock.startsWith(Constants.THROW_PREFIX)) {
        	mock = mock.substring(Constants.THROW_PREFIX.length()).trim();
            /**
             * 201805 hushichao去掉mock = mock.replace('`', '"');
             * 让其支持配置throw 异常，格式配置为throw开头，后接异常全称 例如：throwcom.dubbo.mock.MockException
             */
//            mock = mock.replace('`', '"');
            if (StringUtils.isBlank(mock)){
            	throw new RpcException(" mocked exception for Service degradation. ");
            } else { //用户自定义类
            	Throwable t = getThrowable(mock);
				throw new RpcException(RpcException.BIZ_EXCEPTION, t);
            }
        }

**Comment by zhaojigang** [comment]
开放的呀，只是文档没写而已。我自己总结了一下：http://www.cnblogs.com/java-zhao/p/8320519.html，你可以看一下，没必要改源码

**Comment by kivenhu** [comment]
@zhaojigang  谢谢回复，看了你的文章，进行了一个配置：mock="fail:throw => throw new RpcException('mocked exception for Service degradation')"  启动就会报错的。可以加qq 1062340050探讨一下吗？ 
Invalid mock="fail:throw => throw new RpcException('mocked exception for Service degradation')" contain illegal charactor, only digit, letter, '-', '_' and '.' is legal.

**Comment by nzomkxia** [comment]
here is the document:   
http://dubbo.apache.org/books/dubbo-user-book/demos/service-downgrade.html   
 http://dubbo.apache.org/books/dubbo-user-book/demos/local-mock.html

**Comment by zhaojigang** [comment]
嗯，通常在admin配置就好了，我是习惯自己调接口 @kivenhu 
dubbo的服务降级这一块儿的文档写的比较散 @nzomkxia

**Comment by kivenhu** [comment]
@nzomkxia 官方文档倒是看过，里面没有关于统一配置抛出异常的。谢谢各位。
