### ISSUE TITLE
Missing protocol in @Reference annotation

### ISSUE THREAD

**Issue by kimylrong** [apache/incubator-dubbo#1807]
Field protocol missed in the @Reference annotation.
But ServiceConfig has protocol.  API way.
We prefer the annotation(Spring Boot).
Could you please help add the protocol in the @Reference?

**Comment by carryxyh** [comment]
Hi, I have check the code:
https://github.com/apache/incubator-dubbo/blob/d8282fe1b8075a453c7b44b4ae7982a4285df7b7/dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/annotation/Reference.java#L258

It has been supported.
