### ISSUE TITLE
dubbo rest

### ISSUE THREAD

**Issue by zhizhi555555** [apache/incubator-dubbo#1812]
现在dubbo支持rest协议吗？

**Comment by ralf0131** [comment]
Yes, thanks Dangdang for donating this featue to Dubbo. Please checkout this: https://github.com/apache/incubator-dubbo-docs/blob/master/dubbo-user-book/rest.md .

We will soon integrate into the official documentation. The donation is still under ASF ip clearance process, so it will take some time.
