### ISSUE TITLE
can dubbo support Serialization configuration to dubbo:service or dubbo:method

### ISSUE THREAD

**Issue by KMnO4** [apache/incubator-dubbo#1813]
In my scenario, some methods in the provider return a large amount of data each time, because the response is internally duplicated, so the serialization and transmission performance can be improved by implementing a new Serialization (protostuff+snappy).I hope that the remaining services or methods in the provider continue to use the default Hessian2 Serialization, however， the Serialization configuration supports only the protocol level.
  In dubbo-remoting-netty, NettyServer, when the tcp connection is established, the response serialization type is specified through the NettyCodecAdapter's final url, it seems that Serialization configuration can not support the service or method level now.
  Does dubbo subsequently plan to support serialization configuration to service or method?

在我们的使用场景中，provider中有些接口返回数据量较大，在M级别，因为数据内部重复数据多，通过实现新的Serialization插件（protostuff+snappy）可以提高序列化和传输的性能。我们希望provider中其余service或者method继续使用默认hessian2 Serialization，但是现有Serialization配置只支持到protocol级别。

netty通讯方式中，NettyServer当中，当tcp连接被建立，response序列化方式通过NettyCodecAdapter的final url被指定下来，Serialization配置不能支持到service或者method级别。

dubbo后续有计划将Serialization配置支持到service或者method么？

**Comment by 1017727621** [comment]
always do not support bro!

**Comment by beiwei30** [comment]
no, I don't think this kinda support is reasonable.
