### ISSUE TITLE
Filter order issues

### ISSUE THREAD

**Issue by wujun8** [apache/incubator-dubbo#1817]
In ExtensionLoader , user's ```<dubbo:service />``` filters always after ```@Activate``` filters ,
Why not order them together? 
```@Activate``` doesn't means that it's internal, also may be user's custom filter, right? Now, when I have ```@Activate``` and ```<dubbo:service />``` config both, the order is not work between them any more.

**Comment by diecui1202** [comment]
@wujun8 IMO, if your Filter with Annotation Activate, it will be activated by default. You do not need to config like `<dubbo:service filter="f1,f2"/>`.

@Activate doesn't means that it's internal, also may be user's custom filter, right?
/// Yes, u r right. But once your filter with this annotation, it will be performed.

u can refer this doc: http://dubbo.apache.org/zh-cn/docs/dev/impls/filter.html

If you want to activate a filter on a specify service, don't use the annotation.

**Comment by wujun8** [comment]
OK, annotation only applies to certain filter that exec before filters on a specify service, or don't use annotation.
