### ISSUE TITLE
AnnotationProvider启动报错

### ISSUE THREAD

**Issue by zyongbai** [apache/incubator-dubbo#1819]
com.alibaba.dubbo.examples.annotation.AnnotationProvider

Exception in thread "main" java.lang.IllegalStateException: No such application config! Please add <dubbo:application name="..." /> to your spring config.

**Comment by diecui1202** [comment]
@zyongbai We provide a new samples project, which is https://github.com/dubbo/dubbo-samples/tree/master/dubbo-samples-annotation

dubbo-test module maybe deleted one day.

**Comment by diecui1202** [comment]
Please close it. Feel free to reopen it if also have problem.
