### ISSUE TITLE
dubbo-admin installed success, but failed to connect to zk 

### ISSUE THREAD

**Issue by xjliang2007** [apache/incubator-dubbo#1835]
hi, dubboers : 
Recently I encounter a extremely strange issue when I use the dubbo-admin , it shows that it can not connect to the zk , so it can not discover services.   see the following pictures :   

![image](https://user-images.githubusercontent.com/9584000/40407245-604812de-5e96-11e8-8cf0-7d1a77f1929a.png)

![image](https://user-images.githubusercontent.com/9584000/40407408-e90674a8-5e96-11e8-8742-bd8ff656ca88.png)

I have checked the dubbo.properties file to indicate zk address, and the zk server has already started.  see this picture :  

![image](https://user-images.githubusercontent.com/9584000/40407430-fd9525e0-5e96-11e8-8e03-d2bc176de320.png)

And I also check that the zk can be telnet , just as following picture shows :  

![image](https://user-images.githubusercontent.com/9584000/40407547-5c64d87c-5e97-11e8-862e-7485692a2b4c.png)

So, the above case really makes me confusing, I hope that someone encounters such case can give me help or tips, thanks.

**Comment by xjliang2007** [comment]
I later try another test case, deploy the admin platform in the same tomcat-7.x for both test environment and production environment, the only difference between them is the zk addresses. Then I got different results, the production case runs good, but the test env case still badly work, just like the above description.  

Later I try to deploy them to tomcat-9.x , for test env, I use zkclient as registry client, and for production env, I do not change its default setting(namely it still use curator as the registry client), then it is amazing, both of them work good.  But the reason remains unknown to me.  

Any idea about such strange case?

**Comment by beiwei30** [comment]
@xjiliang2007 what I suggest is to cross examine the compatibility between zkclient/curator client and your ZooKeeper server. I believe it's caused by compatibility between server and client. 

Feel free to reopen this issue once you have new finding. Thanks.
