### ISSUE TITLE
Typo of destory

### ISSUE THREAD

**Issue by hqq2023623** [apache/incubator-dubbo#1845]
branch : master , version : 2.6.2-SNAPSHOT
RegistryDirectory , line 562
<img width="943" alt="image" src="https://user-images.githubusercontent.com/6971152/40523539-abfd7142-6008-11e8-8296-791017c9d511.png">

ProtocolConfig#destory() ,line 457

Fix : destory -> destroy

**Comment by diecui1202** [comment]
Thanks for your report. We will fix it ASAP.

**Comment by ralf0131** [comment]
Hi, would you mind send a pull request?

**Comment by diecui1202** [comment]
Yeah, my fault, sorry. The community wants everyone to join into. You can contribute your modification through sending a PR.

**Comment by lovepoem** [comment]
close this via https://github.com/apache/incubator-dubbo/pull/1851
