### ISSUE TITLE
How could I  show services info  on dubbo-admin by more groups?

### ISSUE THREAD

**Issue by Python-IBM** [apache/incubator-dubbo#1847]
Hi，I have two group, one group name is 'user-group'，another group name is 'car-group', I want show double group  services info on dubbo-admin，but the dubbo-admin only show  first group，don't show another group .How could I config on dubbo-admin support double group?

**Comment by nzomkxia** [comment]
please try new dubbo admin with `develop` branch: https://github.com/apache/incubator-dubbo-ops, here is a demo: http://47.91.207.147/#/service?filter=%2a&pattern=service, now it's possible to show all groups for a service.
![image](https://user-images.githubusercontent.com/1183397/52935728-2aa34e80-3395-11e9-8099-6f773b595945.png)
