### ISSUE TITLE
13/5000   I have a problem, how to solve it.This is the error screenshot.

### ISSUE THREAD

**Issue by zhaoyh001** [apache/incubator-dubbo#1848]
![1527236263 1](https://user-images.githubusercontent.com/34473608/40534215-e6be0eac-6037-11e8-983f-5e8d88215cc2.png)

**Comment by diecui1202** [comment]
According to the error message, you can set JAVA_HOME env variable and try it again.

**Comment by ralf0131** [comment]
Hi, I think @diecui1202 's comments clearly answered this question, I am closing it now.
