### ISSUE TITLE
一直出现 timeout response finally return

### ISSUE THREAD

**Issue by 4T-Shirt** [apache/incubator-dubbo#185]
求助，在做dubbo的性能压测时，一直出现timeout response finally return。
而我已经设置了服务端和客户端的timeout，且retry=0，为什么timeout了，还会一直返回数据呢？
￼
『
WARN ] 2015-12-21 12:18:29,501 method:com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:242)
 [DUBBO] The timeout response finally returned at 2015-12-21 12:18:29.501, response Response [id=41775695, version=null, status=20, event=false, error=null, result=RpcResult [result={ret=0, msg=ok, gpsz=24430.00, zzc=100024430.00, fund=com.mogucaifu.powermnjy.domain.Fund@777216cf, gfList=[com.mogucaifu.powermnjy.domain.Gf@179cb9f]}, exception=null]], channel: /10.45.186.137:41610 -> /10.45.190.131:20880, dubbo version: 2.5.3, current host: 10.45.186.137
[WARN ] 2015-12-21 12:18:29,501 method:com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:242)
 [DUBBO] The timeout response finally returned at 2015-12-21 12:18:29.501, response Response [id=41775689, version=null, status=20, event=false, error=null, result=RpcResult [result={ret=0, msg=ok, gpsz=24430.00, zzc=100024430.00, fund=com.mogucaifu.powermnjy.domain.Fund@298347e7, gfList=[com.mogucaifu.powermnjy.domain.Gf@4a325c54]}, exception=null]], channel: /10.45.186.137:41610 -> /10.45.190.131:20880, dubbo version: 2.5.3, current host: 10.45.186.137
[WARN ] 2015-12-21 12:18:29,501 method:com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:242)
 [DUBBO] The timeout response finally returned at 2015-12-21 12:18:29.501, response Response [id=41775698, version=null, status=20, event=false, error=null, result=RpcResult [result=com.mogucaifu.powermnjy.domain.Fund@63e4aa0d, exception=null]], channel: /10.45.186.137:41610 -> /10.45.190.131:20880, dubbo version: 2.5.3, current host: 10.45.186.137
[WARN ] 2015-12-21 12:18:29,501 method:com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:242)
 [DUBBO] The timeout response finally returned at 2015-12-21 12:18:29.501, response Response [id=41775692, version=null, status=20, event=false, error=null, result=RpcResult [result=com.mogucaifu.powermnjy.domain.Fund@48ba30d5, exception=null]], channel: /10.45.186.137:41610 -> /10.45.190.131:20880, dubbo version: 2.5.3, current host: 10.45.186.137
[WARN ] 2015-12-21 12:18:29,500 method:com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:242)
 [DUBBO] The timeout response finally returned at 2015-12-21 12:18:29.500, response Response [id=41775690, version=null, status=20, event=false, error=null, result=RpcResult [result=com.mogucaifu.powermnjy.domain.Fund@ff35026, exception=null]], channel: /10.45.186.137:41610 -> /10.45.190.131:20880, dubbo version: 2.5.3, current host: 10.45.186.137
』

**Comment by teaey** [comment]
估算下报错的请求的RT是多大，然后设置dubbo:reference的timeout值

**Comment by ltliujunxi** [comment]
timeout  初始值  要在60000 以上60ms

**Comment by diecui1202** [comment]
&READY-TO-CLOSE&
