### ISSUE TITLE
Dynamic register/deregister service from registry

### ISSUE THREAD

**Issue by eonezhang** [apache/incubator-dubbo#1850]
any plan to support dynamic register/deregister from registry?
here is my scenario,
**online**
after service started, I don't want it register to registry immediately, since some warm up actions will be performed, after that I could register the service to the registry manually.
**offline**
and also deregister from registry is wanted.

**Comment by kimmking** [comment]
that's a good idea

**Comment by diecui1202** [comment]
@eonezhang You can reference here for delaying registry services or not registry them: 

http://dubbo.apache.org/books/dubbo-user-book/demos/delay-publish.html
http://dubbo.apache.org/books/dubbo-user-book/demos/subscribe-only.html

And use [qos](http://dubbo.apache.org/books/dubbo-user-book/references/qos.html) to online/offline them manually.

**Comment by eonezhang** [comment]
@diecui1202  it inspired me some how, thanks
