### ISSUE TITLE
the issue for  setting loadbalancer.select  (@SPI)  completely  extendable

### ISSUE THREAD

**Issue by smallh0a1n1d0s** [apache/incubator-dubbo#1861]

**Comment by smallh0a1n1d0s** [comment]
suggest that   move  the code  in abstract  or remove it  before loadbalancer.select

**Comment by smallh0a1n1d0s** [comment]
@diecui1202  I really want to join our big family, but now I have a lot of work to do .I need to liberate myself first.   Recently, the expansion of flow control and fuses has been completed. There are a lot of things to do

**Comment by carryxyh** [comment]
hi @smallh0a1n1d0s 
Is this PR of mine the result you want?

https://github.com/apache/incubator-dubbo/pull/2156

**Comment by smallh0a1n1d0s** [comment]
It's good  to  optimize  initialization of loadbalance .  To my confusion : l can't  extend the SPI for ( loadbalancer.select )  when there is  none or  only one  invoker 。 Actually ,   the  sortable routers can't  support very well , So that l have to accomplish a sortable composition.   If some logics like  alarm notification when none or only one invoker , we can also extend the SPI  ( loadbalancer.select )  to achieve it . This is not a very good example, but it also means better scalability.

**Comment by carryxyh** [comment]
OK, I know, thx for your issue and looking forward to your pr to solve this problem.
:)

**Comment by beiwei30** [comment]
I think @smallh0a1n1d0s hopes AbstractLoadBalance shouldn't provide select() impl like this:

```java
    @Override
    public <T> Invoker<T> select(List<Invoker<T>> invokers, URL url, Invocation invocation) {
        if (CollectionUtils.isEmpty(invokers)) {
            return null;
        }
        if (invokers.size() == 1) {
            return invokers.get(0);
        }
        return doSelect(invokers, url, invocation);
    }
```

**Comment by beiwei30** [comment]
> It's good to optimize initialization of loadbalance . To my confusion : l can't extend the SPI for ( loadbalancer.select ) when there is none or only one invoker 。 Actually , the sortable routers can't support very well , So that l have to accomplish a sortable composition. If some logics like alarm notification when none or only one invoker , we can also extend the SPI ( loadbalancer.select ) to achieve it . This is not a very good example, but it also means better scalability.

router's route() happens before load balancer's select(). In this case, it is reasonable to return null when there's no invoker and directly return **the** invoker when there's only one.

**Comment by smallh0a1n1d0s** [comment]
I see, but there are three cases where loadbalance. select (@SPI) is not extensible. Why not move it completely in the abstract method?

` if (invokers == null || invokers.size() == 0)
            return null;
        if (invokers.size() == 1)
            return invokers.get(0);
        // 如果只有两个invoker，退化成轮循
        if (invokers.size() == 2 && selected != null && selected.size() > 0) {
            return selected.get(0) == invokers.get(0) ? invokers.get(1) : invokers.get(0);
        }
        Invoker<T> invoker = **loadbalance.select**(invokers, getUrl(), invocation);
`

**Comment by smallh0a1n1d0s** [comment]
Hi @beiwei30 . see you again, I'm not sure it's still a problem . For tag 2.5.5 , there are three cases where loadbalance. select (@SPI) is not extensible. Why not move it completely in the abstract method AbstractLoadBalance.select?  

```java
        if (invokers == null || invokers.size() == 0)
            return null;
        if (invokers.size() == 1)
            return invokers.get(0);
        // 如果只有两个invoker，退化成轮循
        if (invokers.size() == 2 && selected != null && selected.size() > 0) {
            return selected.get(0) == invokers.get(0) ? invokers.get(1) : invokers.get(0);
        }
        Invoker<T> invoker = loadbalance.select(invokers, getUrl(), invocation);

```

**Comment by carryxyh** [comment]
Hi, @smallh0a1n1d0s 
Seems like this logic has been moved into select in the latest version:

![image](https://user-images.githubusercontent.com/12047600/52936788-3d6b5280-3398-11e9-96b3-895e1dd5b9a4.png)

Is this still a problem for u? Or do you mean that we should bring this change to the 2.5.x branch?

**Comment by smallh0a1n1d0s** [comment]
Hi,@carryxyh 

l meant  the  AbstractClusterInvoker (eg) not the AbstractLoadBalance.
Shall we go a little further？Move  prepositional logic into AbstractLoadBalance.select or remove completely ~

```java
       private Invoker<T> doSelect(LoadBalance loadbalance, Invocation invocation,
                                List<Invoker<T>> invokers, List<Invoker<T>> selected) throws RpcException {

        if (CollectionUtils.isEmpty(invokers)) {
            return null;
        }
        if (invokers.size() == 1) {
            return invokers.get(0);
        }
        Invoker<T> invoker = loadbalance.select(invokers, getUrl(), invocation);
```

**Comment by smallh0a1n1d0s** [comment]
Hi,@carryxyh 

l meant  the  AbstractClusterInvoker (eg) not the AbstractLoadBalance.
Shall we go a little further？Move  prepositional logic into AbstractLoadBalance.select or remove completely ~

```java
       private Invoker<T> doSelect(LoadBalance loadbalance, Invocation invocation,
                                List<Invoker<T>> invokers, List<Invoker<T>> selected) throws RpcException {

        if (CollectionUtils.isEmpty(invokers)) {
            return null;
        }
        if (invokers.size() == 1) {
            return invokers.get(0);
        }
        Invoker<T> invoker = loadbalance.select(invokers, getUrl(), invocation);
```

**Comment by smallh0a1n1d0s** [comment]
for the tag 2.7.0  above

**Comment by carryxyh** [comment]
reasonable.
I will try to optimize this problem.

**Comment by carryxyh** [comment]
@smallh0a1n1d0s 
Pls check whether my pr can solve your problems, thx:
https://github.com/apache/incubator-dubbo/pull/3501

**Comment by zonghaishang** [comment]
@smallh0a1n1d0s 
I think you should extend the routing implementation yourself (refer: https://github.com/apache/incubator-dubbo/issues/1861).

```java
public class WarningRouter implements Router {

    @Override
    public <T> List<Invoker<T>> route(List<Invoker<T>> invokers, URL url, Invocation invocation)
            throws RpcException {

        if(invokers == null || invokers.isEmpty()){
            // trigger warning, no provider available
            return null;
        }

        int size = invokers.size();

        if(size > 1){
            // don't care about that. do nothing.
            return invokers;
        }

        if(size == 1)  {
            // trigger warning, only 1 provider available
            return invokers;
        }

        return invokers;
    }
}
```

> it is reasonable to return null when there's no invoker and directly return the invoker when there's only one
+1

**Comment by zonghaishang** [comment]
I don't agree with this modification. https://github.com/apache/incubator-dubbo/pull/3501 @carryxyh

**Comment by smallh0a1n1d0s** [comment]
@zonghaishang In my opinion.Firstly, let's think about why Dubbo provides both @SPI route and load balance . Secondly, whether the load balance @SPI is limited, or in some cases can't be extended. Users may want perfect extensibility for a framework, rather than simply filtering an invoker here.

**Comment by smallh0a1n1d0s** [comment]
I didn't say that the original writing was wrong, but there was a suggestion to make the SPI more extensible. If so, why not?

**Comment by zonghaishang** [comment]
If the requirements are not met, please override the select method.

**Comment by smallh0a1n1d0s** [comment]
Reasonable. I agree that `loadbalance` is more focused on filtering `invoker` logic. Let the extension logic rise to the `route` layer, and different applications customize the optional extension logic, such as: canary, circuit breaker, notification (existing 0 or 1 invoker ). As far as i know , `route` can only be expanded into a whole logic. `route` may need to use composite design pattern or configurable like `filter`.

**Comment by zonghaishang** [comment]
Router supports priority, similar to filter call.
so, temporarily close, and then reopen if necessary.

**Comment by smallh0a1n1d0s** [comment]
@zonghaishang 

@version 2.7.0
 ```java
    private Optional<List<Router>> toRouters(List<URL> urls) {
        if (urls == null || urls.isEmpty()) {
            return Optional.empty();
        }

        List<Router> routers = new ArrayList<>();
        for (URL url : urls) {
            if (Constants.EMPTY_PROTOCOL.equals(url.getProtocol())) {
                continue;
            }
            String routerType = url.getParameter(Constants.ROUTER_KEY);
            if (routerType != null && routerType.length() > 0) {
                url = url.setProtocol(routerType);
            }
            try {
 ######### Router looks like a single extension rather than The Filter Design Pattern############
                Router router = routerFactory.getRouter(url);
                if (!routers.contains(router)) {
                    routers.add(router);
                }
            } catch (Throwable t) {
                logger.error("convert router url to router error, url: " + url, t);
            }
        }

        return Optional.of(routers);
    }
```
