### ISSUE TITLE
接口继承接口的实际意义是什么 

### ISSUE THREAD

**Issue by zhaoyexing** [apache/incubator-dubbo#1863]
![image](https://user-images.githubusercontent.com/12453031/40660499-bc10d10e-6383-11e8-8d72-4d970281a440.png)
![image](https://user-images.githubusercontent.com/12453031/40660517-c9853e60-6383-11e8-8ee7-167c67eb9dd2.png)
![image](https://user-images.githubusercontent.com/12453031/40660524-d157fbd2-6383-11e8-80c4-aaf9a89197ee.png)
看了这段代码不是很懂，能不能解释一下呢？
还有，如果想要顺序消费和并行消费一起的话，应该怎么写这个外层抽象类，因为想要并行的方法只执行并行的消息，顺序的消息只执行顺序的消息 。现在的问题是，如果消息是并行的话，消息也会进入到顺序的消费里面，怎么限制这种情况呢？

**Comment by ralf0131** [comment]
This is not a issue related to Dubbo, please ask on the rocketmq community.
