### ISSUE TITLE
dubbo invoke 异常

### ISSUE THREAD

**Issue by BruceAKABear** [apache/incubator-dubbo#1867]
两个应用放在linux系统上，注册中心等放在另一个服务器上，在调用的时候出现invoke异常。所有常见的错误已经排除，有没有谁知道原因

**Comment by diecui1202** [comment]
Hi, @BruceAKABear Could you provider more information ? Such as exception stack trace.

**Comment by diecui1202** [comment]
Feel free to reopen if necessary.
