### ISSUE TITLE
IPC通信的支持

### ISSUE THREAD

**Issue by lingfengsan** [apache/incubator-dubbo#1869]
最近在做中间件比赛，需要实现service mesh功能，其中Provider和ProviderAgent是在同一主机上的，而目前dubbo里面通信的话我关注的netty里面是没有对IPC通信支持的。据我所知netty里面有一个可以支持的EpollServerDomainSocketChannel和EpollDomainSocketChannel(https://github.com/netty/netty/pull/3344)
是否可以支持下呢？

**Comment by carryxyh** [comment]
I tried to integrate, but for now, dubbo still can't support Domain socket.
I have already feedback this question to the community, and may integrate in the future.
:)

&READY-TO-CLOSE&
