### ISSUE TITLE
start.sh脚本问题

### ISSUE THREAD

**Issue by feelwing1314** [apache/incubator-dubbo#1879]
start.sh脚本中有三处使用ps命令的地方：第一处是ps -ef ~~~，第二处和第三处是ps -f ~~~。
但是ps -f并不能查出进程，我们在生产环境都统一改成了ps -ef，请问这里是不是有点小问题？

执行命令日志如下：
[afei@jtcrtvdra35 ~]$ ps -f | grep java
afei    30036 28792  0 14:53 pts/1    00:00:00 grep --color java
[afei@jtcrtvdra35 ~]$ 
[afei@jtcrtvdra35 ~]$ ps -ef | grep java
afei      325     1  0 Apr11 ?        11:43:37 java ... ...
afei     1406     1  0 May18 ?        02:20:11 java ... ...
... ...

**Comment by ralf0131** [comment]
Hello, would you please send a pull request?
