### ISSUE TITLE
Heartbeat detection mechanism optimization

### ISSUE THREAD

**Issue by chickenlj** [apache/incubator-dubbo#1888]
The original ticket in Apache JIRA: https://issues.apache.org/jira/browse/DUBBO-12

Related issues: #1371, #1454, #1365, #1450

**Comment by ralf0131** [comment]
#1454, #1365, #1450 are all closed.
Leaving it open since #1371 is still open.

**Comment by ralf0131** [comment]
All the related issues are closed. I am closing this now.
