### ISSUE TITLE
dubbo-admin启动报错

### ISSUE THREAD

**Issue by weishengshui** [apache/incubator-dubbo#189]
JDK1.7版本

java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;

**Comment by teaey** [comment]
详细堆栈贴下。

**Comment by ddatsh** [comment]
用自己编译的dubbo-admin启动的？
是不是jdk8编译的，去JDK7启动

**Comment by teaey** [comment]
@weishengshui  这个问题是在java8中编译的包，在低版本的java中去运行

**Comment by F191919** [comment]
![qq 20160112144231](https://cloud.githubusercontent.com/assets/11403274/12256726/b7f306e6-b93a-11e5-9de5-e3af65315897.png)

**Comment by F191919** [comment]
请问一下？这些名称空间都找不到了？ 启动不了？

**Comment by babydance** [comment]
jar包引用对的话，应该不会这样的，建议查一下依赖

**Comment by F191919** [comment]
我是直接克隆下master下的源码的啊 没改任何东西啊 浏览器直接访问也是404啊

**Comment by babydance** [comment]
启动的是哪个项目，看看这里https://github.com/alibaba/dubbo/issues/50，我是按照@stirp ，后来就没有问题了

**Comment by F191919** [comment]
是jdk版本问题 谢谢啊 麻烦了

**Comment by qct** [comment]
jdk版本的问题，
java8返回  ConcurrentHashMap.KeySetView<K,V>， 
java7返回 Set<K>。

**Comment by ralf0131** [comment]
This is because you compiled the code under Java 8 but run it under Java 7 or lower.
