### ISSUE TITLE
dubbo支持序列化kryo协议吗（！！！！！非dubbox）？

### ISSUE THREAD

**Issue by llx206** [apache/incubator-dubbo#1897]
想问下，dubbo采用的序列化协议可以支持kryo嘛。我知道，dubbo一直是采用heessian协议进行序列化的，没有采用kryo序列化协议。看代码中有kryo协议的代码，问下，dubbo什么时间开始支持kryo协议的。
另外，看过当当网的dubbox，他们是在dubbo的基础上面实现了自定义序列化协议kryo和fst等。阿里开源的dubbo现在也支持自定义kryo序列化吗，求大神解答！

**Comment by llx206** [comment]
服务端xml配置：
<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:dubbo="http://dubbo.apache.org/schema/dubbo"
       xmlns="http://www.springframework.org/schema/beans"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-4.3.xsd
       http://dubbo.apache.org/schema/dubbo http://dubbo.apache.org/schema/dubbo/dubbo.xsd">

    
    <dubbo:application name="demo-provider"/>

    <dubbo:protocol name="dubbo" dispatcher="all" threadpool="fixed" threads="200" />

    
    
    <dubbo:registry address="zookeeper://10.143.44.178:2181?backup=10.143.44.184:2181,10.143.44.190:2181" />

    
    <dubbo:protocol name="dubbo" port="23880" accepts="30"/>
    <dubbo:protocol name="dubbo" serialization="kryo" />                                                                                                             

    
    <bean id="demoService" class="com.alibaba.dubbo.demo.provider.DemoServiceImpl"/>

    
    <dubbo:service interface="com.alibaba.dubbo.demo.DemoService" ref="demoService" timeout="30" retries="0" version= "1.0" />
</beans>

采用<dubbo:protocol name="dubbo" serialization="kryo" /> kryo序列化协议，消费端和服务端运行正常，
但是根据perl工具+Flame，获取程序运行的火焰图，发现序列化协议仍然为hessian2，如下图所示：
![hessian](https://user-images.githubusercontent.com/39985288/41083472-d8ddf852-6a63-11e8-995e-e1c035b42498.png)

帮忙看下，是哪个地方使用不对吗，还是dubbo不能支持kryo序列化协议呢

**Comment by ralf0131** [comment]
Yes, dubbo does supports kryo. Please try using Dubbo 2.6.0+, the latest version 2.6.2 has just been released. Dangdang has donated the features to Dubbo. see: http://dubbo.apache.org/books/dubbo-user-book/demos/serialization.html

**Comment by gMan1990** [comment]
@llx206 ```perl工具+Flame，获取程序运行的火焰图```是什么东西，什么作用？
