### ISSUE TITLE
开发环境是否可以不依赖于远程服务，而是通过模拟服务来实现服务的调用？

### ISSUE THREAD

**Issue by wyc3146** [apache/incubator-dubbo#1909]
一个项目依赖太多dubbo服务，但是这些dubbo服务分属在不同的项目，在开发的时候一定要把依赖的服务都注册到注册中心吗？有没有什么模拟服务的方法？

**Comment by LinoMay** [comment]
1、如果你的目的是不注册到注册中心，但是还是要使用这些接口的处理逻辑，那么可以选择直连；
2、如果你不需要调用服务，只是想要正常起服务的话，那么可以在启动服务的时候，consumer 配置文件配置 check=“false” 属性；

**Comment by kimmking** [comment]
you can use mock service ref:
http://dubbo.apache.org/books/dubbo-user-book/demos/local-mock.html

**Comment by diecui1202** [comment]
Feel free to reopen it if u get other problem
