### ISSUE TITLE
Please add "git checkout dubbo-2.6.2" in the docs of demo.

### ISSUE THREAD

**Issue by guanpengchn** [apache/incubator-dubbo#1910]
When I use the demo of Dubbo, there are some errors in it. 
Please add `git checkout dubbo-2.6.2` in the docs of demo.
Such as:
```
git clone https://github.com/apache/incubator-dubbo.git
git checkout dubbo-2.6.2
cd incubator-dubbo
```

[Doc link](http://dubbo.apache.org/books/dubbo-admin-book/)

**Comment by chickenlj** [comment]
> When I use the demo of Dubbo, there are some errors in it.
What exactly is the error? Could you describe in more details? Do you get the problem with the master branch?

**Comment by guanpengchn** [comment]
Maven can't find and download the jar packages.
For example:
`import com.alibaba.dubbo.rpc.RpcContext;` get error. 
But if I switch to `dubbo-2.6.2`, all the best.
Could you tell me the reason?

**Comment by beiwei30** [comment]
not sure what happens, you may consider to clean up your environment and give it a retry. master branch is running everyday and guarded with travis CI.
