### ISSUE TITLE
dubbo2.6.0 restful service cors domain

### ISSUE THREAD

**Issue by leiyazhen** [apache/incubator-dubbo#1911]
how to fix the problem that cors domain problem in using rest servie ,protocal is netty.

**Comment by chickenlj** [comment]
I am not much familiar with the CORS problem with REST, shouldn't it be a specific problem related to Resteasy (the framework Dubbo uses as REST solution)? 

Is the way Dubbo integrates RestEasy blocks you from using CORS?

**Comment by leiyazhen** [comment]
I fixed this problem by edit client request method through another way that jquery callback.
I just wonder how to fix this problem on service side.
The restful service in dubbo is anotioned by resteasy framework,and i do not find the anotion about enable corss domain request.

**Comment by leiyazhen** [comment]
I fixed this problem by edit client request method through another way that jquery callback.
I just wonder how to fix this problem on service side.
The restful service in dubbo is anotioned by resteasy framework,and i do not find the anotion about enable corss domain request.

**Comment by kimmking** [comment]
I will replace jackson lib by fastjson for rest protocol, then I will set CORS option is open by default.

**Comment by beiwei30** [comment]
Looks like there's nothing need to implement, pls. check http://docs.jboss.org/resteasy/docs/3.1.3.Final/userguide/html/ch30.html.

You could simply include **CorsFilter** like this:

```xml
<dubbo:protocol name="rest" port="8888" extension="org.jboss.resteasy.plugins.interceptors.CorsFilter"/>
```
