### ISSUE TITLE
dubbo-monitor-simple Missing service menu

### ISSUE THREAD

**Issue by llx206** [apache/incubator-dubbo#1914]
![image](https://user-images.githubusercontent.com/39985288/41219864-3e28fffa-6d92-11e8-9901-853c14cb22e0.png)

After the monitoring service starts, the services menu cannot be found. The icon statistics item is not found

**Comment by kingwang317** [comment]
me too!!

**Comment by kingwang317** [comment]
my problems are resolved 

if your services in docker

/dubbo-monitor-simple/src/main/resources/METAINF/dubbo/internal/com.alibaba.dubbo.container.Container 

Edit to 
jetty-monitor=com.alibaba.dubbo.monitor.simple.container.JettyContainer

and find dubbo.properties edit to 
 
dubbo.container=log4j,spring,registry,jetty-monitor

**Comment by htynkn** [comment]
@llx206 this issue was fixed 
 via https://github.com/apache/incubator-dubbo-ops/commit/3dc581f938eb84ae424cb7b2c63f0f8571150a03

Could you try latest version?
