### ISSUE TITLE
Condition is not properly used ?

### ISSUE THREAD

**Issue by SoyeeDst** [apache/incubator-dubbo#1917]
https://github.com/apache/incubator-dubbo/blob/3e9b66854c6f70b1dfa7dd19e689bd04ae0ecb41/dubbo-registry/dubbo-registry-redis/src/main/java/com/alibaba/dubbo/registry/redis/RedisRegistry.java#L590

https://github.com/apache/incubator-dubbo/blob/3e9b66854c6f70b1dfa7dd19e689bd04ae0ecb41/dubbo-registry/dubbo-registry-redis/src/main/java/com/alibaba/dubbo/registry/redis/RedisRegistry.java#L602

Just read the RedisRegistry.java and got doubtful about the above lines. Is the following code more appropriate ?

```
if (first) {
   // blah blah												
} 
```

**Comment by carryxyh** [comment]
Feel free to submit a PR to optimize this section.
 I also think that you can optimize the indentation of the code...
The current indentation is not beautiful.
:)

**Comment by CrazyHZM** [comment]
if there is an exception in the subscription to Redis, when the disconnection is successful, we can think that the Redis connection is broken, we need to re-initiate the subscription, and we need to get the latest data from Redis again. But in JedisPool, no connection monitoring mechanism is provided.
The first attribute is to achieve the effect of connection monitoring.
If my idea is correct, I will submit  the PR to fix it #3087
