### ISSUE TITLE
Redundant toString() is called

### ISSUE THREAD

**Issue by hqq2023623** [apache/incubator-dubbo#1925]
branch : master , version : 2.7.0-SNAPSHOT
ServiceConfig#doExportUrlsFor1Protocol , line 482

<img width="890" alt="image" src="https://user-images.githubusercontent.com/6971152/41273922-035827c2-6e4e-11e8-8a72-71562d138cf9.png">

The type of Constant.SCOPE_Xxx is String already , no need to call toString() again

**Comment by hqq2023623** [comment]
BTW , there are some rebundant comparison of null like : 
ServiceBean# afterPropertiesSet , line 217
<img width="818" alt="image" src="https://user-images.githubusercontent.com/6971152/41275171-9e1e3c2a-6e52-11e8-95b2-b6c1079f438e.png">

registryConfigs is a new instance of ArrayList , will not be null
In addition , if registryConfigs is null , the for () statement will throw NPE before the comparison

**Comment by ralf0131** [comment]
Hi, thanks for reporting, would you please send a pull request?
