### ISSUE TITLE
Enhancing IDE support for custom spring namespace elements (dubbo)

### ISSUE THREAD

**Issue by ulinkwo** [apache/incubator-dubbo#1927]
when we add dubbo configuration in xml file, the IDE ( like IntelliJ )starts warning me about `Custom Spring Beans` not being parsed. There is a quick fix for it, but it pops back as soon as any changes are made. It’s just a warning, everything will work fine at runtime. But annoying nonetheless.

**Comment by bianjp** [comment]
Met the same problem, and I opened a [ticket](https://youtrack.jetbrains.com/issue/IDEA-190547) for IntelliJ IDEA two months ago, but it seems that no progress has been made until now.

I'm not sure whether Dubbo or IntelliJ IDEA should be responsible for this issue.

**Comment by bianjp** [comment]
It still didn't solve the problem that IDE cannot parse the correct bean type?
