### ISSUE TITLE
if i disable dubbo qos,are there any other effects? 

### ISSUE THREAD

**Issue by zhuguoming** [apache/incubator-dubbo#1928]
i use  dubbo.application.qos.enable=false  to close qos server,but dont konw whether has any other effects.

**Comment by ralf0131** [comment]
What are your concerns? Disabling qos will cause you cannot view the stats via telnet/http, and you may not be able to execute commands like online/offline services.

**Comment by ralf0131** [comment]
Hi, I am closing this issue, feel free to reopen it if necessary.
