### ISSUE TITLE
No such configuration property version

### ISSUE THREAD

**Issue by ulinkwo** [apache/incubator-dubbo#1929]
https://github.com/apache/incubator-dubbo/blob/5a4c0768fd8989c1f82710a50a288e26fa69215a/dubbo-config/dubbo-config-spring/src/test/resources/com/alibaba/dubbo/config/spring/annotation-version-consumer.xml#L26

as above, there is no configuration property `version` in dubbo.xsd, it is eally confused. i think it could be removed if no other purpose.

**Comment by chickenlj** [comment]
Would you please send a pull request?
