### ISSUE TITLE
2.6.2没有dubbo-admin了？

### ISSUE THREAD

**Issue by empireghost** [apache/incubator-dubbo#1931]
dubbo 2.6.2 版本下载后执行 mvn clean package ,怎么没有找到 dubbo-admin？

**Comment by empireghost** [comment]
另外，现在 dubbo2.6.2 也支持 rest了，怎么没看到相关的文档？

**Comment by ulinkwo** [comment]
@empireghost 

https://github.com/apache/incubator-dubbo-ops

dubbo-admin is here

**Comment by ulinkwo** [comment]
dubbo rest is merged from dubbox ( #1001 ), so i think u could only refer to the docs currently (https://github.com/dangdangdotcom/dubbox)

**Comment by ralf0131** [comment]
@ulinkwo The documentation are also merged into Dubbo, checkout here: http://dubbo.apache.org/books/dubbo-user-book/references/protocol/rest.html
