### ISSUE TITLE
redis相关模块缺少jar包依赖

### ISSUE THREAD

**Issue by LinoMay** [apache/incubator-dubbo#1937]
dubbo-registry-redis/dubbo-rpc-redis 这两个模块是否缺少common-pool2.jar包依赖？
clone项目后编译，发现这两个模块均缺少common-pool2.jar包依赖，pom加上依赖后编译通过。

**Comment by LinoMay** [comment]
com.alibaba.dubbo.rpc.protocol.redis.RedisProtocol&com.alibaba.dubbo.registry.redis.RedisRegistry
都用到了org.apache.commons.pool2.impl.GenericObjectPoolConfig这个类，而现有的项目中并没有该jar包依赖

**Comment by beiwei30** [comment]
dubbo.jar includes all dubbo relevant files but doesn't include its dependencies, that means, you need to explicitly include the desired dependencies by yourself. For your convenience, you can import the following bom to simplify this part of work:

```xml
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>dubbo-dependencies-bom</artifactId>
                <version>${dubbo.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```
