### ISSUE TITLE
zk node可能无法删除导致路由规则与动态配置内容无法删除

### ISSUE THREAD

**Issue by xinyonda** [apache/incubator-dubbo#194]
通过检查，可能的原因是node name包含空格，或者换行等导致执行zk命令时，name被截取了部分，所以导致无法删除或更新，需要处理nodename时，去掉空格与换行等可能导致截取部分字符串的情况

**Comment by teaey** [comment]
你们的node name是什么样的？

**Comment by justein** [comment]
node name在有空格时，zk貌似真存在这个问题

**Comment by diecui1202** [comment]
@xinyonda Have you solved the problem? We are going to close this issue. Feel free to reopen it.

&READY-TO-CLOSE&

**Comment by zonghaishang** [comment]
Feel free to reopen it
