### ISSUE TITLE
dubbo 2.6.x与2.4.x互相调用的兼容问题

### ISSUE THREAD

**Issue by breakenknife** [apache/incubator-dubbo#1942]
我们公司现在还是2.4.x,想从部分应用开始升级为2.6.x.  请问会有兼容问题吗? 
如果有,那么2.4.x最高可与哪个版本兼容呢?

**Comment by kimmking** [comment]
I guess it will be okay,

**Comment by swift1911** [comment]
@breakenknife 我们用下来是没有问题的

**Comment by carryxyh** [comment]
@breakenknife 
Still have any problems? 
If not we will close this issue soon. :)
