### ISSUE TITLE
How do provider inside the k8s communicate with  customer outside the k8s?

### ISSUE THREAD

**Issue by jack161641** [apache/incubator-dubbo#1947]
provider inside the k8s communicate register POD ip into zookeeper, how customer outside the k8s call the provider inside the k8s?

**Comment by ralf0131** [comment]
You may check this example: https://github.com/dubbo/dubbo-samples/tree/master/dubbo-samples-docker

**Comment by Jeff-Lv** [comment]
Provider inside k8s and consumer out of control of k8s? Please take some time to look into K8S tutorial about Ingress part. 

This issue is not related to Dubbo and should be closed.

**Comment by chickenlj** [comment]
As @Jeff-Lv suggested, please try the Ingress part first.

Reopen this issue if necessary.

**Comment by FANHIDE** [comment]
@chickenlj ，麻烦问下ingress支持dubbo服务吗
