### ISSUE TITLE
@Reference check=false不生效

### ISSUE THREAD

**Issue by mycybyby** [apache/incubator-dubbo#195]
AbstractConfig中appendAnnotation方法中：
if (value != null && ! value.equals(method.getDefaultValue())) 
因为check=false等于默认值，所以if里面的逻辑没有执行（setter方法没有被调用），导致AbstractReferenceConfig的check没有修改为false，还是null。
根本原因还是AbstractReferenceConfig中check的默认值是null，而@Reference的默认值是false，修改方法要不把AbstractReferenceConfig的check改成false，要不把上面的判断去掉。

**Comment by kxyfyh** [comment]
直接
@Reference
中的默认值该为true 也能搞定吧

**Comment by liuanxin** [comment]
也就是所有不值设置为 false 的都将会被忽略 然后实际用到这个值的地方没有同时设置这个默认值. 加这种 `!value.equals(method.getDefaultValue())` 自做聪明的判断, 又不把后续处理的地方同步!

单说这个问题, 目前看来只能在运行时加上 `-Ddubbo.reference.check=false` 这么处理了

**Comment by liuanxin** [comment]
@kxyfyh 这样就把运行时的语义给变了. 这么处理只会带来更多的问题

**Comment by Comven** [comment]
@liuanxin  我在IDEA启动时加上-Ddubbo.reference.check=false 执行效果是一样的呢

**Comment by Comven** [comment]
目前测试到spring-boot-starter-dubbo项目必须设置consumer.check=false才行，这样一来变成了所有都不检查，虽然不是初衷，但是目前只能这样子了，还是希望官方修复下@Reference注解

**Comment by AniFengx** [comment]
@Comven spring.dubbo.consumer.check=false 我添加这个配置并没有生效，他还是会所有都检测一遍，如果我希望消费方先于提供方启动有什么办法吗

**Comment by jaychang9** [comment]
我是直接搞个spring-dubbo-consumer.xml
然后配一个
`    
    <dubbo:consumer check="false"/>` 就可以了
