### ISSUE TITLE
跨group调用

### ISSUE THREAD

**Issue by liudc001** [apache/incubator-dubbo#1955]
现在的版本能支持服务跨组调用吗？（2.6.0上试过不行）

+ provider group A
`
<dubbo:registry protocol="zookeeper" address="192.168.50.130:2181" check="false" group="A"/> <dubbo:service interface="com.alibaba.dubbo.demo.DemoService" ref="demoService"/>
`
+ consumer group B
`
<dubbo:registry protocol="zookeeper" address="192.168.50.130:2181" check="false" group="B"/> <dubbo:reference id="demoService" check="false" interface="com.alibaba.dubbo.demo.DemoService" group="A"/>
`

**Comment by kimmking** [comment]
You can't invoke services between groupA and groupB.
Until now, one group is designed to be an independent and isolated cluster, cause in a registry center a group has a root path that is not the same one from another. The a consumer will never see a provider in other group.
In your case, the provider in group A send its metadata to zk in path /A/....
And then the consumer in group B will fetch metadata from zk in path /B/....
So consumer can't find demoService provider.

**Comment by liudc001** [comment]
@kimmking  thank you for your response .
my case like this 
+ business system A  --- group A
+ business system B --- group B
+ some common system (some like sequence service ) --- group C 

business system must be isolated，such as A and B， but common system service is sharing...
util now，Is there a better solution？
Will this case be supported in the future?

**Comment by kimmking** [comment]
<dubbo:reference id="demoServiceA" check="false" interface="com.alibaba.dubbo.demo.DemoService" group="A"/>

<dubbo:reference id="demoServiceB" check="false" interface="com.alibaba.dubbo.demo.DemoService" group="B"/>

**Comment by chickenlj** [comment]
Duplicate of #1977
