### ISSUE TITLE
dubbo.application.qos.enable=false 在apollo中无效

### ISSUE THREAD

**Issue by 457049726** [apache/incubator-dubbo#1964]
项目用 spring boot ,dubbo 2.6.1接合apollo配置中心，包括 spring.application.name 、dubbo.protocol.port 在内的 几乎所有配置都放在apollo，但运行后发现 qos无法禁用，把 dubbo.application.qos.enable=false配置到apollo时无效，但放到 applocation.proterties 后正常。初步确定可能是 框架没有从配置中心获取 dubbo.application.qos.enable 配置，从而采用默认的配置

**Comment by EonianGlutton** [comment]
application.properties或者application.yml中，加了这个没？apollo.bootstrap.enabled=true

**Comment by 457049726** [comment]
回复  EonianGlutton ：
项目用的是spring boot  配合 apollo配置中心 一起使用，项目没有 dubbo.properties配置文件，而且application.properties或者application.yml 没有任何dubbo方面的配置，所有配置被转移到 apollo。但是spring.application.name 、dubbo.protocol.port之类的参数，配置在 apollo 中正正常被系统拉取到。但唯独  dubbo.application.qos.enable 和  dubbo.application.qos.port 配置无效。
不过刚刚经过自己查看 dubbo配置方面的源代码，尝试性的在 apollo中将 dubbo.application.qos.enable 配置改成  dubbo.application.qosEnable 这个，问题得到解决。

**Comment by 457049726** [comment]
总结：解决 pos方面的配置写到 apollo配置中心无效的方法是把， dubbo.application.qos.enable 配置改成  dubbo.application.qosEnable，同理，如果想替换默认端口，需要把  dubbo.application.qos.port 改成  dubbo.application.qosPort

**Comment by jKill** [comment]
为什么 dubbo.application.qos.enable 配置改成 dubbo.application.qosEnable就解决了，有找到原因吗

**Comment by brianshilei** [comment]
> 项目用 spring boot ,dubbo 2.6.1接合apollo配置中心，包括 spring.application.name 、dubbo.protocol.port 在内的 几乎所有配置都放在apollo，但运行后发现 qos无法禁用，把 dubbo.application.qos.enable=false配置到apollo时无效，但放到 applocation.proterties 后正常。初步确定可能是 框架没有从配置中心获取 dubbo.application.qos.enable 配置，从而采用默认的配置

方便发我下demo吗
