### ISSUE TITLE
最新的trunk代码编译后将dubbo-admin.war部署到tomcat7下报错！

### ISSUE THREAD

**Issue by jpr1990** [apache/incubator-dubbo#197]
git clone https://github.com/alibaba/dubbo dubbo

mvn clean install -Dmaven.test.skip=true

upload the compiled dubbo-admin.war to tomcat7.x

startup.sh

-> throw Exception:

Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'productionModeSensiblePostProcessor': Cannot create inner bean '(inner bean)' of type [com.alibaba.citrus.springext.util.SpringExtUtil$ConstructorArg] while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#11': FactoryBean threw exception on object creation; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'registryService': Instantiation of bean failed; nested exception is java.lang.ExceptionInInitializerError
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:230)

**Comment by jpr1990** [comment]
已解决。

我的解决办法（实测通过）：
将本地的Windows环境变量JAVA_HOME设置为1.7版本。
同时Idea打开的Dubbo的JDK也设置为1.7版本
执行 mvn clean install -Dmaven.test.skip=true

本地Tomcat7测试通过，Linux测试环境测试通过；没有修改官方的trunk源码。

**Comment by jpr1990** [comment]
需要tomcat7.x和jdk6/7支持；JDK8运行会报错，切记！

**Comment by teaey** [comment]
请问，jdk8 运行，有完成的错误堆栈么？

**Comment by ralf0131** [comment]
This issue should be fixed.
