### ISSUE TITLE
AbstractConfigTest.appendAnnotation not stable in Java 10

### ISSUE THREAD

**Issue by diecui1202** [apache/incubator-dubbo#1971]
line 270: 
```
        TestCase.assertEquals("<dubbo:annotation filter=\"f1, f2\" listener=\"l1, l2\" />",
                annotationConfig.toString());
```

Sometimes failed, the error is: 

```
junit.framework.ComparisonFailure: 
Expected :<dubbo:annotation filter="f1, f2" listener="l1, l2" />
Actual   :<dubbo:annotation listener="l1, l2" filter="f1, f2" />
```

**Comment by ralf0131** [comment]
`org.apache.dubbo.config.AbstractConfig#toString` use reflection to iterate the methods, according to the java doc, the elements in the returned array are not sorted and are not in any particular order.

I am afraid that this issue will affect all Java versions.

**Comment by diecui1202** [comment]
#2097 has fixed this problem.
