### ISSUE TITLE
啥时候dubbo能用euraka 做注册中心，然后和springcloud的微服务互相调用，那就完美了

### ISSUE THREAD

**Issue by wodebite** [apache/incubator-dubbo#1981]
诉求

**Comment by beiwei30** [comment]
noted and will consider

**Comment by ralf0131** [comment]
related to #1960

**Comment by RodgerLai** [comment]
万民血书求上euraka

**Comment by luyuanwan** [comment]
我觉得可以自己先做一个简易的版本试一下，如果觉得不错，可以提交上来，再决定是否要合并到主分支

**Comment by diecui1202** [comment]
Eureka 2.0 is discontinued. Refer https://github.com/netflix/eureka/wiki

So it's necessary to support eureka for registry?

**Comment by diecui1202** [comment]
@wodebite We found that Eureka is suitable for rest service discovery, but not for RPC service. In Spring Cloud application can just registry the ip, port and metadata to Eureka, which is called ServiceInstance. But for Dubbo, we need to registry all the services. 

We try to put all the service meta info into ServiceInstance metadata, and find that we need to use ApplicationName as the key for service discovery, and then parse it's metadata.  It works, but it's not suitable.

IMO, we can defer the integrate dubbo with Eureka.

**Comment by diecui1202** [comment]
Feel free to reopen if necessary. Welcome more discussions.
