### ISSUE TITLE
can dubbo support protobuf ? 

### ISSUE THREAD

**Issue by wangaicui** [apache/incubator-dubbo#1983]
请问是否有版本支持protobuf序列化方式

**Comment by kimmking** [comment]
https://www.bbsmax.com/A/pRdBaZ75nx/

**Comment by chickenlj** [comment]
@vangoleo is working on this, @vangoleo , would you like to share your implementation and progress here?

**Comment by diecui1202** [comment]
@wangaicui just a demo, https://github.com/vangoleo/incubator-dubbo/tree/protobuf

Any one wants to improve this ?

**Comment by diecui1202** [comment]
@satansk That's great.

**Comment by beiwei30** [comment]
follow up with https://github.com/apache/incubator-dubbo/pull/2691

**Comment by beiwei30** [comment]
but in order to support protostuff better, we still need enhance the current implementation further.
