### ISSUE TITLE
作者是否能够将这个应用在Docker容器里面的网络通用问题解决了，再发布一个新版本出来

### ISSUE THREAD

**Issue by hanwangkun** [apache/incubator-dubbo#1992]

**Comment by ralf0131** [comment]
What problem have you encountered? You need to clearly describe it, unless the community cannot help you. 

These question you propose make no sense to solve your problem.

**Comment by kimmking** [comment]
@hanwangkun 
I guess you can mapping a specified port across docker containers.

**Comment by chickenlj** [comment]
Would you please describe your problems with more details? We are thinking of the enhancements Dubbo should do in order to satisfy Docker and K8S, it will help a lot if you can do that.

**Comment by hanwangkun** [comment]
就是如果把dubbo服务发布在docker容器里面，注册到zk里面的地址是docker的内网，这样，其他的机器就不能访问这个dubbo服务了。

**Comment by ralf0131** [comment]
Please check this example: https://github.com/dubbo/dubbo-samples/tree/master/dubbo-samples-docker

It should solve your problem. I am closing it now.

If not, please reopen this issue.
