### ISSUE TITLE
怎么配置多协议

### ISSUE THREAD

**Issue by luosai001** [apache/incubator-dubbo#2000]
在application.properties定义了两个协议 rest,dubbo，配置文件提示重复key. 
在两个service中分别使用rest,和dubbo协议暴露。启动服务保存，找不到rest;
是不是后面的dubbo,覆盖了rest.如果是这样那该怎么定义多协议呢

**Comment by luosai001** [comment]
已经解决了，不能通过配置文件配置多个协议。需要通过API配置多个协议注入

**Comment by chickenlj** [comment]
It should work with .properties, would you please show your configuration files or attach a demo so we can reproduce the problem?

**Comment by chickenlj** [comment]
Problem solved.
