### ISSUE TITLE
泛化调用出现递归问题导致StackOver,升级到2.5.10问题依然存在

### ISSUE THREAD

**Issue by lgxnu** [apache/incubator-dubbo#2007]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/wiki/FAQ) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.4.6
* Operating System version: xxx
* Java version: xxx

### Step to reproduce this issue

 ApplicationConfig application = new ApplicationConfig();
        application.setName("yyy");

        ReferenceConfig<com.alibaba.dubbo.rpc.service.GenericService> reference =
                new ReferenceConfig();

        reference.setInterface("com.xx.user.center.service.IUserCenterService");
//        reference.setVersion("1.0");
        reference.setApplication(application);
        reference.setGeneric(true); // 声明为泛化接口
        reference.setTimeout(1000000);
        RegistryConfig registry = new RegistryConfig();
         registry.setAddress("zookeeper://test.zookeeper.hujiao:2181");
 

         reference.setRegistry(registry);
         reference.setUrl("dubbo://xxx.xxx.xxx.xxx:10800/com.xx.user.center.service.IUserCenterService");

        // reference.setApplication(new ApplicationConfig("call-dubbo-demo"));

// 用com.alibaba.dubbo.rpc.service.GenericService可以替代所有接口引用
        com.alibaba.dubbo.rpc.service.GenericService genericService = reference.get();

// 基本类型以及Date,List,Map等不需要转换，直接调用
        Object result = genericService.$invoke("getUserHobbies", new String[] {"long"}, new Object[] {17795906});

### Expected Result
Expected return corresponding result

### Actual Result

What is actually happen?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```
.MonitorService%26pid%3D10844%26timestamp%3D1530173780280&owner=nobody&pid=10844&revision=1.2.2-SNAPSHOT&side=consumer&timestamp=1530173780231, cause: java.lang.StackOverflowError
java.lang.StackOverflowError
	at java.lang.Exception.<init>(Exception.java:102)
	at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:89)
	at java.lang.reflect.InvocationTargetException.<init>(InvocationTargetException.java:72)
	at sun.reflect.GeneratedMethodAccessor88.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at com.alibaba.dubbo.common.utils.PojoUtils.generalize(PojoUtils.java:168)
	at com.alibaba.dubbo.common.utils.PojoUtils.generalize(PojoUtils.java:168)
	at com.alibaba.dubbo.common.utils.PojoUtils.generalize(PojoUtils.java:168)
	at com.alibaba.dubbo.common.utils.PojoUtils.generalize(PojoUtils.java:168)

**Comment by lgxnu** [comment]
https://code.aliyun.com/alibaba/dubbo/commit/73700cb7296399be98316e09b44fb2ed4be5e924

This link should fix this bug, but I don't know which version on github works

**Comment by diecui1202** [comment]
@lgxnu could you try it with dubbo 2.6.2 ?

**Comment by lgxnu** [comment]
@diecui1202 many thanks, the problem resolved. Indeed, it caused by my pojo, the following code will case recursive calling on converting pojo to map as dubbo will convert every method starts with get to a map field. to correct this, we can change the method name which don't start with get 
 
e.g.

Class Person{
Person getPerson(){
return this
}

}

**Comment by diecui1202** [comment]
Got it. Please label 'FAQ' on this issue for other users. Thanks a lot.
