### ISSUE TITLE
problem about dubbo's status checker SpringStatusChecker when using springboot

### ISSUE THREAD

**Issue by LijyCasey** [apache/incubator-dubbo#2009]
recently I use spring boot to develop a dubbo monitor system like dubbo-admin or handu's dubbo-monitor.When I check the system's status with dubbo status checker,the SpringStatusChecker.check() throws an Exception:

```
Caused by: java.lang.UnsupportedOperationException: GenericWebApplicationContext does not support getConfigLocations()
	at org.springframework.web.context.support.GenericWebApplicationContext.getConfigLocations(GenericWebApplicationContext.java:244) ~[spring-web-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	... 92 common frames omitted
```

It seems like GenericWebApplicationContext dosen't support function getConfigLocations().I think this exception related to Spring Boot because the same code run in the triditional Spring MVC project didn't throw exception and can get the correct spring config information.I want to know how to resolve this problem .
And here is my code to get the system status : 

```java
@PostMapping()
	public Result<DubboStatus> status(){
		List<DubboStatus> rows = new ArrayList<DubboStatus>();
        Set<String> names = ExtensionLoader.getExtensionLoader(StatusChecker.class).getSupportedExtensions();
        DubboStatus dubboStatus;
        for (String name : names) {
            StatusChecker checker = ExtensionLoader.getExtensionLoader(StatusChecker.class).getExtension(name);
            Status status = checker.check();
            if (status != null && !Status.Level.UNKNOWN.equals(status.getLevel())) {
                dubboStatus = new DubboStatus();
                dubboStatus.setName(name);
                dubboStatus.setStatus(status);
                dubboStatus.setDescription(status.getMessage());
                rows.add(dubboStatus);
            }
        }
        return ResultUtils.wrapResult(rows);
	}
```
I'm looking forward to the answer ,thanks for watching.

**Comment by LijyCasey** [comment]
edit title

**Comment by nzomkxia** [comment]
can you provide a demo that can reproduce this issue?

**Comment by beiwei30** [comment]
in fact, it is a warning log message instead of a thrown exception, see below in org.apache.dubbo.config.spring.status.SpringStatusChecker#check:

```java
        } catch (Throwable t) {
            logger.warn(t.getMessage(), t);
        }
```

I think this is not a bug. Right now SpringStatusChecker checks config locations for all potential ConfigurableWebApplicationContext's implementations within which some impls may throw UnsupportedOperationException but I think it's fine since eventually SpringStatusChecker will **catch** all exceptions and logs a warning.
