### ISSUE TITLE
dubbo provider和consumer传输对象用什么协议比较好，需要序列化吗

### ISSUE THREAD

**Issue by kuaikuaikim** [apache/incubator-dubbo#201]
dubbo provider和consumer传输对象用什么协议比较好，需要序列化吗

**Comment by orika** [comment]
肯定需要序列化，协议目前默认是用dubbo私有协议的，效率高点

**Comment by ralf0131** [comment]
Please checkout the available protocols: http://dubbo.apache.org/books/dubbo-user-book/references/protocol/introduction.html
