### ISSUE TITLE
application.yml文件里的dubbo节点无法处理${}形式的变量引用

### ISSUE THREAD

**Issue by gy0801151351** [apache/incubator-dubbo#2012]
如下面所示:
dubbo:
　application:
　　id: service-core
　　name: service-core
　　version: 1.0.0
　　owner: GongYan

上面是一般配置, 可以正常读取, 但如果采用了${}的形式, 就无法正确解析属性值
dubbo:
　application:
　　id: service-core
　　name: service-core
　　version: 1.0.0
　　owner: ${dubbo.application.name}

但是, spring原生体系中,是可以通过${}形式解析属性值的

**Comment by gudegg** [comment]
fixed  (#1895 )

**Comment by ralf0131** [comment]
The placeholder feature has been added recently, please check the latest code. Feel free to reopen if it still exists.
