### ISSUE TITLE
configurators 里面的参数不能动态生效

### ISSUE THREAD

**Issue by Nocturnana** [apache/incubator-dubbo#2015]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/wiki/FAQ) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.5.3
* Operating System version: xxx
* Java version: xxx

### Step to reproduce this issue

1. configurators 里面的参数不能动态生效

### Expected Result

动态生效

### Actual Result

不生效

```
Just put your stack trace here!
```

**Comment by luyuanwan** [comment]
可以把你的问题描述得再具体一些，比如给个具体的例子 @Nocturnana

**Comment by chickenlj** [comment]
@Nocturnana A more detailed case will help to reproduce the problem.

**Comment by chickenlj** [comment]
Please reopen this issue when you can provide more details.
