### ISSUE TITLE
dubbo javassist 动态生成的类如何调试

### ISSUE THREAD

**Issue by hubuyt** [apache/incubator-dubbo#2021]
你好 我正在研究dubbo源代码 感觉dubbo里面大量应用了javassist生成新的类，不好调试，我把生成的类 自己新建类放到项目下去 可以直接调试吗
![qq 20180704132259](https://user-images.githubusercontent.com/11042146/42258320-b176fbee-7f8d-11e8-9abb-b9f5be65ca4b.png) 类似这样的  ，我试过adaptive 类的代码可以  provider的本地代理好像不行

**Comment by peachyy** [comment]
之前也尝试过这样的需求，感觉意义不大

**Comment by chickenlj** [comment]
You can try proxy='jdk', which is more easy to debug.

Reopen whenever is necesary
