### ISSUE TITLE
upgrade netty4 to the latest release and make it the default option for transporter

### ISSUE THREAD

**Issue by beiwei30** [apache/incubator-dubbo#2029]
we should upgrade netty4 to the latest release and make it the default option for transporter

**Comment by zonghaishang** [comment]
It look goods to me :-)

**Comment by carryxyh** [comment]
looks good!
I'd like to add flow control into netty4 transport

**Comment by chickenlj** [comment]
Fixed in the master branch with #2049, need to sync to 2.6.x.
