### ISSUE TITLE
请问怎么关闭 dubbo的telnet

### ISSUE THREAD

**Issue by xizhimen** [apache/incubator-dubbo#2033]
### Environment

* Dubbo version: 2.5.3
* Operating System version: redhat 6.8
* Java version: 1.7

只看到这个https://github.com/apache/incubator-dubbo/issues/1433 但没找到具体方法

**Comment by carryxyh** [comment]
use like this : <dubbo:service filter="-telnet" />

**Comment by xizhimen** [comment]
@carryxyh 我这么配的,但是报错了,具体如下: 
![image](https://user-images.githubusercontent.com/19748550/42359264-6a7991de-8113-11e8-8248-546802e89553.png)
报错:
No such extension telnet for filter/com.alibaba.dubbo.rpc.Filter

**Comment by carryxyh** [comment]
It might be a bug. @xizhimen

**Comment by bohrqiu** [comment]
关闭不了吧  https://github.com/apache/incubator-dubbo/blob/9e5d3bf031e63569b39171490dc15f52ecaf6b0f/dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeHandler.java#L201

**Comment by xizhimen** [comment]
@bohrqiu 
但https://github.com/apache/incubator-dubbo/issues/1433这里说可以关的

**Comment by carryxyh** [comment]
@xizhimen @bohrqiu 
It should be.
But not  :(
we have noticed it. A response can be given soon.

**Comment by chickenlj** [comment]
@carryxyh Please help check if it's a bug, if not, we can complete the document.

**Comment by luyuanwan** [comment]
可以拉取最新代码，试试就知道是不是bug
