### ISSUE TITLE
@Reference用起来有点别扭

### ISSUE THREAD

**Issue by kibear** [apache/incubator-dubbo#2038]
dubbo和spring-boot集成的时候。
consumer注入远程bean的时候，现在只能用 `@Reference` 来实现，
类似：
```
@Reference
private HelloService helloService;
```

为什么不提供一个@Autowired的注解来实现属性注入
```
@Autowired
private HelloService helloService;
```

这样看起来更加直观。

**Comment by brucelwl** [comment]
@Reference代表远程调用, @Autowired 代表本地注入 我觉得很合理

**Comment by kibear** [comment]
`@reference`代表引用spring中定义的bean，`@Autowired`代表注入spring中定义的bean，实际上他们功能是一直的，只不过ref是以前xml的有这个概念，Autowired是注解方式用的。既然现在都是用springboot全注解开发，当然用`@Autowired`来实现注入。没有远程不远程，ref没有远程意思，Autowired也没用本地的意思，如果有，那也是你们自己解释的。
