### ISSUE TITLE
Dubbo admin同步zookeeper服务延迟比较长

### ISSUE THREAD

**Issue by imxig** [apache/incubator-dubbo#2039]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/wiki/FAQ) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.5.3
* Operating System version: xxx
* Java version: 1.7

Dubbo admin同步zookeeper服务延迟比较长，请问这是什么原因？？？困扰了好久

**Comment by kimmking** [comment]
Update dubbo to latest version and retry.
@imxig

**Comment by chickenlj** [comment]
Please update both dubbo-admin and Dubbo to the latest version first.
