### ISSUE TITLE
对于复杂enum作为参数的情况，dubbo是默认不支持的吗

### ISSUE THREAD

**Issue by AllenBlock** [apache/incubator-dubbo#2040]
com.alibaba.dubbo.common.json.GenericJSONConverter.writeValue(Object, JSONWriter, boolean);
对于如下的enum：
public enum AAAEnum {
	A {
		@Override
		public void doSomething() {}
	},
	B {
		@Override
		public void doSomething() {}
	};
	public abstract void doSomething();
}
// 类似这种比较复杂一点点的enum里的对象，举个例子TimeUnit.DAY

Class<?> c = obj.getClass();// obj.getDeclareClass() 可以正确判断
c.isEnum();// 只会为false

这时候会导致如下异常：
java.lang.IllegalArgumentException: java.lang.IllegalAccessError: sun/misc/Launcher$ExtClassLoader
        at sun.misc.Launcher$ExtClassLoader$sw11.getPropertyValue(Launcher$ExtClassLoader$sw11.java) ~[?:1.8.0_77]

**Comment by luyuanwan** [comment]
Talking is cheap,show me your code please! @kimmking

**Comment by kimmking** [comment]
@luyuanwan I think you can reproduce and fix it, I will give you some guides for it. Are you want to try?

**Comment by kimmking** [comment]
@AllenBlock Can you show a testcase?

**Comment by chutian52** [comment]
我觉得你这个问题，问的不应该是dubbo的问题，应该问你序列化的问题。

**Comment by web1992** [comment]
To resolve this problem, I think need more test code show what happend.

**Comment by chickenlj** [comment]
@AllenBlock Please forget about the embedded `json` serialization, it has been deprecated and turned out to have some bugs.

recommend use the other serializations, fastjson, hessian, kryo, etc.

**Comment by chickenlj** [comment]
Reopen if necessary.
