### ISSUE TITLE
dubbo:annotation标签在消费者端无法实例化Controller

### ISSUE THREAD

**Issue by SkyDriveCN** [apache/incubator-dubbo#2044]
您好，我使用dubbo2.6.2版本时在服务端使用**dubbo:annotation**标签能够正常将服务注册到zookeeper。
但是在消费端使用**dubbo:annotation**标签扫描controller类所在包时，访问该controller中的方法一直404，改成使用dubbo:reference标签引用服务就可以了。请问这个问题是由什么原因造成的？
**这是服务端的配置：**
![1](https://user-images.githubusercontent.com/23717846/42412599-e38fc7c6-8241-11e8-8d43-53b827b31184.png)
![image](https://user-images.githubusercontent.com/23717846/42412607-0a7d7aae-8242-11e8-9f51-5794ac6d9788.png)
![image](https://user-images.githubusercontent.com/23717846/42412610-23f7d5a6-8242-11e8-84b9-05c87cf7f513.png)
**这是消费端的配置：**
![image](https://user-images.githubusercontent.com/23717846/42412665-31114186-8243-11e8-928c-31cc3f7f3684.png)
![image](https://user-images.githubusercontent.com/23717846/42412673-5d07fc44-8243-11e8-9149-3d92f10408a3.png)
![image](https://user-images.githubusercontent.com/23717846/42412678-836dcd8c-8243-11e8-9284-257005feb092.png)
**这是访问结果：**
![image](https://user-images.githubusercontent.com/23717846/42412696-d849a326-8243-11e8-976a-382e5e999b7b.png)

**这是消费端启动时的SpringMVC日志：**
`信息: Initializing Spring FrameworkServlet 'dispatcherServlet'
[INFO] Refreshing WebApplicationContext for namespace 'dispatcherServlet-servlet': startup date [Sun Jul 08 00:10:28 CST 2018]; root of context hierarchy
[INFO] Loading XML bean definitions from class path resource [spring-servlet.xml]
00:10:28,752  INFO LoggerFactory:? - using logger: com.alibaba.dubbo.common.logger.log4j.Log4jLoggerAdapter
00:10:28,868  INFO ServiceAnnotationBeanPostProcessor:190 -  [DUBBO] BeanNameGenerator bean can't be found in BeanFactory with name [org.springframework.context.annotation.internalConfigurationBeanNameGenerator], dubbo version: 2.6.2, current host: 192.168.110.2
00:10:28,869  INFO ServiceAnnotationBeanPostProcessor:192 -  [DUBBO] BeanNameGenerator will be a instance of org.springframework.context.annotation.AnnotationBeanNameGenerator , it maybe a potential problem on bean name generation., dubbo version: 2.6.2, current host: 192.168.110.2
00:10:28,898  WARN ServiceAnnotationBeanPostProcessor:155 -  [DUBBO] No Spring Bean annotating Dubbo's @Service was found under package[com.pinyougou.controller], dubbo version: 2.6.2, current host: 192.168.110.2
[INFO] JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
[INFO] Looking for @ControllerAdvice: WebApplicationContext for namespace 'dispatcherServlet-servlet': startup date [Sun Jul 08 00:10:28 CST 2018]; root of context hierarchy
[INFO] Looking for @ControllerAdvice: WebApplicationContext for namespace 'dispatcherServlet-servlet': startup date [Sun Jul 08 00:10:28 CST 2018]; root of context hierarchy
[INFO] Mapped URL path [/**] onto handler 'org.springframework.web.servlet.resource.DefaultServletHttpRequestHandler#0'
[INFO] FrameworkServlet 'dispatcherServlet': initialization completed in 996 ms`

**Comment by chutian52** [comment]
你的reference标注的，貌似不是dubbo的reference吧？dubbo的reference依赖注入是在你的controller初始化的时候自动使用`org.springframework.beans.factory.config.InstantiationAwareBeanPostProcessor`在bean实例化的时候注入的。有兴趣可以看下源码。你的`@Reference`注解是`jdk.narshron.internal.ir.annotation.Reference`, dubbo表示自己手太短，够不到阿！

**Comment by SkyDriveCN** [comment]
您好，之前试了很多遍，最后截图的时候@Reference注解应该导错包了，不过我刚刚再试了一次还是不行。
我现在使用**dubbo:reference**标签可以做到引用该服务进行调用：
![image](https://user-images.githubusercontent.com/23717846/42427445-1abed2b2-8361-11e8-9015-0be5f8746c86.png)
![image](https://user-images.githubusercontent.com/23717846/42427465-2c57e676-8361-11e8-842d-1a2206427779.png)
但是使用**dubbo:annotation**标签扫描注解时却无法做到，如果我用的是**dubbox2.8.4**版本是能成功的：
![image](https://user-images.githubusercontent.com/23717846/42427522-83933db4-8361-11e8-80c1-23dd08992d02.png)
![image](https://user-images.githubusercontent.com/23717846/42427552-a5fd098e-8361-11e8-95d8-06f173f0d962.png)

**Comment by chutian52** [comment]
404表示DispatcherServlet找不到HandlerMethod，其实跟dubbo本身没有关系。我觉得你应该先确定下没有dubbo的情况下请求路径是否可以被访问。

**Comment by SkyDriveCN** [comment]
去除掉dubbo是能够访问到的，我刚才测试了下，发现当使用@Refrence注解和dubbo:annotation标签扫描时，Controller类的构造方法没有被执行即该Controller没有被实例化，而当我使用dubbo:refrence标签和context:component-scan组件扫描时这个Controller是能够被实例化并可以正常访问的。难道dubbo:annotation标签不支持扫描@RestController和@Controller?好像dubbox是支持的，dubbo不是已经合并了dubbox的代码吗？

**Comment by chutian52** [comment]
xml形式的没有研究过，对于dubbo spring boot 而言，是可以的。爱莫能助

**Comment by zonghaishang** [comment]
@SkyDriveCN 
Please provide a demo project to github.

**Comment by SkyDriveCN** [comment]
@zonghaishang 这是我在GitHub上提供的Demo项目，网址是https://github.com/SkyDriveCN/pinyougou-parent，Demo项目当中用到了ZooKeeper集群作为注册中心，你可以根据情况修改下

**Comment by jackHelix** [comment]
你好这个问题你解决了吗

**Comment by jackHelix** [comment]
@SkyDriveCN 你好，我也遇到同样的一个问题，目前还没解决，请问你解决没，还请指教

**Comment by SkyDriveCN** [comment]
@jackHelix 你好，这个问题暂时没有解决。如果使用的是当当的dubbox就没有这个问题，如果是用的dubbo就会存在这个问题。目前只能从dubbo:reference标签引入服务与使用dubbox两种方案中进行取舍。

**Comment by jackHelix** [comment]
@SkyDriveCN  好的，多谢大佬，那只好二者取其一了

**Comment by beiwei30** [comment]
> 去除掉dubbo是能够访问到的，我刚才测试了下，发现当使用@Refrence注解和dubbo:annotation标签扫描时，Controller类的构造方法没有被执行即该Controller没有被实例化，而当我使用dubbo:refrence标签和context:component-scan组件扫描时这个Controller是能够被实例化并可以正常访问的。难道dubbo:annotation标签不支持扫描@RestController和@controller?好像dubbox是支持的，dubbo不是已经合并了dubbox的代码吗？

`<dubbo:annotation>` 仅仅负责扫描 dubbo 自己相关的类，也就是有 @Reference 和 @Service 注解的类。其他的 spring 的类是不会扫描的。你的工程使用的是 spring 的 rest，需要结合 `<context:component-scan>` 来触发 spring 自己的扫描。

当当的 dubbox 中 REST 相关的注解之所以可以工作，是因为 dubbo 框架集成了 resteasy，由 resteasy 负责扫描的 JAX-RS 的标准注解。
