### ISSUE TITLE
采用dubbo的@Reference注解如何使用方法级别配置

### ISSUE THREAD

**Issue by brucelwl** [apache/incubator-dubbo#2045]
例如:如果是xml配置可以这样使用,
<dubbo:reference interface="com.xxx.XxxService">
    <dubbo:method name="findXxx" timeout="3000" retries="2" />
</dubbo:reference>
但是如果是 
@Reference
private com.xxx.XxxService xxxService;
如何针对XxxService类中的findXxx 方法配置进行设置

**Comment by kimmking** [comment]
Add reference annotation to methods directly

**Comment by chutian52** [comment]
目前情况下好像是不可以的，你可以尝试下在parameters这个参数中设置下看看。

**Comment by zhengjieyuan** [comment]
同问 关注下

**Comment by dslchd** [comment]
目前好像不能，我之前一直想在provider方的@Service注解，配置方法级别的服务provider配置，没有这些选项，只能用xml配置。但是既然用了注解，就肯定不再单独用xml配置了。

**Comment by kute** [comment]
看看这个 https://my.oschina.net/roccn/blog/871032

**Comment by chickenlj** [comment]
@cvictory please apply this change https://github.com/apache/incubator-dubbo/pull/2603to the master branch.

**Comment by cvictory** [comment]
https://github.com/cvictory/incubator-dubbo/tree/issue_2045

**Comment by cvictory** [comment]
I still need to do some test .
