### ISSUE TITLE
anonymous inner class doesn't work in callback.

### ISSUE THREAD

**Issue by L-Angel** [apache/incubator-dubbo#2054]
* Dubbo version: 2.5.10
* Operating System version: Win 10
* Java version: 1.8

下面这种写法 会报没有实现Serializable接口

/*cDubboDemoService.helloWorldAsyncCallback(req, new AsncCallbackListener<HelloWorldResponseType>() {
     @Override
     public void onComplete(HelloWorldResponseType response) {
         System.out.println("Async Callback : \n");
         System.out.println(response.getRetMsg());
         System.out.println("Client DateTime : " + new Date());
     }
 });*/

**Comment by chickenlj** [comment]
Could you please describe in more detail, for example, stack trace and your configuration?

**Comment by chickenlj** [comment]
And do you get this problem when using this feature? http://dubbo.apache.org/#/docs/user/demos/callback-parameter.md?lang=en-us

**Comment by L-Angel** [comment]
Yes.is this feature.And some information as bellow is the part of trace.
```
cause: Serialized class com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler must implement java.io.Serializable\n Java field: private java.lang.reflect.InvocationHandler com.alibaba.dubbo.common.bytecode.proxy0.handler\n
```

**Comment by chickenlj** [comment]
Do you add this part ? `<dubbo:argument index="1" callback="true" />`

**Comment by L-Angel** [comment]
yes,this config is already add to provider.xml that in server.

**Comment by beiwei30** [comment]
would you mind to take a look at https://github.com/dubbo/dubbo-samples/blob/master/dubbo-samples-callback/src/main/java/com/alibaba/dubbo/samples/callback/CallbackConsumer.java#L35 which is exact a anonymous inner class implementation?

**Comment by L-Angel** [comment]
but this demo inner class is in static method not in a object.

**Comment by beiwei30** [comment]
@L-Angel I don't see the difference. I move all logic in `main` into another class say `CallbackClient`:

```java
package com.alibaba.dubbo.samples.callback;

import com.alibaba.dubbo.samples.callback.api.CallbackListener;
import com.alibaba.dubbo.samples.callback.api.CallbackService;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class CallbackClient {
    public void execute() {
        ClassPathXmlApplicationContext context = new ClassPathXmlApplicationContext(new String[]{"spring/callback-consumer.xml"});
        context.start();
        CallbackService callbackService = (CallbackService) context.getBean("callbackService");
        callbackService.addListener("foo.bar", new CallbackListener() {
            public void changed(String msg) {
                System.out.println("callback1:" + msg);
            }
        });
    }
}
```

and change `CallbackConsumer` to:

```java
package com.alibaba.dubbo.samples.callback;

/**
 * CallbackConsumer
 */
public class CallbackConsumer {

    public static void main(String[] args) throws Exception {
        new CallbackClient().execute();
        System.in.read();
    }

}
```

it still works.

**Comment by L-Angel** [comment]
@beiwei30 i push a demo project.the reps address is [https://github.com/L-Angel/dubbodemo](https://github.com/L-Angel/dubbodemo).
And this the reponse body is as bellow
```
{
    "timestamp": 1531381852287,
    "status": 500,
    "error": "Internal Server Error",
    "exception": "com.alibaba.dubbo.rpc.RpcException",
    "message": "Failed to invoke remote method: hello, provider: dubbo://127.0.0.1:20882/com.langel.dubbo.api.DubboDemoService?application=DubboDemoClient&dubbo=2.5.1&hello.async=true&interface=com.langel.dubbo.api.DubboDemoService&methods=hello&pid=109608&protocol=dubbo&side=consumer&timeout=100000&timestamp=1531381847703, cause: Failed to send message Request [id=0, version=2.0.0, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=hello, parameterTypes=[class com.langel.dubbo.api.HelloWorldRequest, interface com.langel.dubbo.api.AsyncCallBack], arguments=[com.langel.dubbo.api.HelloWorldRequest@53f016e7, com.langel.dubbo.client.DemoController$1@52c34b27], attachments={async=true, path=com.langel.dubbo.api.DubboDemoService, id=0, interface=com.langel.dubbo.api.DubboDemoService, version=0.0.0, timeout=100000}]] to /10.0.75.1:20882, cause: Serialized class com.langel.dubbo.client.DemoController$1 must implement java.io.Serializable",
    "path": "/hello"
}
```

**Comment by diecui1202** [comment]
@L-Angel 

I think there has two steps to use callback invoke mechanism:
1. register the callback, then provider side hold this callback service
2. the provider trigger invoking callback service with suitable time

Check this sample: https://github.com/dubbo/dubbo-samples/tree/master/dubbo-samples-callback

**Comment by L-Angel** [comment]
I think the reason of this error is that the inner class defined in a class ,when we serialize this inner class must to serialize its parent class. In other words,In this demo the class demoController must to be serialized when the class DemoController$0.this$1 is serialized , and the DemoController is not implement 
Serialiable interface.So we cant use func class.isAssignableFrom to judge that inner class implenment Serialiable.  
we can modify this part
```
protected Serializer getDefaultSerializer(Class cl)
  {
    if (_defaultSerializer != null)
      return _defaultSerializer;

    if (! Serializable.class.isAssignableFrom(cl)
	&& ! _isAllowNonSerializable) {
      throw new IllegalStateException("Serialized class " + cl.getName() + " must implement java.io.Serializable");
    }

    return new JavaSerializer(cl, _loader);
  }
```

**Comment by L-Angel** [comment]
If the consumer only have a instance.
consider one case like that there are saveral request at the same time to request provider.
the provider invoking callback service,
then i how to make a mapping with the callback result and request context.

**Comment by diecui1202** [comment]
Maybe the callback is not suitable for this scenario. When the callback result returns, the corresponding request has been released. Because the provider invokes the callback is not immediately, such as waiting for some condition occurs.

**Comment by diecui1202** [comment]
@L-Angel We'll close this issue. Feel free to reopen it
