### ISSUE TITLE
Dubbo是否可以增加内部事件

### ISSUE THREAD

**Issue by zhoujw8792** [apache/incubator-dubbo#2056]
比如dubbo开始启动、停止、发布服务完成等事件

**Comment by diecui1202** [comment]
@zhoujw8792 Dubbo 3.0 will provide these features, you can visit https://lists.apache.org/thread.html/2adaf2156c27a32330b7f0844e4b4c27ff03aa0a1669cc51d325cb4d@%3Cdev.dubbo.apache.org%3E for more information about Dubbo 3.0

Please stay tuned. Thanks.
