### ISSUE TITLE
NPE when use callback and injvm together

### ISSUE THREAD

**Issue by L-Angel** [apache/incubator-dubbo#2062]
原因：
本地调用不会拿注册中心URL，会使用referenceConfig里面生成的URL，这个URL里面没有CallBack参数信息即INV_ATT_CALLBACK_KEY这个参数的信息

**Comment by diecui1202** [comment]
@L-Angel I'll appreciate that you could provide a demo : )

**Comment by beiwei30** [comment]
@L-Angel I tried to reproduce but failed, would you mind to provide a reproducer in your GitHub repo?

**Comment by L-Angel** [comment]
@diecui1202 @beiwei30  i push a demo project  that remove internal information to github on weekends.

**Comment by beiwei30** [comment]
sure, waiting for your reproducer. @L-Angel pls. make it as simple as possible.

**Comment by L-Angel** [comment]
@beiwei30 [https://github.com/L-Angel/dubbodemo](https://github.com/L-Angel/dubbodemo)
use callback-npe branch

**Comment by beiwei30** [comment]
great, I will take a look.

**Comment by diecui1202** [comment]
The same issue? https://github.com/apache/incubator-dubbo/issues/2054

**Comment by diecui1202** [comment]
@L-Angel Feel free to reopen it if also have problem.
