### ISSUE TITLE
@Service(register=false)  is not work

### ISSUE THREAD

**Issue by xfbxag** [apache/incubator-dubbo#2063]
- [*] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [*] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/wiki/FAQ) of this repository and believe that this is not a duplicate.

* Dubbo version: 2.6.2
* Operating System version: CentOS 7
* Java version: 1.8

@Service(interfaceClass = DubboSwaggerService.class, protocol = "rest", register = false)
register is not work

@Documented
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE})
@Inherited
public @interface Service {

    Class<?> interfaceClass() default void.class;

    String interfaceName() default "";

    String version() default "";

    String group() default "";

    String path() default "";

    boolean export() default false;

    String token() default "";

    boolean deprecated() default false;

    boolean dynamic() default false;

    String accesslog() default "";

    int executes() default 0;

    boolean register() default false;        // this default value should be true

**Comment by ralf0131** [comment]
Hi, this is fixed in the master branch, I think it should be back ported to 2.6.x branch. @beiwei30

**Comment by cvictory** [comment]
@nzomkxia  please commit a pr , then we will merge to master.
