### ISSUE TITLE
dubbo注册zk乱码

### ISSUE THREAD

**Issue by simon518** [apache/incubator-dubbo#2065]
异常：
zk节点： /dubbo/  下面一堆
%25252525252525252525252525，
%25252525252525252525252525，
com.***.**provider     

正常：
    /dubbo/
com.***.***provider...

把zk /dubbo节点写了32m的数据，导致连不上zk

**Comment by beiwei30** [comment]
pls. provide a reproducer.

**Comment by beiwei30** [comment]
looks like lots of `%` is written into zookeeper, not sure what happens.

**Comment by wangchangbing** [comment]
% encodig导致的  @simon518  你给下你的注册上去的原始值看看，去掉特殊符号应该就成

**Comment by niejian** [comment]
怎么解决的，求解.....
