### ISSUE TITLE
2.5.3版本reference注解调用抛空指针异常

### ISSUE THREAD

**Issue by wallacepang** [apache/incubator-dubbo#2067]
环境：2.5.3
异常：
A服务通过reference注解引用B，A启动的时候B服务宕机，后面重启B服务
A服务调用B的时候抛NullPointException 
正常：
后面重启A服务，调用B服务才正常

**Comment by luyuanwan** [comment]
You can give the stack trace.

**Comment by diecui1202** [comment]
@wallacepang could you please try out the lastest version 2.6.2?

Feel free to reopen it if you also get problem.

**Comment by wallacepang** [comment]
2.6.2 也是这个问题，@Reference 默认 check=true,  把check改成false ,服务B能正常调用

**Comment by wallacepang** [comment]
@diecui1202  2.6.2 也是这个问题，@reference 默认 check=true, 把check改成false ,服务B能正常调用

**Comment by diecui1202** [comment]
@wallacepang can you provide the stack trace?

**Comment by ATAKing1023** [comment]
I opened a pull request for this issue. [https://github.com/apache/incubator-dubbo/pull/1999](url)
@ralf0131 can you please review the change? It's a minor fix.

**Comment by ATAKing1023** [comment]
Here is another reported issue with stacktrace. #1765 
@diecui1202

**Comment by zonghaishang** [comment]
merged, see: https://github.com/apache/incubator-dubbo/pull/1999
