### ISSUE TITLE
Is Alibaba Cloud EDAS compatibile for dubbo?

### ISSUE THREAD

**Issue by 34176470** [apache/incubator-dubbo#2075]
阿里云EDAS完全兼容dubbo吗？
EDAS环境是不是不支持dubbo自扩展Filter、ExtensionFactory？

**Comment by for5million** [comment]
是的，目前EDAS暂时不支持此类特性，能支持80%左右的特性。

**Comment by kimmking** [comment]
see here:
https://www.aliyun.com/product/edas?spm=5176.8142029.388261.335.e9396d3esa0ozo

**Comment by diecui1202** [comment]
The EDAS on Alibaba Cloud is compatible with Dubbo for the two features you mentioned. You can refer EDAS documentation for more information.

**Comment by 34176470** [comment]
自己根据dubbo的filter扩展方式，自己扩展了一个filter

在本机spring boot方式启动时，可以正常进入filter，并执行后续逻辑

在测试环境docker方式启动时，也可以正常进入filter，并执行后续逻辑

但在UAT环境，使用阿里云EDAS环境时，始终进入不了自己扩展的filter

请问这与EDAS环境有关吗？如何解决？

下面是代码：

@Activate(group = {Constants.PROVIDER, Constants.CONSUMER}, value = "tracing")
public final class TracingFilter implements Filter {

    private static Logger logger = LoggerFactory.getLogger(TracingFilter.class);

    Tracer tracer;
    TraceContext.Extractor<Map<String, String>> extractor;
    TraceContext.Injector<Map<String, String>> injector;

    public void setTracing(Tracing tracing) {
        tracer = tracing.tracer();
        extractor = tracing.propagation().extractor(GETTER);
        injector = tracing.propagation().injector(SETTER);
    }

    @Override
    public Result invoke(Invoker<?> invoker, Invocation invocation) throws RpcException {
        logger.info("Dubbo Parameters ==>> " + invoker.getUrl().getParameters());
        logger.info("Interface ==>> " + buildSpanName(invoker, invocation));

        if (tracer == null) {
            logger.info("Tracer is null.");
            return invoker.invoke(invocation);
        }

        //do something...
}

![image](https://user-images.githubusercontent.com/2172570/42685513-b86a2e0a-86c5-11e8-8d81-7be5e7446172.png)

**Comment by chickenlj** [comment]
Can you give a complete runnable package, for example, your own Github repository? So that we can help to reproduce the problem.

**Comment by 34176470** [comment]
https://github.com/34176470/springboot-dubbo-zipkin-brave.git

**Comment by ralf0131** [comment]
@34176470 Please don't mix up the issues, please file a new issue for your problem.

I am going to close this issue.
