### ISSUE TITLE
dubbo返回值不能序列化

### ISSUE THREAD

**Issue by moayi** [apache/incubator-dubbo#2083]
在使用dubbo时，如果返回值是public  GridFSDBFile findFileById(String id);
例如此类的接口，返回值要怎么处理？

**Comment by lovepoem** [comment]
What is wrong with your code? 
Please paste some exception stack info

**Comment by moayi** [comment]
因为这个返回值是一个二进制文件，没有序列化导致的，我现在不方便截图，有时间给您截图，谢谢

**Comment by moayi** [comment]
因为这个返回值是一个二进制文件，没有序列化导致的，我现在不方便截图，有时间给您截图，谢谢

**Comment by kimmking** [comment]
You can't serialize objects those reference external resources such as InputStream, Graphic, Connection...

**Comment by moayi** [comment]
那针对这种问题有什么好的解决办法呢？

**Comment by kimmking** [comment]
My suggestion is that you should implement a POJO to contains all data you need as the return value type of exported services.

**Comment by chickenlj** [comment]
Currently, Dubbo does not support the transmission of big files,  you can use [hessian protocol instead](http://dubbo.apache.org/#!/docs/user/references/protocol/hessian.md?lang=zh-cn). Hessian allows you can define an interface looks like this:
```java
public File findFileById(String id);
public InputStream findFileById(String id);
```
