### ISSUE TITLE
dubbo注解service与spring注解service同时在一个类上使用, 无法暴露服务

### ISSUE THREAD

**Issue by hsl727261250** [apache/incubator-dubbo#2093]
dubbo: 2.6.6
spring: 4.3.2

背景:
spring+dubbo项目, spring使用xml配置, 配置文件中打开dubbo注解扫描. dubbo使用注解配置. 整个项目没有使用事务, 没有使用Transactional注解.

症状:
1. 在一个类上同时使用dubbo的service注解和spring的service(或component)注解, 无法暴露dubbo服务.
2. 如果在其他类中使用Autowried注入该类当做spring服务使用, 则dubbo服务也可正常暴露.
3. 使用delay=-1配置, 依然无法暴露.

**Comment by kimmking** [comment]
can you provide a test case to reproduce it?

**Comment by tswstarplanet** [comment]
It seems that you don't need to use @Service or @Component of spring if you use @Service of dubbo

**Comment by hsl727261250** [comment]
经过调试发现是lazy-init的原因.
我的项目指定了全局lazy-init=true, 所以一般情况下spring管理的类都会延迟加载.
当我单独使用dubbo的service注解时, 该类不由spring管理, 启动时正常加载正常暴露服务.
当同时使用两个注解时, spring启动时会延迟加载该类, 所以无法暴露服务.
当同时使用两个注解, 并在其他类中Autowired该类时, 不满足延迟加载条件, 启动时正常加载正常暴露服务.

为什么会同时使用dubbo和spring的service注解? 因为这个服务内部外部都要使用.

**Comment by kimmking** [comment]
It seems  @service of dubbo should register bean to spring context to avoid this case.

**Comment by kimmking** [comment]
It seems  @service of dubbo should register bean to spring context to avoid this case.

**Comment by mercyblitz** [comment]
Please use latest dubbo release, this issue has been fixed.
