### ISSUE TITLE
provider start qos-server can not bind localhost:22222

### ISSUE THREAD

**Issue by MicroCountry** [apache/incubator-dubbo#2100]
### Environment

* Dubbo version:  2.6.2
* Operating System version: centos
* Java version: 1.8
* config : 
 
dubbo.application.id=service-shop
dubbo.application.name=service-shop
 
dubbo.protocol.id=zookeeper
dubbo.protocol.name=dubbo
dubbo.protocol.port=12000
dubbo.protocol.status=server
 
dubbo.registry.id=jhmf
dubbo.registry.address=172.16.137.230:2181
dubbo.registry.protocol=zookeeper
dubbo.registry.timeout=30000
dubbo.protocol.threads=200
dubbo.consumer.check=false

when start provider service maybe thorw BindException: Address already in use,like this

![image](https://user-images.githubusercontent.com/16758768/42870823-6e5d5aa0-8aab-11e8-8a33-bae120b2af3d.png)

but I don't have this port number in my project, and this service can run normal

**Comment by tswstarplanet** [comment]
You can change the port to another number to see if it works so that you know if it is a bug.

**Comment by blackdancers** [comment]
![image](https://user-images.githubusercontent.com/4956686/42924132-6220eca6-8b5b-11e8-8f4e-22f6ffb23fac.png)

**Comment by zonghaishang** [comment]
@MicroCountry
The local port should be occupied by other processes, try the solution provided by ralf0131
