### ISSUE TITLE
Dubbo有什么因素会导致客户端调用服务超时

### ISSUE THREAD

**Issue by xtylxx** [apache/incubator-dubbo#2102]
线上环境稳定运行近1年，突然出现dubbo客户端调用服务超时情况，dubbo服务端启动正常，且dubboadmin看提供者也是正常的，服务端没有任何异常信息。这个服务只是一个基于zookeeper的主键生成服务，zookeeper是正常的，且基于zookeeper的solr集群也没有任何异常。想请问下，除了服务端不可用，还有什么因素会出现这个情况吗？

**Comment by luyuanwan** [comment]
我以前遇到过一个项目，运行近1年半，很久没有人维护，导致表数据越来越多（单表1000万，开发时没有考虑到后期缺少维护这个点，所以在设计时是按照单体引用来设计的），虽然系统能稳定运行1年半，但是之后会发生因SQL执行时间变长导致dubbo调用超时。

**Comment by xtylxx** [comment]
我这个dubbo服务只是一个基于zookeeper的分布式主键服务，没有数据库。重启后就正常了，万能的重启~~

**Comment by zonghaishang** [comment]
Please provide the error stack
1. Possible network jitter
2. Provider time consuming
3. server full gc (stop the world)
4. Timeout parameter configuration is incorrect
and so on..

Reopen whenever is necesary
