### ISSUE TITLE
Lack of ip and application name subscripting MonitorService

### ISSUE THREAD

**Issue by jasonjoo2010** [apache/incubator-dubbo#2110]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: ALL
* Operating System version: nop
* Java version: nop

### Step to reproduce this issue

1. enable monitor
2. open admin console
3. consumer links in MonitorService will be wrong - lack of consumers's application name and ip address.

### Expected Result

They should not be empty.

### Actual Result

lack of them.

```
consumer:///com.alibaba.dubbo.monitor.MonitorService?category=consumers&check=false&dubbo=2.0.1&interface=com.alibaba.dubbo.monitor.MonitorService&pid=2867×tamp=1532173971611
```

**Comment by zonghaishang** [comment]
fixed, it will be closed
