### ISSUE TITLE
如何自定义serviceName、methodName？

### ISSUE THREAD

**Issue by wenweihu86** [apache/incubator-dubbo#2112]
最近在扩展dubbo来支持brpc协议，遇到serviceName和methodName无法自定义问题。
我能想到的是，在接口方法上加注解，但是dubbo貌似没提供设置这两个字段？

**Comment by tswstarplanet** [comment]
这个好像目前不行，因为dubbo要靠这两个属性去路由，否则怎么知道调哪个接口哪个方法？

**Comment by beiwei30** [comment]
@wenweihu86, would you mind explain a little bit more why these two fields are needed to customize?

**Comment by wenweihu86** [comment]
@beiwei30 brpc中namespace和method的命名规则和java都不一样，比如c++中namespace不会命名成java的包名，methodName一般是首字母大写的。所以对于brpc提供的服务，java client需要做自定义serviceName和methodName。

**Comment by notlate** [comment]
你这里所说的自定义，其实generic泛型服务可以做到自定义servicename，提供者跟sericename、methodname完全解耦，自定义实现，具体可以查看generic的使用例子。@wenweihu86
