### ISSUE TITLE
It is time to add registry to nacos?

### ISSUE THREAD

**Issue by tswstarplanet** [apache/incubator-dubbo#2115]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

Now nacos is open sourced. I think it is time to develop registry to nacos

**Comment by diecui1202** [comment]
You're right. We are communicating with Nacos team for this task. Stay tuned pls.

**Comment by tswstarplanet** [comment]
@diecui1202 I'm trying to finish the task, but I find it not so easy.

**Comment by diecui1202** [comment]
We are going to close this issue. Feel free to reopen it if necessary.

&READY-TO-CLOSE&

**Comment by snifferhu** [comment]
yeah.I want join it. it's powerful feature.
