### ISSUE TITLE
I hava write a Intellij dubbo plugin, can i put it to the readme  ecosystem part

### ISSUE THREAD

**Issue by gejun123456** [apache/incubator-dubbo#2120]
here is the source code of the intellij dubbo plugin  https://github.com/gejun123456/IntellijDubboPlugin

**Comment by playaround88** [comment]
hi, welcome!
You can follow the dubbo extension guilde[1] below to notify the community.
and your plugin maybe add to the awaresome of dubbo group.

[1] https://github.com/apache/incubator-dubbo/wiki/Dubbo-extension-guide

&READY-TO-CLOSE&

**Comment by ralf0131** [comment]
As suggested by @playaround88 , please follow the guide above to transfer the repository to Dubbo ecosystem. After that you can send a pull request to update the readme.
