### ISSUE TITLE
NullPointExexception  in RpcContextFilter

### ISSUE THREAD

**Issue by gaboolic** [apache/incubator-dubbo#2127]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.1 - newest

### Step to reproduce this issue

1.  
String value = null;
RpcContext.getContext().getAttachments().put("demokey", value)
2. 
then invoke one method will NullPointException

**The Exception reason:
In RpcContextFilter.java，public void filter(ClientRequestContext requestContext) throws IOException
for (Map.Entry<String, String> entry : RpcContext.getContext().getAttachments().entrySet()) {
            if (entry.getValue().contains(",") || entry.getValue().contains("=")

the entry.getValue not judge null!!**

**Comment by gaboolic** [comment]
I hope com.alibaba.dubbo.rpc.protocol.rest.RpcContextFilter can judge entry.getValue()  null

**Comment by carryxyh** [comment]
This is not a normal case that use put attachments.
I think there are only one case to use put(key,null) is to remove a key or value.
In this case, u can use remove to do the same thing.

**Comment by carryxyh** [comment]
&READY-TO-CLOSE&

**Comment by gaboolic** [comment]
String value = getStringFromXXX();
RpcContext.getContext().getAttachments().put("demokey", value)
这种场景做数据透传的时候会用。我并不需要校验value是否为空，我仅仅是从某个地方去获取几个字符串然后放到上下文里面透传到下一个服务。
然鹅这样会报错，而且报的错是服务提供方有空指针，实际上这个异常是dubbo自己的filter抛出的，但是被catch了。那个filter的作用仅仅是校验一下value是否有逗号和等于号，然后throw一个异常。如果Nul也不是预期的值，至少也该和逗号等于号一样，抛出一个异常来有一个友好提示吧？

**Comment by gaboolic** [comment]
另外只有rest协议 会有这个RpcContextFilter。其他的协议似乎我可以想往RpcContext.getContext().getAttachments()里放什么就放什么吧，应该是可以放null的；就算我用rest协议，null   逗号 等于号 为什么不让我放呢，不能因为dubbo自己内部实现是用逗号和等于号就不让我用吧，其实完全可以做个转码啊。

**Comment by gaboolic** [comment]
@carryxyh

**Comment by carryxyh** [comment]
First case : 

```
String value = getStringFromXXX();
RpcContext.getContext().getAttachments().put("demokey", value)
```

Why do u didn't check the value is null ? 
In this way it is obviously more rigorous: 

```
String value = getStringFromXXX();
if (value != null ){
      RpcContext.getContext().getAttachments().put("demokey", value)
}
```

Second case : 
I haven't said that "u can not put null into attachment".
Can u just tell us, in which case u want to put a null into attachment?
If just the case that u don't check the value u put in, I don't think this is a bug which should be fixed.

**Comment by eMorphling** [comment]
@carryxyh One common case I image is that, in a hashmap, can not get a key and a key's value is null is different in some special business case. 
有一些特殊的case是在一个map里面，拿不到一个key和这个key的值是null应该是不一样的意义。

**Comment by gaboolic** [comment]
first case:
 目前的解决方案就是预先做了null检查，因为看了最新的dubbo实现，那个filter还是那个样子
second case:
 因为一些值我只是透传到下一个应用，我并不关心里面的内容，为什么要做null校验？但那个filter的目的仅仅是为了校验逗号和等于号而抛了空指针，我不认为这不是bug
就算校验逗号和等于号，在之前也应该先校验一下Null，如果不允许为null，也请抛一个异常出来，而不是空指针被另外的一个地方catch，导致我debug很久才找到原因

**Comment by gaboolic** [comment]
@eMorphling 说的也是对的，在一些场景里面，能取到一个Key，value是null 和压根没有这个key意义是不一样的

**Comment by carryxyh** [comment]
@gaboolic 
In some case, we should get a null value like @eMorphling  said.
Ok, I know, thank you very much for your issue.
I will fix this problem as soon as possible.
:)

**Comment by gaboolic** [comment]
不过rest协议 应该也可以支持往Attachments里面放,= 啊，只要做一个编解码就可以了。不过这又是另一个issue的故事了……
