### ISSUE TITLE
should use dubbo.qos.port instead of dubbo.application.qos.port about set qos port?

### ISSUE THREAD

**Issue by chunInsane** [apache/incubator-dubbo#2128]
### Environment
* Dubbo version: 2.5.8
* Java version: 1.8.0_40

### Step to reproduce this issue

使用文档(http://dubbo.apache.org/#!/docs/user/references/qos.md?lang=zh-cn)
介绍dubbo.application.qos.port参数设置qos端口无用，查看源码用的dubbo.qos.port参数进行设置，是文档有问题还是使用姿势不对？

dubbo源码
public interface Constants {

    int DEFAULT_PORT = 22222;
    // 通过-D参数指定port
    String QOS_PORT = "dubbo.qos.port";
    String BR_STR = "\r\n";
    String CLOSE = "close!";

    // 通过-D参数指定当前qos是否能够拒绝外部ip的联入
    String ACCEPT_FOREIGN_IP = "dubbo.qos.accept.foreign.ip";
}

**Comment by jasonjoo2010** [comment]
版本过低，这个改动应该貌似是从2.5.9开始的，2.6.x应该也一致。

**Comment by jasonjoo2010** [comment]
另外目前正处在改package的阶段，建议追一下版本到2.6，无坑版建议先上2.6.2

**Comment by chunInsane** [comment]
已经升级2.5.9了。当时看文档里写的2.5.8，有点尴尬

**Comment by yuxiao97** [comment]
我用的2.6.0发现无法禁用qos-server,源码截图如下
![image](https://user-images.githubusercontent.com/27430795/51370148-10c1e200-1b31-11e9-9564-b21201bb632b.png)
是否启用qos-server,在2.6.0+的版本中可以配置了，配置代码如下:
```
<dubbo:application name="demo-server" >
        <dubbo:parameter key="qos.enable" value="false" />
        <dubbo:parameter key="qos.port" value="33333"/>
        <dubbo:parameter key="qos.accept.foreign.ip" value="*"/>
    </dubbo:application>
```
在服务封装URL时，会把配置参数配置到URL，qos-server启动时会检查配置参数，2.6.1的源码截图如下：
![image](https://user-images.githubusercontent.com/27430795/51370392-e7ee1c80-1b31-11e9-9918-874af0a010dc.png)
