### ISSUE TITLE
consumer端依赖包问题导致报错 No provider available for the service xxxx

### ISSUE THREAD

**Issue by yuqiyi** [apache/incubator-dubbo#213]
我们的provider端和consumer端不在同一个项目,需要各自维护依赖项.
将两边的协议切换为hessian之后,在provider端加载了hessian依赖包,消费端没有加载,但是在整个过程中没有报任何依赖包缺失或者相关的错误,导致查了很长时间,最后想到可能是两边依赖包不对应的问题,消费端加上依赖包之后,问题才解决.
但是现在依然有RMI协议无法调通的问题.

**Comment by Xiaobaxi** [comment]
@yuqiyi 能贴下具体详细的错误日志还有例子吗？没有出现过这个问题，不过rmi内部有漏洞，我们已经不使用了

**Comment by lovepoem** [comment]
What's the mean of "RMI prtoclol" ?
Now the default prtoclol is Dubbo protocol 
I will close it. Feel free to reopen it when you have any queations.
