### ISSUE TITLE
Check if we can switch serialization/deser between IO and Dubbo Threads.

### ISSUE THREAD

**Issue by chickenlj** [apache/incubator-dubbo#2131]
Here's the doc describing Dubbo's ThreadPool Model: http://dubbo.apache.org/#!/docs/user/demos/thread-model.md?lang=zh-cn

Here's the code deciding Serialization thread       
https://github.com/apache/incubator-dubbo/blob/70e1e6220b82fd20611d7ec2624726442671bf95/dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboCodec.java#L88

**Comment by tswstarplanet** [comment]
Excuse me. What is the meaning of "switch serialization/deser between IO and Dubbo Threads"

**Comment by zonghaishang** [comment]
Netty io thread & dubbo thread pool

**Comment by tswstarplanet** [comment]
@zonghaishang So it just means that we should check if the serialization/deser can success ?

**Comment by zonghaishang** [comment]
You are right, but more likely to provide a parameter configuration, the internal decision of the framework

**Comment by tswstarplanet** [comment]
But how do we know if the serialization/deser will succeed?

**Comment by ranchoswang** [comment]
Since I noticed that only in decoding it is able to switch the two different thread models, I am wondering if it is neccessary or useful to make encoding capable of switching as well? Will doing this optimize performances in any cases?

**Comment by ranchoswang** [comment]
In default , decode in io is open , You can use <dubbo:decode.in.io="false"> in xml to close it (when you think deser takes long enough time).

**Comment by sinmaystar** [comment]
we can switch serialization thread like this:
    <dubbo:protocol name="dubbo" port="20880">
        <dubbo:parameter key="decode.in.io" value="false"/>
    </dubbo:protocol>

there is no need to modify source code or add user define xml schema

**Comment by diecui1202** [comment]
@chickenlj IMO, there is nothing we can do from the comments, I'll close it. Any thoughts ?
