### ISSUE TITLE
java.lang.NoClassDefFoundError in com.alibaba:dubbo-rpc-thrift, due to dependency conflict issue

### ISSUE THREAD

**Issue by LeoAugust19** [apache/incubator-dubbo#2134]
### Environment
* Dubbo version: com.alibaba:dubbo-rpc-thrift:jar:2.6.2
* Operating System version: Windows
* Java version: Jdk 1.7

### Descirption
Hi, there are two versions of **org.apache.httpcomponents:httpcore:jar** exist in com.alibaba:dubbo-rpc-thrift, and only **org.apache.httpcomponents:httpcore:jar:4.1.3** can be loaded during packaging process based on "nearest wins strategy". However, **class org.apache.http.util.Args** only included in **org.apache.httpcomponents:httpcore:jar:4.4.6:compile** which is shadowed by Maven. When your project referencing the missing class, java.lang.NoClassDefFoundError will be thrown.

### Dependency tree
com.alibaba:dubbo-rpc-thrift:jar:2.6.2
+- com.alibaba:dubbo-rpc-api:jar:2.6.2:compile
+- org.apache.thrift:libthrift:jar:0.8.0:compile
|  +- org.slf4j:slf4j-api:jar:1.7.25:compile (version managed from 1.5.8)
|  +- commons-lang:commons-lang:jar:2.5:compile
|  +- org.apache.httpcomponents:httpclient:jar:4.5.3:compile (version managed from 4.1.2)
|  |  +- (org.apache.httpcomponents:httpcore:jar:4.4.6:compile - **omitted for conflict with 4.1.3**)
|  |  +- (commons-logging:commons-logging:jar:1.2:compile - version managed from 1.1.1; omitted for duplicate)
|  |  \- commons-codec:commons-codec:jar:1.9:compile
|  \- org.apache.httpcomponents:httpcore:jar:4.1.3:compile

### Test case:
[RandomAccessByteArrayOutputStreamTest.txt](https://github.com/apache/incubator-dubbo/files/2228066/RandomAccessByteArrayOutputStreamTest.txt)

As the automatic test case generation tool can not deal with complex conditions, so before analyzing the source file, we mutated the program to allow-----

OutputStream out = new org.apache.http.impl.conn.LoggingOutputStream(new java.io.FileOutputStream("D:\\test.txt"),new org.apache.http.impl.conn.Wire(null));

in 
 method com.alibaba.dubbo.rpc.protocol.thrift.io.RandomAccessByteArrayOutputStream.writeTo(RandomAccessByteArrayOutputStream.java:93)

which is a reasonable condition. 

Mutated program:
[LoggingOutputStream.txt](https://github.com/apache/incubator-dubbo/files/2228099/LoggingOutputStream.txt)
[RandomAccessByteArrayOutputStream.txt](https://github.com/apache/incubator-dubbo/files/2228100/RandomAccessByteArrayOutputStream.txt)

Then we got the following stack trace.

### Stack trace:
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/util/Args
	at org.apache.http.impl.conn.Wire.output(Wire.java:110)
	at org.apache.http.impl.conn.LoggingOutputStream.write(LoggingOutputStream.java:73)
	at com.alibaba.dubbo.rpc.protocol.thrift.io.RandomAccessByteArrayOutputStream.writeTo(RandomAccessByteArrayOutputStream.java:93)
	at com.alibaba.dubbo.rpc.protocol.thrift.io.RandomAccessByteArrayOutputStreamTest.main(RandomAccessByteArrayOutputStreamTest.java:11)
Caused by: java.lang.ClassNotFoundException: org.apache.http.util.Args
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 4 more

### Suggested solution
I found that you only deal with the dependency conflict issue for httpclient in version mangement file.
Could you please set the version of httpcore to 4.4.6 (dependencyManagement) in pom.xml?

**Comment by kimmking** [comment]
you can submit a PR to exclude the older version.

**Comment by beiwei30** [comment]
@LeoAugust19 

dubbo-rpc-thrift doesn't introduce multiple versions for http-core. I think the only reason you see two versions is because you introduce `org.apache.http.impl.conn.Wire` in `org.apache.dubbo.rpc.protocol.thrift.io.RandomAccessByteArrayOutputStream`, which is only available in http-client 4.5.3.

```sh
[INFO] ------------------------------------------------------------------------
[INFO] Building dubbo-rpc-thrift 2.7.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.10:tree (default-cli) @ dubbo-rpc-thrift ---
[INFO] org.apache.dubbo:dubbo-rpc-thrift:jar:2.7.0-SNAPSHOT
[INFO] +- org.apache.dubbo:dubbo-rpc-api:jar:2.7.0-SNAPSHOT:compile
[INFO] |  +- org.apache.dubbo:dubbo-common:jar:2.7.0-SNAPSHOT:compile
[INFO] |  |  +- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  |  +- log4j:log4j:jar:1.2.16:compile
[INFO] |  |  +- org.javassist:javassist:jar:3.20.0-GA:compile
[INFO] |  |  +- com.alibaba:hessian-lite:jar:3.2.3:compile
[INFO] |  |  +- com.alibaba:fastjson:jar:1.2.46:compile
[INFO] |  |  +- com.esotericsoftware:kryo:jar:4.0.1:compile
[INFO] |  |  |  +- com.esotericsoftware:reflectasm:jar:1.11.3:compile
[INFO] |  |  |  |  \- org.ow2.asm:asm:jar:5.0.4:compile
[INFO] |  |  |  \- com.esotericsoftware:minlog:jar:1.3.0:compile
[INFO] |  |  +- de.javakaffee:kryo-serializers:jar:0.42:compile
[INFO] |  |  \- de.ruedigermoeller:fst:jar:2.48-jdk-6:compile
[INFO] |  |     +- com.fasterxml.jackson.core:jackson-core:jar:2.8.6:compile
[INFO] |  |     \- com.cedarsoftware:java-util:jar:1.9.0:compile
[INFO] |  |        \- com.cedarsoftware:json-io:jar:2.5.1:compile
[INFO] |  \- org.apache.dubbo:dubbo-serialization-api:jar:2.7.0-SNAPSHOT:compile
[INFO] +- org.apache.dubbo:dubbo-rpc-dubbo:jar:2.7.0-SNAPSHOT:compile
[INFO] |  \- org.apache.dubbo:dubbo-container-api:jar:2.7.0-SNAPSHOT:compile
[INFO] +- org.apache.dubbo:dubbo-remoting-api:jar:2.7.0-SNAPSHOT:compile
[INFO] +- org.apache.dubbo:dubbo-remoting-netty4:jar:2.7.0-SNAPSHOT:compile
[INFO] |  \- io.netty:netty-all:jar:4.1.25.Final:compile
[INFO] +- org.apache.thrift:libthrift:jar:0.8.0:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.25:compile
[INFO] |  +- commons-lang:commons-lang:jar:2.5:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.3:compile
[INFO] |  |  \- commons-codec:commons-codec:jar:1.9:compile
[INFO] |  \- org.apache.httpcomponents:httpcore:jar:4.1.3:compile
[INFO] +- org.springframework:spring-context:jar:4.3.16.RELEASE:compile
[INFO] |  +- org.springframework:spring-aop:jar:4.3.16.RELEASE:compile
[INFO] |  +- org.springframework:spring-beans:jar:4.3.16.RELEASE:compile
[INFO] |  +- org.springframework:spring-core:jar:4.3.16.RELEASE:compile
[INFO] |  \- org.springframework:spring-expression:jar:4.3.16.RELEASE:compile
[INFO] +- org.apache.dubbo:dubbo-config-spring:jar:2.7.0-SNAPSHOT:test
[INFO] |  +- org.apache.dubbo:dubbo-config-api:jar:2.7.0-SNAPSHOT:test
[INFO] |  |  +- org.apache.dubbo:dubbo-monitor-api:jar:2.7.0-SNAPSHOT:test
[INFO] |  |  +- org.apache.dubbo:dubbo-filter-validation:jar:2.7.0-SNAPSHOT:test
[INFO] |  |  |  \- javax.validation:validation-api:jar:1.1.0.Final:test
[INFO] |  |  \- org.apache.dubbo:dubbo-filter-cache:jar:2.7.0-SNAPSHOT:test
[INFO] |  |     \- javax.cache:cache-api:jar:1.0.0:test
[INFO] |  +- org.apache.dubbo:dubbo-bootstrap:jar:2.7.0-SNAPSHOT:test
[INFO] |  +- org.springframework:spring-web:jar:4.3.16.RELEASE:test
[INFO] |  \- org.apache.dubbo:dubbo-rpc-injvm:jar:2.7.0-SNAPSHOT:test
[INFO] +- org.apache.dubbo:dubbo-registry-multicast:jar:2.7.0-SNAPSHOT:test
[INFO] |  \- org.apache.dubbo:dubbo-registry-api:jar:2.7.0-SNAPSHOT:test
[INFO] |     \- org.apache.dubbo:dubbo-cluster:jar:2.7.0-SNAPSHOT:test
[INFO] +- junit:junit:jar:4.12:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- org.hamcrest:hamcrest-all:jar:1.3:test
[INFO] +- org.mockito:mockito-core:jar:2.18.3:test
[INFO] |  +- net.bytebuddy:byte-buddy:jar:1.8.5:test
[INFO] |  +- net.bytebuddy:byte-buddy-agent:jar:1.8.5:test
[INFO] |  \- org.objenesis:objenesis:jar:2.6:compile
[INFO] \- cglib:cglib-nodep:jar:2.2:test
```

**Comment by LeoAugust19** [comment]
@beiwei30 
Hi, executing the command **mvn dependency:tree -Dverbose**, you can get the complete dependency tree of  dubbo-rpc-thrift.

PS C:\Users\Apple\Downloads\incubator-dubbo-dubbo-2.6.2\dubbo-rpc\dubbo-rpc-thrift> mvn dependency:tree -Dverbose
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building dubbo-rpc-thrift 2.6.2
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.10:tree (default-cli) @ dubbo-rpc-thrift ---
[WARNING] Using Maven 2 dependency tree to get verbose output, which may be inconsistent with actual Maven 3 resolution
[INFO] com.alibaba:dubbo-rpc-thrift:jar:2.6.2
[INFO] +- com.alibaba:dubbo-rpc-api:jar:2.6.2:compile
[INFO] |  +- com.alibaba:dubbo-common:jar:2.6.2:compile
[INFO] |  |  +- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  |  +- log4j:log4j:jar:1.2.16:compile
[INFO] |  |  +- org.javassist:javassist:jar:3.20.0-GA:compile
[INFO] |  |  +- com.alibaba:hessian-lite:jar:2.6.2:compile
[INFO] |  |  +- com.alibaba:fastjson:jar:1.2.46:compile
[INFO] |  |  +- com.esotericsoftware:kryo:jar:4.0.1:compile
[INFO] |  |  |  +- com.esotericsoftware:reflectasm:jar:1.11.3:compile
[INFO] |  |  |  |  \- org.ow2.asm:asm:jar:5.0.4:compile
[INFO] |  |  |  +- com.esotericsoftware:minlog:jar:1.3.0:compile
[INFO] |  |  |  \- org.objenesis:objenesis:jar:2.2:compile
[INFO] |  |  +- de.javakaffee:kryo-serializers:jar:0.42:compile
[INFO] |  |  |  \- (com.esotericsoftware:kryo:jar:4.0.1:compile - version managed from 4.0.0; omitted for duplicate)
[INFO] |  |  \- de.ruedigermoeller:fst:jar:2.48-jdk-6:compile
[INFO] |  |     +- com.fasterxml.jackson.core:jackson-core:jar:2.8.6:compile
[INFO] |  |     +- (org.javassist:javassist:jar:3.20.0-GA:compile - version managed from 3.19.0-GA; omitted for duplicate)
[INFO] |  |     +- (org.objenesis:objenesis:jar:2.4:compile - omitted for conflict with 2.2)
[INFO] |  |     \- com.cedarsoftware:java-util:jar:1.9.0:compile
[INFO] |  |        +- (commons-logging:commons-logging:jar:1.2:compile - version managed from 1.1.1; omitted for duplicate)
[INFO] |  |        \- com.cedarsoftware:json-io:jar:2.5.1:compile
[INFO] |  \- com.alibaba:dubbo-serialization-api:jar:2.6.2:compile
[INFO] |     +- (com.alibaba:dubbo-common:jar:2.6.2:compile - omitted for duplicate)
[INFO] |     +- (com.alibaba:hessian-lite:jar:2.6.2:compile - omitted for duplicate)
[INFO] |     +- (com.alibaba:fastjson:jar:1.2.46:compile - omitted for duplicate)
[INFO] |     +- (com.esotericsoftware:kryo:jar:4.0.1:compile - version managed from 4.0.0; omitted for duplicate)
[INFO] |     +- (de.javakaffee:kryo-serializers:jar:0.42:compile - omitted for duplicate)
[INFO] |     \- (de.ruedigermoeller:fst:jar:2.48-jdk-6:compile - omitted for duplicate)
[INFO] +- com.alibaba:dubbo-rpc-dubbo:jar:2.6.2:compile
[INFO] |  +- (com.alibaba:dubbo-rpc-api:jar:2.6.2:compile - omitted for duplicate)
[INFO] |  +- (com.alibaba:dubbo-remoting-api:jar:2.6.2:compile - omitted for duplicate)
[INFO] |  \- com.alibaba:dubbo-container-api:jar:2.6.2:compile
[INFO] |     \- (com.alibaba:dubbo-common:jar:2.6.2:compile - omitted for duplicate)
[INFO] +- com.alibaba:dubbo-remoting-api:jar:2.6.2:compile
[INFO] |  +- (com.alibaba:dubbo-common:jar:2.6.2:compile - omitted for duplicate)
[INFO] |  \- (com.alibaba:dubbo-serialization-api:jar:2.6.2:compile - omitted for duplicate)
[INFO] +- com.alibaba:dubbo-remoting-netty:jar:2.6.2:compile
[INFO] |  +- (com.alibaba:dubbo-remoting-api:jar:2.6.2:compile - omitted for duplicate)
[INFO] |  \- org.jboss.netty:netty:jar:3.2.5.Final:compile
[INFO] +- org.apache.thrift:libthrift:jar:0.8.0:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.25:compile (version managed from 1.5.8)
[INFO] |  +- commons-lang:commons-lang:jar:2.5:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.3:compile (version managed from 4.1.2)
[INFO] |  |  +- (org.apache.httpcomponents:httpcore:jar:4.4.6:compile - omitted for conflict with 4.1.3)
[INFO] |  |  +- (commons-logging:commons-logging:jar:1.2:compile - version managed from 1.1.1; omitted for duplicate)
[INFO] |  |  \- commons-codec:commons-codec:jar:1.9:compile
[INFO] |  \- org.apache.httpcomponents:httpcore:jar:4.1.3:compile
[INFO] +- org.springframework:spring-context:jar:4.3.16.RELEASE:compile
[INFO] |  +- org.springframework:spring-aop:jar:4.3.16.RELEASE:compile
[INFO] |  |  +- (org.springframework:spring-beans:jar:4.3.16.RELEASE:compile - omitted for duplicate)
[INFO] |  |  \- (org.springframework:spring-core:jar:4.3.16.RELEASE:compile - omitted for duplicate)
[INFO] |  +- org.springframework:spring-beans:jar:4.3.16.RELEASE:compile
[INFO] |  |  \- (org.springframework:spring-core:jar:4.3.16.RELEASE:compile - omitted for duplicate)
[INFO] |  +- org.springframework:spring-core:jar:4.3.16.RELEASE:compile
[INFO] |  |  \- (commons-logging:commons-logging:jar:1.2:compile - version managed from 1.1.1; omitted for duplicate)
[INFO] |  \- org.springframework:spring-expression:jar:4.3.16.RELEASE:compile
[INFO] |     \- (org.springframework:spring-core:jar:4.3.16.RELEASE:compile - omitted for duplicate)
[INFO] +- com.alibaba:dubbo-config-spring:jar:2.6.2:test
[INFO] |  +- com.alibaba:dubbo-config-api:jar:2.6.2:test
[INFO] |  |  +- (com.alibaba:dubbo-registry-api:jar:2.6.2:test - omitted for duplicate)
[INFO] |  |  +- com.alibaba:dubbo-monitor-api:jar:2.6.2:test
[INFO] |  |  |  \- (com.alibaba:dubbo-rpc-api:jar:2.6.2:test - omitted for duplicate)
[INFO] |  |  +- (com.alibaba:dubbo-remoting-api:jar:2.6.2:test - omitted for duplicate)
[INFO] |  |  +- (com.alibaba:dubbo-rpc-injvm:jar:2.6.2:test - omitted for duplicate)
[INFO] |  |  +- com.alibaba:dubbo-filter-validation:jar:2.6.2:test
[INFO] |  |  |  +- (com.alibaba:dubbo-rpc-api:jar:2.6.2:test - omitted for duplicate)
[INFO] |  |  |  \- javax.validation:validation-api:jar:1.1.0.Final:test
[INFO] |  |  \- com.alibaba:dubbo-filter-cache:jar:2.6.2:test
[INFO] |  |     +- (com.alibaba:dubbo-rpc-api:jar:2.6.2:test - omitted for duplicate)
[INFO] |  |     \- javax.cache:cache-api:jar:1.0.0:test
[INFO] |  +- (org.springframework:spring-beans:jar:4.3.16.RELEASE:test - omitted for duplicate)
[INFO] |  +- (org.springframework:spring-context:jar:4.3.16.RELEASE:test - omitted for duplicate)
[INFO] |  \- com.alibaba:dubbo-rpc-injvm:jar:2.6.2:test
[INFO] |     \- (com.alibaba:dubbo-rpc-api:jar:2.6.2:test - omitted for duplicate)
[INFO] +- com.alibaba:dubbo-registry-multicast:jar:2.6.2:test
[INFO] |  \- com.alibaba:dubbo-registry-api:jar:2.6.2:test
[INFO] |     +- com.alibaba:dubbo-cluster:jar:2.6.2:test
[INFO] |     |  \- (com.alibaba:dubbo-rpc-api:jar:2.6.2:test - omitted for duplicate)
[INFO] |     \- (com.alibaba:dubbo-container-api:jar:2.6.2:test - omitted for duplicate)
[INFO] +- junit:junit:jar:4.12:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- org.easymock:easymock:jar:3.4:test
[INFO] |  \- (org.objenesis:objenesis:jar:2.2:compile - scope updated from test; omitted for duplicate)
[INFO] +- org.jmockit:jmockit:jar:1.33:test
[INFO] \- cglib:cglib-nodep:jar:2.2:test
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.668 s
[INFO] Finished at: 2018-07-27T13:56:16+08:00
[INFO] Final Memory: 18M/266M
[INFO] ------------------------------------------------------------------------

**Comment by LeoAugust19** [comment]
@kimmking Could you please reopen this issue?
What kind of evidence do you need to confirm its a bug?

**Comment by LeoAugust19** [comment]
### Stack trace
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/util/Args
	at org.apache.http.impl.conn.Wire.output(Wire.java:110)
	at org.apache.http.impl.conn.LoggingOutputStream.write(LoggingOutputStream.java:73)
	at com.alibaba.dubbo.rpc.protocol.thrift.io.RandomAccessByteArrayOutputStream.writeTo(RandomAccessByteArrayOutputStream.java:93)
	at com.alibaba.dubbo.rpc.protocol.thrift.io.RandomAccessByteArrayOutputStreamTest.main(RandomAccessByteArrayOutputStreamTest.java:11)
Caused by: java.lang.ClassNotFoundException: org.apache.http.util.Args
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 4 more
