### ISSUE TITLE
dubbo-compatible do not work in dubbo 2.7

### ISSUE THREAD

**Issue by hengyunabc** [apache/incubator-dubbo#2144]
* User has a filter:

```
@com.alibaba.dubbo.common.extension.Activate(group = { Constants.CONSUMER })
public class TraceIdFilter implements com.alibaba.dubbo.rpc.Filter {
```

* `org.apache.dubbo.common.extension.ExtensionLoader.loadClass(Map<String, Class<?>>, URL, Class<?>, String)` load the `TraceIdFilter` class, but `@Activate` check fail, because in `loadClass` method the annotation is `@org.apache.dubbo.common.extension.Activate`.

```java
            String[] names = NAME_SEPARATOR.split(name);
            if (names != null && names.length > 0) {
                Activate activate = clazz.getAnnotation(Activate.class);
                if (activate != null) {
                    cachedActivates.put(names[0], activate);
                }
```

* Need to add annotation check for `@com.alibaba.dubbo.common.extension.Activate`

**Comment by diecui1202** [comment]
Get it. I will check it ASAP.

**Comment by diecui1202** [comment]
@hengyunabc I've fix this issue. You can try it out.
