### ISSUE TITLE
dubbo配置好springMVC之后怎么访问呢

### ISSUE THREAD

**Issue by kanghouchao** [apache/incubator-dubbo#2149]
### Environment

* Dubbo version: 2.6.2
* Operating System version: ubuntu 18.04
* Java version: 1.8

1. 我新建了一个dubbo项目，加入了spring和loj4j的依赖，配置成功了，项目也启动起来了，我在zookeeper可以看到server已经注册了
2. 在provider和consumer我都是用dubbo自带的Main.main启动的
3. 然而，有个迷思，consumer启动之后，我的springMVC怎么访问，我没有web.xml，也没有配置tomcat，那我应该怎么访问我在consumer端配置的controller呢?

谢谢

**Comment by diecui1202** [comment]
@kanghouchao Maybe you need to start the consumer with spring boot or tomcat. If tomcat, you need to package it to war(it required web.xml, then put the war to webapps dir).

If spring boot, refer http://start.dubbo.io for more information.

%READY-TO-CLOSE&, please reopen it if you also have problem.

**Comment by zonghaishang** [comment]
@kanghouchao Maybe you should use rest protocol, see: http://dubbo.apache.org/#!/docs/user/references/protocol/rest.md?lang=zh-cn
