### ISSUE TITLE
The code about the port of Protocol config is not consiste with the description of the Document

### ISSUE THREAD

**Issue by tswstarplanet** [apache/incubator-dubbo#2151]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: latest

### Step to reproduce this issue

1. Config the protocol, but do not config the port parameter
2. Start the application integrating dubbo.

According the document, if user does not config the port of protocol, Dubbo will pick an available port that count from the default port dynamically.
But the actual result is that Dubbo just pick the default port. It does not pick an available port dynamically.

So should we modify the code or document ?

**Comment by kimmking** [comment]
can you submit a PR for document in https://github.com/apache/incubator-dubbo-website

**Comment by tswstarplanet** [comment]
@kimmking You means that we should update the document to comply with the code

**Comment by tswstarplanet** [comment]
@kimmking I have submit a PR #64
