### ISSUE TITLE
@Reference annotation issue

### ISSUE THREAD

**Issue by YoungHu** [apache/incubator-dubbo#2164]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.2
* Operating System version: mac os  10.13/win10
* Java version: JDK6/7/8

### Step to reproduce this issue

1. provider side shutdown
2. start consumer side use @Reference annotation(check=true)
3. invoke provider get NPE

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

like consumer with xml config `<dubbo:refrence>`, if not provider application startup failed.

### Actual Result

application startup successful, and when invoke provider get NPE, then we startup the provider side still get NPE

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

case reason:
when use @refence  annotation(be know that check default value is true) , if no provider actually `ReferenceConfig` class throw exception, but this exception was ignored.

**Comment by rocky-peng** [comment]
this issue had been resolved in the newest master . test date: 2018-08-4

**Comment by YoungHu** [comment]
same issue with #1999 ,so close this one
