### ISSUE TITLE
eclipse 运行dubbo admin 报错

### ISSUE THREAD

**Issue by jackiilong** [apache/incubator-dubbo#217]
INFO context.ContextLoader - Root WebApplicationContext: initialization started
 INFO context.WebxComponentsContext - Refreshing com.alibaba.citrus.webx.context.WebxComponentsContext@6a48fb06: display name [Root WebApplicationContext]; startup date [Tue Mar 22 13:35:22 CST 2016]; root of context hierarchy
ERROR context.ContextLoader - Context initialization failed
java.lang.IllegalArgumentException: Could not include schema "../wsdl/http-conf.xsd" in cxf.apache.org/schemas/configuration/http-conf.xsd

**Comment by lvan100** [comment]
我也遇到了，有人解决了吗？

**Comment by lansefeiyang122** [comment]
先启动zookeeper
在命令行窗口执行
d:
cd d:\dubbo.trunk
mvn -Dmaven.test.skip=true clean install
mvn jetty:run

试试看，我的也遇到这个错误，这样就能正常启动，不要在eclipse里启动

**Comment by lvan100** [comment]
我已经放弃dobbo了，开始关注[spring cloud](http://projects.spring.io/spring-cloud/)。

**Comment by avatar21** [comment]
同样，我把项目换成gradle格式了，用gretty测的
后面我又用mvn插件jetty测得，也不行 
会试试tomcat插件，如果可以那就是jetty插件检验的太严了。

**Comment by ralf0131** [comment]
The dubbo-admin has been refactored to be a spring-boot project. Please check it again!

https://github.com/apache/incubator-dubbo-ops
