### ISSUE TITLE
dubbo monitor建议

### ISSUE THREAD

**Issue by xryg2276287715** [apache/incubator-dubbo#2182]
感谢抽空查看。
..../services/statistics/method?service=XXXProvider&method=XXXmethod
关于这个链接对应的页面，建议优化以下2点：
1、可以考虑将consumer以对应的应用名称进行显示，不要以ip显示，同个ip上会存在若干个不同的应用，生产问题排查时，有时需要查看各个应用产生的调用量。
2、列表页(Success,Failure,Avg Elapsed,Max Elapsed,Max Concurrent)要是能够增加可选排序就好了，类似于js控件datatables差不多效果。

**Comment by nzomkxia** [comment]
thank you for your advice, i'll take this into consideration during dubbo ops refactoring

**Comment by dengjiexiao** [comment]
我想问下dubbo admin 怎么看不到消费者了？

**Comment by nzomkxia** [comment]
@dengjiexiao can you provide more details about this?

**Comment by nzomkxia** [comment]
@dengjiexiao the dubbo admin is under refactoring, please refer to the develop branch
