### ISSUE TITLE
ConsistentHashLoadBalance  selectForKey can optimization

### ISSUE THREAD

**Issue by huangyunbin** [apache/incubator-dubbo#2188]
Map.Entry<Long, Invoker<T>> entry = virtualInvokers.tailMap(hash, true).firstEntry();
==》
Map.Entry<Long,` Invoker<T>> entry = virtualInvokers.ceilingEntry(hash);

**Comment by huangyunbin** [comment]
ok, pr is https://github.com/apache/incubator-dubbo/pull/2190

**Comment by carryxyh** [comment]
👍 
Thx for your contribution.
