### ISSUE TITLE
Annotation @Reference can't support to export a service with a sync one and an async one

### ISSUE THREAD

**Issue by jayruen** [apache/incubator-dubbo#2194]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.2
* Operating System version: Win7
* Java version: 1.8

### Step to reproduce this issue
不支持同时存在一个异步引用和一个同步引用，dubbo注入两个对象的地址都是相同的，第一个如果是异步则两个都是异步。 第一如果是同步则两个都是同步

    @Reference(async = true)
    private DebugService ansyncDebugService;

    @Reference(async = false)
    private DebugService debugService;

**Comment by diecui1202** [comment]
@mercyblitz How about this issue ?

**Comment by cvictory** [comment]
@mercyblitz  How is it going?

**Comment by zonghaishang** [comment]
same as : https://github.com/apache/incubator-dubbo/issues/2522

I will fix it this weekend.

**Comment by FrankMiaoHao** [comment]
这个问题是不是 2.6.4已经解决了？ 貌似现在 可以了。
在一个方法内测试了一下 还没有具体多个地方测试 不清楚是不是Context在同一个Context的原因

**Comment by zonghaishang** [comment]
fixed, close it now. see : https://github.com/apache/incubator-dubbo/pull/2649
