### ISSUE TITLE
客户端调服务端，服务端代码有输出，客户端接收却为""

### ISSUE THREAD

**Issue by zjzhujie125** [apache/incubator-dubbo#2216]
批量场景：服务A每3秒调用一次服务B，用于获取实时报价。
1.交易端服务A调用报价端服务B。
2.服务B查完数据库有数据返回，并封装好返回服务A。
3.服务A在获取服务B的返回结果时，为""，（请注意是空，不是null）。
分析：
通过日志文件，发现服务B并没有被调用的日志。
所以开始产生各种猜想：难道服务B有缓存？？取了服务B的缓存结果？

**Comment by kimmking** [comment]
can you submit a demo to reproduce it?

**Comment by kimmking** [comment]
can you submit a demo to reproduce it?

**Comment by yy-Eddy** [comment]
嘿, 我也遇到这个问题了,但是我的不同点是可以确定我没有使用缓存,也没有配置dubbo使用缓存,我这边因为提供者返回的对象 所以返回的是空对象 而非"", 我也是在提供者return结果上一行打印的信息是不为空的

**Comment by chickenlj** [comment]
Hi @zjzhujie125 , have you checked the serialization part?

**Comment by lovepoem** [comment]
@zjzhujie125 What's the dubbo version of your project?

**Comment by beiwei30** [comment]
feel free to reopen this issue if you can provide a demo to reproduce, @zjzhujie125
