### ISSUE TITLE
When using telnet "invoke" method, if there is a [null] param, the response always be [null] 

### ISSUE THREAD

**Issue by elvis9xu163** [apache/incubator-dubbo#2218]
dubbo> invoke com.alibaba.dubbo.demo.DemoService.sayHello(null)    // null as parameter
null

reason: 
InvokeTelnetHandler.isMatch(Class<?>[] types, List<Object> args)
    ...
    } else if (ReflectUtils.isPrimitive(arg.getClass())) {  // there should judge arg is null first

原因： InvokeTelnetHandler.isMatch(Class<?>[] types, List<Object> args)中判断arg的类型时未做null值判断, arg.getClass()抛出了空指针异常

**Comment by ralf0131** [comment]
Hi, would you mind send a pull request?

**Comment by chickenlj** [comment]
http://dubbo.apache.org/#!/docs/user/references/telnet.md?lang=zh-cn

**Comment by xujunjie97** [comment]
#2259

**Comment by diecui1202** [comment]
Since the PR #2273 has been merged to master, we need a new PR that merge it to 2.6.x
