### ISSUE TITLE
Any better solutions for http request

### ISSUE THREAD

**Issue by haiyang1985** [apache/incubator-dubbo#2224]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: xxx
* Operating System version: xxx
* Java version: xxx

# Http Request Solutions

We are going to export dubbo service for front-end request(eg: h5 outside). We are doubt about the advantage and disadvantage of below two solutions, anyone have good ideas for that?

Generally, there are two ways to support that. 
Solution1: Add proxy(through GenericService) for the http request (http -> proxy -> dubbo)
Solution2: Support dubbo & http protocol in service side (eg: dubbox/jsonrpc).

### Advantage:
1. It's easy for the user, no need to maintain both http & dubbo protocols.
2. No need to maintain two types of configurations (one for dubbo, another for http). Following two conditions may confuse the user. Firstly, xxx config support for dubbo and http, but they are in different key. Secondly, yyy config is supported in dubbo, not for http. User maybe confused on so much of the configs.

### Disadvantage:
1. The latency is high for the proxy mode. 
For dubbo protocol:  1k request/100k response/3000QPS, average response is 1-2ms, and able to support 7000-8000QPS in 8Core server.
For the proxy mode: 1K request/100K response/600QPS, the average response is 14ms, only with 600QPS.
2. The proxy CPU is very high.
For dubbo protocol: With 7000-8000QPS, the service CPU is about 80-90%, with 600QPS, the service CPU below 5-10% maybe.
For proxy mode: With 600QPS, service CPU is low, but the proxy's CPU is almost full (80-90%). That means, it need 4-5times of the server to host the request.

### Advantage:
1. The latency is very low, as it's directly connect to the service.
### Disadvantage:
1. User have to maintain both dubbo & http protocol, as described in solution 1 . 

We are confused to find a better solution. Am i in a wrong way, or anyone have good suggestions or solutions for http request?

Thanks for any suggestions.

**Comment by kimmking** [comment]
Rest via HTTP is not a high perfermance protocol in RPC domain.
1. If you wanna add some biz logic above dubbo-service, proxy layer is a good choice.
1. If you throw returnValue of service method directly, then rest protocol +filter is a nice way.
1. For perfermance, think about mutil-level cache strategy, multiple providers loadbalance, etc.

**Comment by haiyang1985** [comment]
Thanks!
Is there any existing products for rest protocol + filter solution?

**Comment by kimmking** [comment]
dubbox with its samples

**Comment by haiyang1985** [comment]
Not sure whether I've got your points of rest protocol+filter way. I've generally looked at the dubbox these days, please help me to confirm on whether dubbox is the rest protocol+filter way? And this is the samples as you said https://blog.csdn.net/nmyphp/article/details/79174225?
