### ISSUE TITLE
remove hessian-lite license info from LICENSE in the next release.

### ISSUE THREAD

**Issue by beiwei30** [apache/incubator-dubbo#2226]
Since we remove the hessian-lite, I suggest we remove the license info
in LICENSE.

I checked ASF release policy[1], it says:

Each package MUST provide a LICENSE file and a NOTICE file which
account for the package's exact content. LICENSE and NOTICE MUST NOT
provide unnecessary information about materials which are not bundled
in the package, such as separately downloaded dependencies.

**Comment by ralf0131** [comment]
I have removed the hessian-lite license info from LICENSE and committed to 2.6.3-release branch, it will be merged into 2.6.x branch.

I also checked master branch, it has already been removed.

In 2.5.x branch, hessian-lite is not removed, so everything is fine.

So I think this issued has been fixed.
