### ISSUE TITLE
zk做注册中心时，怎么设置dubbo在zk中的根路径？

### ISSUE THREAD

**Issue by nlskyfree** [apache/incubator-dubbo#2234]
### Environment

* Dubbo version: 2.5.7
* Operating System version: centos
* Java version:1.8

如题，多个环境依赖于同一个zk集群，是否支持修改zookeeper注册中心的根路径
比如将/dubbo改为/dubbo1 /dubbo2

**Comment by playaround88** [comment]
Did you test zookeeper's chroot? feature added in zookeeper 3.2.0.
like this: "host1:port,host2:port/dubbo1"

**Comment by nlskyfree** [comment]
@kimmking 恩，看源码发现了，group就是根路径名称，问题我关了
