### ISSUE TITLE
[Enhancement] Reactor the generation rule for @Service Bean name 

### ISSUE THREAD

**Issue by mercyblitz** [apache/incubator-dubbo#2235]
- [X] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [X] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Target

Add a generation rule of `@Service` Bean name in order to avoid duplication and is easy to look-up injected-dependencies.

### Environment

* Dubbo version: 2.6.4
* Operating System version: all
* Java version: 1.6-1.8

**Comment by chickenlj** [comment]
What is the rule exactly now after the refactor?
