### ISSUE TITLE
[Enhancement] Resolve the placeholders for sub-properties 

### ISSUE THREAD

**Issue by mercyblitz** [apache/incubator-dubbo#2297]
- [X] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [X] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Details

For now on, Dubbo does not support to resolve all placeholders from property value from any `PropertySource`, thus it will impact Dubbo Spring Boot's externalization configuration, like this issue : 
* [Can provider boot features external config placeholders in properties?](https://github.com/apache/incubator-dubbo-spring-boot-project/issues/249)

What's more, Dubbo's `PropertySourcesUtils` will be removed and replaced by [Alibaba's spring-context-support](https://github.com/alibaba/spring-context-support)'s [`PropertySourcesUtils`](https://github.com/alibaba/spring-context-support/blob/1.0.1/src/main/java/com/alibaba/spring/util/PropertySourcesUtils.java)

**Comment by diecui1202** [comment]
@mercyblitz How about this issue? Ready for merge?
