### ISSUE TITLE
动态修改accepts配置效果非预期

### ISSUE THREAD

**Issue by hupuxiaojun** [apache/incubator-dubbo#2300]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.2
* Operating System version: win7
* Java version: 1.8

### Step to reproduce this issue

1. 在本机启动了一个provider, accepts参数设置的为1：
java -Ddubbo.protocol.port=12345 -Dserver.port=9090 -Dmanagement.server.port=9091 -Ddubbo.application.qos-port=22221 -Ddubbo.protocol.accepts=1 -jar dubbo-demo-provider\target\dubbo-provider-1.0-SNAPSHOT.jar 
2. 在本机启动了两个consumer:
java -Dserver.port=8080 -Dmanagement.server.port=8081 -Ddubbo.registry.file=xxx.properties  -jar dubbo-demo-consumer\target\dubbo-consumer-1.0-SNAPSHOT.jar
java -Dserver.port=8084 -Dmanagement.server.port=8085 -Ddubbo.registry.file=yyy.properties  -jar dubbo-demo-consumer\target\dubbo-consumer-1.0-SNAPSHOT.jar
第二个启动的consumer会正常被accepts=1给断开连接。
3. 然后我在admin中动态修改配置,将accepts改为2
![image](https://user-images.githubusercontent.com/16410900/44095585-c6213462-a00b-11e8-9175-1352b298b4cb.png)
发现第二个启动的consumer可以正常连接，没问题
4.在admin页面中，将accepts再次修改成1,发现两个consumer仍然会正常连接，理论上是要有一个被踢下线的才对。

### Expected Result

期望只有一个consumer连接，另外一个consumer会由于超过accepts数而拒绝连接

### Actual Result

两个consumer都正常连接着，并能够正常对外提供服务

**Comment by ningyu1** [comment]
@hupuxiaojun 
Do you have a good idea? Do in the startup phase control is reasonable, you can provide a ` PR ` up to discuss.
Mandatory stop of services that have been started will have several problems:
1. Which one to stop?
2. If a request is being processed, it needs to be stopped after the request is completed

**Comment by beiwei30** [comment]
目前行为是符合预期的，已有的连接不会立即关闭，需要等调用方使用完毕后才会关。而新建的连接会受到新的 accepts 值的限制。

```java
    @Override
    public void connected(Channel ch) throws RemotingException {
        // If the server has entered the shutdown process, reject any new connection
        if (this.isClosing() || this.isClosed()) {
            logger.warn("Close new channel " + ch + ", cause: server is closing or has been closed. For example, receive a new connect request while in shutdown process.");
            ch.close();
            return;
        }

        Collection<Channel> channels = getChannels();
        if (accepts > 0 && channels.size() > accepts) {
            logger.error("Close channel " + ch + ", cause: The server " + ch.getLocalAddress() + " connections greater than max config " + accepts);
            ch.close();
            return;
        }
        super.connected(ch);
    }
```
