### ISSUE TITLE
[BUG] @Reference#parameters() does not work

### ISSUE THREAD

**Issue by mercyblitz** [apache/incubator-dubbo#2301]
- [X] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [X] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.3
* Operating System version: all
* Java version: all

### Step to reproduce this issue

1. To setting `@Reference#parameters()` 

### Expected Result

`ReferenceBean` contains parameters `Map`

### Actual Result

`ReferenceBean` does not contain parameters `Map`

**Comment by diecui1202** [comment]
@mercyblitz could u pls. send a PR?

**Comment by cvictory** [comment]
I write a demo to check this issue, but I found ReferenceBean has this parameter.

modify dubbo configuration file :   
```
    <dubbo:annotation/>
    <context:component-scan base-package="com.alibaba.dubbo.demo.consumer">
        <context:include-filter type="annotation" expression="com.alibaba.dubbo.config.annotation.Reference"/>
    </context:component-scan>
```

write service:  
```
@Service
public class ConsumerService {

    @Reference(parameters = {"k1", "v1"})
    private DemoService demoService;

    public void testReference() {
        System.out.println(demoService.sayHello("www.world"));
    }
}
```

And debug the referenceConfig, I found the parameter contain this key as follow:  

I write a demo to check this issue, but I found ReferenceBean has this parameter.

modify dubbo configuration file :   
```
    <dubbo:annotation/>
    <context:component-scan base-package="com.alibaba.dubbo.demo.consumer">
        <context:include-filter type="annotation" expression="com.alibaba.dubbo.config.annotation.Reference"/>
    </context:component-scan>
```

write service:  
```
@Service
public class ConsumerService {

    @Reference(parameters = {"k1", "v1"})
    private DemoService demoService;

    public void testReference() {
        System.out.println(demoService.sayHello("www.world"));
    }
}
```

And debug the referenceConfig, I found the parameter contain this key as follow:  

![Uploading image.png…]()

**Comment by cvictory** [comment]
@mercyblitz  please check this issue again.  

&READY-TO-CLOSE&
