### ISSUE TITLE
qos-server can not bind localhost:22222, dubbo version: 2.6.2。what is qos-server？

### ISSUE THREAD

**Issue by 65725738** [apache/incubator-dubbo#2304]
qos-server can not bind localhost:22222, dubbo version: 2.6.2

what is qos-server？ manual doesn't mention it。

where to set qos-sever port？

**Comment by ralf0131** [comment]
Please refer to this blog: http://dubbo.apache.org/zh-cn/blog/introduction-to-dubbo-qos.html
