### ISSUE TITLE
2.6.4 release todo list

### ISSUE THREAD

**Issue by diecui1202** [apache/incubator-dubbo#2305]
1. #2303 Change consumer retries default value from 0 to 2. Need to change docs
2. #2024 Fix the problem that attachment is lost when retry
3. #2166 Add ip and application name for MonitorService
4. #2146 Support access Redis with password
5. #2137 Support char array for GenericService
6. #2402 New ASCII logo for Dubbo
7. #2451 Direct return when the server goes down abnormally
8. #2453 Fix NPE when telnet get a null parameter
9. #2455 Add log when qos start failed
10. #2499 PojoUtil support subclasses of java.util.Date

**Comment by diecui1202** [comment]
@chickenlj

**Comment by carryxyh** [comment]
Hi, This pr mainly to fix the problem that attachment is lost when retry：
https://github.com/apache/incubator-dubbo/pull/2024
Maybe change to Fix the problem that attachment is lost when retry.

FolkInvokeCluster should be ForkingClusterInvoker.

Other fix options have been checked.

**Comment by diecui1202** [comment]
@carryxyh you can edit the list above directly.

**Comment by carryxyh** [comment]
@diecui1202 
Has fixed it. :)
