### ISSUE TITLE
dubbo how Dynamic modification service group?

### ISSUE THREAD

**Issue by zhongzunfa** [apache/incubator-dubbo#2308]
dubbo can Dynamic modification service group?
Like enable service or disabled service.

for example ： 
<dubbo:reference id="demoServiceA" check="false" interface="com.alibaba.dubbo.demo.DemoService" group="A"/>
<dubbo:reference id="demoServiceB" check="false" interface="com.alibaba.dubbo.demo.DemoService" group="B"/>
<dubbo:service interface="com.alibaba.dubbo.demo.DemoService" id="demoService" group="C"/>

I will to change group A to C , so this group A can remote group C .

**Comment by zonghaishang** [comment]
Currently dubbo has no way to support this feature, We have noticed this demand and have plans to solve it.
There is a solution that is not elegant：
1. Calling cached services that need to be grouped by generalization

**Comment by zhongzunfa** [comment]
@zonghaishang Thank you for your answer, Take the liberty to ask. Will dubbo version 2.7.0 solve this problem?

**Comment by kimmking** [comment]
@zhongzunfa uncertainty

**Comment by zonghaishang** [comment]
Temporarily closed, can be reopened if needed

**Comment by thinking-github** [comment]
Is the problem solved please?
