### ISSUE TITLE
Bootstrap blocked

### ISSUE THREAD

**Issue by bobchengit** [apache/incubator-dubbo#2310]
When I use the version of dubbo 2.6.2, application blocking occurs on some machines. Check out the update history of dubbo, this bug has been fixed in version 2.5.7. Since there is no log to view, how do I need to locate this problem?

**Comment by diecui1202** [comment]
@bobchengit you can use jstack to check the main thread stack.

**Comment by carryxyh** [comment]
Hi, @bobchengit 
Pls push your demo onto github and provide a link to us.
We will check the problem soon.
