### ISSUE TITLE
About Handle "Duplicate class com/alibaba/dubbo/common/Version.class in 2 jar"

### ISSUE THREAD

**Issue by changwei0708** [apache/incubator-dubbo#2314]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.5.10
* Operating System version: windows7
* Java version: jdk1.8

use dubbo-2.5.x and dubbo-2.6.x, it is need to exclude dubbo-common , otherwise, boot log output 
```
Duplicate class com/alibaba/dubbo/common/Version.class in 2 jar
```
and then i do this 
```
<dependency>
			<groupId>com.alibaba</groupId>
			<artifactId>dubbo</artifactId>
			<scope>system</scope>
			<version>${alibaba.dubbo.version}</version>
			<systemPath>${basedir}/lib/dubbo-2.5.10.jar</systemPath>
			<exclusions>
				<exclusion>
					<groupId>com.alibaba</groupId>
					<artifactId>dubbo-common</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```
but when i include kryo , i need to repeat that ,just like 
```
<dependency>
			<groupId>com.alibaba</groupId>
			<artifactId>dubbo-serialization-kryo</artifactId>
			<version>2.6.2</version>
			<exclusions>
				<exclusion>
					<groupId>com.alibaba</groupId>
					<artifactId>dubbo-common</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```

but this Dependency transfer problem is not appear in  https://github.com/dangdangdotcom/dubbox,
can fix it ?

**Comment by zonghaishang** [comment]
Please run ` mvn dependency:tree > tree.log` in your project root directory.
And  upload the file `tree.log` here (just drag the file here).

**Comment by beiwei30** [comment]
@changwei0708 @salamando I cannot reproduce this issue on 2.6.2. Pls. share me your demo app in your github space, and reopen this issue if you still have the problem.
