### ISSUE TITLE
[BUG] Maven package issues on JavaDoc plugin in 2.6.x

### ISSUE THREAD

**Issue by mercyblitz** [apache/incubator-dubbo#2315]
- [X] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [X] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.x
* Operating System version: all
* Java version: 1.6+

### Step to reproduce this issue

`mvn clean package`

### Expected Result

BUILD SUCCESS

### Actual Result

BUILD FAILED

**Comment by diecui1202** [comment]
@mercyblitz Could u pls. send a PR for this?

**Comment by diecui1202** [comment]
#2454
