### ISSUE TITLE
move some extensions to ecosystem

### ISSUE THREAD

**Issue by diecui1202** [apache/incubator-dubbo#2316]
Move the following modules to ecosystem, each extension as a single project.
* dubbo-registry-redis

* dubbo-remoting-grizzly
* dubbo-remoting-p2p
* dubbo-remoting-zookeeper
* dubbo-remoting-mina

* dubbo-rpc-memcached
* dubbo-rpc-redis
* dubbo-rpc-thrift
* dubbo-rpc-webservice

* dubbo-serialization-fst

The previous discussion thread is here: https://lists.apache.org/thread.html/6cddfb3edf3d2c66cad621dc177c64cfeb8cfe8ef80a366023b50b4c@%3Cdev.dubbo.apache.org%3E

**Comment by ulinkwo** [comment]
I sent a pull request #2330 for this issue, but how could I contribute to ecosystem ( https://github.com/dubbo), I cloud not create a dubbo-serialization-fst repository in the group.

**Comment by diecui1202** [comment]
As the mentors suggest us moving ecosystem to apache group, I think this task should be closed.

@ulinkwo Thanks for your work. Expecting see you continue to contribute to dubbo.
