### ISSUE TITLE
Add @author rule in checkstyle

### ISSUE THREAD

**Issue by htynkn** [apache/incubator-dubbo#2317]
According to [code-conventions](https://github.com/apache/incubator-dubbo/blob/master/CONTRIBUTING.md#code-conventions), "@ author" tag is not allow in source code.

I notice some PR and some test code still have "@ author" tag, considering we already have checkstyle plugin, I suggest add a new rule to check @ author tag. it can save time to review PR.

Some configuration sample:
https://github.com/danielb987/EmojicodeEditor/blob/master/checkstyle/emojicode_checks.xml#L93

**Comment by carryxyh** [comment]
Agree with this proposal. 
I think:
1. We should check and remove present author tag.
2. The same thing should be done in branch 2.6.x.
:)

**Comment by kimmking** [comment]
@htynkn 
I think we should post this proposal to mail list.

**Comment by diecui1202** [comment]
@htynkn I suggest running checkstyle and rat plugin during release phase. For daily travis ci, just running mvn test, it needs to be completed ASAP.

Now the ci task takes a bit long time.

**Comment by markt-asf** [comment]
An approach I have seen taken in other projects is to remove @author tags but move the names to the appropriate POM section (if they are not already present).

**Comment by diecui1202** [comment]
I've enabled checkstyle and rat plugin for default travis CI.

**Comment by diecui1202** [comment]
https://github.com/apache/incubator-dubbo/pull/2393
