### ISSUE TITLE
dubbo序列化为什么结果不是预期的。

### ISSUE THREAD

**Issue by 65725738** [apache/incubator-dubbo#2318]
服务提供者的数据。
Page{count=true, pageNum=1, pageSize=2, startRow=0, endRow=0, total=10, pages=5, reasonable=null, pageSizeZero=null}[com.bdsaas.distribution.oa.dao.domain.Profile@2e7f1d08, com.bdsaas.distribution.oa.dao.domain.Profile@78162f84]

服务消费者的数据。
Page{count=true, pageNum=0, pageSize=0, startRow=0, endRow=0, total=0, pages=0, reasonable=null, pageSizeZero=null}[com.bdsaas.distribution.oa.dao.domain.Profile@1fc4b996, com.bdsaas.distribution.oa.dao.domain.Profile@500a8e3a]

page是个继承arraylist的类。里面加了一些自定义的属性。这些自定义的属性，序列化之后，都没有结果。arraylist里面的对象可以得到序列化的结果。这个是什么原因？

**Comment by 65725738** [comment]
public class Test<E> extends ArrayList<E> {

    private static final long serialVersionUID = 1L;

    private long total;
}

这样的类，jdk本身是可以序列化反序列化的。
但是dubbo接口不行。

什么原因？

**Comment by ZhuoSiChen** [comment]
默认采用的是Hessian 序列化，所以需要在 Test 里加默认构造函数。同理也需要在Page里加默认构造函数。

**Comment by kimmking** [comment]
My suggestion is:
Using Composite Style instead of Extend extension.
In your case, a more graceful design is:
```
@Data
public class Page{
private boolean count;
private int pageNum;
private int pageSize;
private int startRow;
...
private List<XXX> data;
}
```

**Comment by 65725738** [comment]
yes i did, but i don't know why it can't be serialized. @kimmking

**Comment by 65725738** [comment]
@ZhuoSiChen 
public class Test<E> extends ArrayList<E> {

    private static final long serialVersionUID = 1L;

    private long total;

    private int pages;

    private int pageNum;

    private int pageSize;

    public Test() {
    }

}

这样吗？结果还是一样。
