### ISSUE TITLE
自定义异常处理

### ISSUE THREAD

**Issue by ls9527** [apache/incubator-dubbo#2320]
关于ExceptionFilter最后面一句 return new RpcResult(new RuntimeException(StringUtils.toString(exception))); 换成一个可以继承的。

如下:

   public Result invoke(Invoker<?> invoker, Invocation invocation) throws RpcException {
       ///省略...
       return getDefaultRpcResult(exception);
    }

    protected RpcResult getDefaultRpcResult(Result result) {
        return new RpcResult(new RuntimeException(StringUtils.toString(result.getException())));
    }

可以解决项目中自定义异常的时候。我不用复制 ExceptionFilter 的所有代码，然后只改其中的一小部分

**Comment by diecui1202** [comment]
@ls9527 Why do you need to process biz exception in your project ?

**Comment by ls9527** [comment]
我是想说，我想扩展 ExceptionFilter 默认的处理。

以这个场景为例子。  我必须复制`ExceptionFilter` 整个类。  

我可能需要 com.mycompany 包下的都抛出去，
也可能A包的Exception与B包的Interface 的情况下，抛出去。
也可能指定的com.a.b.MyExcpetion的无论怎么样都抛出去

就以目前的业务而言，我就希望对于指定某几个类一定要抛出去，不管调用者是不是找得到。
我列举的这些场景，如果扩展 ExceptionFilter 的默认处理方式自然是最好的。
但是我不得不抄一遍ExceptionFilter的实现

加入自定义处理器根本处理不了这些异常。
必须删除默认的，然后自己扩展 ExceptionFilter 的默认情况

**Comment by kimmking** [comment]
@diecui1202 
Do we make RpcException instead of RuntimeException?

**Comment by diecui1202** [comment]
@kimmking IMO, use RpcException can not support this requirement yet.

**Comment by diecui1202** [comment]
Feel free to reopen if necessary.
