### ISSUE TITLE
Failed to read artifact descriptor for com.alibaba:dubbo:jar:2.6.3

### ISSUE THREAD

**Issue by huadong** [apache/incubator-dubbo#2326]
### Environment

* Dubbo version: 2.6.3
* Operating System version: Ubuntu 18.04
* Java version: 10.0.1

### Step to reproduce this issue

1. create a new project with maven pom.xml depend on dubbo 2.6.3
2. compile the project

### Actual Result

> Failed to read artifact descriptor for com.alibaba:dubbo:jar:2.6.3: Could not find artifact com.alibaba:dubbo-parent:pom:2.6.3 in central (http://central.maven.org/maven2/) 

com.alibaba:dubbo-parent:pom:2.6.3 has not been deployed to [http://mvnrepository.com/artifact/com.alibaba/dubbo-parent](http://mvnrepository.com/artifact/com.alibaba/dubbo-parent)

but all of others have been deployed to [http://mvnrepository.com/artifact/com.alibaba/dubbo](http://mvnrepository.com/artifact/com.alibaba/dubbo)

**Comment by dslchd** [comment]
I have the same question. Is there any official answer?

**Comment by dslchd** [comment]
I rolled back to version 2.5.10. 
Version 2.6.2 also had the shutdown graceful problem in tomcat 8.5.23, and I had to use the following method in my listener:
ProtocolConfig.destroyAll();

**Comment by chickenlj** [comment]
@huadong The Apache community is still voting for v2.6.3, so it's not available at present. I have updated the release note: https://github.com/apache/incubator-dubbo/releases/tag/untagged-24fcb73b05663c44192a

**Comment by huadong** [comment]
@chickenlj Thank you! 
The tag for v2.6.3 is very helpful, I can try the v2.6.3 from the source code. I think the feature which shutdown graceful is very important, for sometimes we need to use the hot reload feature of tomcat.

**Comment by dotnet123** [comment]
I have the same question.

**Comment by huadong** [comment]
@chickenlj I had packaged v2.6.3 from the source code. When shutdown tomcat, it logged this WARNING: 

> appears to have started a thread named [DubboClientReconnectTimer-thread-2] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
>  sun.misc.Unsafe.park(Native Method)
>  java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
>  java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
>java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1088)
>  java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
>  java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
>  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
>  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>  java.lang.Thread.run(Thread.java:748)

So I had to kill the tomcat process instead of executing the shutdown.sh of tomcat.

Should I do any more configurations?

**Comment by huadong** [comment]
@dslchd According to #1155, the netty blocks shutdown tomcat. 
the conflict is : 
> dubbo v2.6.3 depends on netty v3.2.5, 
> curator-framework v2.12.0 depends on netty v3.7.0.

tomcat shutdown normally after exclude netty from curator-framework.
Maybe dubbo should explicitly close zookeeper client in the future.

**Comment by dslchd** [comment]
@huadong Thank you for your answer.
But I'm not using dubbo v2.6.x right now, because I was using v2.6.2 and the graceful shutdown of dubbo was still a problem in tomcat, which is probably why you said it.
I'm now rolling back to v2.5.10 to solve this problem using the following solution
The code is as follows:
`        ProtocolConfig.destroyAll();
`
`            Field field = NettyClient.class.getDeclaredField("channelFactory");
`
`            field.setAccessible(true);
`
`            ChannelFactory channelFactory = (ChannelFactory) field.get(NettyClient.class);
`
`            channelFactory.releaseExternalResources();
`
`            field.setAccessible(false);
`

**Comment by huadong** [comment]
@ralf0131 Sorry! I filed a new issue #2334 for the elegant shutdown.
