### ISSUE TITLE
[DISCUSS]A new Dubbo ascii logo is wanted

### ISSUE THREAD

**Issue by carryxyh** [apache/incubator-dubbo#2332]
A new ASCII LOGO is wanted.

Here are some examples:
https://devops.datenkollektiv.de/banner.txt/index.html

pls. vote your favorite by clicking 👍

**Comment by diecui1202** [comment]
Another choice: http://patorjk.com/software/taag/#p=display&h=1&f=Small%20Slant&t=DUBBO

```
   ___   __  __ ___   ___   ____ 
  / _ \ / / / // _ ) / _ ) / __ \
 / // // /_/ // _  |/ _  |/ /_/ /
/____/ \____//____//____/ \____/ 
                                 
```

Please thumbs up if you like this logo.

**Comment by carryxyh** [comment]
```
 ________   ___  ___   ________   ________   ________     
|\   ___ \ |\  \|\  \ |\   __  \ |\   __  \ |\   __  \    
\ \  \_|\ \\ \  \\\  \\ \  \|\ /_\ \  \|\ /_\ \  \|\  \   
 \ \  \ \\ \\ \  \\\  \\ \   __  \\ \   __  \\ \  \\\  \  
  \ \  \_\\ \\ \  \\\  \\ \  \|\  \\ \  \|\  \\ \  \\\  \ 
   \ \_______\\ \_______\\ \_______\\ \_______\\ \_______\
    \|_______| \|_______| \|_______| \|_______| \|_______|

```

**Comment by kimmking** [comment]
[dubbo-logo.txt](https://github.com/apache/incubator-dubbo/files/2309292/dubbo-logo.txt)
here is many logos
you can write your logo font here.

I liiikkkeee varsity
![image](https://user-images.githubusercontent.com/807508/44449468-d35c3580-a620-11e8-9d37-0aba8988c096.png)

**Comment by xwlmdd** [comment]
big

**Comment by xwlmdd** [comment]
standard

**Comment by maqiang** [comment]
standard

**Comment by beiwei30** [comment]
standard:

```
|  _ \  | | | | | __ )  | __ )   / _ \ 
| | | | | | | | |  _ \  |  _ \  | | | |
| |_| | | |_| | | |_) | | |_) | | |_| |
|____/   \___/  |____/  |____/   \___/ 
```

**Comment by beiwei30** [comment]
big:

```
  _____    _    _   ____    ____     ____  
 |  __ \  | |  | | |  _ \  |  _ \   / __ \ 
 | |  | | | |  | | | |_) | | |_) | | |  | |
 | |  | | | |  | | |  _ <  |  _ <  | |  | |
 | |__| | | |__| | | |_) | | |_) | | |__| |
 |_____/   \____/  |____/  |____/   \____/ 
                                           
```

**Comment by beiwei30** [comment]
cybermedium

```
___  _  _ ___  ___  ____ 
|  \ |  | |__] |__] |  | 
|__/ |__| |__] |__] |__| 
                         
```

**Comment by beiwei30** [comment]
jerusalem

```
 ____   _   _  ____   ____    ___  
|  _ \ | | | || __ ) | __ )  / _ \ 
| | | || | | ||  _ \ |  _ \ | | | |
| |_| || |_| || |_) || |_) || |_| |
|____/  \___/ |____/ |____/  \___/ 
                                   
```

**Comment by wenshenjun** [comment]
@diecui1202  this good.

**Comment by beiwei30** [comment]
lcd

```
 ___         ___   ___   ___  
  | | |   |   | |   | | |   | 
  + | |   |   +-    +-  |   | 
  | | |   |   | |   | | |   | 
 ---   ---   ---   ---   ---  
```

**Comment by yida-lxw** [comment]
I choose the big one.

>  ____   _   _  ____   ____    ___  
|  _ \ | | | || __ ) | __ )  / _ \ 
| | | || | | ||  _ \ |  _ \ | | | |
| |_| || |_| || |_) || |_) || |_| |
|____/  \___/ |____/ |____/  \___/

**Comment by beiwei30** [comment]
mini

```
  _         _    _    _  
 | \  | |  |_)  |_)  / \ 
 |_/  |_|  |_)  |_)  \_/ 
                         
```

**Comment by beiwei30** [comment]
old banner

```
######  #     # ######  ######  ####### 
#     # #     # #     # #     # #     # 
#     # #     # #     # #     # #     # 
#     # #     # ######  ######  #     # 
#     # #     # #     # #     # #     # 
#     # #     # #     # #     # #     # 
######   #####  ######  ######  ####### 
```

**Comment by wenshenjun** [comment]
,--.          ,--.    ,--.            
 ,-|  | ,--.,--. |  |-.  |  |-.   ,---.  
' .-. | |  ||  | | .-. ' | .-. ' | .-. | 
\ `-' | '  ''  ' | `-' | | `-' | ' '-' ' 
 `---'   `----'   `---'   `---'   `---'

**Comment by beiwei30** [comment]
slant

```
    ____    __  __    ____     ____    ____ 
   / __ \  / / / /   / __ )   / __ )  / __ \
  / / / / / / / /   / __  |  / __  | / / / /
 / /_/ / / /_/ /   / /_/ /  / /_/ / / /_/ / 
/_____/  \____/   /_____/  /_____/  \____/  
                                            
```

**Comment by beiwei30** [comment]
smslant


```
   ___   __  __   ___    ___   ____ 
  / _ \ / / / /  / _ )  / _ ) / __ \
 / // // /_/ /  / _  | / _  |/ /_/ /
/____/ \____/  /____/ /____/ \____/ 
                                    
```

**Comment by htynkn** [comment]
standard looks good

**Comment by wenshenjun** [comment]
soft

<pre _ngcontent-c0="" class="form-control-static">                                         
   ,--.          ,--.    ,--.            
 ,-|  | ,--.,--. |  |-.  |  |-.   ,---.  
' .-. | |  ||  | | .-. ' | .-. ' | .-. | 
\ `-' | '  ''  ' | `-' | | `-' | ' '-' ' 
 `---'   `----'   `---'   `---'   `---'  
                                         
</pre>

**Comment by wenshenjun** [comment]
speed 
<pre _ngcontent-c0="" class="form-control-static">_________        ______  ______         
______  /____  _____  /_ ___  /_ ______ 
_  __  / _  / / /__  __ \__  __ \_  __ \
/ /_/ /  / /_/ / _  /_/ /_  /_/ // /_/ /
\__,_/   \__,_/  /_.___/ /_.___/ \____/ 
                                        
</pre>

**Comment by wenshenjun** [comment]
eftirobot

<pre _ngcontent-c0="" class="form-control-static">   _       _    _        
  ( )     ( )  ( )       
 _| | _ _ | |_ | |_  ___ 
/ o )( U )( o \( o \( o )
\___\/___\/___//___/ \_/ 
                         
</pre>

**Comment by wenshenjun** [comment]
double

<pre _ngcontent-c0="" class="form-control-static"> ____   __ __ ____  ____    ___  
 || \\  || || || )) || ))  // \\ 
 ||  )) || || ||=)  ||=)  ((   ))
 ||_//  \\_// ||_)) ||_))  \\_// 
                                 
</pre>

**Comment by wenshenjun** [comment]
alpha

<pre _ngcontent-c0="" class="form-control-static">          _____                    _____                    _____                    _____                   _______         
         /\    \                  /\    \                  /\    \                  /\    \                 /::\    \        
        /::\    \                /::\____\                /::\    \                /::\    \               /::::\    \       
       /::::\    \              /:::/    /               /::::\    \              /::::\    \             /::::::\    \      
      /::::::\    \            /:::/    /               /::::::\    \            /::::::\    \           /::::::::\    \     
     /:::/\:::\    \          /:::/    /               /:::/\:::\    \          /:::/\:::\    \         /:::/~~\:::\    \    
    /:::/  \:::\    \        /:::/    /               /:::/__\:::\    \        /:::/__\:::\    \       /:::/    \:::\    \   
   /:::/    \:::\    \      /:::/    /               /::::\   \:::\    \      /::::\   \:::\    \     /:::/    / \:::\    \  
  /:::/    / \:::\    \    /:::/    /      _____    /::::::\   \:::\    \    /::::::\   \:::\    \   /:::/____/   \:::\____\ 
 /:::/    /   \:::\ ___\  /:::/____/      /\    \  /:::/\:::\   \:::\ ___\  /:::/\:::\   \:::\ ___\ |:::|    |     |:::|    |
/:::/____/     \:::|    ||:::|    /      /::\____\/:::/__\:::\   \:::|    |/:::/__\:::\   \:::|    ||:::|____|     |:::|    |
\:::\    \     /:::|____||:::|____\     /:::/    /\:::\   \:::\  /:::|____|\:::\   \:::\  /:::|____| \:::\    \   /:::/    / 
 \:::\    \   /:::/    /  \:::\    \   /:::/    /  \:::\   \:::\/:::/    /  \:::\   \:::\/:::/    /   \:::\    \ /:::/    /  
  \:::\    \ /:::/    /    \:::\    \ /:::/    /    \:::\   \::::::/    /    \:::\   \::::::/    /     \:::\    /:::/    /   
   \:::\    /:::/    /      \:::\    /:::/    /      \:::\   \::::/    /      \:::\   \::::/    /       \:::\__/:::/    /    
    \:::\  /:::/    /        \:::\__/:::/    /        \:::\  /:::/    /        \:::\  /:::/    /         \::::::::/    /     
     \:::\/:::/    /          \::::::::/    /          \:::\/:::/    /          \:::\/:::/    /           \::::::/    /      
      \::::::/    /            \::::::/    /            \::::::/    /            \::::::/    /             \::::/    /       
       \::::/    /              \::::/    /              \::::/    /              \::::/    /               \::/____/        
        \::/____/                \::/____/                \::/____/                \::/____/                 ~~              
         ~~                       ~~                       ~~                       ~~                                       
                                                                                                                             
</pre>

**Comment by majinkai** [comment]
block

**Comment by wenshenjun** [comment]
alligator

<pre _ngcontent-c0="" class="form-control-static">      :::::::::      :::    :::       :::::::::       :::::::::       :::::::: 
     :+:    :+:     :+:    :+:       :+:    :+:      :+:    :+:     :+:    :+: 
    +:+    +:+     +:+    +:+       +:+    +:+      +:+    +:+     +:+    +:+  
   +#+    +:+     +#+    +:+       +#++:++#+       +#++:++#+      +#+    +:+   
  +#+    +#+     +#+    +#+       +#+    +#+      +#+    +#+     +#+    +#+    
 #+#    #+#     #+#    #+#       #+#    #+#      #+#    #+#     #+#    #+#     
#########       ########        #########       #########       ########       
</pre>

**Comment by lexburner** [comment]
The font `small slant` looks very coooooool.
```
   ___   __  __ ___   ___   ____ 
  / _ \ / / / // _ ) / _ ) / __ \
 / // // /_/ // _  |/ _  |/ /_/ /
/____/ \____//____//____/ \____/ 
```

**Comment by wenshenjun** [comment]
standard

<pre _ngcontent-c0="" class="form-control-static">      _           _       _             
   __| |  _   _  | |__   | |__     ___  
  / _` | | | | | | '_ \  | '_ \   / _ \ 
 | (_| | | |_| | | |_) | | |_) | | (_) |
  \__,_|  \__,_| |_.__/  |_.__/   \___/ 
                                        
</pre>

**Comment by wenshenjun** [comment]
jerusalem

<pre _ngcontent-c0="" class="form-control-static">                                    
   ____   ___   ___   ___  ________ 
  |__  | |_  | |_  | |_  ||.  ___  |
     | |   | |   | |   | | | |   | |
 ____| |   | | __| | __| | | |___| |
/____/\_\  |_||____||____| |_______|
                                    
</pre>

**Comment by majinkai** [comment]
Block
```
 _|_|_|    _|    _|  _|_|_|    _|_|_|      _|_|    
 _|    _|  _|    _|  _|    _|  _|    _|  _|    _|  
 _|    _|  _|    _|  _|_|_|    _|_|_|    _|    _|  
 _|    _|  _|    _|  _|    _|  _|    _|  _|    _|  
 _|_|_|      _|_|    _|_|_|    _|_|_|      _|_|    
```

**Comment by beiwei30** [comment]
pls. don't dup, just vote on your favorite with thumb up.

**Comment by wenshenjun** [comment]
pls.using 👍 to vote.

**Comment by wenshenjun** [comment]
how about this?

spliff
<pre _ngcontent-c0="" class="form-control-static"> _____  __ __  _____  _____  _____ 
|  _  \/  |  \/  _  \/  _  \/  _  \
|  |  ||  |  ||  _  &lt;|  _  &lt;|  |  |
|_____/\_____/\_____/\_____/\_____/
                                   
</pre>

**Comment by carryxyh** [comment]
@wenshenjun 
Nice, too. :)

**Comment by kongchong** [comment]
i like the block style

 _|_|_|    _|    _|  _|_|_|    _|_|_|      _|_|    
 _|    _|  _|    _|  _|    _|  _|    _|  _|    _|  
 _|    _|  _|    _|  _|_|_|    _|_|_|    _|    _|  
 _|    _|  _|    _|  _|    _|  _|    _|  _|    _|  
 _|_|_|      _|_|    _|_|_|    _|_|_|      _|_|

**Comment by chickenlj** [comment]
I think it would better if the ASCII banner looks similar like the official LOGO
http://dubbo.apache.org/zh-cn/index.html

**Comment by huahaihuang** [comment]
@wenshenjun so good~

**Comment by kongchong** [comment]
like block style

**Comment by KingBlueSky** [comment]
the big one

**Comment by ningyu1** [comment]
![image](https://user-images.githubusercontent.com/3387548/44459389-0fe95a80-a63c-11e8-924c-521171ada0c7.png)
big style +1

**Comment by carryxyh** [comment]
Close this issue.
I will vote for the new dubbo logo as soon as possible.
Thank you everyone for voting

**Comment by carryxyh** [comment]
After a few days of voting, the top three LOGOs were: small slant, big and standard.
So we will choose to use small slant as the new ascii logo.
Thank you everyone for voting. :)

**Comment by diecui1202** [comment]
Cool
