### ISSUE TITLE
Spring Boot集成Dubbo, Dubbo读取不到Config Server配置文件里配置

### ISSUE THREAD

**Issue by zhugleo** [apache/incubator-dubbo#2336]
Spring Boot使用Config Server集中管理应用的配置文件 , Dubbo相关配置也在该文件中 ; 对比本地YAML文件和Config Server中YAML文件的读取 , Dubbo并不能读取到Config Server中的配置。导致Reference注入为null. 
![image](https://user-images.githubusercontent.com/23161243/44505808-eb41c100-a6d5-11e8-811d-dbfaf68f3c3e.png)

**Comment by chutian52** [comment]
Dubbo默认是读取application.properties/application.yaml中的配置，Dubbo的解析是通过ConfigUtils来实现的。你可以写一个类集成EnvironmentPostProcessor，把Environment中的所有的Dubbo配置都写进来。
或者你可以使用Dubbo Spring Boot Project。最好是让你的EnvironmentPostProcessor执行在Config拉取之后，应该可以解决你的问题
