### ISSUE TITLE
Some problems were encountered while processing the POMs:

### ISSUE THREAD

**Issue by DreamHill** [apache/incubator-dubbo#2346]
Non-resolvable import POM: Failure to find org.apache.dubbo:dubbo-dependencies-bom:pom:2.7.0-SNAPSHOT 
in https://maven.aliyun.com/repository/public/ was cached in the local repository, resolution will not be reattempted until the update interval of alimaven has elapsed or updates are forced @ org.apache.dubbo:dubbo-parent:2.7.0-SNAPSHOT, G:\Einker\incubator-dubbo\pom.xml, line 152, column 25
 @

**Comment by ralf0131** [comment]
Hi,
2.7.0-SNAPSHOT has not been deployed to repository yet. Please build it locally.

**Comment by diecui1202** [comment]
Stay tuned pls.
