### ISSUE TITLE
Error running demo

### ISSUE THREAD

**Issue by yejunyu** [apache/incubator-dubbo#2350]
### Environment

* Dubbo version: master
* Operating System version: 4.9.0-deepin13-amd64 #1 SMP PREEMPT Deepin 4.9.57-1 (2017-10-19) x86_64 GNU/Linux
* Java version: 1.8.0_161

### Step to reproduce this issue
if i didn't write `<dubbo:provider server="netty4"></dubbo:provider>` in `dubbo-demo-provider.xml`,
this program will report an error

>https://github.com/apache/incubator-dubbo/tree/master/dubbo-demo/

If there is an exception, please attach the exception trace:

![](http://oqb4aabpb.bkt.clouddn.com/18-8-27/3496952.jpg)

**Comment by diecui1202** [comment]
In my local env, it works only with adding `-Djava.net.preferIPv4Stack=true` to vm args. 

@yejunyu u can check it again. Make sure your local repo is clean.

**Comment by diecui1202** [comment]
Pls. feel free to reopen if necessary.
