### ISSUE TITLE
dubbo 中文文档错别字

### ISSUE THREAD

**Issue by jacendfeng** [apache/incubator-dubbo#2351]
http://dubbo.apache.org/zh-cn/docs/user/references/xml/dubbo-reference.html
![image](https://user-images.githubusercontent.com/11593158/44638848-83e48380-a9eb-11e8-8b51-a5b610103ee3.png)

**Comment by carryxyh** [comment]
Hi, would u pls send a pr to fix it?

**Comment by ralf0131** [comment]
Please send a pull request to https://github.com/apache/incubator-dubbo-website
