### ISSUE TITLE
 Is it necessary to set the value of SPI?

### ISSUE THREAD

**Issue by freeseawind** [apache/incubator-dubbo#2398]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

Dubbo version: 2.6.2
Operating System version: win7
Java version: 1.8

### Step to reproduce this issue

阅读源码发现，每个代理实现类都会去判断默认实现

```
public class Protocol$Adaptive implements org.apache.dubbo.rpc.Protocol
{
    public void destroy()
    {
        throw new UnsupportedOperationException(
                "method public abstract void org.apache.dubbo.rpc.Protocol.destroy() of interface org.apache.dubbo.rpc.Protocol is not adaptive method!");
    }

    public int getDefaultPort()
    {
        throw new UnsupportedOperationException(
                "method public abstract int org.apache.dubbo.rpc.Protocol.getDefaultPort() of interface org.apache.dubbo.rpc.Protocol is not adaptive method!");
    }

    public org.apache.dubbo.rpc.Invoker refer(java.lang.Class arg0, org.apache.dubbo.common.URL arg1)
        throws org.apache.dubbo.rpc.RpcException
    {
        if (arg1 == null)
            throw new IllegalArgumentException("url == null");
        org.apache.dubbo.common.URL url = arg1;
        String extName = (url.getProtocol() == null ? "dubbo" : url.getProtocol());
        if (extName == null)
            throw new IllegalStateException("Fail to get extension(org.apache.dubbo.rpc.Protocol) name from url("
                    + url.toString() + ") use keys([protocol])");
        org.apache.dubbo.rpc.Protocol extension = (org.apache.dubbo.rpc.Protocol) ExtensionLoader
                .getExtensionLoader(org.apache.dubbo.rpc.Protocol.class).getExtension(extName);
        return extension.refer(arg0, arg1);
    }

    public org.apache.dubbo.rpc.Exporter export(org.apache.dubbo.rpc.Invoker arg0)
        throws org.apache.dubbo.rpc.RpcException
    {
        if (arg0 == null)
            throw new IllegalArgumentException("org.apache.dubbo.rpc.Invoker argument == null");
        if (arg0.getUrl() == null)
            throw new IllegalArgumentException("org.apache.dubbo.rpc.Invoker argument getUrl() == null");
        org.apache.dubbo.common.URL url = arg0.getUrl();
        String extName = (url.getProtocol() == null ? "dubbo" : url.getProtocol());
        if (extName == null)
            throw new IllegalStateException("Fail to get extension(org.apache.dubbo.rpc.Protocol) name from url("
                    + url.toString() + ") use keys([protocol])");
        org.apache.dubbo.rpc.Protocol extension = (org.apache.dubbo.rpc.Protocol) ExtensionLoader
                .getExtensionLoader(org.apache.dubbo.rpc.Protocol.class).getExtension(extName);
        return extension.export(arg0);
    }
}
```

**Comment by diecui1202** [comment]
@freeseawind Could u describe your problem more detailedly ?

**Comment by freeseawind** [comment]
dubbo里的服务扩展接口包含@SPI注解，但没有指定默认值，而是在Adaptive中指定，是否给@SPI注解指定默认值会更合理

**Comment by zonghaishang** [comment]
Existing logic should not be modified, no reasonable demand.
```
public static <T> ExtensionLoader<T> getExtensionLoader(Class<T> type) {
        if (!withExtensionAnnotation(type)) {
            throw new IllegalArgumentException();
        }
}
```
Just check that the interface belongs to SPI

**Comment by freeseawind** [comment]
@zonghaishang  不是改这个逻辑，而是改SPI
```
@Documented
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE})
public @interface SPI {

    /**
     * default extension name
     */
    String value() default "";

   //  改为 String value()；

}
```

**Comment by gudegg** [comment]
不指定就没有默认扩展，这并没有什么问题，不需要改。

**Comment by freeseawind** [comment]
@gudegg  问题是DUBBO在动态类里有代码去生成了默认

**Comment by carryxyh** [comment]
Hi, there are some problems with your understanding of SPI. The value in SPI refers to the default implementation. And withExtensionAnnotation is to determine whether there is a SPI annotation modification on a class. You can observe the ChannelHandler class, which is a typical extension class without a default implementation.
@freeseawind

**Comment by carryxyh** [comment]
So setting the SPI value to required is problematic, as @gudegg said.

**Comment by freeseawind** [comment]
if SPI value is not required why dymaic class Protocol$Adaptive check extension name like this
`
String extName = (url.getProtocol() == null ? "dubbo" : url.getProtocol());`

**Comment by gudegg** [comment]
@freeseawind  See ExtensionLoader createAdaptiveExtensionClassCode,it will produce different proxy codes according to different situations.

**Comment by freeseawind** [comment]
@gudegg I have read most of the implementations of dubbo.

**Comment by freeseawind** [comment]
@gudegg  createAdaptiveExtensionClassCode just implement dymaic proxy by service interface

**Comment by freeseawind** [comment]
@zonghaishang  dubbo 的SPI宗旨在于不依赖于容器时，如spring，对bean进行加载和管理，类似于Spring ioc的功能，从源码上来看，实现的是byName的方式

**Comment by carryxyh** [comment]
Yep, always implement on one way. But it is confused right?
The value of SPI means "default extension name". Can interface didn't have default extension?
I think it could.

A typical example is the ChannelHandler. For such extension points that do not have a default implementation.

**Comment by carryxyh** [comment]
I agree with @zonghaishang . At least we should not modify it at present. :)

**Comment by freeseawind** [comment]
@carryxyh  I find the code ChannelHandler when it use, It is not injected through @SPI

See  NettyClient.java :
```
    @Override
    protected void doOpen() throws Throwable {
        final NettyClientHandler nettyClientHandler = new NettyClientHandler(getUrl(), this);
        bootstrap = new Bootstrap();
        bootstrap.group(nioEventLoopGroup)
                .option(ChannelOption.SO_KEEPALIVE, true)
                .option(ChannelOption.TCP_NODELAY, true)
                .option(ChannelOption.ALLOCATOR, PooledByteBufAllocator.DEFAULT)
                //.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, getTimeout())
                .channel(NioSocketChannel.class);
```

**Comment by zonghaishang** [comment]
@freeseawind 

I have check your point , `org.apache.dubbo.common.extension.ExtensionLoader#getExtension` spi value is required. The actual usage habits will specify a name

**Comment by zonghaishang** [comment]
@freeseawind  Thank you very much for your contribution to dubbo, Welcome to submit pr

**Comment by freeseawind** [comment]
@zonghaishang  I down the release code .  but  miss some maven depency version like log4j2 jetty

**Comment by freeseawind** [comment]
@zonghaishang 

![image](https://user-images.githubusercontent.com/19760912/44897503-7b16e900-ad2e-11e8-8526-fe44e59e4cbb.png)

**Comment by freeseawind** [comment]
@zonghaishang I have never compile success once.

![image](https://user-images.githubusercontent.com/19760912/44897712-3a6b9f80-ad2f-11e8-9fe2-9eceb017c4d6.png)

![image](https://user-images.githubusercontent.com/19760912/44897725-48b9bb80-ad2f-11e8-8efa-2371e3cea261.png)

**Comment by carryxyh** [comment]
Hi, @freeseawind 
This is a good issue, thx for your issue first. :)

I think the reason for the SPI value is not necessarily required: First, the meaning of the SPI value is "default extension name", we should allow classes with no default extensions (ex: Merger, RouterFactory, ChannelHandler, etc.). Second, there is no need, because with @Adaptive annotations, we can still specify an extension implementation.
A doc can be found at @Adaptive annotation:

If default extension's name is not give on interface's {@link SPI}, then a name is generated from interface's class name with the...

Explain that the value of spi itself is designed to be non-required.

The above is my opinion.

**Comment by carryxyh** [comment]
@freeseawind 
Use SPI means "it can be used" into dubbo extension, not "it have to".
I can use channelHandler as spi, or not. :)

**Comment by freeseawind** [comment]
@carryxyh  I don't agree with you . I find the code ChannelHandler when it use, It is not injected through @SPI
see DubboProcotol.java

```
    private ExchangeServer createServer(URL url) {
        // send readonly event when server closes, it's enabled by default
        url = url.addParameterIfAbsent(Constants.CHANNEL_READONLYEVENT_SENT_KEY, Boolean.TRUE.toString());
        // enable heartbeat by default
        url = url.addParameterIfAbsent(Constants.HEARTBEAT_KEY, String.valueOf(Constants.DEFAULT_HEARTBEAT));
        String str = url.getParameter(Constants.SERVER_KEY, Constants.DEFAULT_REMOTING_SERVER);

        if (str != null && str.length() > 0 && !ExtensionLoader.getExtensionLoader(Transporter.class).hasExtension(str))
            throw new RpcException("Unsupported server type: " + str + ", url: " + url);

        url = url.addParameter(Constants.CODEC_KEY, DubboCodec.NAME);
        ExchangeServer server;
        try {
            server = Exchangers.bind(url, requestHandler);
        } catch (RemotingException e) {
            throw new RpcException("Fail to start server(url: " + url + ") " + e.getMessage(), e);
        }
        str = url.getParameter(Constants.CLIENT_KEY);
        if (str != null && str.length() > 0) {
            Set<String> supportedTypes = ExtensionLoader.getExtensionLoader(Transporter.class).getSupportedExtensions();
            if (!supportedTypes.contains(str)) {
                throw new RpcException("Unsupported client type: " + str);
            }
        }
        return server;
    }
```

important code :
`
server = Exchangers.bind(url, requestHandler);`

how it create 

`private ExchangeHandler requestHandler = new ExchangeHandlerAdapter()`

important thing ExchangeHandler  implements channelHandler

**Comment by carryxyh** [comment]
@freeseawind 
Use SPI means "it can be used" into dubbo extension, not "it have to".
I can use RouterFactory as:
`private static final RouterFactory routerFactory = ExtensionLoader.getExtensionLoader(RouterFactory.class).getAdaptiveExtension();`

But RouterFactory didn't have a spi value. I can just use @Adaptive and spi too.

**Comment by freeseawind** [comment]
@carryxyh  yet , without you use @SPI or @adaptive , it providers extension name. Why you add @SPI into interface,  may be you want use extension loader feture. you can  also inject without container manager like 
`ExchangeHandler requestHandler = new ExchangeHandlerAdapter()`

but if you  use extension loader you must provider default extension name, may be you can check dubbo source code. The order of lookup is：@adaptive @SPI

**Comment by carryxyh** [comment]
@freeseawind 
`阅读源码发现，每个代理实现类都会去判断默认实现`
It is incorrect. U can look at the code which create by RouterFactory.

Some interfaces have no default extensions. 
Dynamic adjustment is always better than hard code. 
Write value in Adaptive instead of spi, this is the real adaptive.

The default extension point is only the last level, not a prerequisite.

As you mean, you must have an existing default extension to use. And I mean, there is no default extension, you can also use it well(with Adaptive).

**Comment by freeseawind** [comment]
@carryxyh  you can try it . if you not provider URL key to extension name . How it work , if have not default SPI value.
I saw the RouterFactory code follow, it provider default value "null" :

```
    public org.apache.dubbo.rpc.cluster.Router getRouter(org.apache.dubbo.common.URL arg0)
    {
        if (arg0 == null)
            throw new IllegalArgumentException("url == null");
        org.apache.dubbo.common.URL url = arg0;
        String extName = url.getProtocol();
        if (extName == null)
            throw new IllegalStateException(
                    "Fail to get extension(org.apache.dubbo.rpc.cluster.RouterFactory) name from url(" + url.toString()
                            + ") use keys([protocol])");
        org.apache.dubbo.rpc.cluster.RouterFactory extension = null;
        try
        {
            extension = (org.apache.dubbo.rpc.cluster.RouterFactory) ExtensionLoader
                    .getExtensionLoader(org.apache.dubbo.rpc.cluster.RouterFactory.class).getExtension(extName);
        }
        catch (Exception e)
        {
            if (count.incrementAndGet() == 1)
            {
                logger.warn("Failed to find extension named " + extName
                        + " for type org.apache.dubbo.rpc.cluster.RouterFactory, will use default extension null instead.",
                        e);
            }
            extension = (org.apache.dubbo.rpc.cluster.RouterFactory) ExtensionLoader
                    .getExtensionLoader(org.apache.dubbo.rpc.cluster.RouterFactory.class).getExtension("null");
        }
        return extension.getRouter(arg0);
    }
```

**Comment by carryxyh** [comment]
If not, it will throw exception. But provide the key into url is the user thing.

That is what I said: The default extension point is only the last level, not a prerequisite.

And default value "null" means that there are no default extension for RouterFactory.

With this issue, I can tell u that SPI value is not need to be necessary. 
:)

**Comment by freeseawind** [comment]
@carryxyh  we talk about use extension. your opinion is not necessary , why dubbo source code check default value like this 
`String extName = (url.getProtocol() == null ? "dubbo" : url.getProtocol());`

that's not a good idea

**Comment by carryxyh** [comment]
first, not everytime, it didn't check in RouterFactory.
The default extension point is only the last level, not a prerequisite.(I said three times for this. :) )

Throwing an exception is obviously better than using the default value such as for RouterFactory.
It can tell user that RouterFactory didn't have a default extension, u should provide one.

If u make it necessary, what do you think is the default implementation for RouterFactory?

**Comment by freeseawind** [comment]
if you think this code is not idea please remove from source code (I said more times)
`String extName = (url.getProtocol() == null ? "dubbo" : url.getProtocol());`
I agree with not use hard code. so how to change it.

**Comment by carryxyh** [comment]
1. If it has a default extension:
     (1). user didn't provide -> use default.
     (2). user provided -> use provided one.
2. If not:
     (1). user didn't provide -> throw exception.
     (2). user provided -> use provided one.

`String extName = (url.getProtocol() == null ? "dubbo" : url.getProtocol());`
This is useful into case 1.

:)

**Comment by freeseawind** [comment]
@carryxyh  I know this logic. I ignore the code generate by reflect. so I think this is hard code. This is my mistake.

**Comment by carryxyh** [comment]
This is a good issue!
Welcome to dubbo community to discuss with us.
Thx for your contribution.
:)

**Comment by freeseawind** [comment]
I think can optimization byte code generate. When I want to customer my SPI. dubbo could not provider good way.

**Comment by carryxyh** [comment]
Get it.
I agree with u. The code readability here needs to be improved.
Maybe it will be better soon. :)
