### ISSUE TITLE
ReferenceConfig(dubbo://127.0.0.1:20880) is not DESTROYED when FINALIZ

### ISSUE THREAD

**Issue by valiantwu** [apache/incubator-dubbo#2400]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: xxx
* Operating System version: xxx
* Java version: xxx

### Step to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What is actually happen?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by carryxyh** [comment]
Hi, would you like to provide some details that will reproduce the problem?

**Comment by cvictory** [comment]
@valiantwu  can you describe how to reproduce the problem？

**Comment by valiantwu** [comment]
ReferenceConfig referenceConfig = new ReferenceConfig();
            referenceConfig.setApplication(applicationConfig);
//            referenceConfig.setId(inter);
            referenceConfig.setInterface(model);
//            referenceConfig.setInterface(inter);
            referenceConfig.setCheck(true);
            referenceConfig.setProtocol(System.getProperty("dubbo.protocol.name", "dubbo"));
            referenceConfig.setUrl(System.getProperty("dubbo.consumer.url", "dubbo://127.0.0.1:20880"));
            referenceConfig.setRegistry(registryConfig);
            referenceConfig.setConsumer(consumerConfig);
创建一个ReferenceConfig对象然后设置相应的值，运行会报这个错误哦

**Comment by carryxyh** [comment]
Hi, I can not reproduce this issue on my env.
Could u send your demo onto github and provide a link to us?
