### ISSUE TITLE
 Can Dubbo support network isolation between Consumer and Provider?

### ISSUE THREAD

**Issue by xiabobin** [apache/incubator-dubbo#2403]
咨询一下Dubbo是否满足以下需求、场景。

> 请大家忽略需求、场景的真实性，请大家就事论事

废话不多说。

### 需求描述

假设一台服务器命名为A，其IP为192.168.1.100，部署Dubbo Provider。另一台服务器命名为B，部署Dubbo Consumer。在A、B两台服务器之间使用“网闸”隔离，服务器B可以通过网闸IP：172.10.1.100映射到服务器A（192.168.1.100）上。此时Consumer无法调通Provider，因为Consumer通过注册中心获取的是Provider真实IP，而Consumer与Provider之间有网闸隔离，无法使用真实IP通讯，必须使用其他IP代理。那么此种场景Dubbo该如何处理。

请赐教。

**Comment by carryxyh** [comment]
I don't think this scene is currently supported if u have to use registry.
Maybe use explicit-target to solve this problem:
https://dubbo.incubator.apache.org/zh-cn/docs/user/demos/explicit-target.html

**Comment by carryxyh** [comment]
Hi, do u still have problem for this issue?
If not, we will close it soon.
@xiabobin

**Comment by zonghaishang** [comment]
Currently dubbo does not support registration of logical service identifiers， You can use @carryxyh  advice
