### ISSUE TITLE
.ConstraintDescriptorImpl' could not be instantiated

### ISSUE THREAD

**Issue by z499326979** [apache/incubator-dubbo#2407]
* Dubbo version: 2.6.2
* Operating System version: win7
* Java version: 1.8
开启配置：
dubbo.provider.validation = true

consumer端报错如下：
com.alibaba.com.caucho.hessian.io.HessianFieldException: org.hibernate.validator.internal.engine.ConstraintViolationImpl.constraintDescriptor: 'org.hibernate.validator.internal.metadata.descriptor.ConstraintDescriptorImpl' could not be instantiated

**Comment by carryxyh** [comment]
Would u pls to send the demo which can recreate the issue to github?
And provide the demo address, pls.

**Comment by ningyu1** [comment]
@z499326979  You can refer to the following ways
similar issue:  https://github.com/apache/incubator-dubbo/issues/1637
pr: https://github.com/apache/incubator-dubbo/pull/1708

**Comment by ymmzhp** [comment]
这个错误后来是怎么解决的？我也碰到这个报错
consumer端报错如下：
com.alibaba.com.caucho.hessian.io.HessianFieldException: org.hibernate.validator.internal.engine.ConstraintViolationImpl.constraintDescriptor: 'org.hibernate.validator.internal.metadata.descriptor.ConstraintDescriptorImpl' could not be instantiated
