### ISSUE TITLE
can i get consumer from provider

### ISSUE THREAD

**Issue by chenshun00** [apache/incubator-dubbo#2411]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.5.2(test)，but there are many different versions inside the company.
```
     <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>dubbo</artifactId>
            <version>2.5.2</version>
            <exclusions>
                <exclusion>
                    <artifactId>javassist</artifactId>
                    <groupId>org.javassist</groupId>
                </exclusion>
            </exclusions>
        </dependency>
```
* Operating System version: `uname -a`
```
Darwin tes.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
```
* Java version: java -version ，but there are many different versions（1.6，1.7） inside the company.
```
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
```

### Reason

The low version of dubbo does not provide elegant closure of the dubbo service network, so we are compatible with reflection, but now we don't know the number of consumers.

i can get provider bu using reflect,but can't get consumer. Thanks in advance. please 
forgive my lame English

**Comment by zonghaishang** [comment]
dubbo-2.6.3 support shtdown gracefully, please try use it: https://github.com/apache/incubator-dubbo/releases
Do you want to get all consumer calls for a particular provider?

**Comment by zonghaishang** [comment]
dubbo-2.6.3 support shtdown gracefully, please try use it: https://github.com/apache/incubator-dubbo/releases.
 If you just want to support graceful downtime, don't need to know consumers.

**Comment by chenshun00** [comment]
yeah , don't need to know consumers indeed , and i have found how to get the count about consumer,  thinks again. 😄
