### ISSUE TITLE
中文文档语意词调整（“轮循”应调整为“轮询”）

### ISSUE THREAD

**Issue by yxhsmart** [apache/incubator-dubbo#2422]
http://dubbo.apache.org/zh-cn/docs/user/references/xml/dubbo-reference.html
错误所在位置，左侧的菜单 ，“轮循”应调整为“轮询”
1、用户文档》成熟度》
2、示例》负载均衡》

**Comment by ralf0131** [comment]
Hi,

Would you please send a pull request to https://github.com/apache/incubator-dubbo-website?

Thanks!
