### ISSUE TITLE
用户文档中给出的分组聚合相关的示例代码404

### ISSUE THREAD

**Issue by chlsmile** [apache/incubator-dubbo#2430]
用户文档中给出的分组聚合相关的示例代码404

文档链接：https://dubbo.incubator.apache.org/zh-cn/docs/user/demos/group-merger.html

404链接：https://github.com/apache/incubator-dubbo/tree/master/dubbo-test/dubbo-test-examples/src/main/java/com/alibaba/dubbo/examples/merge

**Comment by diecui1202** [comment]
The correct link is https://github.com/dubbo/dubbo-samples/tree/master/dubbo-samples-merge

@chlsmile could u pls. send a PR to fix this? Thanks so much.

**Comment by chlsmile** [comment]
Already send a PR to fix
https://github.com/apache/incubator-dubbo-website/pull/129

@diecui1202

**Comment by satansk** [comment]
@chlsmile 可以在 PR 评论中将 issue 连接贴上，这样能直接引用 issue，在 issue 页面也能看到有 PR 引用它，非常直观。
