### ISSUE TITLE
dubbo-rpc-thrift ThriftCodec bug

### ISSUE THREAD

**Issue by andyyin** [apache/incubator-dubbo#244]
``` java
static final ConcurrentMap<Long, RequestData> cachedRequest =
            new ConcurrentHashMap<Long, RequestData>();
```
1. map元素没有删除，内存可能会爆
2. 解码是key是由不同的客户端生成的，可能会重复

**Comment by andyyin** [comment]
有人遇到吗

**Comment by ralf0131** [comment]
Hi,

ThriftCodec is deprecated since 2.7.0, please check out this project: https://github.com/dubbo/dubbo-rpc-native-thrift
