### ISSUE TITLE
Frequent register and unregister of services using Redis registry

### ISSUE THREAD

**Issue by Vensence** [apache/incubator-dubbo#2441]
-  I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
-  I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

本人第一次在GitHub发issue，如有不妥请大佬见谅
* Dubbo version: 2.6.2
* Operating System version: cent os 6
* Java version: 1.8

### Step to reproduce this issue
redis event: /dubbo/com.wehotel.rpcApi.ValidateApi/providers = register, dubbo version: 2.6.2,
redis event: /dubbo/com.wehotel.rpcApi.ValidateApi/providers = unregister, dubbo version: 2.6.2,
redis event: /dubbo/com.wehotel.rpcApi.ValidateApi/providers = register, dubbo version: 2.6.2,
redis event: /dubbo/com.wehotel.rpcApi.ValidateApi/providers = unregister, dubbo version: 2.6.2,
![image](https://user-images.githubusercontent.com/22963992/45068064-576ded00-b0f8-11e8-95b0-4b1d4c69ff22.png)

### Expected Result

请教大佬这个问题的可能原因是什么

### Actual Result

What is actually happen?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```
本来想添加一下label但是不知道怎么加

**Comment by diecui1202** [comment]
> 本人第一次在GitHub发issue，如有不妥请大佬见谅

@Vensence Welcome to dubbo community. That's good. Nothing to worry about.

Could u pls. provide a demo to reproduce this problem? U could attach u github repo here.

**Comment by diecui1202** [comment]
> 本来想添加一下label但是不知道怎么加

Maybe u have no permission to label until becoming a committer. :)

**Comment by playaround88** [comment]
@Vensence hi, does your service interface is end with * ? 
I have check the code, and find that when subscribe service interface is end with *，the expireExecutor will clean all registed service!

**Comment by Vensence** [comment]
@playaround88 well...nope, it seems like the problem is from the network. Cause the service goes fine in my local machine, but not in the remote machine. What Really strange is when I deploy it in the machine(like10.100.112.15), everything is fine, but when I deploy it in 10.100.120.21 the problem comes out, and the monitor can't get the provider either

**Comment by Vensence** [comment]
FYI:  the registry address is redis://10.100.112.26:6379

**Comment by Vensence** [comment]
I‘ve tried , well...problem still exists

**Comment by Vensence** [comment]
@playaround88 @diecui1202 I am wondering if the machine time isn't correct, would it cause the frequently register and unregister?

**Comment by Vensence** [comment]
guys, I've changed the machine time and the application went fine. But I still don't understand what cause the problem, apparently the service expired is according to the System.currentTimeMillis()

**Comment by Vensence** [comment]
yes it use System.currentTimeMillis() to determin the service is expired or not. According to the code the RedisRegistry has a expireFuture to check the service is expired or not every 30000ms(by default, and I use the default value), no matter the machine time is correct or not it should check every 30s, it couldn't be so frequently. I am really confusing now, these things flying around in my head for several days

**Comment by beiwei30** [comment]
it looks like there are two machines with the different time providing the same service.
