### ISSUE TITLE
Hope user manual can search by keyword

### ISSUE THREAD

**Issue by MLeft** [apache/incubator-dubbo#2442]
Noticed [Dubbo user manual](http://dubbo.apache.org/zh-cn/docs/user/quick-start.html) has no search button, it will be nice if support search by keyword

**Comment by lovepoem** [comment]
Hi,   @purple-force
As the author of https://github.com/purple-force/docsite-doc
Would you please  provider "Website local search" function for https://github.com/apache/incubator-dubbo-website

**Comment by carryxyh** [comment]
New issue in dubbo-website is here:
https://github.com/apache/incubator-dubbo-website/issues/133

close this one.
