### ISSUE TITLE
Wrapper的deal with get/set method的作用

### ISSUE THREAD

**Issue by 491311184** [apache/incubator-dubbo#245]
`dubbo-common/src/main/java/com/alibaba/dubbo/common/bytecode/Wrapper.java`
第292行开始，对方法名为getXXX ,setXXX,isXX,canXXX,hasXXX的特殊处理的作用是什么呢？

我现在遇到一个问题是，如果我的方法为void getXXX();的时候，会报
`compile error: getPropertyValue (Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object; in com.alibaba.dubbo.common.bytecode.Wrapper26: inconsistent stack height -1`
这样一个错误。

我理解我的方法定义及命名可能存在问题，但是我不理解这段特殊处理代码的作用，还请解答一下，谢谢！

**Comment by whiker** [comment]
getXXX()不能返回void, 可以返回lang下的Void呀

**Comment by chickenlj** [comment]
`void getXXX(); `, turns out you should never return void for a getter method when using javassist.
