### ISSUE TITLE
The sha512 hashes are missing the '*' marker that indicates

### ISSUE THREAD

**Issue by chickenlj** [apache/incubator-dubbo#2459]
Issues from previous RC still present in this RC:
=================================================

The sha512 hashes are missing the '*' marker that indicates they are
hashes for binary files rather than text files. Trivial issue. New RC
not required.

**Comment by satansk** [comment]
I'm happy to work on this, can you provide more information ? @chickenlj

**Comment by diecui1202** [comment]
From Mark:

> The sha512 hash is missing the '*' marker to indicate that this is a
binary file. Minor issue but one that was present on the previous
release and should have been fixed by now.

This issue must be fixed in 2.6.5.

**Comment by chickenlj** [comment]
I have sent an email to the dev mailing list for help.

**Comment by chickenlj** [comment]
This issue can be solved when packaging:

> https://linux.die.net/man/1/sha512sum
> 
> You want ‘-b

**Comment by cvictory** [comment]
I will modify the release.sh , and -b into shasum.
