### ISSUE TITLE
Fix UT bug in AbstractInterfaceConfigTest

### ISSUE THREAD

**Issue by chickenlj** [apache/incubator-dubbo#2461]
I see the following test failures:
 Oracle Java 8 update 181
 Ubuntu 18.04.1 LTS (fully patched)
 Maven 3.5.4

This fails consistently for me:
-------------------------------------------------------------------------------
Test set: com.alibaba.dubbo.config.AbstractInterfaceConfigTest
-------------------------------------------------------------------------------
Tests run: 38, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.119
sec <<< FAILURE! - in com.alibaba.dubbo.config.AbstractInterfaceConfigTest
checkApplication1(com.alibaba.dubbo.config.AbstractInterfaceConfigTest)
Time elapsed: 0.006 sec  <<< FAILURE!
junit.framework.ComparisonFailure: expected:<10[0]> but was:<10[]>
	at
com.alibaba.dubbo.config.AbstractInterfaceConfigTest.checkApplication1(AbstractInterfaceConfigTest.java:90)

I note that this test has been observed to fail for other community
members in earlier RCs.

I can recreate this failure on the command line but not in an IDE.

Whether this failure is significant enough to halt the release is
something for those more knowledgeable about Dubbo than I to decide.

**Comment by diecui1202** [comment]
#2302 
has been merged to 2.6.x

**Comment by playaround88** [comment]
hi, why most of commitor use mac or linux, windows is OK?
I have run 2.6.3 release UT on windows10 and lot of errors occurred!

**Comment by diecui1202** [comment]
@playaround88 pls. issue all of the failed tests. Thanks.
