### ISSUE TITLE
dubbo doesn't work with spring boot devtool

### ISSUE THREAD

**Issue by kiansoung** [apache/incubator-dubbo#2466]
dubbo和spring-boot热部署冲突问题

使用spring-boot-devtools部署，导致dubbo调用失败，

```
com.alibaba.dubbo.rpc.RpcException: Failed to invoke remote proxy method getAll to registry://127.0.0.1:2181/com.alibaba.dubbo.registry.RegistryService?application=provider&dubbo=2.5.3&export=dubbo%3A%2F%2F10.0.75.1%3A20880%2Fcom.neo.facade.UseServiceFacade%3Fanyhost%3Dtrue%26application%3Dprovider%26dubbo%3D2.5.3%26interface%3Dcom.neo.facade.UseServiceFacade%26methods%3DgetAll%2CgetOne%2Cupdate%2Cinsert%2Cdelete%26pid%3D2224%26revision%3D1.0.0%26side%3Dprovider%26timestamp%3D1526971274301%26version%3D1.0.0&pid=2224&registry=zookeeper×tamp=1526971274290, cause: java.lang.ClassCastException: com.neo.service.UserService cannot be cast to com.neo.service.UserService
```

总是报`cause: java.lang.ClassCastException: com.neo.service.UserService cannot be cast to com.neo.service.UserService`错误

去掉spring-boot-devtools依赖时，可以正常使用

**Comment by zonghaishang** [comment]
@kiansoung Thank you very much for your feedback. Please provide a github address to reproduce the problem, I think it may be a problem with the classloader

**Comment by beiwei30** [comment]
Looks like spring boot devtool leverages classloader for hot deployment. Here's one relevant discussion:  https://github.com/spring-projects/spring-boot/issues/7331

**Comment by diecui1202** [comment]
Feel free to reopen if necessary.
