### ISSUE TITLE
关于provider和reference的group属性配置问题

### ISSUE THREAD

**Issue by aloneshun** [apache/incubator-dubbo#2469]
<dubbo:service>和<dubbo:reference>的group缺省值默认是什么？ 如果同时暴露一个接口的两个实现类， <dubbo:service>中一个设置group属性，另一个不设置， 那么<dubbo:reference> 是不是同样需要一个设置group属性与service相同， 另一个不需要设置。 是不是这样就可以调用正确？

**Comment by iyokka** [comment]
Group 不配置的话就为空

group必须一致才能相互调用，你说的对

**Comment by zonghaishang** [comment]
@aloneshun you are right.
