### ISSUE TITLE
There are several XML/XSD errors reported on dubbo-config-spring project.

### ISSUE THREAD

**Issue by elmar-chen** [apache/incubator-dubbo#2471]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: master branch, latest code as of 9/8/2018.
* Operating System version: not os specific 
* Java version: 1.8

### Step to reproduce this issue
1. Checkout the latest code, using git clone. 
2. import all projects as maven projects in eclipse. 
3. Do a full build

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

There should be no validation error

### Actual Result
There are several xml/xsd validation errors reported on “dubbo-config-spring” project:

Description	Resource	Path	Location	Type
cvc-complex-type.2.2: Element 'name' must have no element [children], and the value must be valid.	web-fragment.xml	/dubbo-config-spring/src/main/resources/META-INF	line 5	XML Problem
cvc-elt.1: Cannot find the declaration of element 'beans'.	provider-nested-service.xml	/dubbo-config-spring/src/test/resources/org/apache/dubbo/config/spring	line 22	XML Problem
cvc-pattern-valid: Value 'dubbo-fragment' is not facet-valid with respect to pattern '($|_|\p{L})(\p{L}|\p{Nd}|_|$)*' for type 'null'.	web-fragment.xml	/dubbo-config-spring/src/main/resources/META-INF	line 5	XML Problem
Referenced file contains errors (http://dubbo.apache.org/schema/dubbo).  For more information, right click on the message in the Problems View and select "Show Details..."	annotation-consumer.xml	/dubbo-config-spring/src/test/resources/org/apache/dubbo/config/spring	line 1	XML Problem
src-resolve: Cannot resolve the name 'beans:property' to a(n) 'element declaration' component.	dubbo.xsd	/dubbo-config-spring/src/main/resources/META-INF	line 1106	XML Schema Problem
src-resolve: Cannot resolve the name 'beans:property' to a(n) 'element declaration' component.	dubbo.xsd	/dubbo-config-spring/src/main/resources/META-INF/compat	line 1112	XML Schema Problem
![image](https://user-images.githubusercontent.com/1620432/45254268-2582b200-b3a8-11e8-8c81-af517d1bc37f.png)

What is actually happen?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by elmar-chen** [comment]
PS: there is a grammar error in the issue template. "What is actually happen?" should have been: what is actually happen**ing**?

**Comment by zonghaishang** [comment]
![image](https://user-images.githubusercontent.com/15549777/45360981-94a81280-b603-11e8-8f9c-c86e6d16d79e.png)
I am using intellij idea, without any errors or warnings， Which eclipse version are you using?

**Comment by elmar-chen** [comment]
Eclipse Java EE IDE for Web Developers.

Version: Oxygen.2 Release (4.7.2)
Build id: 20171218-0600

**Comment by sevencd** [comment]
I also using intellij idea,without any errors,maybe it is eclipse's bug

**Comment by elmar-chen** [comment]
@sevencd I seriously doubt that whether did you ever try to validate the xml/xsd. 
Did you try to right click the file and choose "Validate"?
![image](https://user-images.githubusercontent.com/1620432/45485791-72410100-b78b-11e8-95b7-1f5bf75f401d.png)

**Comment by beiwei30** [comment]
@elmar-chen, good catch. 

I tried to validate these files in Intellij Idea. I agree we should fix issue in web-fragment.xml since the value in `<name>` element is invalid.

But for other files: dubbo.xsd, provider-nested-service.xml, annotation-consumer.xml, Intellij idea doesn't report any warning or error. 

Intellij idea is smart enough to validate these files against the local schema, instead of requiring one explicit schema location specified.

I think we can simply ignore other files, but fix web-fragment.xml only. What do you think?

**Comment by elmar-chen** [comment]
@beiwei30, well, that's up to you. I'll modify the pr.

**Comment by beiwei30** [comment]
@elmar-chen I am fine with specify schema location in the target xml. It's no harm and should help eclipse users. Do you mind to initial a discussion on dev@dubbo.apache.org?

**Comment by elmar-chen** [comment]
@beiwei30 - I'll do that. For the mean while, I will modify the current pr to include just web-fragment.xml and raise another one if the discussion ends with a yes about adding the schemaLocation.

**Comment by laoqie** [comment]
@elmar-chen Sure, pls. do it, though I am now lean to add schema location after I realize it's necessary since it will help on dev experience for eclipse user. Let's see what other people say.

**Comment by beiwei30** [comment]
@elmar-chen Sure, pls. do it, though I am now lean to add schema location after I realize it's necessary since it will help on dev experience for eclipse user. Let's see what other people say.

**Comment by beiwei30** [comment]
not valid bug any longer, since we remove the web-fragment.xml completely.
