### ISSUE TITLE
dubbo:registry  dubbo:registery   不一致

### ISSUE THREAD

**Issue by hhzhi** [apache/incubator-dubbo#2485]
resource/META-INFO.spring/dubbo-demo-provider.xml
修改其中的dubbo:registery，替换成真实的注册中心地址，推荐使用zookeepe

代码中为

<dubbo:registry address="multicast://224.5.6.7:1234"/>

**Comment by zonghaishang** [comment]
The demo is as simple as possible, using zookeeper to introduce unnecessary configuration
