### ISSUE TITLE
dubbo  provider服务延迟收到请求

### ISSUE THREAD

**Issue by ranxizhaozhi** [apache/incubator-dubbo#2486]
现象：
dubbo  consumer发起请求，但provider过了很久才收到请求，有时会延迟几秒，有时会延迟十几秒,
比如，consumer发起请求的时间为2018-08-08 08:08:08.000，provider收到该请求的时间为2018-08-08 08:08:20.000

可以确定的是：
1、网络没有问题
2、未配置重试机制
3、provider线程池fixed，无任务队列
4、timeout为10s
provider服务处理较慢（调老系统接口），机器压力较大，会出现Thread pool is EXHAUSTED

谁能提供解决思路？

**Comment by www1350** [comment]
优化。或者加机器。这和dubbo本身无关。。。

**Comment by zonghaishang** [comment]
@ranxizhaozhi please login telnet and invoke `status -l`
step1: `telnet localhost 20880`(dubbo protocol port)
step2: type `status -l`  and copy past here.

**Comment by ranxizhaozhi** [comment]
@zonghaishang 这样看过，但看不出什么异常，现在要找到这个原因，可以提供什么思路吗？

**Comment by beiwei30** [comment]
@ranxizhaozhi 

Pls. paste the relevant information from dubbo.log here. What I suggest is to try to find out when the request is sent out to the network on the client side, and when this request is received from the network on the server side.

It would be helpful if you can add more debugging log on netty layer.

I close this issue for now, feel free to reopen it once you get more details or believe it is dubbo bug.

**Comment by jefferson-chern** [comment]
> 现象： dubbo consumer发起请求，但provider过了很久才收到请求，有时会延迟几秒，有时会延迟十几秒, 比如，consumer发起请求的时间为2018-08-08 08:08:08.000，provider收到该请求的时间为2018-08-08 08:08:20.000
> 
> 可以确定的是： 1、网络没有问题 2、未配置重试机制 3、provider线程池fixed，无任务队列 4、timeout为10s provider服务处理较慢（调老系统接口），机器压力较大，会出现Thread pool is EXHAUSTED
> 
> 谁能提供解决思路？

您好 最后找到原因了吗？我们也遇到了，使用的dubbo版本是2.7.15
