### ISSUE TITLE
Provide more meaningful binary releases.

### ISSUE THREAD

**Issue by chickenlj** [apache/incubator-dubbo#2491]
Provide more meaningful binary releases: 
Currently, the binary releases are only repackaging of source jars[1] which makes no sense to users, instead, I think we should provide some well-packaged demo projects and scripts so that users can quickly experience Dubbo.

1. https://www.apache.org/dyn/closer.cgi?path=incubator/dubbo/2.6.3/apache-dubbo-incubating-2.6.3-bin-release

**Comment by ningyu1** [comment]
package a sample in binary releases, right?
experience it in a "java-jar" way.

**Comment by diecui1202** [comment]
Maybe start.dubbo.io would be better.

**Comment by chickenlj** [comment]
> package a sample in binary releases, right?

@ningyu1 Yes, that's what I mean. Some packaged jar and starting scripts can be a good choice. Facilitating user usage as much as possible.

**Comment by chickenlj** [comment]
@ningyu1 Do you want to give it a try? I am fully engaged in 2.7.0 these days, and would not available for this task until 2.7.0 is released.

**Comment by chickenlj** [comment]
Currently, the binary release is packaged from the [dubbo-distribution](https://github.com/apache/incubator-dubbo/tree/master/dubbo-distribution) module, I think packaging dubbo-demo or adding an extra sample module would all be ok, u can also try to  figure out a better way.

**Comment by ningyu1** [comment]
@chickenlj I am happy to try, but I have been busy recently and need to wait for some time.

**Comment by chickenlj** [comment]
> @chickenlj I am happy to try, but I have been busy recently and need to wait for some time.

Thank you for the attention, you are welcome whenever you get some time. 

Now, I will move this one to the 'some day' milestone.
