### ISSUE TITLE
消费端多个dubbo配置文件

### ISSUE THREAD

**Issue by OhunterO** [apache/incubator-dubbo#250]
最近项目由于需求，配置了多个dubbo配置文件，启动时候报错
【Caused by: java.lang.IllegalStateException: Duplicate application configs:】
at com.alibaba.dubbo.config.spring.ReferenceBean.afterPropertiesSet(ReferenceBean.java:104)
看了下源码，以下报错的地方是不是不允许一个项目中出现多个配置文件

for (ApplicationConfig config : applicationConfigMap.values()) {
                    if (config.isDefault() == null || config.isDefault().booleanValue()) {
                        if (applicationConfig != null) {
                            throw new IllegalStateException("Duplicate application configs: " + applicationConfig + " and " + config);
                        }
                        applicationConfig = config;
                    }
                }

**Comment by helloworldss** [comment]
已解决。去掉application name，保留一个就行了
