### ISSUE TITLE
Prompted Maven update is causing a malfunction to my Repository Loader - HELP!!!

### ISSUE THREAD

**Issue by RLHankerson** [apache/incubator-dubbo#2503]
Hello,

I received a pop message to update to the newest version of Maven.  
I updated to the newest version and now my project seems to be malfunctioning. 
Rather than updating the features located in the folder of the initial path, it seems as though
Maven created an entirely new folder.  

After running the update, the variable was no longer located in the environment.
The bin folder was no longer visible from the original location that received the
initial download and install.  However, the new folder created after the recent update
displayed the bin folder.

I added the updated Maven variable and bin folder to the Environment.
Now, I receive the following errors.  Please email me via RachelHankerson@InternationalPROOFSystems.com
or call 314-452-6880 if you are able to provide any assistance. 

-Doomph.update.url=http://download.eclipse.org/oomph/updates/milestone/latest
-Doomph.redirection.index.redirection=index:/->http://git.eclipse.org/c/oomph/org.eclipse.oomph.git/plain/setups/

Regards, 
Rachel Hankerson

**Comment by cvictory** [comment]
I donot know what happened to you.   And I cannot find the error log.

Is this related to dubbo?

**Comment by beiwei30** [comment]
I think you file issue at wrong project. You may need to either take a look at [maven](https://maven.apache.org) or [Eclipse Oomph project](https://projects.eclipse.org/projects/tools.oomph), I guess.
