### ISSUE TITLE
请问自定义 Filter 支持打包在 jar 包里面使用吗？

### ISSUE THREAD

**Issue by kiwiflydream** [apache/incubator-dubbo#2510]
自定义 Filter 实现，在项目里面直接使用没有问题。但是打包成 jar 包，别的项目依赖就发现这个 Filter 无效了。请问是否还其它需要配置的地方。可以像 dubbo 原生自带的 Filter 那样可以被依赖使用。

**Comment by zonghaishang** [comment]
@kiwiflydream please read doc: http://dubbo.apache.org/zh-cn/docs/dev/impls/filter.html
Create a directory and file `META-INF/dubbo/com.alibaba.dubbo.rpc.Filter` in your project.
```text
META-INF/dubbo/com.alibaba.dubbo.rpc.Filter：
```
Then append a line to the file `com.alibaba.dubbo.rpc.Filter`:
```text
xxx=com.xxx.XxxFilter
```

`xxx` is your spi name, `com.xxx.XxxFilter` is your filter impl.

**Comment by kiwiflydream** [comment]
@zonghaishang 感谢回复，我是按文档进行的操作，Filter代码在项目中没有问题，但是打成 jar，给别的项目使用，不能使用，无论spi 的配置文件在 jar 里，还是在当前使用的项目里都不生效，看描述跟这个issues 有点像，[#2507](https://github.com/apache/incubator-dubbo/issues/2507)

**Comment by EdwardLee03** [comment]
@kiwiflydream Dubbo 版本是多少？`dubbo-2.5.8`没有这个问题。
