### ISSUE TITLE
Failfast config problem

### ISSUE THREAD

**Issue by freeseawind** [apache/incubator-dubbo#2511]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.2
* Operating System version: win7
* Java version: 1.8

### Steps to reproduce this issue

1. 启动两个服务提供者
2. 对其中一个服务提供者设置断点使其不响应客户端
3. 启动服务消费者消费服务

#### 服务消费者代码

```
@Reference(loadbalance = "random", cluster = "failfast", retries = 2)
private DemoService failFastService;

@Test
public void testFail()
{
      String str = failFastService.sayHello("freeseawind");
       System.out.println(str);
}
```
##### 服务提供者示例截图

![image](https://user-images.githubusercontent.com/19760912/45597745-2f895e00-ba03-11e8-8b06-35bfb99570c7.png)

问题重现工程地址：https://github.com/freeseawind/copycat-dubbo

### Expected Result

调用失败后立即结束

### Actual Result

随机重试了服务消费者，日志显示的是FailOver调用失败而不是Failfast

![image](https://user-images.githubusercontent.com/19760912/45597823-05846b80-ba04-11e8-97ce-8bb5ef4fac2e.png)

@carryxyh

**Comment by zonghaishang** [comment]
![image](https://user-images.githubusercontent.com/15549777/45690659-786b1f00-bb89-11e8-98c9-31a0e65d55e5.png)

The annotation uses the cache internally, using the same instance

**Comment by freeseawind** [comment]
你可以注释掉failOverService的注解 @zonghaishang  @carryxyh

**Comment by zonghaishang** [comment]
I changed to the correct value, the instance is still wrong, it should be an annotated bug.

**Comment by zonghaishang** [comment]
The same interface annotation has a cache, comment the following code:

```
public class ConsumerApplication
{
    //@Reference
    // private DemoService demoService;
    
    public static void main(String[] args)
    {
        SpringApplication.run(ConsumerApplication.class, args);
    }
    
    //@RequestMapping("/a")
    //@ResponseBody
    //public String sayHello()
    //{
    //    return demoService.sayHello("freeseawind");
    //}
}
```
