### ISSUE TITLE
重启dubbo provider的时候,能否避免consumer请求的失败

### ISSUE THREAD

**Issue by jackzhangyk** [apache/incubator-dubbo#2514]
在重启dubbo provider的时候,现有的停机策略为
 
- 停止时，先标记为不接收新请求，新请求过来时直接报错，让客户端重试其它机器。
 - 然后，检测线程池中的线程是否正在运行，如果有，等待所有线程执行完成，除非超时，则强制关闭。

用客户端重试的方式来进行服务可用性的保证,但这会引起一些问题

1. 部份操作不允许重试,这样操作就会失败
1. 可能会因此请求失败,引起不必要的报警,影响运维

是否有可能,在停机的时候,先从注册中心摘除掉注册信息,确保consumer首先感知到服务下线,从而不再发布流量,然后provider服务停留一段时间,确保正在执行的服务已经执行完毕,然后再关机
这种策略方式是不是会更优雅一些

**Comment by carryxyh** [comment]
Hi,
I have check the code(not debug yet).
Now the dubbo is doing the same thing as you said at the end of the server.

U can check the class:
org.apache.dubbo.registry.integration.RegistryProtocol.DestroyableExporter

**Comment by carryxyh** [comment]
If there is something wrong with my understanding, please let me know. Thx. 
:)

**Comment by jackzhangyk** [comment]
OK I will check it right now.Thanks

**Comment by zonghaishang** [comment]
@jackzhangyk 请问你使用哪个dubbo版本？
在dubbo2.6.3+版本，优雅停机问题已经修复，处理逻辑：
1. 服务端下掉注册中心数据，客户端感知服务下线
2. 如果注册中心有延迟，会立即受到readonly事件，下次不会再掉用这台机器，当前已经调用的会处理完

我们公司内部优雅停机使用修复过的版本，已经正常运行了3个月+了，应该没有你说的问题。

**Comment by carryxyh** [comment]
Hi @jackzhangyk 
please check the code. As @zonghaishang  said, this problem has been fixed. If there is still a problem, reopen this issue.
Thx. :)

**Comment by jackzhangyk** [comment]
@zonghaishang 多谢答复,之前用的是2.6.1,升级为2.6.3后,我们测试了下,通知客户端服务下线功能没有问题,客户端不会再发送请求过来.但是貌似在rest协议下,优雅停机时长参数dubbo.service.shutdown.wait貌似不起作用,我们demo设置的数值为30s,测试provider阻塞请求超过30s,貌似不到kill命令发出后,不到30s即被强制停机,在dubbo协议下没有问题,不知道是不是配置问题,明天再详细测试下;
