### ISSUE TITLE
Remove getSpringContext() from org.apache.dubbo.config.spring.ServiceBean

### ISSUE THREAD

**Issue by beiwei30** [apache/incubator-dubbo#2516]
org.apache.dubbo.config.spring.ServiceBean#getSpringContext looks like a hack, we need to remove it.

**Comment by zonghaishang** [comment]
@beiwei30 Should not delete it.

I found it was used here:

`org.apache.dubbo.config.spring.status.DataSourceStatusChecker#check` and  `org.apache.dubbo.config.spring.status.SpringStatusChecker#check`
