### ISSUE TITLE
Can we make the bom and all module become the child module of dubbo-parent?

### ISSUE THREAD

**Issue by chickenlj** [apache/incubator-dubbo#2519]
mvn versions:set versions:commit -DprocessAllModules=true -DnewVersion=$next_version

**Comment by chickenlj** [comment]
both 2.6.x and master need this change.

**Comment by zonghaishang** [comment]
Which module of the master branch should be changed?

**Comment by chickenlj** [comment]
I saw the master branch has already changed and since 2.6.x is a maintenance branch, I tend to keep it not change.

https://github.com/apache/incubator-dubbo/blob/6938d487a388cc8cd0a2bc8740fe9ee8d378767e/dubbo-all/pom.xml#L19

**Comment by chickenlj** [comment]
Will be released on 2.7.0
