### ISSUE TITLE
我用mule去Java代码里调用dubbo客户端，出现问题！mule的容器是glass fish

### ISSUE THREAD

**Issue by ahu0605** [apache/incubator-dubbo#252]
JerseyUriBuilder 和 RPC 调用时转型ResteasyUriBuilder 冲突，我的解决方法JerseyUriBuilder继承ResteasyUriBuilder ，感觉不够优雅，有好的方案吗？

**Comment by kimmking** [comment]
dubbox是基于resteasy的

**Comment by xkcoding** [comment]
@ahu0605 请问现在怎么解决的呢？

**Comment by ralf0131** [comment]
Hi, the latest Dubbo has supported REST, which is based on resteasy.

Please check the latest code.

I am closing this issue now, please feel free to reopen it if it still exists.
