### ISSUE TITLE
Dubbo优雅关机

### ISSUE THREAD

**Issue by Super4You** [apache/incubator-dubbo#2524]
### 关于2.6.3版本优雅关机问题
你好：
* 1.经过测试DubboProtocol在关机时在此协议中是独立实现了的https://github.com/apache/incubator-dubbo/issues/2514 中提到org.apache.dubbo.registry.integration.RegistryProtocol.DestroyableExporter 这个类为任何协议使用时可以做到优雅关机。
* 2.在新版本中debug时发现DestroyableExporter的unexport()方法从没被调用到，追溯到上游代码发现在org.apache.dubbo.bootstrap.DubboBootstrap中registerServiceConfig(ServiceConfig)在全局中没任何调用，serviceConfigList始终为初始化状态，从而在DubboBootstrap.stop()进行关机时，应用启动暴露接口返回的DestroyableExporter没有任何代码去调用其unexport()进行关机前的取消注册与订阅操作以及等待用户设置dubbo.service.shutdown.wait时间操作。

### 以下为DubboBootstrap类截图
![image](https://user-images.githubusercontent.com/25604732/45725932-c4e94580-bbef-11e8-8a93-0282b3749a0c.png)

![image](https://user-images.githubusercontent.com/25604732/45725942-d599bb80-bbef-11e8-8e0e-ef79b543e20a.png)

* 3.水平有限，不知道是我没找到相应的代码或配置，还是有其他问题，请指教一下，谢谢。

### Environment

* Dubbo version: 2.6.3
* Operating System version: mac ox
* Java version: 1.8

**Comment by zonghaishang** [comment]
@Super4You 

I checked the code，your point of view is correct.

The current graceful shutdown core logic is triggered by the `shutdownHook.destroyAll`.

**Comment by Super4You** [comment]
@zonghaishang 
感谢您的回复，意思就是rest与hessian等协议在设置了dubbo.service.shutdown.wait参数是无效的？DestroyableExporter这个类目前没有发挥其功能么？如果是这样后边版本会完善这个点么？
