### ISSUE TITLE
how to support websocket

### ISSUE THREAD

**Issue by bgping** [apache/incubator-dubbo#2530]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.1
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

how config dubbo(x) to support websocket,I've tried many methods, but didn't work.

don't know how to config rest easy to support it.

**Comment by zonghaishang** [comment]
Dubbo does not currently support websocket, welcome to submit pr, you can check netty includes websocket codec support.

netty websocket: `https://github.com/netty/netty/tree/4.1/codec-http/src/main/java/io/netty/handler/codec/http/websocketx`
