### ISSUE TITLE
Increase the schedule frequency of HeartbeatTask.

### ISSUE THREAD

**Issue by chickenlj** [apache/incubator-dubbo#2537]
Here is how heartbeat works in Dubbo:
Heartbeat scheduler will schedule HeartbeatTask in every `heartbeat` time, when being scheduled, HeartbeatTask will internally continue to check the necessity of sending a heartbeat event (only send when it find that the idle interval `>heartbeat`).
Consider different combinations of these two intervals: schedule interval and idle interval, we may have a chance of idle for `2*heartbeat` on a wire without any request/response or heartbeat event being sent.

Though the timeout interval in Dubbo is `3*heartbeat`, and `2*heartbeat` idle would not mislead Dubbo to terminate the connection, we may need to increase the frequency of the scheduler to make it more accurate.

**Comment by chickenlj** [comment]
https://github.com/apache/incubator-dubbo/blob/cd60e58e1a579749c89c6ac8ddb39f8e8e894ef5/dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeClient.java#L186

**Comment by carryxyh** [comment]
Hi, I will start a work on it.
I plan to use hashwheeltimer to make each client's heartbeat more frequent.
What's your opinion?

**Comment by carryxyh** [comment]
Close via https://github.com/apache/incubator-dubbo/pull/2658.
