### ISSUE TITLE
provider service register version incorrect

### ISSUE THREAD

**Issue by yuqichou** [apache/incubator-dubbo#2542]
### Environment

* Dubbo version: 2.6.3
* Operating System version: win
* Java version: 1.8.0_73

### Steps to reproduce this issue

1. starting provider

### Expected Result

regist 2.6.3 version

### Actual Result

the actual regiser url is:  dubbo://XXXX?**dubbo=2.0.2** ...

#### 备注
当provider注册service时，注册url中传的dubbo 版本号不正确，在注册中心里看到的版本号也不对，传了错误的2.0.2

**Comment by zonghaishang** [comment]
开发环境里面？

**Comment by zonghaishang** [comment]
嗯，在release版本不会有这个问题

**Comment by zonghaishang** [comment]
@chenlushun 这个代表的是协议版本，不是发布版本

**Comment by zonghaishang** [comment]
refer: org.apache.dubbo.config.ServiceConfig#doExportUrlsFor1Protocol

```
    private void doExportUrlsFor1Protocol(ProtocolConfig protocolConfig, List<URL> registryURLs) {
        String name = protocolConfig.getName();
        if (name == null || name.length() == 0) {
            name = "dubbo";
        }

        Map<String, String> map = new HashMap<String, String>();
        map.put(Constants.SIDE_KEY, Constants.PROVIDER_SIDE);
        map.put(Constants.DUBBO_VERSION_KEY, Version.getProtocolVersion());
        ...
```
