### ISSUE TITLE
Dubbo multiple groups, just call the first group

### ISSUE THREAD

**Issue by 653945222** [apache/incubator-dubbo#2544]
Providers have more than one group,
When the client calls grouped into * specified,
But every time can only call in the same group
I view the source, discover the cause of the problem
![image](https://user-images.githubusercontent.com/18380553/45870168-d764aa00-bdbc-11e8-8b09-68e804bc5f5e.png)

Is this a problem?
Disable the first group of service, also do not take effect, still call the first service

**Comment by diecui1202** [comment]
Same question with #2550 ?

**Comment by carryxyh** [comment]
If you don't specify merger=true or something else, then the Consumer will only call a group.
You can get more info from here:
http://dubbo.apache.org/zh-cn/docs/user/demos/group-merger.html
