### ISSUE TITLE
Logical Error in ForkingClusterInvoker?

### ISSUE THREAD

**Issue by shuaijunlan** [apache/incubator-dubbo#2547]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.0-SNAPSHOT
### Steps to reproduce this issue

[Source code Fragment](https://github.com/apache/incubator-dubbo/blob/7f926d9991ba69dba25b56925e4cc5ffcdf50afa/dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/ForkingClusterInvoker.java#L68-L75):
```java
for (int i = 0; i < forks; i++) {
    // TODO. Add some comment here, refer chinese version for more details.
    Invoker<T> invoker = select(loadbalance, invocation, invokers, selected);
    if (!selected.contains(invoker)) {
        //Avoid add the same invoker several times.
        selected.add(invoker);
    }
}
```
When `selected list` contains invoker, it will continue loop, it may result in the size of `selected list` less than `forks`.

**Comment by diecui1202** [comment]
@shuaijunlan the `select` method takes `selected` as a parameter, so that the selected invoker is a new invoker, not in the `selected` list.

**Comment by diecui1202** [comment]
Feel free to reopen if necessary.

**Comment by shuaijunlan** [comment]
@diecui1202 If the selected invoker is a new invoker, so that we can remove the `if-statement`, do you think about it?
