### ISSUE TITLE
dubbo-demo中不能导入<groupId>org.apache.dubbo</groupId>相关的依赖

### ISSUE THREAD

**Issue by DonkeyHu** [apache/incubator-dubbo#2548]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### 如题
- 在阿里云仓库或者maven仓库中根本找不到<groupId>org.apache.dubbo</groupId>下相关的依赖啊，只能找到<groupId>com.alibaba</groupId>下的依赖啊
- 尝试对着这个官方例子练习，一直拉不下jar...

**Comment by lovepoem** [comment]
The version 2.7.x have not been released, you can  find samples from https://github.com/dubbo/dubbo-samples now

**Comment by DonkeyHu** [comment]
ok, thanks your advice
