### ISSUE TITLE
coding rules

### ISSUE THREAD

**Issue by wangnimaa** [apache/incubator-dubbo#2553]
可不可以规范一下编码规则
![image](https://user-images.githubusercontent.com/18657682/45999303-dd69cc00-c0d7-11e8-877a-d037c8f79b57.png)

**Comment by ralf0131** [comment]
Hi, you are right, would you please send pull request to fix them?

**Comment by wangnimaa** [comment]
> Hi, you are right, would you please send pull request to fix them?

ok

**Comment by zonghaishang** [comment]
这个规范对dubbo只适用部分，像author不允许出现的

**Comment by wangnimaa** [comment]
> 这个规范对dubbo只适用部分，像author不允许出现的

好的
