### ISSUE TITLE
org.apache.dubbo.common.utils.ConfigUtils#loadProperties(java.lang.String, boolean, boolean) miss windows scene

### ISSUE THREAD

**Issue by SuperDubbo** [apache/incubator-dubbo#2557]
### Environment

* Dubbo version: dubbo-2.6.4
* Operating System version: windows 10
* Java version: JDK1.8

When run the testcase(com.alibaba.dubbo.config.AbstractInterfaceConfigTest#checkApplication1) in windows environment,It will be wrong. 

So It should add scene judgement in windows environment(org.apache.dubbo.common.utils.ConfigUtils#loadProperties(java.lang.String, boolean, boolean),Line 220).

```java
if (fileName.startsWith("/")) {
````
change to
```java
if (fileName.startsWith("/")||fileName.matches("^[A-z]:\\\\\\S+$")) {
````
the testcase (com.alibaba.dubbo.config.AbstractInterfaceConfigTest#checkApplication1) will go well.

**Comment by ralf0131** [comment]
Hi, thanks for reporting, would you please send a pull request?

**Comment by SuperDubbo** [comment]
>

> Hi, thanks for reporting, would you please send a pull request?

I have try to send a pull a request,but i don't have the access.
Maybe I don't get the right way  to pull a request.
Can you tell me?
![image](https://user-images.githubusercontent.com/20811216/46053935-67b53d00-c177-11e8-9d6d-f8adfe75f99f.png)

**Comment by ralf0131** [comment]
Hi, please refer to this: https://github.com/apache/incubator-dubbo/blob/master/CONTRIBUTING.md

You need to fork Dubbo first.

**Comment by SuperDubbo** [comment]
I have pull a request,Thank You @ralf0131
