### ISSUE TITLE
dubbo启动注册到zookeeper速度不够理想,在spring-boot启动过程中耗时过长

### ISSUE THREAD

**Issue by Anychnn** [apache/incubator-dubbo#2572]
dubbo启动注册到zookeeper速度不够理想,两秒钟一个service,怎么修改让注册这个动作怎么并发进行而不是一个接一个进行,目前使用的是spring-boot+dubbo+zookeeper, 使用的注解@Reference
<dubbo:annotation package="com.xxx"></dubbo:annotation>

**Comment by Anychnn** [comment]
有啥办法能让注册速度更快一些吗

**Comment by jiaoge** [comment]
应该是你的网络问题吧？注册是很快的
