### ISSUE TITLE
Lack of API Configured Sample 

### ISSUE THREAD

**Issue by yihuihan** [apache/incubator-dubbo#2574]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2faf5e7

### Steps to reproduce this issue
There's no samples of provider/consumer configured by API, So I'd like to add one

**Comment by diecui1202** [comment]
@yihuihan samples are here: https://github.com/dubbo/dubbo-samples/tree/master/dubbo-samples-api/src/main/java/com/alibaba/dubbo/samples

dubbo-demo in incubator-dubbo is just a simple use case, we can enrich samples in dubbo-samples project.

**Comment by yihuihan** [comment]
Thanks @diecui1202 for your help. I'll merge it to dubbo-sample then.
