### ISSUE TITLE
ApplicationModel serviceName is not unique

### ISSUE THREAD

**Issue by haiyang1985** [apache/incubator-dubbo#2583]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: all
* Operating System version: all
* Java version: all

### Steps to reproduce this issue
1. create two ReferenceConfig for same service with different configuration.
<dubbo:reference id="demoService" interface="com.alibaba.dubbo.DemoService">
</dubbo:reference>
<dubbo:reference id="demoServiceAsync" interface="com.alibaba.dubbo.DemoService" async="true">
</dubbo:reference>
2. startup the consumer application.
3. get the ConsumerModel from ApplicationModel.

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result
ApplicationModel.allConsumerModels() should returns two ConsumerModel.

### Actual Result
ApplicationModel.allConsumerModels() only returns the first ConsumerModel.

If there is an exception, please attach the exception trace:

With future investigation, ReferenceConfig cannot put the second ConsumerModel as they are in same serviceName.

Also, this is the same issue for provider with below configuration.
<bean id="demoService" class="com.alibaba.dubbo.DemoServiceImpl"/>
<dubbo:service interface="com.alibaba.dubbo.DemoService" ref="demoService">
</dubbo:service>
<bean id="demoService2" class="com.alibaba.dubbo.DemoServiceImpl2"/>
<dubbo:service interface="com.alibaba.dubbo.DemoService" ref="demoService2">
</dubbo:service>

Here is my PR: https://github.com/apache/incubator-dubbo/pull/2582

**Comment by kimmking** [comment]
It is dependent on how do you defind a Service:
- a backend service is a Service
- or a proxy service is a Service

**Comment by haiyang1985** [comment]
Yes. 
The flexibility of refer a service with different proxy is good(As above, one proxy in sync, another in async). But, it's terrible that we are not able to get the proxy we have created. 
For that, we are able to cache the proxy by extend the ProxyFactory. But, the issue is that the wrapper executed without order, which result in different proxy returned. 
Hopefully, the constrains be removed from the ApplicationModel cache.

**Comment by beiwei30** [comment]
@haiyang1985 I drop a comment in https://github.com/apache/incubator-dubbo/pull/2582#pullrequestreview-162318577, pls. take a look.

**Comment by beiwei30** [comment]
@Jeff-Lv I agree with your opinion. For this particular problem, let's consider it as a limitation. User cannot configure two references with the different behavior. We will provide alternative way to user to change the behavior either via API, utilities or dynamic config.

Let's roll back the relevant change in https://github.com/apache/incubator-dubbo/pull/2646.
