### ISSUE TITLE
dubbo泛化调用的时候传parameterTypes问题

### ISSUE THREAD

**Issue by zyh1218** [apache/incubator-dubbo#2588]
1.我不想集成提供者client端。这时候我拿不到提供者中的method 参数类型。
2.参数类型太复杂化了。
[3.当我parameterTypes传null的时候无论是什么参数类型都可以正常返回我不知道是不是正确的。
![image](https://user-images.githubusercontent.com/5111738/46255990-22766f80-c4d7-11e8-8d4e-d3b57710dd92.png)
![image](https://user-images.githubusercontent.com/5111738/46255993-35893f80-c4d7-11e8-9b95-3ea5a0831849.png)

**Comment by zyh1218** [comment]
我在调用 GenericService 这个接口的时候 其中接口里面yo(parameterTypes) 我传空值也可以获取到值，并且这样我没有办法去调用接口直接调用的协议参数了。






At 2018-09-30 20:24:06, "kimmking" <notifications@github.com> wrote:


So your question is what?

**Comment by zonghaishang** [comment]
泛化接口参数用于后端java正确解析和查找真实方法，请遵循接口规范调用，先关闭，如果有使用问题欢迎沟通。
