### ISSUE TITLE
Cache object recovery

### ISSUE THREAD

**Issue by dugenkui03** [apache/incubator-dubbo#2592]
https://github.com/apache/incubator-dubbo/tree/master/dubbo-filter/dubbo-filter-cache/src/main/java/org/apache/dubbo/cache/support/expiring

您好，ExpiringCache对象是否创建了便永远不可被回收？ThreadLocalCache是否也可能造成内存泄漏？

原因：
        1. `ExpiringCache` 对象变量的`store.clear()`方法没有被调用的入口；
        2. 获取`ExpiringCache`对象时，会启动线程执行 检查缓存数据是否过期 的任务。任务中有对`ExpiringMap.delegateMap`的引用。**因此即使创建`ExpiringCache`对象的线程终止后，因为 "超时检查线程"的存在，会导致`ExpiringCache`以其引用的对象不能被回收**‘
        3. 同理，`ThreadLocalCache`中至少应该有一个方法可以调用`store`变量的`remove()`方法。因为线程经常会被复用(尤其在线程池情况下)，但是线程`threadLocals`持有的缓存数据不一定一直有用，如果不清理可能造成内存泄漏和影响后续业务逻辑。

主要调整如下：
```
1. org.apache.dubbo.cache.Cache接口增加
    boolean remove(Object key);
    void clear();
    long size();

2. org.apache.dubbo.cache.support.threadlocal.ThreadLocalCache实现如下
        try{
            store.get().clear();
        }finally {
            store.remove();
        }
```

Hello, if the ExpiringCache object is created, it can never be recycled. Is ThreadLocalCache also likely to cause a memory leak?

the reason:
1. The store.clear() method of the ExpiringCache object variable has no entry to be called;
2. When the ExpiringCache object is obtained, the thread execution is started to check whether the cached data has expired. There is a reference to ExpiringMap.delegateMap in the task. Therefore, even if the thread that creates the ExpiringCache object terminates, because the "timeout check thread" exists, the ExpiringCache object referenced by it cannot be recycled.
3. Similarly, there should be at least one method in the ThreadLocalCache that can call the remove() method of the store variable. Because threads are often reused (especially in the case of thread pools), the cached data held by threads threadLocals is not always useful, and if not cleaned it can cause memory leaks and affect subsequent business logic.

The main adjustments are as follows:
```
1. org.apache.dubbo.cache.Cache interface added
     Boolean remove(Object key);
     Void clear();
     Long size();

2. org.apache.dubbo.cache.support.threadlocal.ThreadLocalCache is implemented as follows
         Try{
             Store.get().clear();
         }finally {
             Store.remove();
         }
```

**Comment by beiwei30** [comment]
@dugenkui03 with the clear method introduced on `Cache` interface, how do you plan to use it?

**Comment by dugenkui03** [comment]
> @dugenkui03 with the clear method introduced on `Cache` interface, how do you plan to use it?

@beiwei30 when we want to invalidate a ExpiringCache object and gc it.for example,yesterday's data does not apply today.

i think there should be implements of 'clear' and 'remove',because high-performance cache alway use "Future" as Value-If a calculation is canceled or fails, it needs to be removed from the cache. this idea can be found in 《java并发编程实战》5.6，page 87(<java Concurrency in practiceh>).

details in [PR](https://github.com/apache/incubator-dubbo/pull/2594)

**Comment by carryxyh** [comment]
Close via https://github.com/apache/incubator-dubbo/pull/2594
a complete set of expiration policies is wanted.
