### ISSUE TITLE
继承集合对象的序列化

### ISSUE THREAD

**Issue by hj819748949** [apache/incubator-dubbo#2598]
例如对象时
public class DataSet extends ArrayList<String>
{
	private static final long serialVersionUID = 5964152976750707429L;
	
	private String tag;
	
	public DataSet()
	{
	}
	public DataSet(String tag)
	{
		super();
		this.tag = tag;
	}
	public String getTag()
	{
		return tag;
	}
	public void setTag(String tag)
	{
		this.tag = tag;
	}
}

这种情况下, hession2，以及fastjson时，tag值无法进行序列化的

**Comment by beiwei30** [comment]
yes, this is a limitation from hessian.
