### ISSUE TITLE
消费者调用报java.lang.NoSuchMethod异常

### ISSUE THREAD

**Issue by Createst** [apache/incubator-dubbo#2599]
Environment
* Dubbo version:2.6.1
* Java version: 1.8
问题描述：
dubbo消费者调用服务提示找不到该方法，通过查看zookeeper已经注册了，通过invoke直接调用是没有问题的，方法调用的参数和名称都是正确的，只有部分方法出现这个问题。这个问题出现两次，第一次是将服务和消费者重新部署就自动好了，第二次是修改了那个方法的名称，重新部署好的。至今不知道为啥出现这样的问题。

**Comment by chickenlj** [comment]
I think most likely you are using different versions of service definition on the Consumer and Provider side. Have you changed the method signature recently?

Can you please paste the exception stack trace?

**Comment by beiwei30** [comment]
it should be interface compatibility issue in your system.

**Comment by Createst** [comment]
> I think most likely you are using different versions of service definition on the Consumer and Provider side. Have you changed the method signature recently?
> 
> Can you please paste the exception stack trace?

服务端和消费者的dubbo版本都是2.6.1。
每次修改方法名都会同步到消费者，而且在第一次上线没有出现问题，第二次出现的问题，代码都没有一点修改。
