### ISSUE TITLE
is there a problem in NettyBackedChannelBuffer.setBytes(...)?

### ISSUE THREAD

**Issue by 46557783** [apache/incubator-dubbo#2619]
hi,I see the  code for method setBytes in class com.alibaba.dubbo.remoting.transport.netty4.NettyBackedChannelBuffer.java which is below,is there a problem ?

![image](https://user-images.githubusercontent.com/20593632/46648646-90eaba00-cbc8-11e8-896d-9a1d235d7e0b.png)

**Comment by qinliujie** [comment]
This is really a bug, but it won't affect it at the moment, because I searched it, there is no place to use this method. please @zonghaishang  check again

**Comment by zonghaishang** [comment]
I have checked that, @46557783 Could you make a pull request to fix it?
