### ISSUE TITLE
provider不指定分组group时，会默认在zk中每个分组都实现服务吗？

### ISSUE THREAD

**Issue by ningmeng7746889** [apache/incubator-dubbo#2628]
zk注册了6个分组，而一个provider提供的接口（未指定group），实际服务治理上发现含有6个不同分组的provider。

**Comment by zonghaishang** [comment]
provider不指定group, zk默认里面会在分组/dubbo分组下存储服务。
如果provider同时包含group和没有分组，服务治理上面都能看到的。
