### ISSUE TITLE
Provide dubbo-all-without-spring module

### ISSUE THREAD

**Issue by SKYhuangjing** [apache/incubator-dubbo#2634]
For now, i need use dubbo without spring enviroment, just like some non-spring runtime framework. so i need using API confirguration.
but when i add **dubbo-all** in my web app lib, i found it will dependency spring-context runtime.
so i have to add dubbo-xxx one by one, it's not easy job.

so can we provide dubbo-all-without-spring module, just like dubbo-all, but dubbo-all-without-spring module did't rely spring-framework and have no dubbo-xxx-spring  module?

I have forked dubbo repo and make [dubbo-all-without-spring](https://github.com/SKYhuangjing/incubator-dubbo/blob/master/dubbo-all-without-spring/pom.xml) module in mine repo.

I'm looking forward for dubbo team offical response.

**Comment by carryxyh** [comment]
Hi,
There is a similar discussion here, we can focus on it:
https://github.com/apache/incubator-dubbo/issues/2570
