### ISSUE TITLE
不看pojo类或代码，能否通过telnet等命令查看pojo类的属性信息?

### ISSUE THREAD

**Issue by lgw8186** [apache/incubator-dubbo#2635]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: xxx
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by beiwei30** [comment]
可以使用 [Arthas](https://github.com/alibaba/arthas) 中的 [jad](https://alibaba.github.io/arthas/jad.html) 来查看。这个功能不适合放在 telnet 中。

**Comment by lgw8186** [comment]
是这样的，我们想做一个通用的dubbo接口测试的功能。希望是只提供zk, 类，方法，参数就可以实现调动，不依赖api。   目前使用泛化实现，但是执行时必须提供dubbo接口参数类型，这样导致参数类型必须要参考相关接口文档或是api，       是否可以有其他方式获取dubbo接口方法的形参？

**Comment by lgw8186** [comment]
> 可以使用[Arthas](https://github.com/alibaba/arthas)中的[jad](https://alibaba.github.io/arthas/jad.html)来查看。这个功能不适合放在telnet中。

不要通过反编译，通过代码能否实现?

**Comment by lgw8186** [comment]
> @lgw8186 你上面的问题解决了吗

没有

**Comment by wanghongenpin** [comment]
watch
