### ISSUE TITLE
Custom router does not support configuration on Provider side

### ISSUE THREAD

**Issue by rhwayfun** [apache/incubator-dubbo#2639]
I have a requirement：
According to the client's request, the specified machine is called for the qualified request, and the other machine is called for the unqualified request. 

So I customize a route, but I find that the route can only take effect on the client. The server（Provider） does not take effect. 

Can Dubbo support the configuration of custom routes on the server（Provider）?

**Comment by carryxyh** [comment]
Hi,
Sorry, I still don't fully understand what you mean.
You are hoping to route on the provider side. If the provider finds that the request is illegal, as you said, do you want the current provider to send the request to another provider?

**Comment by rhwayfun** [comment]
yes, the provider can only handle legal request(eg: specific city request, other city request will be handled on another provider)

**Comment by rhwayfun** [comment]
Thanks, but the problem with custom router is that the client needs to introduce additional dependencies, which means that the client needs to make code changes, not non-perceived. In addition, there are usually a lot of C side, which is very unreasonable. It is best to be able to control the P side itself.

**Comment by carryxyh** [comment]
In response to your situation, dubbo provides a router to solve, you can dynamically configure on dubbo-ops.

The client itself is not likely to be unaware of the server. The behavior of P1 forwarding a request to P2 itself is meaningless. Because we could have the Consumer send the corresponding request directly to the corresponding Provider. Increasing the number of transfers means increasing the risk.

As far as I know, no RPC framework implements this functionality on the server side.

**Comment by rhwayfun** [comment]
Do you mean the condition router?

**Comment by carryxyh** [comment]
Hi,
u can get more info here: http://dubbo.apache.org/zh-cn/docs/user/demos/routing-rule.html

**Comment by rhwayfun** [comment]
I have read it, It does not support parameter routing. Still thank you.

**Comment by rhwayfun** [comment]
Yes, if support parameter router, then the requests specifying conditions will be processed by a specific provider. And it can be used to achieve grayscale requirements.

**Comment by carryxyh** [comment]
I would recommend using dubbo-ops to dynamically configure your route.

**Comment by rhwayfun** [comment]
@carryxyh 
Do you mean dubbo-admin platform？
