### ISSUE TITLE
dubbo为什么不能处理service接口的方法签名上申明的异常的基异常

### ISSUE THREAD

**Issue by zcgewu** [apache/incubator-dubbo#264]
![qq 20160616112822](https://cloud.githubusercontent.com/assets/6211911/16104647/bf27d022-33b5-11e6-82d6-c9a02e286276.png)

例如：我的申明了业务基异常BizException，getSpaceIntroRecordById方法中抛了BizException，在远程调用前，web端是可以正确拿到BizException。
SpaceIntroRecordBo getSpaceIntroRecordById(Integer spaceIntroRecordId)throws SpaceBizException;
public class SpaceBizException extends BizException
public class BizException extends RuntimeException

**Comment by carryxyh** [comment]
Is this issue still exist?
Can u send a simple demo to recreate this problem?

**Comment by carryxyh** [comment]
There no more feedback for this issue.
I think we can close this.
Reopen it if there are still sth about this issue.

&READY-TO-CLOSE&
