### ISSUE TITLE
配置在公用的模块META-INF/dubbo/com.alibaba.dubbo.rpc.Filter，其他模块引用获取不到

### ISSUE THREAD

**Issue by huangyangcong** [apache/incubator-dubbo#2644]
* Dubbo version: 2.6.1
* Operating System version: win10
* Java version: 1.8
如题

**Comment by beiwei30** [comment]
@huangyangcong 能在你的 github 上提供一个例子重现你说的问题吗？你的描述太简单了

**Comment by vkeeper** [comment]
如果你指的是无法获取jar依赖下的配置的话，我这儿测试时可以的，我的测试环境与你一致

- Dubbo version: 2.6.1
- Operating System version: win10
- Java version: 1.8

 你可以通过以下代码测试
```java
public class Test{
    public static void main(String[] args){
        boolean res = ExtensionLoader.getExtensionLoader(Filter.class).hasExtension("customerFilterName");
        System.out.println(res);
    }
}
```

**Comment by huangyangcong** [comment]
谢谢，自己配置出现问题

**Comment by AgentZh0u** [comment]
请问是如何修改的，我也是配置的公共的模块里，启动应用总是读取不到对应模块的META-INF/dubbo
