### ISSUE TITLE
Service export IP in multiple network card machine.

### ISSUE THREAD

**Issue by CoderCai** [apache/incubator-dubbo#2648]
- [-] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [-] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.2
* Operating System version: centos7.0
* Java version: 1.8

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result
Hello,
There are two network cards in my machine, IP are 10.x.x.x and 172.x.x.x,  zookeeper IP is 172.x.x.x, after services start up, providers path in zookeeper, service ip is 10.x.x.x. and because of all my business servers IP are 172.x.x.x, this service who exported with IP 10.x.x.x could not be invoked by other services.

I read the source code of Dubbo, it chooses IP from IP list only if one is a valid IP address.
![image](https://user-images.githubusercontent.com/8693336/47011493-ab96d300-d174-11e8-851e-ec1ef341e825.png)
IP_PATTERN in this picture, just a regular expression which matches a valid IP address.

Can we choose the IP first in the same IP segment with zookeeper address instead of a random one? That's guaranteed that servers are reachable to each other at default configure.

**Comment by lexburner** [comment]
This kind of issue is duplicate. You can search the issues of this repository. 
In my opinion, multi-network cards are really hard to choose, the logic of return `InetAddress` in dubbo depends on **hostname firstly**.
so make sure your available IP, and look up your hostname(you can use the command `hostname` in Mac, Linux, Windows).
configure them in your `hosts` file like this:
```
1.2.3.4 xujingfengdeMacBook-Pro.local
```
`1.2.3.4` is what you really want to register in the registry.

Source code can tell you more details about the logic of choosing `InetAddress`, pls debug into `org.apache.dubbo.common.utils.NetUtils.getLocalAddress()`.

**Comment by cvictory** [comment]
&READY-TO-CLOSE&
