### ISSUE TITLE
Office Document Edit Error

### ISSUE THREAD

**Issue by a601942905git** [apache/incubator-dubbo#2659]
Please click the link [group merger](https://dubbo.incubator.apache.org/zh-cn/docs/user/demos/group-merger.html) to office website, you will found the error like this
```
<dubbo:reference interface="com.xxx.MenuService" group="*">
    <dubbo:method name="getMenuItems" merger="true" />
</dubbo:service>
```

**Comment by carryxyh** [comment]
Hi, can u describe your issue more clearly?

**Comment by lexburner** [comment]
@a601942905git Indeed it is a slip in writing, the `reference` scheme shouldn't be closed by `service`. Would you like to send a PR to dubbo document which its source code is hosted on [here](https://github.com/apache/incubator-dubbo-website).

**Comment by carryxyh** [comment]
@a601942905git 
Hi, I open a issue at here:
https://github.com/apache/incubator-dubbo-website/issues/165

Pls focus on this issue.

Would u pls send a pr to fix this issue?
