### ISSUE TITLE
issues list of 2.6.5 

### ISSUE THREAD

**Issue by cvictory** [apache/incubator-dubbo#2663]
Issue Code | Description  | Status
--- | --- | --- 
[#2063](https://github.com/apache/incubator-dubbo/issues/2063)   | ~~@Service(register=false) is not work type/bug~~ | closed
[#1903](https://github.com/apache/incubator-dubbo/issues/1903)   | ~~Our customized serialization id exceeds the maximum limit, now it cannot work on 2.6.2 anymore. type/bug~~  | closed 
[#2655](https://github.com/apache/incubator-dubbo/issues/2655)   | ~~@Service and @Reference Optimization~~  | closed
[#2194](https://github.com/apache/incubator-dubbo/issues/2194)   | ~~Annotation @Reference can't support to export a service with a sync one and an async one type/bug~~  | closed
[#2522](https://github.com/apache/incubator-dubbo/issues/2522)   | ~~`org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor#generateReferenceBeanCacheKey` has a bug type/bug~~  | closed
[#2256](https://github.com/apache/incubator-dubbo/issues/2256)   | ~~2.6.x Spring Event & Bugfix~~  | closed
[#1641](https://github.com/apache/incubator-dubbo/issues/1641)   | ~~[Enhancement] the algorithm of load issue on Windows good first issue help wanted level/easy type/bug~~  | closed
[#2621](https://github.com/apache/incubator-dubbo/issues/2621)   | ~~fix #1641, support get system load on windows.~~   | closed
[#2600](https://github.com/apache/incubator-dubbo/issues/2600)   | ~~add javadoc to dubbo-all module good first issue help wanted~~ | closed
[#2560](https://github.com/apache/incubator-dubbo/issues/2560)   | ~~A empty directory dubbo-config/dubbo-config-spring/src/test/resources/work after package source tgz~~  | closed
[#1967](https://github.com/apache/incubator-dubbo/issues/1967)   | ~~ignore serialization ID for heartbeat message priority/low type/enhancement~~  | closed
[#2131](https://github.com/apache/incubator-dubbo/issues/2131)   | ~~Check if we can switch serialization/deser between IO and Dubbo Threads. status/wontfix~~  | closed
[#2519](https://github.com/apache/incubator-dubbo/issues/2519)   | Can we make the bom and all module become the child module of dubbo-parent? good first issue help wanted |  closed
[#2235](https://github.com/apache/incubator-dubbo/issues/2235)   | [Enhancement] Reactor the generation rule for @Service Bean name type/enhancement |  closed
XX | ~~Fix incorrect descriptions for dubbo-serialization module~~ | closed [pr](https://github.com/apache/incubator-dubbo/pull/2624)

**Comment by diecui1202** [comment]
When does 2.6.5 start to release? Maybe release notes could be sent to mailing list first.
