### ISSUE TITLE
dubbo -  global router center

### ISSUE THREAD

**Issue by a2833986889** [apache/incubator-dubbo#2671]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: master
* Operating System version: xxx
* Java version: 1.8

### Steps to reproduce this issue

1.  there  have two   provider  on  The machine A and  The machine B   
      machine A is processing  request  very  slowly   ，i want b  provider   only   receive   a  little bit of request
  mostly  request send  to  a

2. updated provider  ， i ’am  doing Service upgrade  ,right now 
   update b provider then  publish ,   but consume is old ,   need  new provider b dont receive any request until consume is  upgrade   done

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by carryxyh** [comment]
Close via https://github.com/apache/incubator-dubbo/pull/2670
