### ISSUE TITLE
AbstractRegistryFactory have  a piece of redundant code

### ISSUE THREAD

**Issue by jingui123** [apache/incubator-dubbo#2685]
I have found  a piece of redundant code, may be is I do not understand.
in AbstractRegistryFactory class, there are two variables，one is LOCK，the other is REGISTRIES,as follows : 
 private static final ReentrantLock LOCK = new ReentrantLock();

    // Registry Collection Map<RegistryAddress, Registry>
    private static final Map<String, Registry> REGISTRIES = new ConcurrentHashMap<String, Registry>();

but when we use REGISTRIES.put() , the section of code is locked.  so I think REGISTRIES will be better  to modify HashMap.
example:
public Registry getRegistry(URL url) {
....
LOCK.lock();
REGISTRIES.put(key, registry);
 LOCK.unlock();
}
public static void destroyAll() {
....
LOCK.lock();
REGISTRIES.clear();
 LOCK.unlock();
}

### Environment

* Dubbo version: 2.7.0-SNAPSHOT
* Java version: jdk1.8

**Comment by carryxyh** [comment]
Hi, would u pls send a pr to fix this?

**Comment by zonghaishang** [comment]
// Lock the registry access process to ensure a single instance of the registry

**Comment by carryxyh** [comment]
Yes, but seems like the REGISTRIES field could change to hashmap.
How do u think about it? @zonghaishang

**Comment by lllichen** [comment]
` public static Collection<Registry> getRegistries() {
        return Collections.unmodifiableCollection(REGISTRIES.values());
    }`
the REGISTRIES.values() escape ?

**Comment by carryxyh** [comment]
I know.
But hashmap.values is also thread safe.

**Comment by jingui123** [comment]
so，do the issue need to be modified to hashmap?

**Comment by carryxyh** [comment]
Hi, @jingui123 
U can send a pr and let more people review it.
:)

**Comment by jingui123** [comment]
ok, i will try it

**Comment by carryxyh** [comment]
Thx for your issue.
