### ISSUE TITLE
dubbo配置支持多协议，不能在service指定其中某一种协议

### ISSUE THREAD

**Issue by fuhao715** [apache/incubator-dubbo#2695]
### Environment

* Dubbo version: 2.6.2
* Operating System version: mac
* Java version: 1.8
配置如下：
  protocols:
    protocol1:
      name: dubbo
      id: dubbo
      status: server
    protocol2:
      id: rest
      name: rest
      status: server
      server: tomcat
      contextpath: api/swift/v1
      extension: com.alibaba.dubbo.rpc.protocol.rest.support.LoggingFilter

服务注释：
@Service(
        version = "${demo.service.version}",
        application = "${dubbo.application.id}",
        registry = "${dubbo.registry.id}",
        protocol = "dubbo"
)

问题： 无法指定服务的协议类型。

建议：
       service协议类型若有则是指定类型，否则按照配置协议类型暴露

**Comment by fuhao715** [comment]
提示错误如下：
Cannot resolve reference to bean 'dubbo' while setting bean property 'protocl'

**Comment by beiwei30** [comment]
@fuhao715 can you provide a sample to reproduce this issue on your GitHub?

**Comment by beiwei30** [comment]
let's close for now.
