### ISSUE TITLE
dubbo的telnet维护功能如何鉴权或者完全禁用？

### ISSUE THREAD

**Issue by flyfeifei66** [apache/incubator-dubbo#2702]
看了官网，说可以设置只允许本机telnet，我们还是希望生产可以完全禁用此功能，或者可以根据IP鉴权，问下dubbo是否支持。

**Comment by beiwei30** [comment]
目前不支持鉴权。可以通过在 `dubbo.properties` 中配置来关闭

```properties
qos.enable=false
```

如果是 spring boot 的应用，在 `application.properties` 中配置

```properties
dubbo.application.qosEnable=false
```

**Comment by beiwei30** [comment]
文档更新了，参考下这里：http://dubbo.apache.org/zh-cn/docs/user/references/telnet.html
