### ISSUE TITLE
模拟提供者与zookeper网络断开后，消费者不能继续调用提供者

### ISSUE THREAD

**Issue by zcgewu** [apache/incubator-dubbo#2718]
### 环境
* Dubbo 版本：2.6.0
* 操作系统版本：centos
* Java版本: 1.8

### 操作步骤
1. 启动提供者
2. 启动消费者
3. iptables禁用提供者的zookeper端口2181

### 结果
![image](https://user-images.githubusercontent.com/6211911/47772874-0ad31680-dd23-11e8-89ef-939aa498fff7.png)

![image](https://user-images.githubusercontent.com/6211911/47772483-c98e3700-dd21-11e8-8020-27e2c8856f0d.png)

看提供者的日志是提供者主动断开与消费者的连接的，不解的地方是zookeeper上的该接口的提供者节点数据也没有了，按理说掐断网络的瞬间不是优雅停机，节点数据是不会删除的（zookeeper有过期删除机智吗？）。接着我试验了用iptable禁用了消费者与zookeeper的2181端口，可以正常消费。按着提供方的现象，是不是可以理解为只要zookeeper挂掉之后，整个服务将不可用，dubbo变成了一个伪的无中心机构。

**Comment by carryxyh** [comment]
> 接着我试验了用iptable禁用了消费者与zookeeper的2181端口，可以正常消费

禁用提供者会影响dubbo admin上消费者的信息。

> 是不是可以理解为只要zookeeper挂掉之后，整个服务将不可用

不可用，除非你使用直连的方式。

> zookeeper有过期删除机智吗？

有。

**Comment by beiwei30** [comment]
can we close it now?

**Comment by zonghaishang** [comment]
先关闭，有疑问在沟通。
