### ISSUE TITLE
SpringBoot 如果手动注入ReferenceBean

### ISSUE THREAD

**Issue by GiftedDrogon** [apache/incubator-dubbo#2722]
使用ConfigurableListableBeanFactory类中的registerSingleton去注入ReferenceBean的话，getBean的时候因为判断是手动注入的  AbstractBeanFactory.getObjectForBeanInstance方法会返回一个null对象,所以注入的不应该是ReferenceBean。那么应该注入的是什么。有大佬可以告知一下？

**Comment by zonghaishang** [comment]
```
RootBeanDefinition beanDefinition = new RootBeanDefinition();
beanDefinition.setBeanClass(ReferenceBean.class);
```
