### ISSUE TITLE
服务端已发送服务调用结果，客户端无响应直至服务调用超时

### ISSUE THREAD

**Issue by TeddyTsui** [apache/incubator-dubbo#2753]
### 环境

* Dubbo version: 2.4.9
* Java version: 1.8

### 问题描述
服务调用返回结果POJO的List。
调用同一服务方法返回数据量小于8M时，调用过程正常。
目前出现无响应的调用返回的数据量约15M。
服务端无报错。

protocol 配置为
<dubbo:protocol name="dubbo" port="20880" payload="16777216"/>

问题追踪至HeaderExchangeChannel.send

请问可能出现问题的原因

**Comment by carryxyh** [comment]
你好，你的Dubbo版本太低了，你可以试试最新的版本。
如果依然有问题，请提供一个最简单且能复现问题的demo，上传至github后把地址提供给我们，我们会去检查。

**Comment by carryxyh** [comment]
@TeddyTsui 
这个问题解决了么？

**Comment by TeddyTsui** [comment]
@carryxyh 
尝试了升级至2.6.0版本后，问题没能解决。暂时还提供不了复现问题的demo。
有进展我再打开，谢谢跟进。

**Comment by carryxyh** [comment]
好的。谢谢你的issue。
