### ISSUE TITLE
dubbo部署

### ISSUE THREAD

**Issue by BellaJiangxia** [apache/incubator-dubbo#2756]
dubbo如何不用main方法启动，部署到服务器上，用tomcat的方法启动服务？

**Comment by carryxyh** [comment]
没看懂你的问题，dubbo只是一个框架，框架需要依赖工程才能起作用。

**Comment by zonghaishang** [comment]
doc: http://dubbo.apache.org/zh-cn/docs/user/quick-start.html
sample:  https://github.com/dubbo/dubbo-samples/tree/master/dubbo-samples-rest

你应该搭建一个web工程(spring):
1. web.xml参考配置：https://github.com/dubbo/dubbo-samples/blob/master/dubbo-samples-rest/src/main/webapp/WEB-INF/web.xml
2. 指定dubbo的服务配置：https://github.com/dubbo/dubbo-samples/blob/master/dubbo-samples-rest/src/main/resources/spring/rest-provider.xml

**Comment by BellaJiangxia** [comment]
谢谢
