### ISSUE TITLE
ReferenceBean's getObject() called in toString()

### ISSUE THREAD

**Issue by beiwei30** [apache/incubator-dubbo#2757]
Intellij Idea's debugger renders object to string in object view (Preferences -> Build, Execution, Deployment -> Debugger -> Data Views -> Java -> Enable 'toString()' object view). This behavior is enabled by default and it leads some strange problem when debug in Dubbo, for examples: #2431, or user may observe a ReferenceConfig may init twice or ReferenceConfig#urls may have two same entries if the breakpoint happens to set in the relevant places. You may interested in looking into the details from http://t.cn/EAhta27, where @code4wt gives the excellent analysis.

**Comment by carryxyh** [comment]
@beiwei30 
How do u think about that toString method print getObject's result.
IMO, toString method should not print this info because this is meaningless.
So I support @code4wt revision.

**Comment by carryxyh** [comment]
Nice pr and analysis.
Thx
