### ISSUE TITLE
[Dubbo - qos-http]  stopServer should be invoked ?

### ISSUE THREAD

**Issue by zonghaishang** [apache/incubator-dubbo#2762]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.0
* Operating System version: mac
* Java version: 1.8

Why this method `org.apache.dubbo.qos.protocol.QosProtocolWrapper#stopServer` not invoked?
My understanding is that when the service stops, the http service should stop.

**Comment by oawang** [comment]
I also have this problem , Dubbo 2.5.10

**Comment by beiwei30** [comment]
looks like we should call 'stopServer' in 'destroy'.
