### ISSUE TITLE
dubbo在listener调用时对异常的处理

### ISSUE THREAD

**Issue by my12us** [apache/incubator-dubbo#2783]
使用场景：使用dubbo Callback回调消费kafka数据
使用目的：1、防止kafka账户信息泄露
                  2、Topic授权校验
                  3、对kafka数据进行过滤
服务发布： 
<dubbo:service interface="com.xx.xx.xx.xxService"  ref="dataSubscriptionService"
                   timeout="200000"  callbacks="1000" connections="100" protocol="dubbo"  group="routing">
        <dubbo:method name="addListener">
            <dubbo:argument  index="2"  callback="true" />
        </dubbo:method>
    </dubbo:service>
服务消费：
<dubbo:reference id="dataSubscriptionService" interface="com.xx.xx.xx.xxService"
                     group="XX"/>
出现问题：
1、服务端稳定，客户端重启【客户端停止后，服务端未监听客户端停止，回调报错】
服务端报错： client disconnected
com.alibaba.dubbo.rpc.RpcException: Failed to send message Request 
Caused by: java.nio.channels.ClosedChannelException: null
会丢失数据条数不定或延迟
2、服务端重启，客户端稳定【服务端停止后，客户端未监听服务端停止重连，永久卡死】
客户端永久卡死，重启后正常消费数据
	1、服务端正在发送数据过程中重启，丢失同批不定条数数据
	2、静置状态重启，客户端重启后数据正常消费，不会丢失数据
3、客户端启动之后非阻塞状态，服务端故障后客户端不再重试

**Comment by AnyOSR** [comment]
1.服务端只会监听provider路径，当你客户端发送请求然后宕机，服务端准备好数据通过channel发送数据到客户端，肯定会报错
2.客户端会去监听服务端的，永久卡死是啥？客户端有超时机制啊
数据丢失问题不能依靠dubbo来解决吧，只是一个RPC，数据并没有落地吧

**Comment by my12us** [comment]
客户端订阅数据是采用的dubbo“参数回调”功能，客户端调用addListener（一次调用）后会等待服务端消息的回调。现在核心的问题：provider挂掉或网络异常后，客户端无感知，也不重试，没有任何报错信息，按理此时长连接已断开，所以想了解dubbo里面“参数回到“的机制，怎么保证连接的稳定性。参数回调文档：https://dubbo.incubator.apache.org/zh-cn/docs/user/demos/callback-parameter.html

**Comment by AnyOSR** [comment]
listener是服务端调用客户端，客户端无法去重试，客户端只能添加listener
另外，客户端是能感知到服务端的上下线的，反正用zk的时候是能的，否则怎么做服务注册和发现
provider调用客户端listener的时候，也会打印出异常信息，例如超时之类的，检查下日志设置？
dubbo不能保证连接的稳定性，没有哪个能保证，issue改成"dubbo在listener调用时对异常的处理"会更好？另外，这是一个discussion还是啥？

**Comment by beiwei30** [comment]
同意 @AnyOSR 的观点，这种情况下，客户端实际上扮演的是服务提供方的角色，你可以考虑在 callback 的实现中使用 Future 来带超时 get

**Comment by rainleon** [comment]
关键点应该是客户端和服务端能够在上层感知捕获连接断开的异常,从而进行业务层面的容错,
如: 
1.服务端检测到,从本地的cache的客户端listener列表里移除出错的listener
2.客户端坚持到,客户端可以进行failover机制.再次调用addListener到另外的provider.

这两种机制如何实现?目前文档并未找到.代码层面也没有找到合适的办法.
