### ISSUE TITLE
dubbo注解方式为啥存在缓存

### ISSUE THREAD

**Issue by BellaJiangxia** [apache/incubator-dubbo#2794]
如题，，，

**Comment by carryxyh** [comment]
请自行查看文档。
http://dubbo.apache.org/zh-cn/docs/user/configuration/annotation.html

**Comment by BellaJiangxia** [comment]
是我自己代码的问题，启动注解的服务里面依赖了另外一个可以成功部署的服务，所以当这个服务失败的时候，他依赖了另外一个服务，部署成功的其实是那个可以部署成功的服务
