### ISSUE TITLE
secondary directory in dubbo's developer guide is not responding

### ISSUE THREAD

**Issue by CrazyHZM** [apache/incubator-dubbo#2806]
I want to reflect a problem, the User doc secondary directory in dubbo's developer guide is not responding.
Address：http://dubbo.apache.org/en-us/docs/dev/build.html

**Comment by carryxyh** [comment]
I can show the page after clicking it, and there is no problem you said.

**Comment by satansk** [comment]
seems like a browser compatibility issue.

**Comment by lovepoem** [comment]
Maybe a network problem

**Comment by carryxyh** [comment]
@CrazyHZM 
Can u visit the guide now?

**Comment by carryxyh** [comment]
Let's focus on this issue:
https://github.com/apache/incubator-dubbo-website/issues/183
