### ISSUE TITLE
dubbo的hessian协议上传文件限制的问题

### ISSUE THREAD

**Issue by moayi** [apache/incubator-dubbo#2813]
各位大佬，dubbo的hessian协议上传文件的大小的限制吗？我用的server默认为jetty，上传几十M的文件没啥问题，倒是上传一个152m的文件就报堆内存溢出的异常了，请教各位大佬，谢谢。

**Comment by gt0012** [comment]
路人甲路过，我无法解决你的问题，但是我想说一下我的看法，dubbo是一个rpc的通信框架，在使用上尽量做到传输多次，数据量小，保证dubbo响应时间尽量缩短，所以是否可以更换一个路子，不要用dubbo传递文件，把文件存储到一个地方，dubbo服务去获取。

**Comment by carryxyh** [comment]
> dubbo的hessian协议上传文件的大小的限制吗

有，8M。个人认为你的问题和dubbo没有什么关系。几十M的文件你也是通过http上传给jetty上的应用的，也不是用dubbo的接口传输的，通过rpc传输超过8M的数据会报错的。
内存溢出调整内存大小即可。
