### ISSUE TITLE
2.6.5的到来是dubbo无侵入的终结？

### ISSUE THREAD

**Issue by JobsZCQ** [apache/incubator-dubbo#2836]

**Comment by carryxyh** [comment]
请准确描述你的问题。

**Comment by JobsZCQ** [comment]
@carryxyh 之前版本，实现业务逻辑的时候，只用关系业务逻辑，顶多一个@Autowire。现在都用@了，如果对Service或Component有配置，岂不是在业务里面出现了很多dubbo的annotation。

**Comment by carryxyh** [comment]
新版本也支持xml，不喜欢用注解就使用xml不就好了么。

**Comment by JobsZCQ** [comment]
@carryxyh 

> 注意
如果你曾使用旧版annotation配置，请删除所有相关配置，我们将在下个版本删除所有旧版配置项。

<dubbo:annotation package="com.alibaba.dubbo.test.service" /> 

以上来自[http://dubbo.apache.org/zh-cn/docs/user/configuration/annotation.html](文档)， <dubbo:annotation package="com.alibaba.dubbo.test.service" /> 这都取消了，在服务中调用其他服务，然后在高一堆 apiconfig 获取bean然后在调用？ 这也太繁琐了

**Comment by JobsZCQ** [comment]
然后用新的 Api， 使用@scan，又要进行javacode级的配置，这样的调整真的有必要么。既然保留xml，为何不让xml可以做到config的所有工作。一件事变成两件事。

**Comment by carryxyh** [comment]
繁琐和入侵是两回事，所以到底你是觉得新版本的api太繁琐还是觉得dubbo对你的业务有入侵呢？

现在xml是可以做所有的配置工作，只不过xml的配置方式在升级以后需要修改一下。升级有兼容升级就有不兼容升级。

**Comment by JobsZCQ** [comment]
我看到的差异就是 旧版本的 可以在xml中指定scan路径，然后在业务中，@Autowire即可引用服务；新版本，Reference与@Autowire使用方式基本上一致，但是使用时，却需要很多的配置。而且这些配置还是基于code的。

**Comment by carryxyh** [comment]
> xml可以做所有的配置工作？针对scan也是吗？我没有看到相关的文档。

这个地方我要去问一下spring相关改动的人员。目前2.6.x分支上和master分支上都是可以使用dubbo:annotation进行scan的。之前提到的文档上的内容好像确实有点迷惑。

> Reference与@autowire使用方式基本上一致

差别很大，Reference可以完全替代xml中的dubbo:reference，autowire是spring的注解，@Reference是dubbo的注解，当然有一些对于dubbo特有的功能，比如配置timeout。建议你用一下新版本的@Reference

**Comment by JobsZCQ** [comment]
Reference与@Autowire差异这块，你说的我认同。但是我表达的是，在业务中引用服务的时候，他们的差异是很小的。 

另外dubbo:annotation的scan，我今天刚用2.6.5测试了。

> java.lang.NoClassDefFoundError: com/alibaba/spring/beans/factory/annotation/AnnotationInjectedBeanPostProcessor

应该是已经调整了。

**Comment by carryxyh** [comment]
新版本的@Reference和@Service就是为了替代xml配置文件。你可以选择完全使用注解的方式配置所有xml中的内容，当然也可以沿用xml。个人认为这两者都没有`入侵业务`，入侵业务我理解是在业务方法中写业务无关的代码，比如业务代码中用springcontext去获取bean，再比如在业务代码里初始化httpclient之类的操作。

**Comment by JobsZCQ** [comment]
这个可能是你我的理解差异吧。 我所理解的无入侵，就是所有的业务逻辑，就像一个完全独立的东西。不需要任何东西。在业务中看到的除了业务还是业务。这些config的东西，也contain的东西，为什么应该存在与业务中。即使只是注解，你脱了了dubbo，你的code走得动吗？ 无入侵的，旧版本dubbo就可以做到。 我把jar放到任何地方，new Impl()即可work

**Comment by carryxyh** [comment]
那你认为spring侵入了你的业务么？脱离了spring，@service  @autowire 也跑不动
如果业务完全独立，那么可能只有写一个main方法这种jar包才算无入侵。那么你将自己管理所有bean的生命周期，所有的http请求，只有这样才是无入侵是么？

> 在业务中引用服务的时候，他们的差异是很小的。

这就是我说的我认为没有入侵业务，如果这个修改导致你必须修改你的业务方法的内容，那么我认为这是入侵了业务。

> 目前的设计，在服务提供者A调用服务提供者B场景中，矛盾更明显。在服务A中如何引用B呢 ？ 是@DubboComponentScan 然后 在@reference 得到B？ 这不就是xml和annotation的矛盾呀？可以用xml，但是服务之间调用得codeconfig，然后@reference获得服务的引用，何其矛盾

```
@Service
A {

   @Reference
   B
}
```

哪里矛盾哪里看不懂了呢？XML和reference是解决同一个问题的两种方式而已。获取bean你可以用注解，也可以用spring给你提供的上下文，那你也要说spring自己是矛盾的么？？？？

**Comment by JobsZCQ** [comment]
@Service和@Reference 使用的提前是什么？ 是基于codeconfig，对吧？只有xml，这可以用吗？所以我说的是xml不能独立用，xml配置在服务间调用需要codeconfig+@Reference。这不就是有些矛盾的意思吗？ 目的是简化，这反倒成繁琐了。

Spring，我理解不算是入侵，因为我需要他的Autowire呀——至少没有那么多的config。

可以想象一下，一个service上一堆的注解额

**Comment by JobsZCQ** [comment]
用过呀。我先说说我的理解，不一定对，但的确我发现了一个我觉得是问题的问题。
对service和reference，他们只有在apiconfig指定scan时才会被load。那么这个就有一个问题，只是我觉得是问题。举个场景，服务A调用服务B，服务B调用服务C，服务C调用服务A。假设服务A是xml配置的，然后B和C都是@refrence的，服务C调用A时是不是也需要refrence 服务A，这样A岂不是又在xml配置又在用注解配置了？当然了，如果都有注解没有问题。但是，情况就在用注解，真的太多不必要的配置在code中了，虽然不影响业务，但真的让人有强迫症。

**Comment by carryxyh** [comment]
> Spring，我理解不算是入侵，因为我需要他的Autowire呀

你要用spring的autowire所以认为不入侵，那你要用dubbo的rpc功能，加个注解怎么就算成入侵了呢？

**Comment by carryxyh** [comment]
> 这样A岂不是又在xml配置又在用注解配置了

不需要，在xml中配置了的，@Resource或者@autowire就可以用了。

**Comment by JobsZCQ** [comment]
首先，dubbo是一个容器，就像tomcat就像jboss，应该尽可能少的关注甚至不关注与他配置相关的东西，他们都是与业务不直接相关的才对呀。tomcat的配置如果在用户业务中，你觉得合理吗？

**Comment by carryxyh** [comment]
> dubbo是一个容器

完全不是，dubbo是框架，不存放任何bean。和spring和jboss tomcat完全不是同一回事。

**Comment by JobsZCQ** [comment]
不需要refrence A，服务C咋引用A呀？

**Comment by carryxyh** [comment]
@autowire
A

从spring容器中获取啊。。。你之前在xml里配置，不就是为了把A注入到spring里么。。。。。。

**Comment by JobsZCQ** [comment]
autowire需要指定scan位置，而scan又给去掉了额

**Comment by JobsZCQ** [comment]
好，就如你所说不是容器，但是意思是那个意思。框架的config不应该交给用户的业务来管理。至少应该透明。

**Comment by carryxyh** [comment]
1. 我觉得你对dubbo理解有点问题，dubbo是rpc框架，跟容器完全不是一回事。
2. 我不同意你对入侵业务理解，你说你要用spring的autowire，所以在业务代码中价格注解不算入侵。那我就问你，你要不要用dubbo的rpc功能，要用的话，加个注解为什么就入侵了你的业务？这个逻辑没法自圆其说。
3. 我觉得你的使用方式可能有问题（注意是可能。。。），最好的方式是你上传一个demo，我们看一下。@Reference和@Service注解可以替代@autowire和spring的@service。所以并不需要很多注解配置，并不繁琐。

**Comment by carryxyh** [comment]
用config的方式可以完全摒弃xml，终极目的是不用xml，都是用注解配置。这个跟spring的趋势很像。spring boot基本都是注解和你说的code config。
你说的那种注解和xml混用的场景，同样的问题你都可以在spring中找到答案。另外关于你说的繁琐问题，其实只是xml中不再允许scan，而是需要用一个注解scan，说白了增加了一个class，这远远不能算繁琐。

**Comment by JobsZCQ** [comment]
如你所说，我们对dubbo理解可能有些差异。我所描述的场景应该属于正常状态。c引用a时使用autowire没有xml的scan就不可能引用成功，加上reference与xml配置就重复配置了。这个描述应该很清楚的呀。我会抽空搞一个demo

**Comment by JobsZCQ** [comment]
今天其实早想说了，这太多springboot的影子了

**Comment by carryxyh** [comment]
> 加上reference与xml配置就重复配置了

很简单，不要又用注解又用xml就好了，选一个用不就行了么。为什么明知道繁琐还要xml和注解一起用呢

**Comment by carryxyh** [comment]
> 今天其实早想说了，这太多springboot的影子了

所以其实相同的问题我觉得你倒是应该先反馈给spring。问问他们为什么要入侵你的业务，为什么配置很繁琐。dubbo对于注解配置这方面，都是依托于spring的。如果spring可以做到不入侵你的业务，不这么繁琐的配置，那么dubbo就可以。所以建议你去spring的社区询问一下。

**Comment by JobsZCQ** [comment]
不是必须xml和config混用，以前之前做的启动器基于xml的，原来这样设计就是未来对业务的尽可能0入侵。

兄台，要我去咨询spring，有点别样意味的哦
