### ISSUE TITLE
Q: 如何控制单台不并发，多台之间可以并发？

### ISSUE THREAD

**Issue by gMan1990** [apache/incubator-dubbo#2840]
比如提供者A，在a机器上部署了A1，在b机器上部署了A2(人工保证不会在同一台设备下部署多份)
怎么控制a/b单台下不能并发，a与b之间是可以同时执行的？
我试了```并发控制```里说的```<dubbo:service interface="com.foo.BarService" executes="1" />```
但是不是我想要的结果，消费者一并发消费者这边就报错了。我以为是请求到提供者那边wait住。
Q：那这种情况我应该如何实现？

**Comment by carryxyh** [comment]
> 怎么控制a/b单台下不能并发，a与b之间是可以同时执行的？

如果ab都配置executes，对于a来说最多有executes个请求在处理。

消费者报错是因为服务端返回的是错误。

**Comment by gMan1990** [comment]
@carryxyh  那这种场景有什么好的实现方案吗，不要报错的那种。哇o(╥﹏╥)o关闭了？可以让大家讨论下解决方案~

**Comment by carryxyh** [comment]
首先生产级别限流不会使用wait，所以这个问题就关闭了。如果有请你描述清楚业务场景我重新打开这个issue。

> 1、a机器的提供者A1在执行了，那么下一个请求到a机器的消费者只能被等待(/报错)
2、b机器的提供者A2在执行了，那么下一个请求到b机器的消费者只能被等待(/报错)
3、a的A1在执行了，b的A2是可以被同时执行的，机器与机器之间不用控制并发

使用executes配置就可以做到。

**Comment by carryxyh** [comment]
catch住rpc调用即可。
