### ISSUE TITLE
SPI entires dup by 3 times.

### ISSUE THREAD

**Issue by beiwei30** [apache/incubator-dubbo#2842]
Recently, a user commit a issue[1] about that the dubbo.internal's files
has repeated content like this:

```
netty=com.alibaba.dubbo.remoting.transport.netty.NettyTransporter
netty4=com.alibaba.dubbo.remoting.transport.netty4.NettyTransporter
mina=com.alibaba.dubbo.remoting.transport.mina.MinaTransporter
grizzly=com.alibaba.dubbo.remoting.transport.grizzly.GrizzlyTransporter

netty=com.alibaba.dubbo.remoting.transport.netty.NettyTransporter
netty4=com.alibaba.dubbo.remoting.transport.netty4.NettyTransporter
mina=com.alibaba.dubbo.remoting.transport.mina.MinaTransporter
grizzly=com.alibaba.dubbo.remoting.transport.grizzly.GrizzlyTransporter

netty=com.alibaba.dubbo.remoting.transport.netty.NettyTransporter
netty4=com.alibaba.dubbo.remoting.transport.netty4.NettyTransporter
mina=com.alibaba.dubbo.remoting.transport.mina.MinaTransporter
grizzly=com.alibaba.dubbo.remoting.transport.grizzly.GrizzlyTransporter
```

Looks like the entries are dup by 3 times, see details from #2828

**Comment by carryxyh** [comment]
Hi, @beiwei30 
I can't reproduce this on my mac.
I use this command: mvn clean install -Prelease -Dmaven.test.skip=true (before this, I have remove the maven-gpg-plugin).

After doing install, the spi file in dubbo-all/target/ looks nice...

**Comment by chickenlj** [comment]
I also tried locally, but cannot reproduce.
1. clone `dubbo-2.6.4` tag
2. run `mvn clean install -DskipTests`

**Comment by beiwei30** [comment]
I cannot reproduce it either on 2.6.5
