### ISSUE TITLE
配置多个procotol时，和单个protocol处理逻辑不一致

### ISSUE THREAD

**Issue by wangmingbo123** [apache/incubator-dubbo#2851]
![2018-11-29 9 19 56](https://user-images.githubusercontent.com/14872046/49224694-06cb0f00-f41d-11e8-9313-d5dc0b9f20ff.png)

<dubbo:service interface="org.apache.dubbo.demo.DemoService" ref="demoService" protocol="dubbo,http"/>

如代码所示，当配置多个protocol时，类型为RuntimeBeanReference，则意味者必须有相应的协议bean，
否则回报没法找到相应的bean,
当配置单个protocol时，类型为ProtocolConfig，导致即使 不配置<dubbo:protocol>标签，也不会报错

**Comment by tswstarplanet** [comment]
> ![2018-11-29 9 19 56](https://user-images.githubusercontent.com/14872046/49224694-06cb0f00-f41d-11e8-9313-d5dc0b9f20ff.png)
> 
> <dubbo:service interface="org.apache.dubbo.demo.DemoService" ref="demoService" protocol="dubbo,http"/>
> 
> 如代码所示，当配置多个protocol时，类型为RuntimeBeanReference，则意味者必须有相应的协议bean，
> 否则回报没法找到相应的bean,
> 当配置单个protocol时，类型为ProtocolConfig，导致即使 不配置dubbo:protocol标签，也不会报错

请问你贴出来这个是哪个类？

**Comment by wangmingbo123** [comment]
DubboBeanDefinitionParser

**Comment by beiwei30** [comment]
@wangmingbo123 pls. check my comments https://github.com/apache/incubator-dubbo/pull/2852#issuecomment-443976988, we cannot do this.
