### ISSUE TITLE
2.6.3是否不支持在外置tomcat中运行了？

### ISSUE THREAD

**Issue by yhzl** [apache/incubator-dubbo#2854]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.3
* Operating System version: xxx
* Java version: 1.8.0_181

### Steps to reproduce this issue

1. 将spring boot与dubbo整合的项目打成war包放在tomcat下面运行
2. 出现30-Nov-2018 13:09:22.070 严重 [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
3. 在本地main方法运行无问题，用的spring boot 2.0.2

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by kexianjun** [comment]
看看是不是类似的问题 #2535

**Comment by yhzl** [comment]
回退到2.6.2就没问题了,试过很多方法都解决不了，启动后两条严重，数条警告，最后还报个异常
