### ISSUE TITLE
2.6.5 META-INF\dubbo\internal下配置文件内容重复了3遍

### ISSUE THREAD

**Issue by lunda1** [apache/incubator-dubbo#2856]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.5
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

1. 下载2.6.5的jar包
2. 解压进入META-INF\dubbo\internal目录
3. 基本上所有配置文件全部重复了3次

![image](https://user-images.githubusercontent.com/11451381/49272920-2fe7b000-f4ae-11e8-9209-cb08e4c998db.png)

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by carryxyh** [comment]
Focus on this issue:
https://github.com/apache/incubator-dubbo/issues/2856

**Comment by lunda1** [comment]
you mean #2842？sorry，i didn't find this before.

**Comment by carryxyh** [comment]
Yep.
My mistake. 2842 is the right one.

**Comment by cvictory** [comment]
It also happen in dubbo-2.6.4
