### ISSUE TITLE
客户端获取不到服务端暴露的服务 No such any registry to reference 

### ISSUE THREAD

**Issue by paddy-w** [apache/incubator-dubbo#2860]
dubbo版本2.6.0，用xml配置方式，没有用注解，点对点直连。
之前一直运行正常，最近加了一个服务接口。通过服务端的debug日志发现新加服务已经Export了，从客户端调用ApplicationContext#getBean获取代理时，报No such any registry to reference 。之前其他的服务都正常，就这个新加的找不到。

**Comment by clevertension** [comment]
please paste more logs and exception stacktrace, thanks

**Comment by code4wt** [comment]
这个错误应该是服务消费者找不到注册中心，表明 Dubbo 走的是注册中心，但又找不到。如果你通过直联的方式连接服务提供者，理论上是不会报这个错。建议你检查一下直联的配置是否正确。你提供的信息比较少，建议以后可以把“核心”的配置以及日志贴出来，方便大家排查问题

**Comment by zonghaishang** [comment]
@paddy-w 
 
try use ：

```
<dubbo:reference  url="dubbo://ip:port" interface="your interface" id="interfaceName"/>
```

please replace `ip:port` to your real `ip&port` and `interface`

**Comment by paddy-w** [comment]
I got it wrong and sorry for the less information. One important thing that I forgot is some configuration is programmic except XML. What the code do is the same like that referred by @zonghaishang .

After I fix the code. It works well!

Thanks all again! @clevertension @code4wt @zonghaishang
