### ISSUE TITLE
Questions about shutdown graceful

### ISSUE THREAD

**Issue by zonghaishang** [apache/incubator-dubbo#2865]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.0
* Operating System version: mac
* Java version: 1.8

`org.apache.dubbo.config.AbstractConfig`:

```
static {
    // this is only for compatibility
    Runtime.getRuntime().addShutdownHook(DubboShutdownHook.getDubboShutdownHook());
}
```
The jvm hook is registered by default. When the user uses spring, the default hook is not removed. It was the earliest cause of this shutdown graceful, mainly due to this reason.  Please note：
Spring does not register hooks by default, but users may register themselves, spring-boot will also register hooks by default.

`org.apache.dubbo.config.spring.extension.SpringExtensionFactory.ShutdownHookListener`:

```
private static class ShutdownHookListener implements ApplicationListener {
    @Override
    public void onApplicationEvent(ApplicationEvent event) {
        if (event instanceof ContextClosedEvent) {
            // we call it anyway since dubbo shutdown hook make sure its destroyAll() is re-entrant.
            // pls. note we should not remove dubbo shutdown hook when spring framework is present, this is because
            // its shutdown hook may not be installed.
            DubboShutdownHook shutdownHook = DubboShutdownHook.getDubboShutdownHook();
            shutdownHook.destroyAll();
        }
    }
}
```

**Comment by zonghaishang** [comment]
@beiwei30 @chickenlj  Please take a look

**Comment by LiZhenNet** [comment]
> @beiwei30 @chickenlj Please take a look

I have  pull  a request about this。 you can take a look  https://github.com/apache/incubator-dubbo/pull/2901

**Comment by zonghaishang** [comment]
``` java
    public static void addApplicationContext(ApplicationContext context) {
        contexts.add(context);
+        Runtime.getRuntime().removeShutdownHook(DubboShutdownHook.getDubboShutdownHook());
        BeanFactoryUtils.addApplicationListener(context, shutdownHookListener);
    }
```

It looks good, close it now.
