### ISSUE TITLE
升级2.6.5后启动报找不到类异常 com.alibaba.dubbo.config.spring.util.PropertySourcesUtils

### ISSUE THREAD

**Issue by 34176470** [apache/incubator-dubbo#2867]
Environment
Dubbo version: 2.6.5
Operating System version: win10
Java version: 1.8
升级到2.6.5后，启动就报错，
Caused by: java.lang.ClassNotFoundException: com.alibaba.dubbo.config.spring.util.PropertySourcesUtils

**Comment by SawamuraEriri** [comment]
<dependency>
                <groupId>com.alibaba.spring</groupId>
                <artifactId>spring-context-support</artifactId>
                <version>1.0.2</version>
            </dependency>
