### ISSUE TITLE
注册中心连接Zookeeper，无法设置超时，如果Zookeeper不可用，启动时会一直阻塞

### ISSUE THREAD

**Issue by yaohonv** [apache/incubator-dubbo#287]

**Comment by yaohonv** [comment]
在这个类com.alibaba.dubbo.remoting.zookeeper.zkclient.ZkclientZookeeperClient中实例化ZkClient时是否可以传入一个超时时间，不知是否有别的考虑

**Comment by chickenlj** [comment]
Fixed since v2.5.7.
