### ISSUE TITLE
捕获dubbo的Reference 断开事件

### ISSUE THREAD

**Issue by flyer5200** [apache/incubator-dubbo#288]
dubbo的Reference 断开事件能捕获到吗? 如果能, 怎么做?
我用的是GenericService, 想要在Remote Reference 断开或者因为网络原因中断时, Consumer这边可以捕获断开事件来做一定的业务处理.

**Comment by beiwei30** [comment]
不能捕获。当你再次调用的时候，如果断连，会重新建立连接的。
