### ISSUE TITLE
2.6.5使用注解方式怎么配置dubbo:provider filter

### ISSUE THREAD

**Issue by liuyi9608** [apache/incubator-dubbo#2908]
2.6.5使用注解方式怎么配置dubbo:provider filter

**Comment by mercyblitz** [comment]
You could 
- add `@EnableDubboConfig` to enable Dubbo Config 
- annotate `@PropertySource("classpath:/config.properties")` for properties :

    ```properties
    dubbo.provider.id = provider1
    dubbo.provider.filter = ${your.filter.name}
    ```

- annotate `@Service(provider="provider1")` on your service's implementation
