### ISSUE TITLE
dubbo2.5.3 版本升级

### ISSUE THREAD

**Issue by goal578** [apache/incubator-dubbo#2937]
### Environment

* Dubbo version: 2.5.3
* Operating System version: Linux version 2.6.32-642.el6.x86_64/win10 64位
* Java version: jdk1.6.0_25

### Steps to reproduce this issue

想升级jdk为1.8，换上jdk1.8以后，dubbo服务直接起不来，是否需要连带升级 dubbo?如果需要，升级为什么版本合适？升级dubbo是否又会导致spring版本的升级？

**Comment by goal578** [comment]
Which version should I choose?
Currently, dubbo keeps 3 versions evolve in parallel:

2.7.x (master): requires Java 1.8, major feature branch.

2.6.x: requires Java 1.6, minor feature & bugfix branch, GA, production ready.

2.5.x: requires Java 1.6, maintenance branch, only accept security vulnerability and critical bugfix, expected to be EOL soon.

**Comment by goal578** [comment]
升级jdk和dubbo版本无关，导致起不来是spring的版本问题

**Comment by JackESong** [comment]
我这边SpringMVC项目接入Dubbo框架，Spring版本用的4.3.21,Dubbo版本从2.5.3升级到2.6.5，如果Dubbo版本用2.6.4，SpringMVC项目也会有报错。是一个Spring bean版本的问题，导致程序启动不起来。

**Comment by goal578** [comment]
我现在dubbo直接使用原来的2.5.3，jdk升级到1.8，spring-core升级到4.3.1.RELEASE，现在正常了；现在准备把dubbo升级到2.6.5

**Comment by JackESong** [comment]
恩，我也正在体验Dubbo最新版本中

**Comment by goal578** [comment]
增加这两个包：	
  <dependency>
		  <groupId>io.netty</groupId>
		  <artifactId>netty-all</artifactId>
		  <version>4.1.32.Final</version>
	  </dependency>
	  <dependency>
		  <groupId>org.apache.curator</groupId>
		  <artifactId>curator-recipes</artifactId>
		  <version>4.0.1</version>
	  </dependency>
但是会报：

**Comment by JackESong** [comment]
IP地址被占用了，换个地址，重启看看

**Comment by goal578** [comment]
应该2.6.5的版本有一个netty服务，都是用22222端口，需要在什么地方禁用一下

**Comment by JackESong** [comment]
你看看这篇文章 是不是能解决你的问题 https://blog.csdn.net/u013202238/article/details/81432784

**Comment by linxiaobai** [comment]
链接都是404。。
