### ISSUE TITLE
Dubbo服务合并第一次请求数据不准确

### ISSUE THREAD

**Issue by WillieMatthewLiu** [apache/incubator-dubbo#294]
使用dubbo-test-examples/src/main/java/com/alibaba/dubbo/examples/merge测试发现。Consumer第一次请求时数据未合并，第二次请求开始数据被合并。
(0) [group-2.1, group-2.2](1) [group-3.1, group-3.2, group-1.1, group-1.2, group-2.1, group-2.2](2) [group-3.1, group-3.2, group-1.1, group-1.2, group-2.1, group-2.2](3) [group-3.1, group-3.2, group-1.1, group-1.2, group-2.1, group-2.2](4) [group-3.1, group-3.2, group-1.1, group-1.2, group-2.1, group-2.2](5) [group-3.1, group-3.2, group-1.1, group-1.2, group-2.1, group-2.2]

**Comment by ralf0131** [comment]
The `dubbo-test-examples/src/main/java/com/alibaba/dubbo/examples/merge` is not working as expected. 

I have added `merger=true` in `merge-consumer.xml` and `merge-consumer2.xml`. Now it is working as expected. The data will be merged from the first invocation.

```
(0) [group-1.1, group-1.2, group-3.1, group-3.2, group-2.1, group-2.2]
(1) [group-1.1, group-1.2, group-3.1, group-3.2, group-2.1, group-2.2]
(2) [group-1.1, group-1.2, group-3.1, group-3.2, group-2.1, group-2.2]
(3) [group-1.1, group-1.2, group-3.1, group-3.2, group-2.1, group-2.2]
(4) [group-1.1, group-1.2, group-3.1, group-3.2, group-2.1, group-2.2]
(5) [group-1.1, group-1.2, group-3.1, group-3.2, group-2.1, group-2.2]
```

**Comment by ralf0131** [comment]
Your issue should be fixed, please check out the latest code.
