### ISSUE TITLE
[Question] About registering of dubbo service using injvm protocol

### ISSUE THREAD

**Issue by tswstarplanet** [apache/incubator-dubbo#2948]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

I have a following question:

Should a service using injvm protocol register to a registry ?

**Comment by beiwei30** [comment]
no, it should not.
