### ISSUE TITLE
spring boot external  config  invalid

### ISSUE THREAD

**Issue by meiping05** [apache/incubator-dubbo#2949]
### Environment

* Dubbo version: 2.6.0
* Operating System version: Red Hat Enterprise Linux Server release 6.3
* Java version: 1.8.0_92

### Steps to reproduce this issue

Spring Boot使用外部配置文件,没有起作用,还是使用的包内application.properties

**Comment by meiping05** [comment]
https://github.com/meiping05/incubator-dubbo-spring-boot-project

**Comment by meiping05** [comment]
* 目前master使用的是DefaultDubboConfigBinder,都是读取默认的参数
* sample中使用的RelaxedDubboConfigBinder,RelaxedDubboConfigBinder数据版本是正确的,但是beanId是错误的,只有beanId读取是通过前缀去查找的

**Comment by mercyblitz** [comment]
@meiping05 Did you have set Dubbo config bean's id? like :
```properties
dubbo.protocol.id = my-protocol
```

**Comment by meiping05** [comment]
## 配置如下 
* application.properties

````
....
dubbo.application.id = dubbo-provider-demo
.....
spring.profiles.active=prod
````

 * application-prod.properties 

````
....
dubbo.application.id = dubbo-provider-demo-dest
````

## Spring Bean ID

* spring bean id 期望为dubbo-provider-demo-dest实际为dubbo-provider-demo

## issue

* 刚看到这个issue已经被merge到master了

**Comment by mercyblitz** [comment]
You can also use Dubbo `2.6.5`, it has been resolved.
