### ISSUE TITLE
同时使用多协议异常

### ISSUE THREAD

**Issue by 501956430** [apache/incubator-dubbo#295]
同时使用多协议异常，dubbo 跟webservice 协议，启动时提示子类的属性重复，而且是所有的子类的的所有属性重复，不是个别的。 有使用过多协议或遇到过类似问题的兄弟，期待能得到您的指点，谢谢。 

![qq 20160729161105](https://cloud.githubusercontent.com/assets/20204491/17241944/305578b8-55a7-11e6-97ea-11d6a7d5b0af.png)

**Comment by ralf0131** [comment]
Hi, 

I have tried the latest code on master branch, it works fine. I am closing this issue now.

Please feel free to reopen it if it still exists.
