### ISSUE TITLE
CuratorZookeeperClient的重试次数变成1

### ISSUE THREAD

**Issue by jmjyw** [apache/incubator-dubbo#2954]
我看之前版本的CuratorZookeeperClient里重试次数是最大的int，现在变成了1，会不会导致断连之后注册不上服务？

**Comment by notlate** [comment]
> 我看之前版本的CuratorZookeeperClient里重试次数是最大的int，现在变成了1，会不会导致断连之后注册不上服务？

只要failedRegistered里面不为空，那么在retry方法里面就会一直不断的重试注册，直到failedRegistered里面没有内容

**Comment by carryxyh** [comment]
@jmjyw hi,
pls look at @notlate 's comment.
There has a retry task to do this.
