### ISSUE TITLE
为什么Hessian不使用重载方法

### ISSUE THREAD

**Issue by sc834466168** [apache/incubator-dubbo#296]
![qq 20160729163447](https://cloud.githubusercontent.com/assets/6834976/17242593/743d64b6-55aa-11e6-9807-56bac2dbd19a.png)

hessianProxyFactory.setOverloadEnabled(true);

然而dubbo协议是支持重载方法的

**Comment by cytle** [comment]
方法名+参数列表能掉重载方法，PHP调用试过，成功的

服务端
```java
public interface TestService {
    public String getName(User user);
    public String getName(int uid);
}
```

客户端
```php
<?php
getUser_int(1);
// 直接跟上参数类型
getUser_User($user);
```

详细可看
[hessian-调用java重载方法](https://cytle.github.io/2016/09/24/hessian-%E8%B0%83%E7%94%A8java%E9%87%8D%E8%BD%BD%E6%96%B9%E6%B3%95/)

**Comment by ralf0131** [comment]
To enable hessian method overloading, you can set `hessian.overload.method=true` to you provider url.
