### ISSUE TITLE
wrong word in dubbo-website

### ISSUE THREAD

**Issue by wanghui14** [apache/incubator-dubbo#2960]
### Steps to reproduce this issue

1. visit http://dubbo.apache.org/en-us/docs/user/quick-start.html
2. look at the Defining service interfaces section, there is a phrase "The proejct structure should look like this:",the "proejct" is wrong word.

### Expected Result

"project"

### Actual Result

"proejct"

**Comment by satansk** [comment]
You can send a PR to fix this.

**Comment by ralf0131** [comment]
Please send pull request to https://github.com/apache/incubator-dubbo-website

**Comment by CrazyHZM** [comment]
This issue has been fixed.
