### ISSUE TITLE
what's design intent of 'SHARED_EXECUTOR' Attribute in WrappedChannelHandler.java

### ISSUE THREAD

**Issue by CrazyHZM** [apache/incubator-dubbo#2970]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: xxx
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by carryxyh** [comment]
the SHARED_EXECUTOR is a static field.

You can find out where this method is being used:
WrappedChannelHandler#getExecutorService

You can find out where this method is being used. If the user-configured executor does not exist, we will use this executor to handle the event. Maybe this is the meaning of sharing.

**Comment by CrazyHZM** [comment]
I agree with this point of view, but I think we  should create a thread pool while the user-configured executor does not exist, instead of treating it as a static variable.

**Comment by CrazyHZM** [comment]
Each url corresponds to a WrappedChannelHandler instance, that is to say, each WrappedChannelHandler has a static constant SHARED_EXECUTOR.
I think this does not play a role, also if the user does not configure I create a thread pool in the constructor , at least it can be ruled out that the user has configured to use this static constant.

**Comment by carryxyh** [comment]
Sometimes we can design a new dispatcher and server.
In this cases, maybe we should use the shared executor.
