### ISSUE TITLE
DubboCodec re-implements Codec2

### ISSUE THREAD

**Issue by shiyangsheng** [apache/incubator-dubbo#2977]
### Environment

* Dubbo version: 2.7.0-SNAPSHOT
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

DubboCodec extends from ExchangeCodec, which already implements codec2, but DubboCodec still re-implements codec2, and it makes me confused. Is this designed specifically？

**Comment by lixiaojiee** [comment]
This issue has been resolved, I will close it now, thank you for your attention.
