### ISSUE TITLE
Code refactoring suggestion for ActivesLimitFilter

### ISSUE THREAD

**Issue by chickenlj** [apache/incubator-dubbo#2984]
![14_40_00__12_17_2018](https://user-images.githubusercontent.com/18097545/50071839-15cc0280-020e-11e9-8303-7323927e0ec3.jpg)

This is a code snippet comes from `ActivesLimitFilter`, `count` and `RpcStatus` refers to the same instance, the mixed usage of these two ways are quite confusing.

**Comment by danielamorais** [comment]
I'm interested in working on this issue

**Comment by carryxyh** [comment]
Hi, @danielamorais 
Welcome! Looking forward to your pull request.
By the way, I recommend you to participate in our mailing list and share your thoughts

http://dubbo.apache.org/en-us/docs/developers/contributor-guide/mailing-list-subscription-guide_dev.html

**Comment by chickenlj** [comment]
@danielamorais Cool, please, send one PR and link to this issue once done.
