### ISSUE TITLE
dubbo最佳实践问题关于dubbo入参需不需要校验

### ISSUE THREAD

**Issue by zhizhi555555** [apache/incubator-dubbo#2986]
dubbo最佳实践中，没有关于dubbo服务的接口的入参校验。
我认为必要的服务提供方对入参是空的校验还是必须的，不然联调过程很不方便。
你们认为呢？

**Comment by carryxyh** [comment]
最佳实践指的是如何使用dubbo。我个人认为参数校验不是dubbo的最佳实践，而是编码规范的最佳实践。理论上任何方法都需要做参数校验。

Best practice refers to how to use dubbo. I personally think that parameter validation is not a best practice for dubbo, but a best practice for coding specifications. 
In theory, any method needs to do parameter verification.

**Comment by carryxyh** [comment]
Seems like this issue doesn't have any comments, close it now.
