### ISSUE TITLE
Dubbo Service 的方法名不允许有下划线等字符，此限制是否必要

### ISSUE THREAD

**Issue by limingwei** [apache/incubator-dubbo#2990]
![qq 20181218113326](https://user-images.githubusercontent.com/1704535/50130515-f9d16b00-02b8-11e9-9a15-e8445beb1ac8.png)
![qq 20181218113403](https://user-images.githubusercontent.com/1704535/50130516-f9d16b00-02b8-11e9-988d-86250350a1e3.png)

**Comment by beiwei30** [comment]
I think it is a reasonable limitation.
