### ISSUE TITLE
2.6.2版本的filter文件名问题

### ISSUE THREAD

**Issue by ctonb** [apache/incubator-dubbo#3006]
使用org.apache.dubbo.rpc.Filter文件名（在META-INF/dubbo目录下）会导致filter extension的错误，使用com.alibaba.dubbo.rpc.Filter作为文件名is Ok

**Comment by ctonb** [comment]
使用org.apache.dubbo.rpc.Filter文件名（在META-INF/dubbo目录下）会导致filter extension的错误，使用com.alibaba.dubbo.rpc.Filter作为文件名is Ok

**Comment by carryxyh** [comment]
Absolutely
only the code in master has the package name of com.apache.dubbo which is not release yet.
