### ISSUE TITLE
Added UT for ActiveLimitFilter and GenericFilter

### ISSUE THREAD

**Issue by khanimteyaz** [apache/incubator-dubbo#3011]
Added UT for 

1. ActiveLimitFilter 
2. GenericFilter

**Comment by carryxyh** [comment]
Nice work, I saw that u have submit a pr. I will take a look.

**Comment by khanimteyaz** [comment]
@carryxyh  thanks for your care.

**Comment by khanimteyaz** [comment]
As the PR for this isuse has been merged, is it ok to close this issue?

**Comment by carryxyh** [comment]
@khanimteyaz  Yep. I'd like do this.
Thanks for your contribution!
