### ISSUE TITLE
dubbo无法找到生产者

### ISSUE THREAD

**Issue by LiosWong** [apache/incubator-dubbo#3019]
生产者、消费者都已经在注册中心成功注册,报错信息: 
com.alibaba.dubbo.rpc.RpcException: Failed to invoke the method compareWithVideoVerify in the service com.xxx.xxx.risk.service.FacePlusPlusService. No provider available for the service com.xx.xxx.risk.service.FacePlusPlusService:1.0.0.0test from registry 192.168.10.6:2181 on the consumer 172.90.14.230 using the dubbo version 2.5.6. Please check if the providers have been started and registered.
请问是什么问题

**Comment by lixiaojiee** [comment]
please check if the group、version are all consistent

**Comment by LiosWong** [comment]
> please check if the group、version are all consistent

group、version都是对的。找到问题了，由于生产者部署在docker容器中，消费者连接时需要指定目的地址为0.0.0.0的缺省路由

**Comment by lixiaojiee** [comment]
> > please check if the group、version are all consistent
> 
> group、version都是对的。找到问题了，由于生产者部署在docker容器中，消费者连接时需要指定目的地址为0.0.0.0的缺省路由

ok
