### ISSUE TITLE
corethreads设置

### ISSUE THREAD

**Issue by zhangwangcz** [apache/incubator-dubbo#303]
为啥在dubbo.xsd中没有配置corethreads标签，我看代码中已经引入了，是否考虑下个版本把缺失的标签全部加上呢？

**Comment by ralf0131** [comment]
I agree. Indeed `corethreads` should be added to `dubbo.xsd`. May there and more to be added. Would you mind send a pull request?

**Comment by tswstarplanet** [comment]
I have commit a pr: https://github.com/apache/incubator-dubbo/pull/1989

**Comment by ralf0131** [comment]
Fixed.
