### ISSUE TITLE
Readability enhancementfor telnate related changes

### ISSUE THREAD

**Issue by khanimteyaz** [apache/incubator-dubbo#3032]
Enhancing readbility as part of remaining stuff from PR https://github.com/apache/incubator-dubbo/pull/3013/files.

- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: xxx
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

Enhancing readability of code as part of PR https://github.com/apache/incubator-dubbo/pull/3013/files

**Comment by khanimteyaz** [comment]
I am on it.

**Comment by carryxyh** [comment]
Since your pr has been merged, I will close this issue.
Thx for your contribution!
