### ISSUE TITLE
Dubbo version: 2.6.4 是否可以升级spring5 

### ISSUE THREAD

**Issue by cookieka** [apache/incubator-dubbo#3034]
* Dubbo version: 2.6.4
* Java version: 1.8
Dubbo version: 2.6.4 是否可以升级spring5

**Comment by kexianjun** [comment]
没啥问题吧，我们生产目前dubbo 是 2.6.2 ，spring 5.0.9

**Comment by zonghaishang** [comment]
@cookieka 建议升级后回归测试，目前dubbo没有升级到5.x的spring, 除非spring自己不兼容， 目前使用spring 4.x版本不低，应该没问题的
