### ISSUE TITLE
org.apache.dubbo.config.AbstractInterfaceConfig#setRegistry(java.lang.String) does't work

### ISSUE THREAD

**Issue by qinliujie** [apache/incubator-dubbo#3056]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.0

### Steps to reproduce this issue

        ReferenceConfig  referenceConfig = new ReferenceConfig();

        //application
        String appName = AppInfoUtils.getAppName();
        ApplicationConfig applicationConfig = new ApplicationConfig();
        applicationConfig.setName(appName);
        referenceConfig.setApplication(applicationConfig);

        //registry
        //zookeeper://127.0.0.1:2181
        referenceConfig.setRegistry("zookeeper://127.0.0.1:2181");
        ......

### Expected Result

it can use zookeeper registry

### Actual Result

it does't work

```
java.lang.IllegalStateException: No registry config found or it's not a valid config! The registry config is: <dubbo:registry zookeeperProtocol="false" valid="false" id="zookeeper://127.0.0.1:2181" prefix="dubbo.registries." />

	at org.apache.dubbo.config.AbstractInterfaceConfig.checkRegistry(AbstractInterfaceConfig.java:129)
	at org.apache.dubbo.config.AbstractInterfaceConfig.loadRegistries(AbstractInterfaceConfig.java:198)
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:358)
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:314)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:232)
```

**Comment by zonghaishang** [comment]
@qinliujie  chickenlj is right.
