### ISSUE TITLE
Travis CI build failure in dubbo-metadata-report-zookeeper

### ISSUE THREAD

**Issue by khanimteyaz** [apache/incubator-dubbo#3081]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment
Travis CI build environment 

* Dubbo version: xxx
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue
Run build in travis CI from latest master branch
1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

Build should not failed because of dubbo-metadata-report-zookeeper UT. below are current error log while running UT on dubbo-metadata-report-zookeeper 

Running org.apache.dubbo.metadata.store.zookeeper.ZookeeperMetadataReportTest
log4j:WARN No appenders could be found for logger (org.apache.dubbo.common.logger.LoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.305 sec <<< FAILURE! - in org.apache.dubbo.metadata.store.zookeeper.ZookeeperMetadataReportTest
testStoreProvider(org.apache.dubbo.metadata.store.zookeeper.ZookeeperMetadataReportTest)  Time elapsed: 2.461 sec  <<< FAILURE!
java.lang.AssertionError
	at org.apache.dubbo.metadata.store.zookeeper.ZookeeperMetadataReportTest.testStoreProvider(ZookeeperMetadataReportTest.java:59)

Results :

Failed tests: 
  ZookeeperMetadataReportTest.testStoreProvider:59

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
[[1;31mERROR[m] Failed to execute goal [32morg.apache.maven.plugins:maven-surefire-plugin:2.19.1:test[m [1m(default-test)[m on project [36mdubbo-metadata-report-zookeeper[m: [1;31mThere are test failures.[m
[[1;31mERROR[m] [1;31m[m
[[1;31mERROR[m] [1;31mPlease refer to /home/travis/build/apache/incubator-dubbo/dubbo-metadata-report/dubbo-metadata-report-zookeeper/target/surefire-reports for the individual test results.[m
[[1;31mERROR[m] -> [1m[Help 1][m
[[1;31mERROR[m] 
[[1;31mERROR[m] To see the full stack trace of the errors, re-run Maven with the [1m-e[m switch.
[[1;31mERROR[m] Re-run Maven using the [1m-X[m switch to enable full debug logging.
[[1;31mERROR[m] 
[[1;31mERROR[m] For more information about the errors and possible solutions, please read the following articles:
[[1;31mERROR[m] [1m[Help 1][m http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[[1;31mERROR[m] 
[[1;31mERROR[m] After correcting the problems, you can resume the build with the command
[[1;31mERROR[m]   [1mmvn <goals> -rf :dubbo-metadata-report-zookeeper[m
/home/travis/.travis/job_stages: line 523:  4690 Terminated              travis_jigger "${!}" "${timeout}" "${cmd[@]}"
```

**Comment by lovepoem** [comment]
Now ci succeed . close via https://github.com/apache/incubator-dubbo/commit/5ea4fa531f9ec5ae446d4cb1ef2417b53712bd46
