### ISSUE TITLE
can dubbo default loadbalance support protocol priority?

### ISSUE THREAD

**Issue by kevin-wang001** [apache/incubator-dubbo#3089]
dubbo provider 多协议暴露时，consumer 端能否默认支持按协议优先级来调用？

比如：provider 暴露 rest 和 dubbo 两种协议的服务，consumer 消费，在调用时，如果优先走 dubbo 协议效率会更高。现在是 RandomLoadBalance

**Comment by lexburner** [comment]
`Protocol` and `LoadBalance` are two different layers in Dubbo. 

Two different protocols will be exported on different ports, there is no mixed invocation between two protocols. Can you provide more details about your question?

**Comment by zonghaishang** [comment]
@kevin-wang001 
<dubbo:reference protocol="dubbo" ../>
or

`@Reference(protocol = { "dubbo" }, ...)`

**Comment by zonghaishang** [comment]
@kevin-wang001 
If this does not solve your problem, you can extend the implementation of a route yourself, giving priority to the dubbo protocol.

**Comment by kevin-wang001** [comment]
Thanks. It works
