### ISSUE TITLE
使用leastactive在provider启动时不会使用预热功能

### ISSUE THREAD

**Issue by LaughXP** [apache/incubator-dubbo#3097]
使用leastactive, provider启动后, 由于sameWeight=true(weight默认都是100), 导致无法走到以下步骤
```java
if (!sameWeight && totalWeight > 0) {
            // If (not every invoker has the same weight & at least one invoker's weight>0), select randomly based on totalWeight.
            int offsetWeight = random.nextInt(totalWeight);
            // Return a invoker based on the random value.
            for (int i = 0; i < leastCount; i++) {
                int leastIndex = leastIndexs[i];
                offsetWeight -= getWeight(invokers.get(leastIndex), invocation);
                if (offsetWeight <= 0)
                    return invokers.get(leastIndex);
            }
        }
```
就无法调用getWeight方法进行预热。这是一个bug吗？
dubbo 2.5.9

**Comment by congcongfu** [comment]
我也遇到了

**Comment by careyyu** [comment]
围观围观

// assert(leastCount > 0)
        if (leastCount == 1) {
            // 如果只有一个最小则直接返回, 大流量场景下   一个provider启动，会不会直接进入到这里呢
            return invokers.get(leastIndexs[0]);
        }
        if (! sameWeight && totalWeight > 0) {
            
            int offsetWeight = random.nextInt(totalWeight);
            for (int i = 0; i < leastCount; i++) {
                int leastIndex = leastIndexs[i];
                offsetWeight -= getWeight(invokers.get(leastIndex), invocation);
                if (offsetWeight <= 0)
                    return invokers.get(leastIndex);
            }
        }
