### ISSUE TITLE
关于 Dubbo web-fragment 配置 "org.springframework.web.context.ContextLoaderListener"  监听器

### ISSUE THREAD

**Issue by Johnson-Jia** [apache/incubator-dubbo#3098]
请问什么时候修复 web-fragment.xml 配置的Spring 监听器 “org.springframework.web.context.ContextLoaderListener” ， 具体发版日期能提供一下吗？

**Comment by lohcve** [comment]
我也是被这个问题坑了一整天，我从2.6.2升级到2.6.5后，从外部tomcat启动spring boot项目会报错，后来慢慢调试tomcat的源代码才发现多出了一个ContextLoaderListener监听器，dubbo只能用2.6.2的版本，超过这个版本就存在web-fragment.xml 文件，这个文件中配置了一个“org.springframework.web.context.ContextLoaderListener”监听器，导致在外部tomcat中运行spring boot项目时，会执行这个监听器，然后就抛出异常。使用spring boot内嵌tomcat没有问题。

**Comment by mangowbm** [comment]
@Johnson-Jia 有确认新版本会解决这个问题么？？ 2.6.6+还是要2.7.x的，外部tomcat运行有什么方式可以临时解决么？

**Comment by Johnson-Jia** [comment]
2.7. x 会解决这个问题，  因为 2.6.[3 4 5]  在dubbo-config/dubbo-config-spring 下面引入了 web-fragment.xml 配置文件，配置了 ContextLoaderListener 。  

临时解决可以把dubbo 切换到2.6.2版本。

**Comment by beiwei30** [comment]
it's been fixed.

**Comment by beiwei30** [comment]
https://github.com/apache/incubator-dubbo/pull/2725
