### ISSUE TITLE
dubbo-config package hard coded value replacement for few java class

### ISSUE THREAD

**Issue by khanimteyaz** [apache/incubator-dubbo#3100]
Replace existing hard coded values for dubbo-config below classes

- dubbo-common/src/main/java/org/apache/dubbo/common/Constants.java
- dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractConfig.java
- dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java
- dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractMethodConfig.java
- dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractReferenceConfig.java
- dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ConsumerConfig.java

Along with hard coded value replacement have done small refactoring to use java stream and lambda.

- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: xxx
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by khanimteyaz** [comment]
on it.

**Comment by zonghaishang** [comment]
merged, close it now.
