### ISSUE TITLE
<Your first Dubbo application> Some descriptions are wrong

### ISSUE THREAD

**Issue by maochaowu** [apache/incubator-dubbo#3125]
http://dubbo.apache.org/en-us/blog/dubbo-101.html  

Run the server
mvn -Djava.net.preferIPv4Stack=true -Dexec.mainClass=com.alibaba.dubbo.samples.server.Application exec:java

Run the client
mvn -Djava.net.preferIPv4Stack=true -Dexec.mainClass=com.alibaba.dubbo.samples.client.Application exec:java

The package name of the class is incorrect

the true is  "org.apache.dubbo.samples.provider.Application " & "org.apache.dubbo.samples.consumer.Application "

**Comment by ralf0131** [comment]
Hi, would you mind send a pull request?
