### ISSUE TITLE
注解

### ISSUE THREAD

**Issue by objectboy2016** [apache/incubator-dubbo#3147]
不能将 
dubbo:service  
dubbo:reference
dubbo:registry
.
.
.
用注解代替吗?  xml看着好像很烦

**Comment by tswstarplanet** [comment]
There are already annotation config, you can see:
http://dubbo.apache.org/zh-cn/docs/user/configuration/annotation.html

**Comment by wangruyu1** [comment]
可以，能像spring注解一样使用，我参考的是https://github.com/apache/incubator-dubbo-spring-boot-project。
