### ISSUE TITLE
dubbo针对契约测试有什么优雅的解决方案吗？

### ISSUE THREAD

**Issue by arccode** [apache/incubator-dubbo#3150]
在单元测试和集成测试间增加【契约测试】，如果服务间调用使用dubbo协议，有什么解决方案吗？

**Comment by Bricks-Man** [comment]
不是很懂契约测试，查了一下。我感觉你自己写个客户端来访问服务端是不是就算契约测试了？

**Comment by beiwei30** [comment]
you can file issue on dubbo admin project (https://github.com/apache/incubator-dubbo-ops), we plan to provide mock function there.
