### ISSUE TITLE
How to disabled qos-server on dubbo version 2.6.0

### ISSUE THREAD

**Issue by yuxiao97** [apache/incubator-dubbo#3155]
* Dubbo version: 2.6.0
Like title, when I disabled qos-server on 2.6.0，but not worked，I use XML config，example:
<dubbo:application name="demo-provider">
    <dubbo:parameter key="qos.enable" value="false"/>
  </dubbo:application>

**Comment by kexianjun** [comment]
参数名字换成qos-enable看看

**Comment by yuxiao97** [comment]
>           参数名字换成qos-enable看看

No, can not worked.

**Comment by CrazyHZM** [comment]
你试着吧<dubbo:parameter key="qos.enable" value="false"/>配置拿出来，别包裹在<dubbo:application ></dubbo:application>

**Comment by CrazyHZM** [comment]
如果还是不行，你可以参考这个issues ＃1545

**Comment by yuxiao97** [comment]
> 如果还是不行，你可以参考这个issues ＃1545
参考的结果就是可能和版本有关系 我的是2.6.0

**Comment by yuxiao97** [comment]
Nobody know this problem or fixed?

**Comment by yuxiao97** [comment]
在2.6.0中发现无法禁用qos-server，源码截图如下：
![image](https://user-images.githubusercontent.com/27430795/51370148-10c1e200-1b31-11e9-9564-b21201bb632b.png)
是否启用qos-server,在2.6.0+的版本中可以配置了，配置代码如下:
```
<dubbo:application name="demo-server" >
        <dubbo:parameter key="qos.enable" value="false" />
        <dubbo:parameter key="qos.port" value="33333"/>
        <dubbo:parameter key="qos.accept.foreign.ip" value="*"/>
    </dubbo:application>
```
在服务封装URL时，会把配置参数配置到URL，qos-server启动时会检查配置参数，2.6.1的源码截图如下：
![image](https://user-images.githubusercontent.com/27430795/51370392-e7ee1c80-1b31-11e9-9918-874af0a010dc.png)
