### ISSUE TITLE
future invoke would block at  org.apache.dubbo.rpc.AsyncRpcResult#getValue 

### ISSUE THREAD

**Issue by uglycow** [apache/incubator-dubbo#3169]
future invoke would block at  org.apache.dubbo.rpc.AsyncRpcResult#getValue. 

DubboInvoker now return AsyncRpcResult other than RpcResult with a default value.  the framework would block when a filter try to access the the result value,  even though it's future invoke.

it just behave differently.

**Comment by carryxyh** [comment]
If u want to get value from future and the future is not completed, it will block.

> DubboInvoker now return AsyncRpcResult other than RpcResult with a default value

Nope, just in async way, but not in sync way.

**Comment by uglycow** [comment]
the invoke return very soon and i would get a default value when i access the result value in my filter in async way before. 

now, the invoke would block and i would get the real value when i access the result value in my filter.

different behavior.

**Comment by carryxyh** [comment]
Don't get your point.
Is this cause some exceptions or sth?

**Comment by uglycow** [comment]
i mean if a legacy filter occasionally tried to access the result value,  we would get blocked there,  that's not the case before.

**Comment by chickenlj** [comment]
> DubboInvoker now return AsyncRpcResult other than RpcResult with a default value. the framework would block when a filter try to access the the result value, even though it's future invoke.

I agree with what @uglycow pointed out, we should avoid blocking legacy Filter extensions.

**Comment by chickenlj** [comment]
Fixed with https://github.com/apache/incubator-dubbo/pull/3185
