### ISSUE TITLE
 Please check registry access list (whitelist/blacklist).

### ISSUE THREAD

**Issue by xyang160** [apache/incubator-dubbo#317]

**Comment by lynnchae** [comment]
我也遇到这个问题，重启就好了，亟待解决

**Comment by haiboyang** [comment]
我也遇到这问题不知道怎么解决，隔断时间就会出现这个问题

**Comment by hesy007** [comment]
这个问题经常在系统启动时会遇到。。。

**Comment by lovepoem** [comment]
provider 没有服务，一般是服务端在重启，或者某个应用的服务全挂了。

**Comment by hesy007** [comment]
出现这个问题时，provider 是正常的，通过 dubbo admin 可以看到。而且，将这个 provider先禁用，再启用，consumer 端就恢复了，不再报错。猜测问题出在 provider 注册服务后，consumer 端没有收到通知而未刷新本地缓存的服务列表。

**Comment by ralf0131** [comment]
Hi, 

Would you please provide detail step/examples to reproduce this issue?
