### ISSUE TITLE
Remove unnessary content for pom file

### ISSUE THREAD

**Issue by htynkn** [apache/incubator-dubbo#3186]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

Now dubbo requires java 8 or above, I notice there are still some configuration or profile for java6 (and hudson?)

Those content is not nessary any more, we need clean up it.

**Comment by tswstarplanet** [comment]
In my impression, dubbo will not support lower version than jdk 8 when the 3.0 version realease ?

**Comment by ralf0131** [comment]
@htynkn Maybe you can add some detail items that can be done, so that someone could come in to help.

**Comment by CrazyHZM** [comment]
> I think the following detail need check:
> 
> 1. argline set -Xmx to 512M
> 2. profile - java6 need remove
> 3. profile - test need remove?
> 4. profile - hudson need remove
> 5. profile - java8-vm-args need remove
> 6. maven-source-plugin - hard code version, should use properties

The first configuration seems to exist already, what do you think?

**Comment by htynkn** [comment]
> > I think the following detail need check:
> > 
> > 1. argline set -Xmx to 512M
> > 2. profile - java6 need remove
> > 3. profile - test need remove?
> > 4. profile - hudson need remove
> > 5. profile - java8-vm-args need remove
> > 6. maven-source-plugin - hard code version, should use properties
> 
> The first configuration seems to exist already, what do you think?

sorry, I mean do we really limit memory to 512M? or it's better let JVM decide?
will add explanation for item 1

**Comment by ralf0131** [comment]
> In my impression, dubbo will not support jdk lower version than version 8 when the 3.0 version realease ?

Dubbo will only support Java 8 and above from 2.7 onwards.
