### ISSUE TITLE
注解配置无法启动

### ISSUE THREAD

**Issue by yexueyouling** [apache/incubator-dubbo#3190]
按照注解配置，使用Springboot，搭建了两个工程，一个消费者，一个服务者，并且创建了一个zookeeper容器。结构如下：
![image](https://user-images.githubusercontent.com/26735625/51016127-16a44a00-15aa-11e9-8360-2daac8012a1c.png)
服务者可以正常启动。
消费者启动失败，有两个错误问题
1、@Reference无法注入服务者的服务。
2、启动报错：Duplicate application configs: <dubbo:application name="service-dUbbo-custom" id="service-dUbbo-custom" /> and <dubbo:application qosEnable="false" />

完全不知道是什么原因。

源码：
消费者：https://github.com/yexueyouling/service-dobbo-custom.git
服务者：https://github.com/yexueyouling/service-dobbo-server.git

**Comment by gudegg** [comment]
ApplicationConfig重复配置了，你把消费者的`ApplicationConfig`Bean配置移除掉再试下

**Comment by kexianjun** [comment]
你的消费端配置依赖

```
<dependency>
			<groupId>com.example</groupId>
			<artifactId>service-dobbo-server</artifactId>
			<version>0.0.1-SNAPSHOT</version>
    </dependency>
```
com.example.dubbo.service.IDemoServer 的实现在 com.example.dubbo.service package,然后又在controller 里面引用IDemoServer，你是想用调用jvm本地调用（injvm）服务吗？Demo可以参考https://github.com/apache/incubator-dubbo/tree/master/dubbo-demo 这里面的，基于xml配置启动的和基于注解的都用

**Comment by yexueyouling** [comment]
@gudegg 不可以去掉消费者的Application Bean，否则会引起下面的错误。
![image](https://user-images.githubusercontent.com/26735625/51152837-88c9a700-18a8-11e9-907c-d32eb91bd431.png)

**Comment by kexianjun** [comment]
> @kexianjun 你说的对，我可以引入server的依赖，然后正常引用。但是我使用了zookeeper，我不希望将server引入到消费端，不然项目庞大了，每引用另一个工程，都要去加依赖，岂不是很难管理。

api的定义和实现分成不同的包，就像dubbo提供的demo一样，api作为公共的依赖

**Comment by yexueyouling** [comment]
@kexianjun 你的意思是，在服务者和消费者中间，加一个中间工程，所有的消费者都调用这个工程，所有的服务这都注入到这个中间工程对吗？

**Comment by yiyutao** [comment]
最近使用最新的springboot和dubbo-spring-boot-starter会报dubbo:application重复配置，我现在的解决办法是把xml中的dubbo:application删除，然后在application.yml单独配置dubbo:application
