### ISSUE TITLE
服务发布的时候，怎么提前摘掉一个节点的服务

### ISSUE THREAD

**Issue by lpydhbt** [apache/incubator-dubbo#3203]
### Environment

* Dubbo version:2.5.7
* Operating System version: linux
* Java version: jdk1.8
 
dubbo优雅关机会检测dubbo的线程池，如果线程池没有任务那么就会提前关闭容器。但是自己的业务线程池又脱离了dubbo线程池的任务，检测不到业务线程池的状态就关闭了，所以希望提前将该节点的服务摘到，让调用方不再向该服务发送任务，等待一段时间后再关机。
![image](https://user-images.githubusercontent.com/19490071/51027188-3009be00-15cb-11e9-9fd1-4b7ed641b0ee.png)

**Comment by lpydhbt** [comment]
目前自己有两个想法
1.调用star-admin的接口，但是没有找到一个统一的去掉某个节点的服务，都是精确到某个具体的方法。所以觉得不好弄
2.提前将的该节点的zk断掉

**Comment by yinghuzhu** [comment]
I wrote a api in the dubbo-admin to disable all of the service in the host. the code like this:

`
    @Autowired
    private ProviderService providerService;
    @Autowired
    private Tool tool;


     //disable services
       List<Provider> providers ;
        try {
            providers = providerService.findByAddress(address);
        }
        catch (Exception e){
            logger.error(e.getMessage()+": "+address, e);
            return false;
        }
        if (!CollectionUtils.isEmpty(providers)) {
            try {
                for (Provider provider : providers) {
                    if (tool.isProviderEnabled(provider)) {
                        providerService.disableProvider(provider.getId());
                    }
                }
            }
            catch (Exception e){
                logger.error(e.getMessage()+": "+address, e);
                return false
            }
        }
`

**Comment by lpydhbt** [comment]
> I wrote a api in the dubbo-admin to disable all of the service in the host. the code like this:
> 
> `
> @Autowired
> private ProviderService providerService;
> @Autowired
> private Tool tool;
> 
> ```
>  //disable services
>    List<Provider> providers ;
>     try {
>         providers = providerService.findByAddress(address);
>     }
>     catch (Exception e){
>         logger.error(e.getMessage()+": "+address, e);
>         return false;
>     }
>     if (!CollectionUtils.isEmpty(providers)) {
>         try {
>             for (Provider provider : providers) {
>                 if (tool.isProviderEnabled(provider)) {
>                     providerService.disableProvider(provider.getId());
>                 }
>             }
>         }
>         catch (Exception e){
>             logger.error(e.getMessage()+": "+address, e);
>             return false
>         }
>     }
> ```
> `

sry,i find this as you say,in com.alibaba.dubbo.governance.web.home.module.screen.Disable,but i don`t know how to invoke this.

 com.alibaba.dubbo.governance.web.home.module.screen.Disable:

    protected String doExecute(Map<String, Object> context) throws Exception {
        String address = request.getParameter("provider");
        if (address == null || address.length() == 0) {
            address = request.getParameter("client");
        }
        if (address == null || address.length() == 0) {
            throw new IllegalArgumentException("The url provider parameter is null! Usage: " + request.getRequestURL().toString() + "?provider=" + operatorAddress);
        }
        List<Provider> providers = providerService.findByAddress(address);
        if (providers != null && providers.size() > 0) {
            for (Provider provider : providers) {
                if (!currentUser.hasServicePrivilege(provider.getService())) {
                    throw new IllegalStateException("The user " + currentUser.getUsername() + " have no privilege of service " + provider.getService());
                }
            }
            for (Provider provider : providers) {
                provider.setUsername(operator);
                provider.setOperatorAddress(operatorAddress);
                providerService.disableProvider(provider.getId());
            }
        }
        return "Disable " + (providers == null ? 0 : providers.size()) + " services.";
    }

**Comment by yinghuzhu** [comment]
@lpydhbt  I export the method as a http api and then it can be called anywhere .

**Comment by lpydhbt** [comment]
@yinghuzhu  dubbo-admin 2.5.7 use [webX](http://www.openwebx.org/), uri is complex......

**Comment by lpydhbt** [comment]
@Kiddinglife  gracefulshutdown()  only check dubbo thread pool ,not check own threadPool。so must remove the provider service  from  consumer a few seconds before  shutdown provider。

**Comment by lpydhbt** [comment]
@Kiddinglife  and modify source code is not recommended is my group。

**Comment by yinghuzhu** [comment]
@lpydhbt I add a new controller in the spring mvc  . it didn't depend on webX

**Comment by lpydhbt** [comment]
@yinghuzhu  i  have found uri use webx，spring mvc not fount use Dubbo version:2.5.7。tks very much

**Comment by lpydhbt** [comment]
@yinghuzhu  and i have another question,if i disable the provider A use dubbo Admin,and redeploy this provider A,need i cancel disable the provider use dubbo admin or self cancel。

**Comment by LiZhenNet** [comment]
可以自己定义一个shutdownhook,然后剔除掉dubbo本身的，在自定义的hook中 实现等待，最后调用dubbo 本身的shutdownhook的方法进行停机。

**Comment by lpydhbt** [comment]
@LiZhenNet 除掉dubbo本身shutdownhook需要修改源码吗

**Comment by lpydhbt** [comment]
@yinghuzhu  i use deleteStaticProvider() instead of disableProvider(), because disableProvider() i don't find the  http api of recover the provider.

**Comment by yinghuzhu** [comment]
> @yinghuzhu and i have another question,if i disable the provider A use dubbo Admin,and redeploy this provider A,need i cancel disable the provider use dubbo admin or self cancel。

you are right , it must need to be enable when it is redeployed after the provider is disable . 



> @yinghuzhu i use deleteStaticProvider() instead of disableProvider(), because disableProvider() i don't find the http api of recover the provider.

I think deleteStaticProvider is ok if you wouldn't like to enable the provider after the provider is redeployed .

**Comment by LiZhenNet** [comment]
> @LiZhenNet 除掉dubbo本身shutdownhook需要修改源码吗

新版本的话不需要，org.apache.dubbo.config.DubboShutdownHook#unregister

**Comment by lpydhbt** [comment]
> 新版本的话不需要，org.apache.dubbo.config.DubboShutdownHook#unregister
> 
> 你先看一下你用的版本有没有 DubboShutdownHook 这个类吧， 因为这个是后加的


嗯嗯，谢了。目前版本没有，还是采用调用dubbo-admin接口

**Comment by lpydhbt** [comment]
@yinghuzhu tks very much.
