### ISSUE TITLE
Spelling mistake in dubbo manual

### ISSUE THREAD

**Issue by Kiddinglife** [apache/incubator-dubbo#3212]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment
None
### Steps to reproduce this issue
 - [https://dubbo.incubator.apache.org/zh-cn/docs/dev/principals/robustness.html](https://dubbo.incubator.apache.org/zh-cn/docs/dev/principals/robustness.html)
 -  ctrl-F search the key words of `服务消息者从注册中心拿到提供者列表后`
### Expected Result
service cosumers
### Actual Result
**服务消息者**
```

**Comment by lovepoem** [comment]
Please send a pr in https://github.com/apache/incubator-dubbo-website

**Comment by Kiddinglife** [comment]
ok. i will do it later.

**Comment by beiwei30** [comment]
https://github.com/apache/incubator-dubbo-website/issues/277
