### ISSUE TITLE
How Dubbo handles the failed RPC Invocation with different failing reasons?

### ISSUE THREAD

**Issue by Kiddinglife** [apache/incubator-dubbo#3215]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Confusion
 - Are there a feature for batched rpc in dubbo? 
what I mean batched rpc is that the individual invocations in a batch are dispatched by a single thread in server-side in the order in which they were placed into the batch message, which guarantees the individual operations in a batched rpc are processed in order in the server.

 - the official-site-doc says we can set up retry-timeout in an xml file and then the client will retry all the failed invocations regardless what's failing the invocation. 
   - Does the Dubbo follow at-most-once semantics when handling failures? 
   - How does Dubbo handle failed invocations in the following cases:
      1. A connection could not be established due to the crash of the remote physical machine (connection unreachable error)
      2. A connection could not be established due to the crash of the remote process (connection refused error)
      3. A connection lost due to the accident shutdown of the remote physical machine (connection unreachable error)
      4. A connection lost due to the crash of the remote process (connection refused error)
      6. An remote invocation timeout expired due to software bug such as thread overflowed, deadlock or high cpu loads, oom.
      7. An exception occurred while sending the request 
      8. An exception occurred while receiving the reply
      9. An exception occurred after sending the request 
      10. An exception occurred after receiving the reply

where abcde are the failure cases and fghi are the state of the system when error happens.
that means we have 20 combinations that need to take into account...

Regards,
Thanks.

**Comment by manzhizhen** [comment]
Regarding the first question, you refer to the batch message, which is only consumed and answered by one thread on the provider side. Then the batch message can be sent by different threads on the consumer side, as long as the batch number is one, right?

关于第一个问题，你指的批量消息，在provider端只由一个线程来消费和应答，那么这个批量消息在consumer端可以由不同的线程来发送，只要批次号是一个就行了是吧？

**Comment by Kiddinglife** [comment]
yes, so it is.

On Sun, 13 Jan 2019 at 11:36 am, yizhenqiang <notifications@github.com> wrote:

Regarding the first question, you refer to the batch message, which is only consumed and answered by one thread on the provider side. Then the batch message can be sent by different threads on the consumer side, as long as the batch number is one, right?

?????????????????provider???????????????????????consumer???????????????????????????

?

**Comment by manzhizhen** [comment]
Then I have a problem, since the consumer side can send messages of the same batch number in multiple threads, then what is the meaning of guaranteeing the same thread consumption on the provider side? Can you give a scene?

那我有个问题，既然consumer端可以多线程发送同一批次号的消息，那么在provider端保证同一线程消费的意义在哪里？能举个场景吗？

**Comment by Kiddinglife** [comment]
It really depends on the imp. One simple way is to bundle all the batched invocations in the same invocation message, in which case it can be sent by any available thread in a client.

We can also put two invocations across more than one invocation message in client but it requires further ordering of the received invocation messages in server.

The key point is the requirement of the ordering of the invocations that are involed in a batch.

Pseudo codes may look like this:
Client side
Batchcall bc = new Batchcall:
batchcall.add(f1);
Batchcall.add(f2);
Batchcall.send()

In Server side. The ordering of invocation must be f1 then f2 regardless of whichever thread is executing the invocation.

Regards,
Thanks.

On Sun, 13 Jan 2019 at 12:07 pm, yizhenqiang <notifications@github.com<mailto:notifications@github.com>> wrote:

Then I have a problem, since the consumer side can send messages of the same batch number in multiple threads, then what is the meaning of guaranteeing the same thread consumption on the provider side? Can you give a scene?

那我有个问题，既然consumer端可以多线程发送同一批次号的消息，那么在provider端保证同一线程消费的意义在哪里？能举个场景吗？

**Comment by manzhizhen** [comment]
Seeing your case, you probably understand what effect you want, and it doesn't matter if you specify a thread to execute on the provider side.
To ensure that the messages are executed in order, the RPC method is better. For example, if you perform the next RPC after the previous RPC call, you can guarantee that the first RPC is executed first. The secondary RPC, the consumer terminal machine for loop, is implemented.

But if you really want Dubbo to implement, there are still a few issues to discuss, such as:
1. How do bulk messages respond in batches?
2. What should I do if the bulk message fails to execute halfway?

In fact, the easiest way is to apply the package to the for loop call. Of course, if the framework is implemented, you can reduce some network back and forth overhead.

看到你举的case，大概明白你想要什么效果了，感觉和provider端指定一个线程执行关系到不大。
要保证消息按照顺序执行，通过RPC的方式是比较好做的，比如你在前一次RPC调用结束后再进行下一次RPC，就可以百分百保证是先执行完第一次RPC再执行第二次RPC，即consumer端子机for循环来实现。

但如果真要Dubbo来实现，还有几个问题需要讨论，例如：
1. 批量消息如何批量应答？
2. 批量消息中途执行失败该如何处理？

其实，最简单的方式，就是应用自己对for循环调用进行下包装，当然，如果框架实现，可以减少一些网络来回开销。

**Comment by kexianjun** [comment]
对于批量处理的需求，provider端提供批量处理的接口不是更合理吗，比如接口接受list参数，服务提供方按顺序处理请求

**Comment by manzhizhen** [comment]
> 对于批量处理的需求，provider端提供批量处理的接口不是更合理吗，比如接口接受list参数，服务提供方按顺序处理请求

@Kiddinglife 的意思应该是顺序调不同的provider的服务

**Comment by Kiddinglife** [comment]
> @Kiddinglife 的意思应该是顺序调不同的provider的服务
@Kiddinglife is saying the server should execute the multi-invocations in the same ordering as the client defines them.  

@manzhizhen you are right. Something I need to point out is that the sample functions f1 anf f2 in the above are expected to be defined and executed in the scope of a single server's process instead of multi-server.

regards.

**Comment by manzhizhen** [comment]
> > @Kiddinglife 的意思应该是顺序调不同的provider的服务
> > @Kiddinglife is saying the server should execute the multi-invocations in the same ordering as the client defines them.
> 
> @manzhizhen Something I need to point out is that the sample functions f1 anf f2 in the above are expected to be defined and executed in the scope of a single server's process instead of multi-servers.
> 
> regards.

Sorry, I still don't understand what kind of problem you can solve in this way. The business party can also achieve this effect by installing the order itself, and can get the return value every time.

抱歉，我还是没有理解到你说的这种方式能解决哪些问题，业务方自己安装顺序调用其实也能达到此效果，并且每次调用都能拿到返回值。

**Comment by Kiddinglife** [comment]
all right. Thanks for your time in the discussion about batched invocation. I think we can let it go at this moment.

It is more interesting if someone can tell me what actions the Dubbo take in such cases I mentioned above?

Regards.

On Mon, 14 Jan 2019 at 1:51 am, yizhenqiang <notifications@github.com<mailto:notifications@github.com>> wrote:

@Kiddinglife<https://github.com/Kiddinglife> 的意思应该是顺序调不同的provider的服务
@Kiddinglife<https://github.com/Kiddinglife> is saying the server should execute the multi-invocations in the same ordering as the client defines them.

@manzhizhen<https://github.com/manzhizhen> Something I need to point out is that the sample functions f1 anf f2 in the above are expected to be defined and executed in the scope of a single server's process instead of multi-servers.

regards.

Sorry, I still don't understand what kind of problem you can solve in this way. The business party can also achieve this effect by installing the order itself, and can get the return value every time.

抱歉，我还是没有理解到你说的这种方式能解决哪些问题，业务方自己安装顺序调用其实也能达到此效果，并且每次调用都能拿到返回值。

**Comment by Kiddinglife** [comment]
Any updates on failed rpc handlings?

**Comment by manzhizhen** [comment]
As for the "at-most-once" semantics, I don't think Dubbo has done that. If we want to do at-most-once, we need to record which requestId has successfully responded on the provider side. When a duplicate requestId arrives, we throw an exception to the consumer side to say that the processing is successful or return the previous value (if there is a cache). At present, we have seen the implementation of dubbo, which should not be done. Personally, it is more appropriate for providers to do idempotent work by themselves.

关于“at-most-once”语义，我认为dubbo是没有做到这一点的，如果想做到at-most-once，在provider端需要记录哪些requestId已经成功应答，当有重复的requestId到来时，给consumer端抛异常说处理成功或者将之前的值（如果有缓存的话）再返回。目前看了dubbo的实现，应该是没有这样做的，个人感觉还是provider的业务方自己做幂等更合适点。

**Comment by manzhizhen** [comment]
about any updates on failed rpc handlings, I'll get back to you tomorrow.

**Comment by Kiddinglife** [comment]
Hi @manzhizhen,
I updated my question. plz take a  look and let me know how you think about it.
regards.

**Comment by Kiddinglife** [comment]
@manzhizhen  so far so good. thanks. I am closing this issue and could re-open in the future if needed. lol.
