### ISSUE TITLE
Dubbo 新版本去掉了 dubbo.properties，因为该约定经常造成配置冲突，是否不太准确？

### ISSUE THREAD

**Issue by manzhizhen** [apache/incubator-dubbo#3216]
### Environment

* Dubbo version: master branch

### Steps to reproduce this issue
https://dubbo.apache.org/zh-cn/docs/dev/principals/configuration.html 中“Dubbo 新版本去掉了 dubbo.properties，因为该约定经常造成配置冲突。” 该描述是否不太准确？目前代码中应该有dubbo.properties的处理逻辑，例如：org.apache.dubbo.common.utils.ConfigUtils

**Comment by chickenlj** [comment]
是的，这里是一处不太严谨的描述，我想作者要表达的是Spring对`.properties配置`驱动开发的支持。
但是dubbo.properties并没有被去除，而是继续作为一个配置源被Dubbo框架加载。

**Comment by chickenlj** [comment]
@mercyblitz 我来尝试修正一下作者的这部分描述。
