### ISSUE TITLE
dubbo quick start API 链接错误

### ISSUE THREAD

**Issue by yinyuhang** [apache/incubator-dubbo#3223]
[dubbo quick start](http://dubbo.apache.org/zh-cn/docs/user/quick-start.html) 中`如果不想使用 Spring 配置，可以通过 API 的方式 进行调用。` 其中 *API* 的 `href` 属性为  `./configuration/api.md` 该资源指向的是无效地址，实际地址是否应该是 [./configuration/api.html](http://dubbo.apache.org/zh-cn/docs/user/configuration/api.html)?

**Comment by ralf0131** [comment]
There is nothing wrong here, I can successfully redirect to the API configuration page by clicking the link. How did you get that error?

**Comment by yinyuhang** [comment]
I just tried and it works fine, so embarrassing...
