### ISSUE TITLE
follow up for pull request #3043

### ISSUE THREAD

**Issue by beiwei30** [apache/incubator-dubbo#3244]
This change now looks good to me.

It looks like we should do the same thing for response, change

```java
            if ((flag & FLAG_EVENT) != 0) {
                res.setEvent(Response.HEARTBEAT_EVENT);
            }
```

to 

```java
            if ((flag & FLAG_EVENT) != 0) {
                res.setEvent(true);
            }
```

_Originally posted by @beiwei30 in https://github.com/apache/incubator-dubbo/pull/3043/comment#issuecomment-454673115_

**Comment by CrazyHZM** [comment]
I will do it.

**Comment by CrazyHZM** [comment]
@beiwei30 
I have submitted a pr fix it, please review it.
