### ISSUE TITLE
负载均衡扩展配置报错

### ISSUE THREAD

**Issue by lionhuo** [apache/incubator-dubbo#3248]
根据文档开发者指南->SPI 扩展实现->负载均衡扩展
src
 |-main
    |-java
        |-com
            |-xxx
                |-XxxLoadBalance.java (实现LoadBalance接口)
    |-resources
        |-META-INF
            |-dubbo
                |-org.apache.dubbo.rpc.cluster.LoadBalance (纯文本文件，内容为：xxx=com.xxx.XxxLoadBalance)

当文件名为org.apache.dubbo.rpc.cluster.LoadBalance报错：

java.lang.IllegalStateException: No such extension com.alibaba.dubbo.rpc.cluster.LoadBalance by name test

文件中内容
test=com.test.TestLoadBalance

将org.apache.dubbo.rpc.cluster.LoadBalance改为com.alibaba.dubbo.rpc.cluster.LoadBalance可以正常工作

### Environment

* Dubbo version: 2.6.5
* Operating System version: win10
* Java version: 1.8

**Comment by carryxyh** [comment]
dubbo版本2.6.5中不存在org.apache.dubbo的包前缀，使用的都是com.alibaba.dubbo。
所以不能使用org.apache.dubbo的接口。
