### ISSUE TITLE
[Enhancement] @Service supports the hierarchical interface

### ISSUE THREAD

**Issue by pjqbys** [apache/incubator-dubbo#3251]

**Comment by tswstarplanet** [comment]
Please give more details.

**Comment by pjqbys** [comment]
dubbo版本2.6.2
使用方式：接口 ---> 抽象类 ---> 服务实现类，@service注解加在服务实现类上。

**Comment by tswstarplanet** [comment]
Can it works if you use xml-based config?

**Comment by tswstarplanet** [comment]
```java
private Class<?> resolveServiceInterfaceClass(Class<?> annotatedServiceBeanClass, Service service) {

        Class<?> interfaceClass = service.interfaceClass();

        if (void.class.equals(interfaceClass)) {

            interfaceClass = null;

            String interfaceClassName = service.interfaceName();

            if (StringUtils.hasText(interfaceClassName)) {
                if (ClassUtils.isPresent(interfaceClassName, classLoader)) {
                    interfaceClass = resolveClassName(interfaceClassName, classLoader);
                }
            }

        }

        if (interfaceClass == null) {

            Class<?>[] allInterfaces = annotatedServiceBeanClass.getInterfaces();

            if (allInterfaces.length > 0) {
                interfaceClass = allInterfaces[0];
            }

        }

        Assert.notNull(interfaceClass,
                "@Service interfaceClass() or interfaceName() or interface class must be present!");

        Assert.isTrue(interfaceClass.isInterface(),
                "The type that was annotated @Service is not an interface!");

        return interfaceClass;
    }
```
Read this method in ServiceAnnotationBeanPostProcessor.java .
If you do not set the interfaceClass of @Service annotation obviously, the method will just find the interfaces that the class declare by itself, but it will not search the interfaces that its super classes declares.
I think it is not a bug, it can be regarded as a simpler design because the a class may have many hierarchies of super classes so searching the interfaces of its super classes recursively may be too heavy.

**Comment by tswstarplanet** [comment]
So even if the super class has declared the interface that is implemented, you can declare it be implemented by the sub class obviously.

**Comment by pjqbys** [comment]
yes，it can be solved by appointing the property interfaceClass of @service annotation ,but I think, dubbo should specify the interface name automatically。算了还是说中文吧，是可以通过制定服务类的@service注解的 interfaceClass= "xxx.class"来解决这个问题，但是难道dubbo不应该是自动地帮我制定最顶层的接口作为这个注解属性interfaceClass的值吗。为何非得认为指定

**Comment by tswstarplanet** [comment]
那样需要递归一层一层往上找所有父类实现的接口，然后聚合成一个list，再取第一个。不是不可用做，只是没必要。spring里也有很多子类继承了父类，然后也声明实现了同一个接口

**Comment by tswstarplanet** [comment]
@mercyblitz Hi, when fix the problem, please consider the issue.
#3357
