### ISSUE TITLE
We should use type inference instead of explicit type parameters

### ISSUE THREAD

**Issue by satansk** [apache/incubator-dubbo#3258]
The source code contains many explicit type parameter use cases, such as:

```
Map<String, String> newMap = new HashMap<String, String>(reserveParams.length);
```

The old style is not suitable now, since we will support Java 8 from Dubbo 2.7, so I think we can improve it.

Since the source code is big, some tools or scripts may be helpful.

**Comment by ralf0131** [comment]
+1 Many users contribute to fix issues like this. I think we can leave to users who would like to help.

**Comment by kezhenxu94** [comment]
Users are glad to help but review progress seems really slower than other types of PRs and they have to resolve conflicts over and over

**Comment by ralf0131** [comment]
> Users are glad to help but review progress seems really slower than other types of PRs and they have to resolve conflicts over and over

Yes, it is a problem, I am thinking of adding a label called `level/easy` for these prs but that requires a committer to label it manually, which is not desired.
The other way is to invite more people to be a committer, who can help to review and merge. The community is on the way.
You can also help to review the pr and approve it even if you are not a committer. :)

**Comment by satansk** [comment]
> +1 Many users contribute to fix issues like this. I think we can leave to users who would like to help.

Yes, many contributors has done great work about this, I was looking for something like maven plugins, but failed. So let's leave it to contributors :)

**Comment by ralf0131** [comment]
Anything we can do in this issue? Shall we close this issue now?

**Comment by satansk** [comment]
I think it's OK to close it now.
