### ISSUE TITLE
消费者消费服务不区分版本（version="*"）出现Not found exported service 错误

### ISSUE THREAD

**Issue by moxh** [apache/incubator-dubbo#3268]
服务引用：<dubbo:reference interface="com.xxx.xxxService" id="xxxService"  version="*"></dubbo:reference>

定义了： version="*" ，还需要配置什么么？

**Comment by moxh** [comment]
还要能支持版本通配符设置么如：version="1.0.*"

**Comment by yuxiao97** [comment]
不配置version就是不限制版本号，至于通配符的具体不了解，就需要看分装URL时对version的解析了。

**Comment by tswstarplanet** [comment]
为什么要用* ？

**Comment by LiZhenNet** [comment]
目前还不支持 version="1.0.*"  这种通配符的形式
 version="*" 跟不配置version  效果是一致的。

**Comment by mercyblitz** [comment]
What's your requirement?

**Comment by xingfudeshi** [comment]
@moxh ignore the version attribute will meet your requirement.
