### ISSUE TITLE
纯消费者项目配置registry register="false"，在Dubbo-Admin机器列表无法看到该项目

### ISSUE THREAD

**Issue by gMan1990** [apache/incubator-dubbo#3277]
老式Dubbo-Admin下试的。
```register: 是否向此注册中心注册服务，如果设为false，将只订阅，不注册```

**Comment by gMan1990** [comment]
@tswstarplanet 感觉有歧义。。
```register: 是否向此注册中心注册服务```
有3种状态吧：是否连了注册中心，是否注册了服务，是否订阅了服务

**Comment by Bricks-Man** [comment]
没问题啊。register=false就是不注册服务啊。不注册服务就不会建节点。连接注册中心这个当你配了register就是连接了啊。
