### ISSUE TITLE
Async optimization.

### ISSUE THREAD

**Issue by chickenlj** [apache/incubator-dubbo#3287]
* Unify Results used on the wire: AsyncRpcResult RpcResult SimpleAsyncRpcResult
* Possible async wrapper. https://github.com/apache/incubator-dubbo/issues/3113
* Some other possible improvements.

**Comment by chickenlj** [comment]
Generic support, https://github.com/apache/incubator-dubbo/pull/3637, done
Filters, https://github.com/apache/incubator-dubbo/issues/3483, almost done
Attachments, https://github.com/apache/incubator-dubbo/issues/3620, just started
Zipkin, https://github.com/apache/incubator-dubbo/issues/3576, need triage
Provider async, https://github.com/apache/incubator-dubbo/issues/3650, need triage

**Comment by carryxyh** [comment]
Just for the record:
Maybe we should consider the case when C and P use asynchronous at the same time. Currently, when the interface returns a value of `CompletableFuture` and uses `AsyncContext` to start asynchronous in `ServiceImpl`, it will cause some problems.

**Comment by maxiaoguang64** [comment]
yes, but we can't know that consumer use async

**Comment by carryxyh** [comment]
Nope, currently Dubbo's consumer asynchronous depends on the server configuration, so we can of course know if the client is using asynchronous...

**Comment by maxiaoguang64** [comment]
if user use like this
`new Thread(() -> service.method()).start()`?

**Comment by carryxyh** [comment]
In this case, the dubbo framework is treated as a synchronous call. This will not cause any problems.
:)

**Comment by maxiaoguang64** [comment]
![image](https://user-images.githubusercontent.com/6637227/53782528-9b776880-3f48-11e9-85b2-27d6a5267987.png)
in this picture, i use `new Thread(() -> service.method()).start()` and service is async

**Comment by carryxyh** [comment]
I don't know the content on this picture. This issue was created to discuss the problem of asynchronous methods in the dubbo framework.

My records are not the same problem as the scene you describe. If there are other problems with dubbo's asynchronous, you should create a complete issue to describe it. Thx.
