### ISSUE TITLE
[Enhancement] Enhance dubbo common logger

### ISSUE THREAD

**Issue by biyuhao** [apache/incubator-dubbo#3306]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

Our common logger is a logging facade just like SLF4J.
We can enhance it to support parametrized logging

We have many places like this:
```
if (logger.isInfoEnabled()) {
                logger.info("aaa" + "bbb" + "ccc");
}
```
We are using logging guard to avoid unnecessary string concatenate.

With the support of parametrized logging, this can be simplified just like:
```
logger.debug("Hello world {} {} and {}", a, b, c);
```
Similar feature discribed in SLF4j:
https://www.slf4j.org/faq.html#logging_performance

Question: Any other points can be enhanced?

**Comment by CrazyHZM** [comment]
I think the place where the logging of parameters can be replaced, is there any other benefit besides readability?

**Comment by biyuhao** [comment]
Let me try to summarize it,
- Better performance
The message string is constructed on demand (logging level is checked inside the method)
- Better readability
Reduce unnecessary logging guard (logger.isXXXEnabled())
More uniquely code style of string construction. (Avoid complex string concatenate with "+" or String.format("xxx"))
Similar grammar with existing modern logging framework like SLF4J

So, should we or is it worthy to do it?

**Comment by biyuhao** [comment]
After some similar discuss in #3438 
I'll close this for now.
