### ISSUE TITLE
Dubbo中文文档错别字

### ISSUE THREAD

**Issue by yuemingming** [apache/incubator-dubbo#3308]
![image](https://user-images.githubusercontent.com/32236524/51532002-f6ae3980-1e79-11e9-86fc-f0025b0b8a52.png)

文档链接：
http://dubbo.apache.org/zh-cn/docs/dev/principals/code-detail.html

![image](https://user-images.githubusercontent.com/32236524/51532030-09287300-1e7a-11e9-9404-62efca790ddf.png)

文档链接：
http://dubbo.apache.org/zh-cn/docs/dev/principals/robustness.html

**Comment by CrazyHZM** [comment]
Hi, would you mind send a pull request？

**Comment by yuemingming** [comment]
> Hi, would you mind send a pull request？
I am willing.

**Comment by biyuhao** [comment]
@yuemingming 
FYI. You can follow the instruction and send PR to https://github.com/apache/incubator-dubbo-website

**Comment by yuemingming** [comment]
Hi , I have already sent a pull request.

**Comment by ralf0131** [comment]
Hi, is this issue solved? @yuemingming

**Comment by yuemingming** [comment]
> Hi, is this issue solved? @yuemingming

Yes, it's settled.
