### ISSUE TITLE
关于AllChannelHandler类，为何没有将sent方法再其内重写？

### ISSUE THREAD

**Issue by mauersu** [apache/incubator-dubbo#331]
public interface ChannelHandler {

```
void connected(Channel channel) throws RemotingException;

void disconnected(Channel channel) throws RemotingException;

void sent(Channel channel, Object message) throws RemotingException;

void received(Channel channel, Object message) throws RemotingException;

void caught(Channel channel, Throwable exception) throws RemotingException;
```

} 
 这个AllChannelHandler没有重写sent方法，sent方法不走线程池，这个地方有何用意？而且已经存在一个ExecutionChannelHandler来做这方面了，AllChannelHandler的设计用途是啥呢？

**Comment by mauersu** [comment]
个人回答下，感觉sent线程发送后就是等待receive了，反正闲着也是闲着，不如由本线程自己发送出去，不去占用线程池资源

**Comment by carryxyh** [comment]
AllChannelHandler is designed to dispatch.
Dispatch the msg to business thread to increase provider system throughput. It can also deal some event like connected and disconnected.

The ExecutionChannelHandler will only dispatch request msg.
Other messages like response, connect, disconnect will be directly executed by I/O thread.

NEED-CLOSE
