### ISSUE TITLE
Maven plugin compile the project

### ISSUE THREAD

**Issue by Joker1995** [apache/incubator-dubbo#3310]
### Environment

* Dubbo version: 2.7.9
* Operating System version: Window10
* Java version: 1.8

### Steps to reproduce this issue
When I type **"mvn clean install -Dmaven.test.skip"** in the commend
there was some error
```
Plugin org.apache.maven.plugins:maven-compiler-plugin or one of its dependencies could not be resolved
```
Later I changed  maven mirror,there was the new error:

```
end tag name </body> must match start tag name <hr> from line 7 (position: TEXT seen ...</address>\n</body>...
```
### Resolve
I update the maven compiler version,and then the project was compile success
```
<maven_compiler_version>3.7.0</maven_compiler_version>
```

**Comment by Joker1995** [comment]
> It worked well in maven 3.5.2 and 3.6.0. What is your maven version in your window machine?

Apache Maven 3.5.0

**Comment by Joker1995** [comment]
> It worked well in maven 3.5.2 and 3.6.0. What is your maven version in your window machine?

otherwise,how could I config the password on the frontEnd ?

**Comment by ralf0131** [comment]
I could not reproduce this issue on my Mac laptop, I think it may due to some network issues. 
Please consider using maven wrapper instead.

```
./mvnw clean install -Dmaven.test.skip
```

**Comment by Joker1995** [comment]
> I could not reproduce this issue on my Mac laptop, I think it may due to some network issues.
> Please consider using maven wrapper instead.
> 
> ```
> ./mvnw clean install -Dmaven.test.skip
> ```

Thanks,how can I setup to the password of  dubbo monitor ?

**Comment by ralf0131** [comment]
Please ask on the https://github.com/apache/incubator-dubbo-ops project

**Comment by Joker1995** [comment]
> Please ask on the https://github.com/apache/incubator-dubbo-ops project

Fine,Thanks for your patience
