### ISSUE TITLE
IDLE_CHECK_TIMER should be stoped when the server shutdown

### ISSUE THREAD

**Issue by kexianjun** [apache/incubator-dubbo#3320]
Is there necessary to stop org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeClient#IDLE_CHECK_TIMER and org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeServer#IDLE_CHECK_TIMER when the server shutdown ?

**Comment by carryxyh** [comment]
Nope.
These two timer is shared for all client(server) and every client(server) close will remove their check tasks.
So never cause some problems.

**Comment by kexianjun** [comment]
> Nope.
> These two timer is shared for all client(server) and every client(server) close will remove their check tasks.
> So never cause some problems.

我的意思是整个服务shutdown的时候，不是指某些client(server)关闭的时候

**Comment by carryxyh** [comment]
不需要。
出于什么考虑需要回收这两个对象呢？

**Comment by kexianjun** [comment]
> 不需要。
> 出于什么考虑需要回收这两个对象呢？

这两个对象里面会启动两个线程，主要是想知道这两个线程需不需要在应用shutdown的时候停掉

**Comment by kexianjun** [comment]
> 不需要。
> 出于什么考虑需要回收这两个对象呢？

清楚了，创建的线程是守护线程，确实不需要

**Comment by carryxyh** [comment]
你可以看下这两个部分的代码，都是守护线程，进程停止以后就会停止。
另外可以参考一下老的DefaultFuture中的超时检查线程，同理。
