### ISSUE TITLE
When can the dubbo:2.7.0 deploy to the central repository

### ISSUE THREAD

**Issue by JasonMing** [apache/incubator-dubbo#3321]
I notice that the tag [dubbo-2.7.0](https://github.com/apache/incubator-dubbo/releases/tag/dubbo-2.7.0) has already been released, is there any schedule about deploying to the central repository?

**Comment by tswstarplanet** [comment]
The release of dubbo-2.7.0 is labelled by "DRAFT", so it should not be deployed to the central repository. Please wait.

**Comment by ACXNX** [comment]
> The release of dubbo-2.7.0 is labelled by "DRAFT", so it should not be deployed to the central repository. Please wait.

So dubbo-2.7.0-release won't be deployed to the central repository?  Does it mean that Dubbo will not be released to the maven central repository with  new package name **org.apache.dubbo** until it graduates from the Apache incubator and becomes an official Apache project?

**Comment by cvictory** [comment]
The release of Dubbo-2.7.0 is still in voting. 
 After voting passed, It will be deployed to maven repository as soon as possible

**Comment by JerryChin** [comment]
To whom it may concern:

Dubbo-2.7.0 has released since 29, Jan at [here].(https://mvnrepository.com/artifact/org.apache.dubbo/dubbo/2.7.0)
