### ISSUE TITLE
dubbo.protocol.port端口使用${random.int(min,max)}不起作用,dubbo框架还是使用默认端口20880.

### ISSUE THREAD

**Issue by leyboy** [apache/incubator-dubbo#3330]
dubbo.protocol.port端口使用${random.int(min,max)}不起作用,dubbo框架还是使用默认端口20880。测试时使用的dubbo协议。

**Comment by CrazyHZM** [comment]
是否可以再讲的详细一点

**Comment by biyuhao** [comment]
Springboot 的 `RandomValuePropertySource` 支持这种表达式，目前 dubbo 可能不支持

https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-random-values

**Comment by CrazyHZM** [comment]
不知道这个项目里面有没有你要的答案，你可以尝试着去这个项目下面提个issue https://github.com/apache/incubator-dubbo-spring-boot-project
