### ISSUE TITLE
dubbo LruCache 错误

### ISSUE THREAD

**Issue by denglt** [apache/incubator-dubbo#334]
```java
public LruCache(URL url) {
    final int max = url.getParameter("cache.size", 1000);
    this.store = new LinkedHashMap<Object, Object>() {
        private static final long serialVersionUID = -3834209229668463829L;
        @Override
        protected boolean removeEldestEntry(Entry<Object, Object> eldest) {
            return size() > max;
        }
    };
}
```

new LinkedHashMap()  应该使用下面的construct:
```java
          public LinkedHashMap(int initialCapacity,
                                                float loadFactor,
                                                boolean accessOrder) 
     accessOrder must is true
```

**Comment by oldratlee** [comment]
@denglt 你说的是写法，能测试发现到不预期的情况的说明吗？

或是给出你这个做法优势的说明吗？

**Comment by denglt** [comment]
public LinkedHashMap(int initialCapacity,
                                                float loadFactor,
                                                boolean accessOrder)
accessOrder - the ordering mode - true for access-order, false for insertion-order

LruCache  must be  access-order.

**Comment by carryxyh** [comment]
public class LRUCache<K, V> extends LinkedHashMap<K, V> {
    public LRUCache(int maxCapacity) {
        super(16, DEFAULT_LOAD_FACTOR, true);
        this.maxCapacity = maxCapacity;
    }
}

This issue has been fixed.

&NEED-TO-CLOSE&
