### ISSUE TITLE
Update package name in README file for release-2.7.0 branch

### ISSUE THREAD

**Issue by htynkn** [apache/incubator-dubbo#3347]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.0-SNAPSHOT

### Steps to reproduce this issue

README file in 2.7.0 branch (https://github.com/apache/incubator-dubbo/blob/2.7.0-release/README.md) still using package name `com.alibaba.dubbo`, it should update to `org.apache.dubbo`

**Comment by CrazyHZM** [comment]
In the release-2.7.0 branch modification or master？
