### ISSUE TITLE
how to use protobuf with dubbo

### ISSUE THREAD

**Issue by kimifdw** [apache/incubator-dubbo#3373]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.0-release
* Operating System version: MacOS
* Java version: 1.8

### Steps to reproduce this issue

I see that in 2.7.0-RELEASE.Dubbo haven been supported protobuf,but I can't find any infomation in document.Please help me some examples how to use protobuf in dubbo, or show me some demos.Thanks

**Comment by chickenlj** [comment]
I think it's quite similar to using other serialization mechanisms, say hessian. The only thing you need to do is to tell the service the serialization type you choose to use, like this:
```xml
<dubbo:service serialization="protostuff" interface="com.alibaba.dubbo.demo.DemoService" ref="demoService"/>
```

Thanks to protostuff, simple POJO java object can be serialized & deserialized directly, no extra .poto files are needed.

**Comment by kimifdw** [comment]
no .poto files?I just want to use .poto with dubbo, is there any way to use with .poto files @chickenlj

**Comment by chickenlj** [comment]
> no .poto files?I just want to use .poto with dubbo, is there any way to use with .poto files @chickenlj

Sorry, I am not familiar enough with protostuff to answer this question. But I am sure that the integration tends to support `no .poto` scenarios, we can further check if protostuff can work with normal .poto files.

**Comment by kimifdw** [comment]
thanks.
