### ISSUE TITLE
使用curator做为zk客户端，zookeeper宕机重启后无法自动重连

### ISSUE THREAD

**Issue by YanXs** [apache/incubator-dubbo#339]
使用curator客户端时，当zookeeper宕机重启后会产生一个None类型的event，在重连时调用CuratorZookeeperClient类的内部类CuratorWatcherImpl的process方法时会陷入死循环，RetryLoop的方法callWithRetry的while循环中。
修改方式升级curator到apache版本，或者在CuratorWatcherImpl的process方法中加入事件类型判断，只对NodeChildrenChanged事件响应

**Comment by 0915240** [comment]
#38

**Comment by htynkn** [comment]
Verify this with:

1. dubbo 2.6.2
2. zookeeper 3.4.12
3. curator-framework 2.12.0

All good. If you try latest version and still able to reproduce issue, please provide full error log.

**Comment by htynkn** [comment]
No more update. Close this issue.
