### ISSUE TITLE
Bad link in 2.7.0 release notes

### ISSUE THREAD

**Issue by foreveryang321** [apache/incubator-dubbo#3391]
### Environment

* Dubbo version: [2.7.0 release notes](https://github.com/apache/incubator-dubbo/releases)

### Steps to reproduce this issue

1. Please check [here](https://github.com/apache/incubator-dubbo/blob/2.7.0-release/CHANGES.md#upgrading-and-compatibility-notifications) for notes and possible compatibility issues for upgrading from 2.6.x or lower to 2.7.0...
请在[这里](https://github.com/apache/incubator-dubbo/blob/2.7.0-release/CHANGES.md#%E5%8D%87%E7%BA%A7%E4%B8%8E%E5%85%BC%E5%AE%B9%E6%80%A7)了解关于升级2.7.x版本的注意事项和兼容性问题...
2. [Simplified registry URL](https://github.com/apache/incubator-dubbo/blob/dubbo-2.7.0). With lower Registry memory use and less notification pressure from Service Directory, separates Configuration notification from Service Discovery...
[更精炼的注册中心URL](https://github.com/apache/incubator-dubbo/blob/dubbo-2.7.0)，进一步减轻注册中心存储和同步压力，初步实现地址和配置的职责分离...
3. [Metadata Center](https://github.com/apache/incubator-dubbo/blob/dubbo-2.7.0). A totally new concept since 2.7.0...
新增服务[元数据中心](https://github.com/apache/incubator-dubbo/blob/dubbo-2.7.0)，负责存储包括服务静态化配置、服务定义（如方法签名）等数据...

**Comment by lixiaojiee** [comment]
Would you please send a pr to fix it?

**Comment by chickenlj** [comment]
Thanks for reporting.

> Please check here for notes and possible compatibility issues for upgrading from 2.6.x or lower to 2.7.0...
> 请在这里了解关于升级2.7.x版本的注意事项和兼容性问题...

I have corrected this one.

> Simplified registry URL. With lower Registry memory use and less notification pressure from Service Directory, separates Configuration notification from Service Discovery...
> 更精炼的注册中心URL，进一步减轻注册中心存储和同步压力，初步实现地址和配置的职责分离...
> Metadata Center. A totally new concept since 2.7.0...
> 新增服务元数据中心，负责存储包括服务静态化配置、服务定义（如方法签名）等数据...

The docs are almost done, maybe later today. We will publish them to the official site and update the links here ASAP.

**Comment by chickenlj** [comment]
All links are updated to date.
