### ISSUE TITLE
[Discuss] Provide command to rerun the CI

### ISSUE THREAD

**Issue by satansk** [apache/incubator-dubbo#3393]
For now, the CI seems unstable and sometimes it failed, and it will succeed after a rebuild. I have encoutered this problem several times, and so as some other contributor(https://github.com/apache/incubator-dubbo/pull/3389).

Do we have or should we have any command to start a rebuild?

**Comment by ralf0131** [comment]
Currently only committer has the permission to trigger the re-build. 
I think what we can do for now is:
- identify why is the UT unstable and fix it
- contributors can request any of the committers to trigger it manually or asking on the mail list for help.

**Comment by kezhenxu94** [comment]
Can @dubbo-bot help in this situation? What I mean is that if dubbo-bot can trigger the rebuild task, we can do something like this:

Mention dubbo-bot in the comment, such as:

> @dubbo-bot test this please

or something like this. Then @dubbo-bot can trigger the build task, this may need more investigation in travis-ci and the GitHub hooks

**Comment by ralf0131** [comment]
I wish it could. 

In fact, dubbo-bot does not have the permission to trigger the build, either. :(
To trigger the build, a write access to the repo is needed.

If you want to trigger it manually without letting the committers to know, you can commit an empty message.

**Comment by kezhenxu94** [comment]
> If you want to trigger it manually without letting the committers to know, you can commit an empty message.

@ralf0131 Yes that's what I've done in #3389

**Comment by ralf0131** [comment]
> > If you want to trigger it manually without letting the committers to know, you can commit an empty message.
> 
> @ralf0131 Yes that's what I've done in #3389

Before you do that, it is better to save the error log, and report to the community to investigate.

**Comment by satansk** [comment]
Sounds reasonable, committers can trigger it manually and contributors can trigger by an empty commit, that's what I want. Thanks @ralf0131 :)
