### ISSUE TITLE
Wrong dubbo version in Url?

### ISSUE THREAD

**Issue by zhengqigo** [apache/incubator-dubbo#3394]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.5
* Operating System version: Windows 10 Pro
* Java version: 1.8

### Steps to reproduce this issue

See into the logs and always get dubbo=2.0.2 in Url format, wrong? design?

I get below code in Version
`    
// Dubbo RPC protocol version, for compatibility, it must not be between 2.0.10 ~ 2.6.2
public static final String DEFAULT_DUBBO_PROTOCOL_VERSION = "2.0.2";
 // Dubbo implementation version, usually is jar version.
private static final String VERSION = getVersion(Version.class, "");
`

**Comment by cvictory** [comment]
In dubbo2.6.5, dubbo=2.0.2 is the protocol version.  
In dubbo2.6.5, there is no dubbo version. 

And In dubbo2.7.0, it has been added dubbo version named `release`
