### ISSUE TITLE
使用<dubbo:config-center />出现的问题

### ISSUE THREAD

**Issue by dai19470** [apache/incubator-dubbo#3400]
我希望使用下面的配置获取dubbo.properties 和spring-demo.xml文件，但是没有获取到。去掉第二个配置能获取到第一个配置文件，	
<dubbo:config-center   address="zookeeper://127.0.0.1:2181" config-file="dubbo.properties"  namespace="dubbo"  />
	<dubbo:config-center   address="zookeeper://127.0.0.1:2181" config-file="spring-demo.xml"   namespace="spring" include-spring-env="true"     /> 

dubbo.properties 和spring-demo.xml 是在zookeeper同级目录里/dubbo/config/dubbo/

**Comment by chickenlj** [comment]
http://dubbo.apache.org/zh-cn/docs/user/configuration/config-center.html

只有`dubbo.properties`这一种格式是可以支持的，spring-demo.xml并不支持

**Comment by chickenlj** [comment]
关于`config-center`各项配置的含义，马上在官网增加一个详细文档。
更详细的解释`namespace`，`include-spring-env="true"`的含义。

**Comment by slowvic** [comment]
支持nacos作为config-center吗？

**Comment by chickenlj** [comment]
> 支持nacos作为config-center吗？

Nacos 的正在做适配：启动配置、服务治理、注册中心（已支持）

**Comment by chickenlj** [comment]
https://github.com/apache/incubator-dubbo-website/blob/asf-site/docs/zh-cn/user/references/xml/dubbo-config-center.md

**Comment by RongXiong2016** [comment]
@chickenlj 你好。我使用的是 dubbo2.7.1+nacos1.0.0+spring-boot2.0.8
nacos新建了一个新的命名空间，在项目配置增加如下配置
config-center:
    address: 127.0.0.1:8848
    namespace: 8ef585bb-44d7-4774-b65b-ff3f0b2fd4e1
服务启动后无法进入新的命名空间还是在public下
