### ISSUE TITLE
官网文档webService相关依赖错误

### ISSUE THREAD

**Issue by dxhguangz** [apache/incubator-dubbo#3416]
<dependency>
    <groupId>org.apache.cxf</groupId>
    <artifactId>cxf-rt-frontend-simple</artifactId>
    <version>2.6.1</version>
</dependency>
<dependency>
    <groupId>org.apache.cxf</groupId>
    <artifactId>cxf-rt-transports-http</artifactId>
    <version>2.6.1</version>
</dependency>

官网上webservice 推荐写的是如下版本的依赖，
但是dubbo 2.6.2 实际依赖是 3.X 者两个版本实现上有区别，按照官网使用会导致空指针

**Comment by CrazyHZM** [comment]
这个问题已经有相同的issues #3411，关于这个问题我已经知道是什么问题，发现3.2.x中cxf实现的HTTPTransportFactory已经不再实现WSDLEndpointFactory接口，所以才会导致wsdl中缺少address的内容，稍后我会提交一个pr修复此问题

**Comment by schdai** [comment]
If you just use cfx 3.x with spring ,the generated wsdl is ok, and the address element exists. But dubbo 2.6.5 + cxf 3.x, the address element lost in the generated wsdl.
