### ISSUE TITLE
dubbo官网集成skywalking文档能否补充详细点

### ISSUE THREAD

**Issue by 511098425** [apache/incubator-dubbo#3422]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.5
* Operating System version: mac
* Java version: 1.8

### Steps to reproduce this issue

官方网站只是简单的说了dubbo集成skywalking,实际有很多细节，skywalking5.x和6.x的配置有很多差异的地方，希望能够稍微详细点说明。

**Comment by yuxiao97** [comment]
> * [ ]  I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
> * [ ]  I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.
> 
> ### Environment
> * Dubbo version: 2.6.5
> * Operating System version: mac
> * Java version: 1.8
> 
> ### Steps to reproduce this issue
> 官方网站只是简单的说了dubbo集成skywalking,实际有很多细节，skywalking5.x和6.x的配置有很多差异的地方，希望能够稍微详细点说明。

这个不属于Dubbo的范畴，人家只是给你提供了一种APM的方式，况且实际使用中的配置和Dubbo也没什么关系。

**Comment by chickenlj** [comment]
@511098425 Sorry, but we don't get enough time with this, hope some volunteers from the community can help with us. It would be great if you can add your valuable experience back to the official doc.
