### ISSUE TITLE
Why apache Dubbo does not supported on Stackoverflow?

### ISSUE THREAD

**Issue by l16h7n1n6s** [apache/incubator-dubbo#3442]
Hello all and thnx for your awesome work. I am wondering why there is not any tag for Apache Dubbo in StackOverflow to help people make questions and get the appropriate answers to solve any kinds of problem. As a result, all the community to be benefited from this positive factor.

**Comment by ralf0131** [comment]
Hi, 

Most of the Dubbo users are from China, they tend to use Github issues to ask questions for Dubbo, or other Chinese equivalent such as [segment fault](https://segmentfault.com/t/dubbo). 

I checked on Stackoverflow too, yes there is not a tag called Dubbo. 

IMO, anyone can create tag when raising questions on Stackoverflow, so just feel free to create a tag there, and let us know about. Hopefully someone in the community will answer it there.

**Comment by l16h7n1n6s** [comment]
@ralf0131 I wish i could but i don't have enough reputation to do it. I checked the website that you mentioned and i feel so embarrassed that i found so many good questions that may help a lot of the community members there. It so ridiculous that someone may want to find a similar question and when he google it the Google engines canot find anything similar cause of the above website, while we have the StackOverflow community which is at the top on google engines when someone googles a question. You have such a nice open source framework and you not help each other. I hope someone will create a tag(in addition,if possible transfer the questions from segmentation fualt if it is possible) there, so  people it just starts the questions there

**Comment by kezhenxu94** [comment]
Hi @l16h7n1n6s , I just checked and find that there is a tag `apache-dubbo` in [StackOverflow](https://stackoverflow.com/questions/tagged/apache-dubbo), you can ask question and label it with `apache-dubbo`

**Comment by l16h7n1n6s** [comment]
@kezhenxu94  thnx a lot its perfect!!!! 👍

**Comment by zonghaishang** [comment]
close it now.
