### ISSUE TITLE
there isn't '/dubbo/config' path in zk after I run dubbo-demo-xml-provider in Tag2.7.0 version

### ISSUE THREAD

**Issue by zhaixiaoxiang** [apache/incubator-dubbo#3462]
注册中心已经改成<dubbo:registry address="zookeeper://localhost:2181"/>

**Comment by zhaixiaoxiang** [comment]
> http://dubbo.incubator.apache.org/zh-cn/docs/user/configuration/config-center.html, <dubbo:config-center address="zookeeper://127.0.0.1:2181"/>

官网文档里提到了, 是我没注意到

**Comment by zhaixiaoxiang** [comment]
http://dubbo.incubator.apache.org/zh-cn/docs/user/configuration/config-center.html, 这个文档里还提到了
>  "为了兼容2.6.x版本配置，在使用Zookeeper作为注册中心，且没有显示配置配置中心的情况下，Dubbo框架会默认将此Zookeeper用作配置中心，但将只作服务治理用途。"

就是说2.7版本的dubbo, 如果没有显式配置配置中心的情况下, zk上也应该会有/dubbo/config目录的吧, 用来做服务治理用途, 但是正如标题里提到的, demo启动后, zk 上并没有相应的目录

**Comment by chickenlj** [comment]
抱歉demo中并没有给出详细的操作步骤。

Dubbo框架自身并不会创建/dubbo/config目录，你需要利用demo中的ZKTools.java工具类或者部署一套dubbo-ops控制台来完成目录创建和规则写入。
