### ISSUE TITLE
How to specify a provider by rule that based on IP globally

### ISSUE THREAD

**Issue by superbible** [apache/incubator-dubbo#3465]
We need to specify a rule for dubbo providers based on IP globally in development environment.
In development environment, we deploy all dubbo services and web servers, and we need to call dubbo services from PC for development, but other PC may register their dubbo services to the zookeeper which should not be called.

So we need to specify a rule based on IP, and it'll apply globally instead of just for one service.
The rule can be like this pattern 192.168.*.*, mean other IP that doesn't match will be excluded.

I found Dubbo can specify a provider IP on @Reference annotation, but this is not what I want:
it's not global settings, which means I need to change code in many places.

If Dubbo don't have this feature already, I think maybe we can achieve with a custom load balance property, means we can choose provider by IP, is this possible?

**Comment by xxlv** [comment]
Use your LB module . Just put it in your project's  META-INT/dubbo/* path  AND you can add any logic u want 

PS. add this config  file to .gitignore file  

Does this solve your problem?

**Comment by superbible** [comment]
> Use your LB module . Just put it in your project's META-INT/dubbo/* path AND you can add any logic u want
> 
> PS. add this config file to .gitignore file
> 
> Does this solve your problem?

Do you mean this: http://dubbo.apache.org/en-us/docs/dev/impls/load-balance.html ?
When I study the inteface LoadBalance, the only method is:
select(List<Invoker<T>> invokers, URL url, Invocation invocation)
So I need to select a inoker from the paramerter invokers, right?
But I can't find any property related to provider's IP in this parameter.
Could you shed some light on it? Thanks.

**Comment by xxlv** [comment]
> > Use your LB module . Just put it in your project's META-INT/dubbo/* path AND you can add any logic u want
> > PS. add this config file to .gitignore file
> > Does this solve your problem?
> 
> Do you mean this: http://dubbo.apache.org/en-us/docs/dev/impls/load-balance.html ?
> When I study the inteface LoadBalance, the only method is:
> select(List<Invoker> invokers, URL url, Invocation invocation)
> So I need to select a inoker from the paramerter invokers, right?
> But I can't find any property related to provider's IP in this parameter.
> Could you shed some light on it? Thanks.

Yes ,i think in your case , you can simply select a invoker. 

`foreach invokers as invoker : check invoker.getUrl  if match your IP  choose it else ignore `

**Comment by superbible** [comment]
> > > Use your LB module . Just put it in your project's META-INT/dubbo/* path AND you can add any logic u want
> > > PS. add this config file to .gitignore file
> > > Does this solve your problem?
> > 
> > 
> > Do you mean this: http://dubbo.apache.org/en-us/docs/dev/impls/load-balance.html ?
> > When I study the inteface LoadBalance, the only method is:
> > select(List invokers, URL url, Invocation invocation)
> > So I need to select a inoker from the paramerter invokers, right?
> > But I can't find any property related to provider's IP in this parameter.
> > Could you shed some light on it? Thanks.
> 
> Yes ,i think in your case , you can simply select a invoker.
> 
> `foreach invokers as invoker : check invoker.getUrl if match your IP choose it else ignore `

Thank you for help. It works. 
But there're bugs in the document:http://dubbo.apache.org/en-us/docs/dev/impls/load-balance.html
META-INF
            |-dubbo
                |-org.apache.dubbo.rpc.cluster.LoadBalance
I put the new load balance settings in above file, but it can't find the rule, when I change the file name portion from org.apache to com.alibaba, it works.
And, I need to start two instances of providers to make dubbo enable load balance, otherwise it'll just ignore it.

**Comment by kexianjun** [comment]
> > > > Use your LB module . Just put it in your project's META-INT/dubbo/* path AND you can add any logic u want
> > > > PS. add this config file to .gitignore file
> > > > Does this solve your problem?
> > > 
> > > 
> > > Do you mean this: http://dubbo.apache.org/en-us/docs/dev/impls/load-balance.html ?
> > > When I study the inteface LoadBalance, the only method is:
> > > select(List invokers, URL url, Invocation invocation)
> > > So I need to select a inoker from the paramerter invokers, right?
> > > But I can't find any property related to provider's IP in this parameter.
> > > Could you shed some light on it? Thanks.
> > 
> > 
> > Yes ,i think in your case , you can simply select a invoker.
> > `foreach invokers as invoker : check invoker.getUrl if match your IP choose it else ignore `
> 
> Thank you for help. It works.
> But there're bugs in the document:http://dubbo.apache.org/en-us/docs/dev/impls/load-balance.html
> META-INF
> |-dubbo
> |-org.apache.dubbo.rpc.cluster.LoadBalance
> I put the new load balance settings in above file, but it can't find the rule, when I change the file name portion from org.apache to com.alibaba, it works.
> And, I need to start two instances of providers to make dubbo enable load balance, otherwise it'll just ignore it.

Which version you use? Maybe the document's description is ok, because on version 2.7.0, all the packages have renamed to org.apache.*, while previous version it is com.alibaba.*.

**Comment by superbible** [comment]
> > > > > Use your LB module . Just put it in your project's META-INT/dubbo/* path AND you can add any logic u want
> > > > > PS. add this config file to .gitignore file
> > > > > Does this solve your problem?
> > > > 
> > > > 
> > > > Do you mean this: http://dubbo.apache.org/en-us/docs/dev/impls/load-balance.html ?
> > > > When I study the inteface LoadBalance, the only method is:
> > > > select(List invokers, URL url, Invocation invocation)
> > > > So I need to select a inoker from the paramerter invokers, right?
> > > > But I can't find any property related to provider's IP in this parameter.
> > > > Could you shed some light on it? Thanks.
> > > 
> > > 
> > > Yes ,i think in your case , you can simply select a invoker.
> > > `foreach invokers as invoker : check invoker.getUrl if match your IP choose it else ignore `
> > 
> > 
> > Thank you for help. It works.
> > But there're bugs in the document:http://dubbo.apache.org/en-us/docs/dev/impls/load-balance.html
> > META-INF
> > |-dubbo
> > |-org.apache.dubbo.rpc.cluster.LoadBalance
> > I put the new load balance settings in above file, but it can't find the rule, when I change the file name portion from org.apache to com.alibaba, it works.
> > And, I need to start two instances of providers to make dubbo enable load balance, otherwise it'll just ignore it.
> 
> Which version you use? Maybe the document's description is ok, because on version 2.7.0, all the packages have renamed to org.apache._, while previous version it is com.alibaba._.

I see.
I'm using 2.6.2
