### ISSUE TITLE
How can I get the provider application.name in a consumer filter

### ISSUE THREAD

**Issue by gougouzcm** [apache/incubator-dubbo#3472]
I am writing a log filter in consumer side， I want to know which provider application that client is calling.

I want to get the provider url, 
So I use the method `RpcContext.getContext().getUrls()`
but the url I got seems is a merged url , not my expected result.

Can any one help me, thk.

**Comment by kexianjun** [comment]
You can get the provider's ip and port int your Filter like this 
```
String providerIp = invoker.getUrl().getHost();
int providerPort = invoker.getUrl().getPort;
```

does this solve your problem?

**Comment by gougouzcm** [comment]
> You can get the provider's ip and port int your Filter like this
> 
> ```
> String providerIp = invoker.getUrl().getHost();
> int providerPort = invoker.getUrl().getPort;
> ```
> does this solve your problem?

@kexianjun  I want get the provider application name . I need the provider application name and do some analyse.

**Comment by Bricks-Man** [comment]
> > You can get the provider's ip and port int your Filter like this
> > ```
> > String providerIp = invoker.getUrl().getHost();
> > int providerPort = invoker.getUrl().getPort;
> > ```
> > does this solve your problem?
> 
> @kexianjun I want get the provider application name . I need the provider application name and do some analyse.

I think you can get result like this:
```
String application = RpcContext.getContext().getUrl().getParameter("application");
```

**Comment by kexianjun** [comment]
> > > You can get the provider's ip and port int your Filter like this
> > > ```
> > > String providerIp = invoker.getUrl().getHost();
> > > int providerPort = invoker.getUrl().getPort;
> > > ```
> > > does this solve your problem?
> > 
> > 
> > @kexianjun I want get the provider application name . I need the provider application name and do some analyse.
> 
> I think you can get result like this:
> 
> ```
> String application = RpcContext.getContext().getUrl().getParameter("application");
> ```

No, the result is consumer's application name

**Comment by chickenlj** [comment]
If you are using v2.7.0, the following statement may help you:
```java
url.getParameter(Constants.REMOTE_APPLICATION_KEY)
```

**Comment by 24kpure** [comment]
`invoker.getUrl().getParameter(REMOTE_APPLICATION_KEY)`
It works for me. Maybe you can get answer from `org.apache.dubbo.rpc.filter.ConsumerContextFilter#invoke`.
