### ISSUE TITLE
Close Resources Properly

### ISSUE THREAD

**Issue by kamaci** [apache/incubator-dubbo#3473]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: xxx
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by chickenlj** [comment]
Thanks. Please provide valid information about your problem so we can help.

**Comment by kamaci** [comment]
> Thanks. Please provide valid information about your problem so we can help.

It is not easy to produce this bug, so I couldn't give more information.

 I've created a PR for this: https://github.com/apache/incubator-dubbo/pull/3474
