### ISSUE TITLE
@Service注解export属性默认值错误导致无法生效

### ISSUE THREAD

**Issue by tobarcn** [apache/incubator-dubbo#3486]
export默认值为false,因为appendAnnotation方法中的 
if (value != null && !value.equals(method.getDefaultValue())) 判断逻辑存在

此时如果将@Service的export设置为false时等,因为该值等同于默认值而无法生效

查了一下,因为这个判断逻辑,导致注解中的很多值都无法正确设置(如retries等),官方能否做一次完整的修复?

**Comment by kexianjun** [comment]
I have check the code, the default value of export is false in the old version, the latest version is true, and it works fine for me in the latest version, can your pls tell us witch version you use, and also provide a demo to reproduce this problem?

**Comment by chickenlj** [comment]
> 因为这个判断逻辑,导致注解中的很多值都无法正确设置(如retries等),官方能否做一次完整的修复?

@tobarcn It's indeed a problem, I just checked and found that most of the default values given to @Service and @Reference are meaningless: `default ""`, `default 0`. 
Further more, if we use `!value.equals(method.getDefaultValue())` to exclude all default values from being used, then why do we provide a default value?

**Comment by chickenlj** [comment]
* Provide a meaning default value or does not provide one.
* Use the value without distinguishing it is inherited by default or provided by user.

**Comment by chickenlj** [comment]
After carefully checked the code, I found `* !value.equals(method.getDefaultValue())` works fine.

We should only make sure that the default values in Service and Reference are the same as the ones used inside the workflow. 
That explains why `register` fails to work: the default value in Service is `false` while the actual default value used in the registering process is `true`.
But this value has been changed to `true` in the latest version.

**Comment by tobarcn** [comment]
> I have check the code, the default value of export is false in the old version, the latest version is true, and it works fine for me in the latest version, can your pls tell us witch version you use, and also provide a demo to reproduce this problem?

我也很奇怪,因为查过几个类似的问题你们都说最新版本都已经修复了,但是我查看最新版本的代码,依然还是false

另外我们目前用的版本是2.6.2

比如master分支
https://github.com/apache/incubator-dubbo/blob/master/dubbo-compatible/src/main/java/com/alibaba/dubbo/config/annotation/Service.java

比如3.x-dev分支
https://github.com/apache/incubator-dubbo/blob/3.x-dev/dubbo-compatible/src/main/java/com/alibaba/dubbo/config/annotation/Service.java

比如2.6.5tag
https://github.com/apache/incubator-dubbo/blob/dubbo-2.6.5/dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/annotation/Service.java

**Comment by kexianjun** [comment]
> > I have check the code, the default value of export is false in the old version, the latest version is true, and it works fine for me in the latest version, can your pls tell us witch version you use, and also provide a demo to reproduce this problem?
> 
> 我也很奇怪,因为查过几个类似的问题你们都说最新版本都已经修复了,但是我查看最新版本的代码,依然还是false,我不知道您所说的已经修复的版本具体是指?
> 
> 另外我们目前用的版本是2.6.2
> 
> 比如master分支
> https://github.com/apache/incubator-dubbo/blob/master/dubbo-compatible/src/main/java/com/alibaba/dubbo/config/annotation/Service.java#L44
> 
> 比如3.x-dev分支
> https://github.com/apache/incubator-dubbo/blob/3.x-dev/dubbo-compatible/src/main/java/com/alibaba/dubbo/config/annotation/Service.java#L44
> 
> 比如2.6.5tag
> https://github.com/apache/incubator-dubbo/blob/dubbo-2.6.5/dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/annotation/Service.java#L47

the package'name has been renamed to org.apchae, pls seee this file 
https://github.com/apache/incubator-dubbo/blob/master/dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/annotation/Service.java
