### ISSUE TITLE
how to choose dubbo ，alibaba version or apache incubator-dubbo ?

### ISSUE THREAD

**Issue by xhqgogogo** [apache/incubator-dubbo#3493]
If you want to use dubbo, will POM win by referring to com. alibaba. Dubbo or org. apache. dubbo, or by using sentinel and other enhancement components of dubbo?

想使用dubbo， 那pom就赢是引用com.alibaba.dubbo ，还是org.apache.dubbo呢，后面还是想用dubbo 的 sentinel 等增强组件

**Comment by chickenlj** [comment]
2.6.x及以下版本，请使用：com.alibaba.dubbo
2.7.0开始，使用org.apache.dubbo

sentinel等适配组件，官方集成版本有些还是对接的dubbo-2.6.x，即使用的com.alibaba.dubbo。
对接最新2.7.0版本的适配组件有些还未发布。

**Comment by xhqgogogo** [comment]
请问后面如果我想从 com.alibaba.dubbo 升级到 org.apache.dubbo 是否能平滑升级呢，有做好兼容吗？
（PS：现在我遇到这样的问题，从dubbox升级回dubbo不兼容，需要所有项目同时升级才能互相调用，这引起极大的麻烦 ，所以想在选型时确定好 ）

**Comment by chickenlj** [comment]
2.7.0与低版本的兼容性，请参考这里的总结：http://dubbo.apache.org/zh-cn/docs/user/versions/version-270.html

**Comment by chickenlj** [comment]
首先，从功能上来说，2.7.0对低版本2.6 2.5是完全兼容的，也就是说版本之间可以互相发现与调用，老版本可以逐步升级为2.7.0版本实现平滑升级。

包修改可能会带来一些改造成本，尤其是你有自定义SPI扩展的情况下，但这个问题是显示的在开发阶段完成的，不会带来运行期升级问题。

2.7.0中的新功能或新的使用方式，你可以逐步按需启用，也就是说在升级Dubbo到2.7.0的依赖后，理论上可以继续以2.6的方式使用。
