### ISSUE TITLE
URL produces too much garbage objects

### ISSUE THREAD

**Issue by kezhenxu94** [apache/incubator-dubbo#3494]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

## PROBLEM
Most of the `setXxxx` and `addParameter*` in `URL` such as `org.apache.dubbo.common.URL#addParameter` and `setXxxx` will return a new `URL` object for chaining calls, and most of the *"middle objects"* are useless and unnecessary, example below:

> class `org.apache.dubbo.config.spring.SimpleRegistryExporter`

```java

    public static Exporter<RegistryService> export(int port, RegistryService registryService) {
        return protocol.export(proxyFactory.getInvoker(registryService, RegistryService.class,
                // HERE
                new URL("dubbo", NetUtils.getLocalHost(), port, RegistryService.class.getName())
                        .setPath(RegistryService.class.getName()) // useless
                        .addParameter(Constants.INTERFACE_KEY, RegistryService.class.getName()) // useless
                        .addParameter(Constants.CLUSTER_STICKY_KEY, "true") // useless
                        .addParameter(Constants.CALLBACK_INSTANCES_LIMIT_KEY, "1000") // useless
                        .addParameter("ondisconnect", "disconnect") // useless
                        .addParameter("subscribe.1.callback", "true") // useless
                        .addParameter("unsubscribe.1.callback", "false")));
    }
```

> class `org.apache.dubbo.config.ServiceConfig`

```java

    @SuppressWarnings({"unchecked", "rawtypes"})
    private void exportLocal(URL url) {
        if (!Constants.LOCAL_PROTOCOL.equalsIgnoreCase(url.getProtocol())) {
            // HERE
            URL local = URL.valueOf(url.toFullString())
                    .setProtocol(Constants.LOCAL_PROTOCOL) // useless
                    .setHost(LOCALHOST_VALUE) // useless
                    .setPort(0);
            Exporter<?> exporter = protocol.export(
                    proxyFactory.getInvoker(ref, (Class) interfaceClass, local));
            exporters.add(exporter);
            logger.info("Export dubbo service " + interfaceClass.getName() + " to local registry");
        }
    }
```

## SOLUTION

And I suggest refactoring the `URL` with [Builder Pattern](https://en.wikipedia.org/wiki/Builder_pattern). And the possible usage may be:

```java
URL url = ...;
URL newURL = new URLBuilder(url)
.addParameter(k, v)
.addParameter(k2, v2)
.setPath(yourPath)
.build();
```

Though we cannot remove the original `addXXX` and `setXxxx` methods due to compability, we can mark them as deprecated and guide users to use the new `URLBuilder`.

> I'd like to try refactoring this if it's good to the comunity :)

**Comment by chickenlj** [comment]
At least, this could avoid the recreation of URL in the `export` and `refer` process.

But, please keep in mind that the URL is designed to be immutable when `Invoker` is created.

**Comment by kezhenxu94** [comment]
@chickenlj The **SOLUTION** I proposed doesn't break the immutability of `URL`, the proposed `URLBuilder` is used to reduce the **middle state objects** when building a new `URL` from an old one.

**Comment by chickenlj** [comment]
Great, looking forward to URLBuilder being available soon.

**Comment by kezhenxu94** [comment]
@chickenlj FYI, I've opened a PR #3500 to fix this issue

**Comment by chickenlj** [comment]
Cool, I am on it.

**Comment by chickenlj** [comment]
I've started a thread discussing this feature on the mailing list.
