### ISSUE TITLE
Call Dubbo Service  return    NullPointerException

### ISSUE THREAD

**Issue by liu2510865** [apache/incubator-dubbo#3496]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.5.3
* Operating System version: Linux version 2.6.32-573.22.1.el6.x86_64 (mockbuild@c6b8.bsys.dev.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC) ) #1 SMP Wed Mar 23 03:35:39 UTC 2016
* Java version: java version "1.8.0_162"

### Steps to reproduce this issue

1. call api throw null exception

 
What actually happens?

If there is an exception, please attach the exception trace:

```
java.lang.NullPointerExceptionat sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)at java.lang.reflect.Constructor.newInstance(Constructor.java:423)at com.alibaba.com.caucho.hessian.io.JavaDeserializer.instantiate(JavaDeserializer.java:271)at com.alibaba.com.caucho.hessian.io.JavaDeserializer.readObject(JavaDeserializer.java:155)at com.alibaba.com.caucho.hessian.io.SerializerFactory.readObject(SerializerFactory.java:397)at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObjectInstance(Hessian2Input.java:2070)at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2005)at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:1990)at com.alibaba.dubbo.common.serialize.support.hessian.Hessian2ObjectInput.readObject(Hessian2ObjectInput.java:88)at com.alibaba.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.decode(DecodeableRpcResult.java:92)at com.alibaba.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.decode(DecodeableRpcResult.java:109)at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCodec.decodeBody(DubboCodec.java:97)at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:126)at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:87)at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCountCodec.decode(DubboCountCodec.java:46)at com.alibaba.dubbo.remoting.transport.netty.NettyCodecAdapter$InternalDecoder.messageReceived(NettyCodecAdapter.java:134)at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:80)at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274)at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261)at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:349)at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:280)at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:200)at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:44)at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)at java.lang.Thread.run(Thread.java:748)
```

**Comment by Bricks-Man** [comment]
Could you push a demo for this issue?Without demo, it is difficult to reproduce this problem.

**Comment by carryxyh** [comment]
Hi @liu2510865 , does your params have a no-args Constructor (private or public) ?

**Comment by liu2510865** [comment]
Hi @carryxyh  

The calling method is as follows：

![image](https://user-images.githubusercontent.com/4935445/52927122-dd62b500-3373-11e9-93ab-2d2eac2847fe.png)

**Comment by carryxyh** [comment]
Yeah, but can u check whether your rpc param has a no-args Constructor?
I just find a xxxMap in your pic..

**Comment by liu2510865** [comment]
@carryxyh 
this is   interface  statement
![image](https://user-images.githubusercontent.com/4935445/52930043-db075780-3381-11e9-9e4a-4b8e4b909082.png)

Provider:
` <dubbo:provider delay="-1"/>
    <dubbo:registry protocol="zookeeper" address="${dubbo.registry.address}"/>
    <dubbo:protocol name="dubbo" port="20891" threads="300"/>
    <dubbo:consumer timeout="10000" check="false"/>`
` <dubbo:service interface="com.alfred.mobile_service.service.payment.AppPaymentSettlementService"
                   ref="appPaymentSettlementService"/>`

**Comment by carryxyh** [comment]
It seems that you can store any object in your map. 
Please check if they all have a parameterless constructor.

**Comment by liu2510865** [comment]
@carryxyh

I solved this problem ,is caused by a business exception in the service.

thanks

**Comment by carryxyh** [comment]
OK. I'd like close this issue.
