### ISSUE TITLE
Getting Start for dubbo 2.5.4-SNAPSHOT

### ISSUE THREAD

**Issue by dongwenting** [apache/incubator-dubbo#350]
最近在研究dubbo，可供参考。dubbo源码还是比较容易看懂的。

git clone https://github.com/alibaba/opensesame.git
cd opensesame
mvn clean install -DskipTests
下载依赖包: http://pan.baidu.com/s/1c2JSdkW 密码: ytpk
解压文件到.m2/repository/com/alibaba

git clone https://github.com/alibaba/dubbo.git
cd dubbo
mvn clean install -DskipTests
Eclispe->Window->Preferences->XML->Xml catalog-->Add
dubbo.xsd在dubbo-config\dubbo-config-spring下
![s](https://cloud.githubusercontent.com/assets/14174726/20737697/56e7d5f4-b6e9-11e6-95d0-875cabac2398.png)
Eclipse -> Menu -> File -> Import -> Exsiting Maven Projects -> Browse -> 选dubbo-> Finish
剩余bug：
annotation-version-consumer.xml删除version=2.0.0
ajax.js41行改为'delete' : function(url, fn) {
dubbo.xsd删除1027行

依次执行以下文件，右键-> Run As -> Java Application: 
dubbo-demo-provider/src/test/java/com.alibaba.dubbo.demo.provider.DemoProvider
dubbo-demo-consumer/src/test/java/com.alibaba.dubbo.demo.consumer.DemoConsumer
dubbo-monitor-simple/src/test/java/com.alibaba.dubbo.monitor.simple.SimpleMonitor
dubbo-registry-simple/src/test/java/com.alibaba.dubbo.registry.simple.SimpleRegistry

启动SimpleRegistry后需要修改配置文件，dubbo.registry.address=dubbo://127.0.0.1:9090，再重启服务:
dubbo-demo-provider/src/test/resources/dubbo.properties
dubbo-demo-consumer/src/test/resources/dubbo.properties
dubbo-monitor-simple/src/test/resources/dubbo.properties
dubbo-registry-simple/src/test/resources/dubbo.properties

访问http://127.0.0.1:8080

**dubbo-demo**
DemoConsumer，DemoProvider都调用com.alibaba.dubbo.container.Main.main(args);
该Main分析启动参数-D或dubbo.properties文件中是否指定dubbo.container和dubbo.shutdown.hook。
dubbo.container：创建容器的类型，默认创建Log4jContainer和SpringContainer容器。
dubbo.shutdown.hook：为true时设置程序退出时清理现场的钩子，即调用container.stop()清理容器。默认为null。

至此成功加载dubbo-demo-consumer的META-INF/spring/dubbo-demo-action.xml和dubbo-demo-consumer.xml文件。
dubbo-demo-action.xm：定义如何使用服务提供方接口。
dubbo-demo-consumer.xml：定义引用dubbo的服务提供方接口。
成功加载dubbo-demo-provider的META/spring/dubbo-demo-provider.xml。
dubbo-demo-provider.xml：为服务提供方接口定义具体实现。

Dubbo默认自动加载classpath根目录下的dubbo.properties，可以通过JVM启动参数：-Ddubbo.properties.file=xxx.properties 改变缺省配置位置。

**dubbo-test**
dubbo-test-examples：各种基本功能的测试，比如annotation测试注释功能，async测试异步调用功能，cache测试cache属性，generic测试泛型功能，merge测试group属性，都是先启动*Provider.java，再启动*Consumer.java。

**dubbo-container**
分为四种容器：jetty/log4j/logback/spring
Container：容器，提供start()和stop()两个接口用于启动和停止容器
JettyContainer：采用mortbay.jetty起了个Server。
Log4jContainer：start()时检查是否设置dubbo.log4j.file（log4j日志输出路径），如果设置，则创建一个DailyRollingFileAppender，检查是否设置dubbo.log4j.subdirectory配置日志子目录，用于多进程启动，避免冲突。
LogbackContainer：跟Log4jContainer类似。
SpringContainer：start()时检查是否设置dubbo.spring.config（配置文件路径），没有则默认加载"classpath*:META-INF/spring/*.xml下的配置文件，创建ClassPathXmlApplicationContext。

**Comment by ralf0131** [comment]
This is an article about learning Dubbo, which does not belong to issue.
