### ISSUE TITLE
dubbo2.7 自动生成异步接口

### ISSUE THREAD

**Issue by ChenAt** [apache/incubator-dubbo#3512]
http://dubbo.apache.org/zh-cn/blog/dubbo-new-async.html
我看到这篇文章的示例2，但是并没有在官方 sample 找到任何例子？请问现在这个支持的怎样了？

**Comment by chickenlj** [comment]
请先阅读这两篇关于异步支持的文档：
[Consumer异步调用](http://dubbo.apache.org/zh-cn/docs/user/demos/async-call.html)
[Provieer异步执行](http://dubbo.apache.org/zh-cn/docs/user/demos/async-execute-on-provider.html)

> 我看到这篇文章的示例2，但是并没有在官方 sample 找到任何例子？请问现在这个支持的怎样了？

关于你提到的这种模式在正式的2.7.0版本中做了调整，请参见`consumer异步调用 -> 重载服务接口`小节。这里有关于这种模式支持的总结和设想：https://github.com/dubbo/dubbo-async-processor

抱歉这篇blog给你带来困扰，稍后我们将更新此篇blog。

**Comment by ChenAt** [comment]
> 请先阅读这两篇关于异步支持的文档：
> [Consumer异步调用](http://dubbo.apache.org/zh-cn/docs/user/demos/async-call.html)
> [Provieer异步执行](http://dubbo.apache.org/zh-cn/docs/user/demos/async-execute-on-provider.html)
> 
> > 我看到这篇文章的示例2，但是并没有在官方 sample 找到任何例子？请问现在这个支持的怎样了？
> 
> 关于你提到的这种模式在正式的2.7.0版本中做了调整，请参见`consumer异步调用 -> 重载服务接口`小节。这里也有关于这种模式支持的进一步总结和设想：https://github.com/dubbo/dubbo-async-processor
> 
> 抱歉这篇blog给你带来困扰，稍后我们将更新此篇blog。

好的明白了。
