### ISSUE TITLE
Why ProviderConfig.setDispatcher() do exchanger check?

### ISSUE THREAD

**Issue by Bricks-Man** [apache/incubator-dubbo#3518]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

我在ProviderConfig.setDispatcher()里面发现了如下代码：
I found the following code in ProviderConfig.setDispatcher()：
```
    public void setDispatcher(String dispatcher) {
        checkExtension(Dispatcher.class, Constants.DISPATCHER_KEY, exchanger);
        checkExtension(Dispatcher.class, "dispather", exchanger);
        this.dispatcher = dispatcher;
    }
```
我不明白为什么需要在这里做这个检查。
I don't understand why this method needs to do this check here.

**Comment by chickenlj** [comment]
I believe exchanger was accidentally checked in here, we should remove it or change to dispatcher.

**Comment by Bricks-Man** [comment]
> I believe exchanger was accidentally checked in here, we should remove it or change to dispatcher.

Well,I think it's an accidentally,too.Could I commit a pr to fix it?

**Comment by CrazyHZM** [comment]
Please feel free to submit.
