### ISSUE TITLE
dubbo 2.7.0 导致springboot中 @Configuration无法使用

### ISSUE THREAD

**Issue by haozi000005** [apache/incubator-dubbo#3529]
### Environment

* Dubbo version: 2.7.0
* Operating System version: windows
* Java version: 1.8

### Steps to reproduce this issue

1. 配置写到单独的被@Configuration标记的配置类中
2. 使用@SpringBootApplication启动项目Main
3. 配置类中的@Bean不执行

**Comment by haozi000005** [comment]
配置类中的@Bean写在Main中是可以执行的

**Comment by mercyblitz** [comment]
Hi, how about your `@Configuration` class.

**Comment by haozi000005** [comment]
`@Configuration
public class DubboProviderConfig {

	@Bean
	public ApplicationConfig applicationConfig() {
		ApplicationConfig applicationConfig = new ApplicationConfig();
		applicationConfig.setName("money-application");
		return applicationConfig;
	}

	@Bean
	public RegistryConfig registryConfig(@Value("${zoo_hosts:zookeeper://127.0.0.1:2181}") String hosts) {
		RegistryConfig config = new RegistryConfig();
		config.setCheck(false);
		config.setAddress(hosts);
		config.setClient("curator");
		Map<String, String> parameters = new HashMap<>();
		parameters.put("qos.enable", "false");
		config.setParameters(parameters);
		return config;
	}

	@Bean
	public ProtocolConfig protocolConfig(@Value("${provider_port:10300}") int port,
			@Value("${provider_host:0.0.0.0}") String host) {
		ProtocolConfig config = new ProtocolConfig();
		config.setName("dubbo");
		config.setServer("netty4");
		config.setPort(port);
		config.setHost(host);
		config.setSerialization("hessian2");
		config.setThreads(500);
		return config;
	}

	@Bean
	public ProviderConfig providerConfig() {
		ProviderConfig config = new ProviderConfig();
		config.setVersion(Constants.SERVICE_VERSION);
		config.setLoadbalance("idBalance");
		config.setDispatcher("all");
		return config;
	}
	
	@Bean
	public ConsumerConfig consumerConfig() {
		ConsumerConfig config = new ConsumerConfig();
		config.setCheck(false);
		config.setMock(false);
		config.setLoadbalance("idBalance");
		config.setClient("netty4");
		config.setTimeout(Constants.DUBBO_RPC_TIMEOUT);
		config.setVersion(Constants.SERVICE_VERSION);
		return config;
	}
}`

**Comment by haozi000005** [comment]
> Hi, how about your `@Configuration` class.

`@Configuration
public class DubboProviderConfig {

	@Bean
	public ApplicationConfig applicationConfig() {
		ApplicationConfig applicationConfig = new ApplicationConfig();
		applicationConfig.setName("money-application");
		return applicationConfig;
	}

	@Bean
	public RegistryConfig registryConfig(@Value("${zoo_hosts:zookeeper://127.0.0.1:2181}") String hosts) {
		RegistryConfig config = new RegistryConfig();
		config.setCheck(false);
		config.setAddress(hosts);
		config.setClient("curator");
		Map<String, String> parameters = new HashMap<>();
		parameters.put("qos.enable", "false");
		config.setParameters(parameters);
		return config;
	}

	@Bean
	public ProtocolConfig protocolConfig(@Value("${provider_port:10300}") int port,
			@Value("${provider_host:0.0.0.0}") String host) {
		ProtocolConfig config = new ProtocolConfig();
		config.setName("dubbo");
		config.setServer("netty4");
		config.setPort(port);
		config.setHost(host);
		config.setSerialization("hessian2");
		config.setThreads(500);
		return config;
	}

	@Bean
	public ProviderConfig providerConfig() {
		ProviderConfig config = new ProviderConfig();
		config.setVersion(Constants.SERVICE_VERSION);
		config.setLoadbalance("idBalance");
		config.setDispatcher("all");
		return config;
	}
	
	@Bean
	public ConsumerConfig consumerConfig() {
		ConsumerConfig config = new ConsumerConfig();
		config.setCheck(false);
		config.setMock(false);
		config.setLoadbalance("idBalance");
		config.setClient("netty4");
		config.setTimeout(Constants.DUBBO_RPC_TIMEOUT);
		config.setVersion(Constants.SERVICE_VERSION);
		return config;
	}
}
`

**Comment by haozi000005** [comment]
我从2.6.5升级到2.7.0，碰到了以下问题。
我的IDE是eclipse
1.在启动类Main中添加注解 @SpringBootApplication
2.配置类写在另外的位置用@Configuration标记
3.此时启动Main无法执行配置类中的@Bean。

在不修改其余代码和配置的情况下，修改启动类名称Main->Launcher，就可以正常执行配置类中的@Bean了。
