### ISSUE TITLE
Netty 的消息处理类（继承自ChannelDuplexHandler）交给spring之后，会自动被触发一些（例如handlerRemoved）事件

### ISSUE THREAD

**Issue by haozi000005** [apache/incubator-dubbo#3545]
### Environment

* Dubbo version: 2.7.0
* Operating System version: windows
* Java version: 1.8
Netty 的消息处理类（继承自ChannelDuplexHandler）交给spring之后，会自动被触发一些（例如handlerRemoved）事件，能否请教下是否是dubbo在使用netty的时候触发的

**Comment by kexianjun** [comment]
Dubbo 在使用 netty 的过程中会触发类似 handlerRemoved，具体是怎么触发以及什么时候触发哪些事件可以去了解一下 netty 的实现机制.
