### ISSUE TITLE
dubbo在集成spring注解扫描时，对于spring代理/字节码增强后的Bean无法处理

### ISSUE THREAD

**Issue by roc-cn** [apache/incubator-dubbo#355]
> 高版本的Spring对于事物或者其他需要aop的bean处理，已经不在使用代理机制了，很多都是通过字节码增强，然后委派处理。

> dubbo的AnnotationBean对class的判断在遇到增强后的class通过反射会得不到com.alibaba.dubbo.config.annotation.Service/com.alibaba.dubbo.config.annotation.Reference注解信息，导致服务的发布/引入失败。

> 对于原有的获取方式：`Service service = bean.getClass().getAnnotation(Service.class);` 需要修改一下。
> 我这里 改成了：
```java
        Class<?> clazz = getBeanClass(bean);
        Service service = clazz.getAnnotation(Service.class);
        private Class<?> getBeanClass(Object bean) {
		Class<?> clazz = bean.getClass();
		if (AopUtils.isAopProxy(bean)) {
			clazz = AopUtils.getTargetClass(bean);
		}
		return clazz;
	}
```
同样，对于`postProcessBeforeInitialization`注入时注解的获取也改成此方式

**Comment by Tong-c** [comment]
你好，可以幫我看下這個異常嗎，感覺和你這邊的問題類似，謝謝
![image](https://user-images.githubusercontent.com/14778144/29010058-1d737f12-7b5b-11e7-8cf4-7501a0f4cc7a.png)
代碼里有涉及到獲取運行時bean
![Uploading image.png…]()
,

**Comment by Tong-c** [comment]
你好，我這邊的項目在發佈dubbo服務時，會有大量異常，無法正常初始化，提示BeanCreationException，但我項目里有獲取運行時bean的一行代碼，想問下，是這行代碼的問題嗎？
![image](https://user-images.githubusercontent.com/14778144/29010544-a70aaf90-7b5e-11e7-8a1e-4bd77eb55cf3.png)

**Comment by ralf0131** [comment]
Hi, could you please send a pull request?

**Comment by ralf0131** [comment]
dup with #512
