### ISSUE TITLE
现在的dubbo与当当的dubbox兼容吗?

### ISSUE THREAD

**Issue by ldcsaa** [apache/incubator-dubbo#3551]
现在的dubbo与当当的dubbox兼容吗？一直用dubbox，想升级一下。
（虽然知道兼容的可能性几乎没有，碰碰运气问一下。）

dubbox修改了dubbo的序列化协议。
\dubbo\rpc\protocol\dubbo\DubboCodec.java 对比：
![image](https://user-images.githubusercontent.com/5990337/53237923-dbca2180-36d2-11e9-9fb4-3a7c260e9c7e.png)

**Comment by htynkn** [comment]
similar with #3537

**Comment by chickenlj** [comment]
Duplicate of #3537
