### ISSUE TITLE
some error link in issue 2911

### ISSUE THREAD

**Issue by morisenmen** [apache/incubator-dubbo#3553]
Just some error link should be fixed in the follow issue:
[https://github.com/apache/incubator-dubbo/issues/2911]
1.[dubbo-samples] repo link should be [https://github.com/apache/incubator-dubbo-samples]
2.[高级用法，多Protocol] link does not exists
3.[高级用户，多Protocol] show us the multi protocol config is [dubbo.protocol.xx.]
#key格式: dubbo.{配置项名称}.{id}.{property}
```
dubbo.protocol.dubbo.name=dubbo
dubbo.protocol.dubbo.port=20990

dubbo.protocol.hessian.name=hessian
dubbo.protocol.hessian.port=8080
```
But,In[https://github.com/apache/incubator-dubbo/issues/1141] says that should be config with[ dubbo.protocols]
And hope that ConfigCenter example contain a Nacos example.

**Comment by ralf0131** [comment]
Question 1 and 2.  Please track the latest doc [here](https://github.com/apache/incubator-dubbo-website/issues/266). If you found any issue, please also reported there.

Question 3. Please follow the latest documentation.

Question 4. Nacos as Config Center has not been impletemented yet. It is expected in 2.7.1.
