### ISSUE TITLE
关于 backup provider 使用场景

### ISSUE THREAD

**Issue by thinkerFenglm** [apache/incubator-dubbo#3554]
1、目前 dubbo 支持多注册中心、只注册、只订阅模式，但不支持只有当前集群环境没有 provider 提供服务时， 会去调用 backupProvider 所在集群的 provider 提供服务。
2、建议增加类似 backupProvider 配置项, `<dubbo:registry address="${dubbo.registry.address}"  backupProvider="${dubbo.registry.backup.provider}"/>`

**Comment by chickenlj** [comment]
Will multi registries meet your requirement? You have, 
<dubbo:registry address="${dubbo.registry.address1} default="true" />
<dubbo:registry address="${dubbo.registry.address2} />

In this case, registry2 is a backup for registry1.

**Comment by thinkerFenglm** [comment]
3q
