### ISSUE TITLE
NPE when package of interface is empty.

### ISSUE THREAD

**Issue by ujjboy** [apache/incubator-dubbo#3556]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.0

### Steps to reproduce this issue

1. Interface without package.

![image](https://user-images.githubusercontent.com/1424920/53320488-ca6e5880-3910-11e9-9493-e074ff1f91a7.png)

2. Export service.
```java
serviceConfig.setInterface(HelloService.class.getName());
serviceConfig.setRef(new HelloServiceImpl());
```

### Expected Result

Export service.

### Actual Result

Catch NPE when export service.

```
java.lang.NullPointerException
	at com.alibaba.dubbo.common.Version.getVersion(Version.java:127)
	at com.alibaba.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:440)
	at com.alibaba.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:358)
	at com.alibaba.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:317)
```

**Comment by tswstarplanet** [comment]
Does the picture have problems ? The interface is in package "com".
