### ISSUE TITLE
com.alibaba.dubbo.rpc.RpcException: Unsupported client type: httpclient, supported client type is grizzly mina netty netty4

### ISSUE THREAD

**Issue by Python-IBM** [apache/incubator-dubbo#3562]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: v2.6.5
* Operating System version:windows 7
* Java version: v1.8

### Steps to reproduce this issue

1. <dubbo:service id="helloService" interface="com.alibaba.hello.api.HelloService" version="1.0.0" protocol="dubbo,hessian" />
2.   <dubbo:reference id="helloService" interface="com.alibaba.hello.api.HelloService"/>

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

hope success

### Actual Result

com.alibaba.dubbo.rpc.RpcException: Unsupported client type: httpclient, supported client type is grizzly mina netty netty4

**Comment by tswstarplanet** [comment]
Would you pls provide a demo to reproduce the problem ?

**Comment by Python-IBM** [comment]
demo:

provider:
<dubbo:protocol name="dubbo" server="netty4" port="8010" accepts="100"/>
<dubbo:protocol name="hessian" server="jetty" port="8011" accepts="100"/>

<dubbo:service id="helloService" interface="com.alibaba.hello.api.HelloService" protocol="dubbo,hessian" />

consumer:
 <dubbo:consumer client="httpclient" >
        <dubbo:reference id="helloService" interface="com.alibaba.hello.api.HelloService"
    registry="leaseReference"/>
</dubbo:consumer>

**Comment by Python-IBM** [comment]
> Would you pls provide a demo to reproduce the problem ?

demo:

provider:
<dubbo:protocol name="dubbo" server="netty4" port="8010" accepts="100"/>
<dubbo:protocol name="hessian" server="jetty" port="8011" accepts="100"/>

<dubbo:service id="helloService" interface="com.alibaba.hello.api.HelloService" protocol="dubbo,hessian" />

consumer:
<dubbo:consumer client="httpclient" >
<dubbo:reference id="helloService" interface="com.alibaba.hello.api.HelloService"/>
</dubbo:consumer>

**Comment by CrazyHZM** [comment]
The value of the consumer side configuration client of dubbo should be one of grizzly mina netty netty4.

**Comment by Python-IBM** [comment]
> The value of the consumer side configuration client of dubbo should be one of grizzly mina netty netty4.

I want use the HTTP protocol.The exception was 'Unsupported client type: httpclient'

**Comment by Python-IBM** [comment]
> The value of the consumer side configuration client of dubbo should be one of grizzly mina netty netty4.

I want use the HTTP protocol.The exception was 'Unsupported client type: httpclient'
