### ISSUE TITLE
【事件通知】是否可以通过注解实现事件通知？

### ISSUE THREAD

**Issue by jaylinwang** [apache/incubator-dubbo#357]
dubbo在与spring结合时，是否可以通过注解方式实现事件通知呢，搜寻资料无果，故提出此问题。

希望有过此类经验的朋友帮忙解答 😄

**Comment by diecui1202** [comment]
@jaylinwang Could you please describe your requirement in detail? Or you could provide a demo for us.

Also, we are going to close it, feel free to reopen it. &READY-TO-CLOSE&

**Comment by zonghaishang** [comment]
feel free to reopen it

**Comment by wade0817wang** [comment]
如何使用注解实现xml配置的 onreturn回调？这个怎么没看到回答就关了
