### ISSUE TITLE
can't access the official site

### ISSUE THREAD

**Issue by Joker1995** [apache/incubator-dubbo#3571]
最近github和apache.org域名访问有些异常，有时候甚至无法访问,能否开一个中文网避免U KNOW WHY的原因呢？

**Comment by kexianjun** [comment]
github 和 Dubbo 官网一直是可以访问的

**Comment by Joker1995** [comment]
> github 和 Dubbo 官网一直是可以访问的

看起来是某些地区运营商屏蔽了的
![image](https://user-images.githubusercontent.com/12840349/53462128-b7c56200-3a7d-11e9-841e-8fd5c7c0612e.png)


![image](https://user-images.githubusercontent.com/12840349/53462113-a714ec00-3a7d-11e9-8efe-86a7b6f470af.png)
