### ISSUE TITLE
Conflict between curator client and dubbo

### ISSUE THREAD

**Issue by haozi000005** [apache/incubator-dubbo#3574]
dubbo版本 2.7.0

使用curator连接zoo
```java
             private void build() {
		client = CuratorFrameworkFactory.builder()
				.connectString(server)
				.sessionTimeoutMs(sessionTimeoutMs)
				.connectionTimeoutMs(connectionTimeoutMs)
				.retryPolicy(retryPolicy)
				.build();
		client.start();
              }
```
```xml
<dependency>
    <groupId>org.apache.dubbo</groupId>
    <artifactId>dubbo-dependencies-bom</artifactId>
     <version>${dubbo.version}</version>
     <type>pom</type>
     <scope>import</scope>
</dependency>
```
导致zoo客户端十分频繁的无法连接zoo服务器。
我使用的zookeeper服务器架在局域网上，在去掉上述dubbo-dependencies-bom后，连接正常

**Comment by Fuyao-JIANG** [comment]
It is confused that there are two zk implements in dubbo.

**Comment by haozi000005** [comment]
but my zkclient is a private instance @Fuyao-JIANG

**Comment by chickenlj** [comment]
related issue https://github.com/apache/incubator-dubbo/pull/3603

**Comment by chickenlj** [comment]
>导致zoo客户端十分频繁的无法连接zoo服务器。
我使用的zookeeper服务器架在局域网上，在去掉上述dubbo-dependencies-bom后，连接正常

I don't understand why `dubbo-dependencies-bom` will cause this problem.
