### ISSUE TITLE
[Issue] SpringStatusChecker execute errors on non-XML Spring configuration 

### ISSUE THREAD

**Issue by mercyblitz** [apache/incubator-dubbo#3615]
### Environment

* Dubbo version: ALL
* Operating System version: ALL
* Java version: ALL

Error code: 
```java
            while (cls != null && method == null) {
                try {
                    method = cls.getDeclaredMethod("getConfigLocations", new Class<?>[0]);
                } catch (NoSuchMethodException t) {
                    cls = cls.getSuperclass();
                }
            }
```

**Comment by WYongLin** [comment]
这个问题，使用spring boot，然后使用import dubbo xml方式也是有这个问题。

**Comment by dongdongzld** [comment]
这个问题依然存在，2.7.1，spring:UNKOWN
` // [Issue] SpringStatusChecker execute errors on non-XML Spring configuration
            // issue : https://github.com/apache/incubator-dubbo/issues/3615
            if(c instanceof GenericWebApplicationContext) { // ignore GenericXmlApplicationContext
                continue;
            }`
c是一个GenericWebApplicationContext但被忽略了，右侧的注释是说忽略GenericXmlApplicationContext？
