### ISSUE TITLE
关于 Dubbo 异步回调超时异常捕获

### ISSUE THREAD

**Issue by glmapper** [apache/incubator-dubbo#3617]
客户端发起异步调用，如何能够捕获到或者感知到超时？

* 在自定义 Filter 中，通过 RpcContext 获取到 Future 对象，然后设置 callback。问题是 DefaultFuture 中的 ResponseCallback 不是数组形式，而且在 FutureAdapter 中会提供默认实现，如下：
```java
 public FutureAdapter(ResponseFuture future) {
        this.future = future;
        this.resultFuture = new CompletableFuture<>();
        // set default callkback
        future.setCallback(new ResponseCallback() {
            @Override
            public void done(Object response) {
                Result result = (Result) response;
                FutureAdapter.this.resultFuture.complete(result);
                V value = null;
                try {
                    value = (V) result.recreate();
                } catch (Throwable t) {
                    FutureAdapter.this.completeExceptionally(t);
                }
                FutureAdapter.this.complete(value);
            }
            @Override
            public void caught(Throwable exception) {
                FutureAdapter.this.completeExceptionally(exception);
            }
        });
    }
```
从测试情况来看，在 Filter 的 invoke 方法中通过以下方式设置callback 会存在callback 执行覆盖问题
```java
Future<Object> future = rpcContext.getFuture(); // the case on async client invocation
      if (future instanceof FutureAdapter) {
        ((FutureAdapter) future).getFuture().setCallback(new CustomCallback());
      }
```

* 使用 onResponse ，onResponse 本身是有了返回结果时才会回调，所以如果发生超时的话意味着 onResponse 将不会被执行。

**Comment by carryxyh** [comment]
Under what circumstances do u need to set up a custom callback function?
If you just want to get a timeout exception(or other exception in a invoke), use the following code:

```
// your rpc invoke
CompletableFuture<Object> future = xxxService.xxx...

// set callback for future
future.whenComplete(new BiConsumer<Object, Throwable>() {
    @Override
    public void accept(Object o, Throwable throwable) {
        if (throwable != null) {
            // deal with invoke exception.
        } else {
            // deal with real data;
        }
    }
});
```

**Comment by glmapper** [comment]
I tried your way and can catch exceptions normally. I have a suggestion that the timeout is also returned to the client as a result, which can be obtained by hasException() and getException().

**Comment by carryxyh** [comment]
Hi. We may not be able to provide a method like `getException` here. Here we need to align the return value with jdk's `CompletableFuture` to provide the latest features. Some internal classes such as `Response` and `Result` are not suitable for being exposed to users here.

If my solution can solve your problem, would you like to close this issue? Thank you for your issue.
:)

**Comment by glmapper** [comment]
> Hi. We may not be able to provide a method like `getException` here. Here we need to align the return value with jdk's `CompletableFuture` to provide the latest features. Some internal classes such as `Response` and `Result` are not suitable for being exposed to users here.
> 
> If my solution can solve your problem, would you like to close this issue? Thank you for your issue.
> :)

Thks
