### ISSUE TITLE
关于dubbo提供者新增节点导致post请求二次调用问题

### ISSUE THREAD

**Issue by zhangchangwei** [apache/incubator-dubbo#3635]
### Environment

* Dubbo version: 2.6.3
* Operating System version: redhat 6.8
* Java version: 1.8.0_144

您好：

最近我在进行测试dubbo服务的热启停，节点增删对前台用户的影响，我使用jmeter进行持续POST请求，在我新增节点启动时，A(正常节点)节点运行正常，可以持续接收POST请求并将数据插入数据库，B节点（新增节点）会出现二次调用POST请求情况，导致应用报错，请问针对dubbo服务在有大量请求使用的前提下，新增节点是否会出现这种情况下？

**Comment by zonghaishang** [comment]
Try to cancel the default retry behavior, `<dubbo:reference ... retries="0" />`

**Comment by zhangchangwei** [comment]
> Try to cancel the default retry behavior, `<dubbo:reference ... retries="0" />`

前几次没有设置这个参数就出现了这种情况，后来加上了这个参数还是会出现，尝试多次之后换了dubbo2.6.6版本之后就没再出现，不知道是不是dubbo的bug还是什么问题

**Comment by zonghaishang** [comment]
When the application is first initialized, the request may be slower, then trigger times out, and the framework will retry by default.

If you still have problems, you can use the warm-up feature. `<dubbo:reference ... warpup="1800000"/>`, warm up for 30 minutes.
