### ISSUE TITLE
能否增加@Reference中url可配置方式，传入参数，我们需要直连方式

### ISSUE THREAD

**Issue by RobinsChens** [apache/incubator-dubbo#364]
能否增加@Reference中url可配置方式，传入参数，我们需要直连方式

**Comment by fenfenxu** [comment]
直连设置可参考这里：http://dubbo.io/User+Guide-zh.htm#UserGuide-zh-%E7%9B%B4%E8%BF%9E%E6%8F%90%E4%BE%9B%E8%80%85

**Comment by ralf0131** [comment]
Please check this: http://dubbo.apache.org/#!/docs/user/demos/explicit-target.md
