### ISSUE TITLE
Dubbo现在出来的新版本还支持injvm吗？

### ISSUE THREAD

**Issue by caojiele** [apache/incubator-dubbo#3641]
- [X] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Steps to reproduce this issue

比如这样配置<dubbo:protocol name="injvm" /> ，会不会配置成功，或者这样配置能暴露一份injvm协议的服务吗？

**Comment by zonghaishang** [comment]
I have confirmed this question and it is supported.

**Comment by caojiele** [comment]
> I have confirmed this question and it is supported.

tks!
