### ISSUE TITLE
通过注解来实现merger

### ISSUE THREAD

**Issue by www1350** [apache/incubator-dubbo#365]
通过xml形式可以实现merger
<dubbo:referenceinterface="com.xxx.DemoService"group="demo1,demo2"merger="true"/> 
        
是否可以通过注解的方式实现merger?
我尝试了下，如果写以下只会调用demo1
@Reference(version = "1.0.0",group = "demo1,demo2" )

**Comment by carryxyh** [comment]
@ Reference annotation don't support this at soon.
Do u still have problems about this?
If not, we will close it.

**Comment by www1350** [comment]
now.no problem on it.

**Comment by carryxyh** [comment]
Thx for your issue. 
 :)

&READY-TO-CLOSE&

**Comment by diecui1202** [comment]
@mercyblitz

**Comment by zonghaishang** [comment]
I have checked reference annotation, missing `merger ` attribute, it should be support in the future.
