### ISSUE TITLE
Two junit tests failed

### ISSUE THREAD

**Issue by zhaixiaoxiang** [apache/incubator-dubbo#3657]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Steps to reproduce this issue

Run `AbstractMonitorFactoryTest.testMonitorFactoryGroupCache()` or `DubboMonitorTest.testCount()` many times(may be less than 10 is enough), you will get junit test failed.

### Cause Analysis

- **AbstractMonitorFactoryTest.testMonitorFactoryGroupCache()**

In AbstractMonitorFactory.getMonitor(), if we call `thenRunAsync()` first, then call `FUTURES.put()`, 
in MonitorListener.run, FUTRUE.get() may get null, then the junit test failed.
![image](https://user-images.githubusercontent.com/11908486/54415689-faeb2a80-4737-11e9-80dd-aaf347905b4d.png)

![image](https://user-images.githubusercontent.com/11908486/54415734-240bbb00-4738-11e9-8713-410fe0f51b4f.png)

![image](https://user-images.githubusercontent.com/11908486/54415998-05f28a80-4739-11e9-985e-1b6650e567f1.png)

****

- **DubboMonitorTest.testCount()**
1. In DubboMonitor constructor, we starter a schedule that call `send()` every 20 milliseconds!!
2. In `testCount()`, we `collect()` first, then `send()`, and `send()` every 20 milliseconds backend, but we will reset data in `send()` everytime, so let's consider this sequence: we call `collect()`, and then call `send()`, and  before Assertions.assertEquals... , call `send()` backend by the schedule to reset the statisticsMap. 

![image](https://user-images.githubusercontent.com/11908486/54414686-e9ecea00-4734-11e9-9bf5-520b306ea352.png)

![image](https://user-images.githubusercontent.com/11908486/54414693-f5d8ac00-4734-11e9-9dc1-394c9870d963.png)

![image](https://user-images.githubusercontent.com/11908486/54414706-00934100-4735-11e9-8574-3cfcd3b108fc.png)

![image](https://user-images.githubusercontent.com/11908486/54414902-9cbd4800-4735-11e9-824a-86be05f0e50e.png)

I describe it in Chinese again:
这个问题是偶现的, 但是可以通过多次执行`testCount()`来复现(执行最多10次一般就能复现出来), 原因是, 在构造Du bboMonitor 的时候, 会启动一个定时器, 每个20毫秒来执行`send()`方法, 且在`send()`设置值以后, 就会reset 全局的statisticsMap, `testCount()`中考虑这么一个执行顺序: 先执行`collect()`, 在执行`send()`, 然后在执行诸多的Assertions.assertEquals之前, 可能会执行每20毫秒执行一次的`send()`, 在这个`send()`方法执行完成后, statisticsMap就会被重置, 导致junit test失败

**Comment by ralf0131** [comment]
This issue has been fixed.
