### ISSUE TITLE
dubbo REST添加扩展的filter时，如何注入Spring中的Bean ?

### ISSUE THREAD

**Issue by sunxboy** [apache/incubator-dubbo#366]
```
  <dubbo:protocol name="rest" port="${dubbo.protocol.rest.port}" threads="500" contextpath="rest" server="tomcat" accepts="500" com.xxxxxx.extension.AuthenticationTraceFilter"/>
```
如上配置，添加了一个扩展，AuthenticationTraceFilter 分别实现了ContainerRequestFilter，ContainerResponseFilter接口。
我想在AuthenticationTraceFilter引入spring中的其它对象，怎么做？@Autowired注解试过了，不行。

**Comment by wsjswy** [comment]
同样遇到这个问题啊；我是在Mock类中想引入spring的其它对象，但是无法注入成功

**Comment by kimmking** [comment]
getBean

**Comment by JasonCL2015** [comment]
`import com.alibaba.dubbo.config.spring.ServiceBean;
ServiceBean.getSpringContext().getBean("xxxServiceImpl")`

**Comment by sunpeng0119** [comment]
ServiceBean.getSpringContext()  这个方法找不到

**Comment by AlbumenJ** [comment]
直接配置对应的 setter 方法，如果在 spring 环境下会自动注入对应类型的 bean 的

参考：org.apache.dubbo.config.spring.extension.SpringExtensionInjector
