### ISSUE TITLE
dubbo支持消费者调用生产者过程当中的节点挂掉，然后迁移到其他节点吗？

### ISSUE THREAD

**Issue by gotheworld** [apache/incubator-dubbo#368]
dubbo支持消费者调用生产者过程当中的节点挂掉，然后迁移到其他节点吗？我配置了  生产者 cluster="failover" retries="2" 消费者依然异常返回

**Comment by diecui1202** [comment]
@gotheworld failover cluster satisfies your requirement. Make sure that when invokes to other providers, the providers are still online and healthy.

Feel free to reopen it. &READY-TO-CLOSE&

**Comment by zonghaishang** [comment]
Invoke failed dubbo framework will automatically find available nodes(excluding biz exception caught)
Temporarily closed, can be reopened
