### ISSUE TITLE
ConfigCenterConfig's member field's key wrong

### ISSUE THREAD

**Issue by tswstarplanet** [apache/incubator-dubbo#3682]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.1-SNAPSHOT
* Operating System version: MacOS 10.14
* Java version: 1.8

I find some member fields of ConfigCenterConfig are annotated by @Parameter, and the 'useKeyAsProperty' property of the annotation is set 'false'.
For example, the 'check' member field is annotated by @Parameter, and its key is "config.check", but the 'useKeyAsProperty' is false.
So the key of this field in URL's parameters is 'check' because the 'useKeyAsProperty' is false, but in config center configuration class like ApolloDynamicConfiguration, the class use 'config.check' to get the property from parameters of URL.
So I think we should adjust the setting. 
How about set the 'useKeyAsProperty' to true ?
I want to listen others' proposals.

### Steps to reproduce this issue
config 
```xml
<dubbo:configcenter address:xxx check="false"/>
```

### Expected Result
the key in url's parameters should be "config.check", because in apollo dynamic configuration class, it use the key to get the check property
What do you expected from the above steps？

### Actual Result

the key in parameters is check

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by chickenlj** [comment]
> So the key of this field in URL's parameters is 'check' because the 'useKeyAsProperty' is false, but in config center configuration class like ApolloDynamicConfiguration, the class use 'config.check' to get the property from parameters of URL.

I don't think the problem you described exists.
To clarify the relations between `check` and `useKeyAsProperty` and also to avoid misunderstanding, I add some comments on @Parameter, please help to check.

**Comment by slankka** [comment]
I noticed the properties of ConfigCenterConfig is not read **correctly** by `org.apache.dubbo.configcenter.support.apollo.ApolloDynamicConfiguration` 

Dubbo Version 2.7.1 
The namespace is changed to consumer, but the program still access the default namespace:dubbo
```
        ConfigCenterConfig configCenterConfig = new ConfigCenterConfig();
        configCenterConfig.setAddress("xxx.com");
        configCenterConfig.setProtocol("apollo");
        configCenterConfig.setNamespace("consumer");
```

The namespace is set by `config.namespace`, then it works fine.
```
 @Bean
    public ConfigCenterConfig configCenterConfig() {
        ConfigCenterConfig apollo = new ConfigCenterBuilder()
                .address("xxx.com")
                .protocol("apollo")
                .namespace("consumer")
                .appendParameter("config.namespace", "consumer")
                .build();

        return apollo;
    }
```

The code in `ApolloDynamicConfiguration`:
```
//CONFIG_NAMESPACE_KEY = "config.namespace"
//DEFAULT_GROUP = "dubbo"
dubboConfig = ConfigService.getConfig(url.getParameter(CONFIG_NAMESPACE_KEY, DEFAULT_GROUP));
```
And it always be "dubbo", due to the url field `parameters` has no `config.namespace` but `namespace`:


![ApolloDyC_20190723121050](https://user-images.githubusercontent.com/8142133/61696862-aa7c7d00-ad68-11e9-82a0-3a725449476b.jpg)

**Comment by slankka** [comment]
#4411 The problem has been solved. Please ignore.
