### ISSUE TITLE
The etcd3 lease should be recycled correctly

### ISSUE THREAD

**Issue by zonghaishang** [apache/incubator-dubbo#3684]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: xxx
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

`org.apache.dubbo.remoting.etcd.jetcd.JEtcdClientWrapper#doClose`:

```
if (globalLeaseId > 0) {
        revokeLease(this.globalLeaseId);
}
```

should be change to :

```
if (globalLeaseId != 0) {
        revokeLease(this.globalLeaseId);
}
```

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by ralf0131** [comment]
Hi, I checked the [doc](https://github.com/etcd-io/etcd/blob/master/Documentation/dev-guide/api_reference_v3.md), there is no guarantee that the id is positive number. So I think changing to `!=0` is safer.
