### ISSUE TITLE
路由扩展无法通过配置方式添加

### ISSUE THREAD

**Issue by yaosiyaoqi** [apache/incubator-dubbo#369]
![image](https://cloud.githubusercontent.com/assets/25213898/22098951/256702e6-de64-11e6-915b-6cb3ea90d80b.png)
没有router的属性

**Comment by lazyman54** [comment]
对的，dubbo源码里也没有定义这个属性，真是坑了

**Comment by tnndwc** [comment]
是啊，路由规则这块怎么配置扩展呢？后续会支持？
