### ISSUE TITLE
关于使用定制的 SPI 过滤器设置 requestTag 不生效问题

### ISSUE THREAD

**Issue by thinkerFenglm** [apache/incubator-dubbo#3694]
使用定制的 SPI 过滤器设置 requestTag，用@Activate 注解group=Constants.CONSUMER 在扩展定制filter 时debug 发现，先进的TagRouter 根据tag 过滤相应的Invoker，此时tag 还没有设置进去，当然在 InvokerInvocationHandler 设置的话是可以的，就是需要改源代码不好。

`/**
 * 路由标签
 */
@Activate(group = Constants.CONSUMER)
public class ServiceChainFilter implements Filter {

    @Override
    public Result invoke(Invoker<?> invoker, Invocation invocation) throws RpcException {
        String sc = EnvUtil.getM_service_chain();
        RpcContext.getContext().setAttachment(Constants.TAG_KEY,sc);
        return invoker.invoke(invocation);
    }

}`
请问有什么特殊技巧嘛？

**Comment by LiZhenNet** [comment]
你可以自定义一个Router

**Comment by thinkerFenglm** [comment]
> 你可以自定义一个Router

是的我在TagRouter 上做了定制化处理，扩展了一个Router

**Comment by blackbyang** [comment]
请问这个问题是只能够通过扩展Router来实现么？

**Comment by WildWolfBang** [comment]
Hi, brother:
Have you found the solutions? The Dubbo execute order is routers-->filters. But I wonder how to set the tag for the consumer by self-defined SPI filters?
