### ISSUE TITLE
dubbo date 序列化 时间值不对

### ISSUE THREAD

**Issue by Jasyl0519** [apache/incubator-dubbo#370]
在开发机器部署了一台provider. **linux机器的系统时间跟北京时间不匹配**. 
我在本地调用provider的dubbo接口返回date类型的时间的值不对. 时间比数据库里面的值多了8个小时,这是为什么?

* 数据库:mysql 
* 字段类型 timestamp
* java字段 java.util.Date

然后我修改了开机机器的系统时间, 跟北京时间一致, 调用dubbo接口返回date类型字段的值正常了,

这到底是为什么???
hessian 序列化的问题
还是date的问题

**Comment by lovepoem** [comment]
I think it's a dubbo serialize issue , please check your business logic and server machine time configuration
