### ISSUE TITLE
dubbo 2.7.1 请上传到maven仓库

### ISSUE THREAD

**Issue by lOCKemM** [apache/incubator-dubbo#3704]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

请上传到maven长裤 自己编译不通过

**Comment by nzomkxia** [comment]
dubbo 2.7.1还在发布流程中

**Comment by lOCKemM** [comment]
> dubbo 2.7.1还在发布流程中

请问流程要多久？是否可以在下载链接中附上jar？ #3386 #3275 的问题困扰了很久了

**Comment by ralf0131** [comment]
Please subscribe the dev mailing list for the latest news: http://dubbo.apache.org/zh-cn/docs/developers/contributor-guide/mailing-list-subscription-guide_dev.html
