### ISSUE TITLE
Merge dubbo-serialization-gson into incubator-dubbo

### ISSUE THREAD

**Issue by ralf0131** [apache/incubator-dubbo#3707]
Merge the code in https://github.com/dubbo/dubbo-serialization-gson into incubator-dubbo

**Comment by tswstarplanet** [comment]
Do we need to download the project and add it to dubbo manually, and then submit a pr ?

**Comment by ralf0131** [comment]
> Do we need to download the project and add it to dubbo manually, and then submit a pr ?

Yes.

**Comment by tswstarplanet** [comment]
I have merged the project to incubator-dubbo, and I will submit a PR.

**Comment by ralf0131** [comment]
This will be available from 2.7.2 onwards.
