### ISSUE TITLE
为什么dubbo2.7的异步调用返回的结果不用netty4.0的ChannelFurture处理呢

### ISSUE THREAD

**Issue by complone** [apache/incubator-dubbo#3715]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7
* Operating System version: Ubuntu 16.04 x64
* Java version: 1.7

### Steps to reproduce this issue

 是这样的，我在想为什么dubbo2.7的异步调用返回的结果不用ChannelFurture去实现呢

Pls. provide [GitHub address] to reproduce this issue.

Example：https://netty.io/4.0/api/io/netty/channel/ChannelFuture.html

![channelFutrue](https://user-images.githubusercontent.com/20021404/54796253-6a0dd500-4c8a-11e9-9e37-ac474ff9acc5.png)

**Comment by carryxyh** [comment]
Because it can only execute callbacks after a successful send, but what we need is to perform a callback after the result is returned.

**Comment by complone** [comment]
> Because it can only execute callbacks after a successful send, but what we need is to perform a callback after the result is returned.

But I look at the documentation, he will return when you finish or do not complete the IO operation.

Doc:

```A ChannelFuture is either uncompleted or completed. When an I/O operation begins, a new future object is created. The new future is uncompleted initially - it is neither succeeded, failed, nor cancelled because the I/O operation is not finished yet. If the I/O operation is finished either successfully, with failure, or by cancellation, the future is marked as completed with more specific information, such as the cause of the failure. Please note that even failure and cancellation belong to the completed state.```

**Comment by carryxyh** [comment]
We need server response but not a write complete notify.
Pls check it by writing a demo.

**Comment by complone** [comment]
> We need server response but not a write complete notify.
> Pls check it by writing a demo.


Ok, thank you for your reply.
