### ISSUE TITLE
make sure all files has ASF license header.

### ISSUE THREAD

**Issue by beiwei30** [apache/incubator-dubbo#3721]
Source file have ASF headers. There are a few xml files and shell scripts that are missing ASF headers.

**Comment by wanghbxxxx** [comment]
i'd like to fix it, pls assign it to me

**Comment by CrazyHZM** [comment]
> i'd like to fix it, pls assign it to me


Please feel free to submit

**Comment by htynkn** [comment]
we should have maven plugin to do this check?
do we have any configuration issue for that plugin?

**Comment by lovepoem** [comment]
Now rat plugin can check the asf header , but some file type is excluded. @beiwei30, can you please point out the file type check list ?
