### ISSUE TITLE
web site docs typo

### ISSUE THREAD

**Issue by PansonPanson** [apache/incubator-dubbo#3725]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

```
I am reading the docs of the website. 
In this page : https://dubbo.incubator.apache.org/zh-cn/docs/user/preface/requirements.html
There is a typo.
> “ 此时需要一个服务注册中心，动态的注册和发现服务，使服务的位置透明。”

it should be(“的” ——> "地"):
> “ 此时需要一个服务注册中心，动态地注册和发现服务，使服务的位置透明。”

```

**Comment by CrazyHZM** [comment]
Could you please send a pull request?
https://github.com/apache/incubator-dubbo-website

**Comment by PansonPanson** [comment]
others fixed
