### ISSUE TITLE
‘ Here’ link in CHANGES.md is invalid

### ISSUE THREAD

**Issue by CrazyHZM** [apache/incubator-dubbo#3732]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

Does it have to be replaced with an upgrade guide link for the official website?
http://dubbo.apache.org/zh-cn/docs/user/versions/version-270.html

**Comment by lixiaojiee** [comment]
I have moved this issue under the website project，please see [#346](https://github.com/apache/incubator-dubbo-website/issues/346), and now I will close this issue, if you have resolved it, please link [#346](https://github.com/apache/incubator-dubbo-website/issues/346) with your pr, thank you.

**Comment by CrazyHZM** [comment]
But the CHANGES.md file is under the project.
