### ISSUE TITLE
调用链追踪

### ISSUE THREAD

**Issue by filamoon** [apache/incubator-dubbo#374]
希望能在每次dubbo调用的时候，消费者都能向生产者传递一个request id，以实现全链路追踪的能力。
如果我自己修改源代码的话，应该从哪里入手呢？望大神指教。

**Comment by filamoon** [comment]
这个能力需要对应用层透明

**Comment by zhanghw89** [comment]
可以在RpcContext中存放相关请求id的参数

**Comment by filamoon** [comment]
那请问又是在哪里 set/get RpcContext呢？我需要在消费者发送请求之前 set，提供者处理请求的时候 get

**Comment by zhanghw89** [comment]
对的，你在consumer端进行setRpcContext,在provider端进行get 你之前存放的RpcContext

**Comment by filamoon** [comment]
consumer/provider 端的代码在哪里呢？请指点迷境

**Comment by ding112** [comment]
RpcContext.getContext()

**Comment by cescme** [comment]
((RpcInvocation)invocation).setAttachment，在filter的invoke方法中

**Comment by filamoon** [comment]
参数是放在 attachment 里面么？还是说自己在 RpcContext 新建一个成员来记录？

**Comment by filamoon** [comment]
所以说 attachment 是随着 rpc call 往下调用的是么？
我应该在ConsumerContextFilter里面放一个 requestId, 然后在 ContextFilter 里面读出来，对吧？

**Comment by zuohl** [comment]
可以参考京东基于dubbo实现的调用链跟踪

**Comment by eonezhang** [comment]
@zuohl 京东的有源代码吗，还有如果是异步调用如何处理

**Comment by justein** [comment]
zipkin可以实现

2017-08-01 

james_gosling 



发件人：zuohl <notifications@github.com>
发送时间：2017-07-31 21:09
主题：Re: [alibaba/dubbo] 调用链追踪 (#374)
收件人："alibaba/dubbo"<dubbo@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

可以参考京东基于dubbo实现的调用链跟踪

**Comment by wuyi5630** [comment]
用pinpoint 非侵入的

**Comment by junfengcode** [comment]
pinpoint +1

**Comment by ralf0131** [comment]
Hi, please check this blog: http://dubbo.apache.org/#!/blog/pinpoint.md?
