### ISSUE TITLE
dubbo-configcenter-etcd的pom文件有问题

### ISSUE THREAD

**Issue by MaWenlong1** [apache/incubator-dubbo#3741]
多了一个<parent>标签

**Comment by ralf0131** [comment]
I am not quite understand. Please specify what is the exact issue?

**Comment by zhangfei9734** [comment]
![image](https://user-images.githubusercontent.com/16345433/55007017-aa1de080-5019-11e9-9356-793436e214c6.png)

I saw
https://github.com/apache/incubator-dubbo/blob/master/dubbo-configcenter/dubbo-configcenter-etcd/pom.xml

**Comment by ralf0131** [comment]
I think there is something wrong when merging 2.7.1-release branch into master. I checked the 2.7.1 tag and all good. 

Would you mind send a pull request to fix this?
