### ISSUE TITLE
dubbo thrift协议问题

### ISSUE THREAD

**Issue by linbenxing** [apache/incubator-dubbo#375]
使用dubbo的thrift协议，服务端会全局缓存第一次调用的返回值类型，返回其他类型的返回值时报参数类型不匹配java.lang.IllegalArgumentException: argument type mismatch

**Comment by lovepoem** [comment]
@linbenxing can you paste more logs or sone code ?

**Comment by diecui1202** [comment]
&READY-TO-CLOSE& ?

**Comment by ralf0131** [comment]
I am closing this issue now, please feel free to reopen it if you still encounter it.
