### ISSUE TITLE
Merge dubbo-rpc-xmlrpc into incubator-dubbo

### ISSUE THREAD

**Issue by ralf0131** [apache/incubator-dubbo#3764]
Merge the code in https://github.com/dubbo/dubbo-rpc-xmlrpc into incubator-dubbo

**Comment by danielamorais** [comment]
Should I add as a dependency in dubbo-all, right? I did it and I changed the name of the package for org.apache.dubbo (previously was io.github.kimmking) but there's no snapshot in https://repository.apache.org/content/groups/snapshots/org/apache/dubbo/ and this is why the build is failing.

Can u help me?

**Comment by ralf0131** [comment]
What is the exact error you got?

**Comment by danielamorais** [comment]
The error was:

> Could not resolve dependencies for project org.apache.dubbo:dubbo:jar:2.7.2-SNAPSHOT: Failure to find org.apache.dubbo:dubbo-rpc-xmlrpc:jar:2.7.2-SNAPSHOT in https://repository.apache.org/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of apache.snapshots has elapsed or updates are forced

I made a lot of confusion, I was needed:
- rename packages from "com.alibaba" to "org.apache"
- add xmlrpc as a module in pom.xml of dubbo-rpc 

I fixed it. Could u please review my PR? I'm not sure if everything is ok

**Comment by ralf0131** [comment]
This will be available from 2.7.2 onwards.
