### ISSUE TITLE
dubbo service facade模式问题

### ISSUE THREAD

**Issue by ghost** [apache/incubator-dubbo#378]
public interface  ServiceFacade {
    pubic ServiceA getServiceA();
    public ServiceB  getServiceB();
}

public class ServiceFacadeImpl implements ServiceFacade {

@autowired
private ServiceA  serviceA;
pubic ServiceA getServiceA(){
    return serviceA;
}
}

public class ServiceAImpl  extends BaseServiceImpl implent ServiceA{

}

public class BaseServiceImpl {
@Autowired
private  SqlMapClient sqlMapClient;
}

执行如下方法:ServiceFacade.getServiceA().method1();
运行异常,SqlMapClient   必须实现串行化,

如何解决它？

**Comment by beiwei30** [comment]
not dubbo issue.
