### ISSUE TITLE
Updating to Dubbo 2.7.1 causing ClassNotFoundException: com.alibaba.dubbo.rpc.RpcInvocation

### ISSUE THREAD

**Issue by John-Smile** [apache/incubator-dubbo#3789]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.1
* Operating System version: xxx
* Java version: 1.8

### Steps to reproduce this issue

Our project reference class 'com.alibaba.dubbo.rpc.RpcInvocation'. But this class is not included in module 'dubbo-compatible'.
It will help us a lot if class 'com.alibaba.dubbo.rpc.RpcInvocation' may be added to module 'dubbo-compatible'.

**Comment by CrazyHZM** [comment]
The 2.7 version of the package naming has been changed to org.apache.dubbo, and this class is also under the dubbo-rpc module.

**Comment by cvictory** [comment]
Maybe you can import dependency:
```
    <groupId>org.apache.dubbo</groupId>
    <artifactId>dubbo-compatible</artifactId>
```
This is campatible jar for dubbo 2.6.x
