### ISSUE TITLE
How to change RpcContext some property value by telnet invoke?

### ISSUE THREAD

**Issue by yuxiao97** [apache/incubator-dubbo#3800]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.0
* Operating System version: Windows 10
* Java version: 1.8

I want set some RpcContext property value by telnet invoke, how to achieve it? thanks~

**Comment by kexianjun** [comment]
maybe you can implement your own telnet command, [SPI](http://dubbo.incubator.apache.org/zh-cn/docs/source_code_guide/dubbo-spi.html) will help you.

**Comment by yuxiao97** [comment]
> maybe you can implement your own telnet command, [SPI](http://dubbo.incubator.apache.org/zh-cn/docs/source_code_guide/dubbo-spi.html) will help you.

Yes,but invoke client is PHP, I need some attachments, so php client how to set it?

**Comment by kexianjun** [comment]
> > maybe you can implement your own telnet command, [SPI](http://dubbo.incubator.apache.org/zh-cn/docs/source_code_guide/dubbo-spi.html) will help you.
> 
> Yes,but invoke client is PHP, I need some attachments, so php client how to set it?

your telnet command implementation should be in your server side, so you can define your own argument rules, parse it and set RpcContext.

**Comment by yuxiao97** [comment]
> > > maybe you can implement your own telnet command, [SPI](http://dubbo.incubator.apache.org/zh-cn/docs/source_code_guide/dubbo-spi.html) will help you.
> > 
> > 
> > Yes,but invoke client is PHP, I need some attachments, so php client how to set it?
> 
> your telnet command implementation should be in your server side, so you can define your own argument rules, parse it and set RpcContext.

I implement TelnetHandler, but it not effect, use default InvokeTelnetHandler.

**Comment by yuxiao97** [comment]
> > > maybe you can implement your own telnet command, [SPI](http://dubbo.incubator.apache.org/zh-cn/docs/source_code_guide/dubbo-spi.html) will help you.
> > 
> > 
> > Yes,but invoke client is PHP, I need some attachments, so php client how to set it?
> 
> your telnet command implementation should be in your server side, so you can define your own argument rules, parse it and set RpcContext.

I found invoke command is default,so my implement is not worked, when use my config command can worded,  how to replace default invoke command???

**Comment by yuxiao97** [comment]
First we should implement org.alibaba.dubbo.remoting.telnet.TelnetHandler(dubbo version 2.6.0), like Dubbo Official website says (http://dubbo.apache.org/zh-cn/docs/dev/impls/telnet-handler.html) xxx=com.xxx.XxxTelnetHandler，when telneted, we can use xxx command. **we can also override default command, like invoke**, we just set <dubbo:provider telnet="invoke" /> invoke=com.xxx.XxxTelnetHandler, then org.alibaba.dubbo.remoting.telnet.TelnetHandler file dir is resoures/META-INFO/dubbo/internal.
