### ISSUE TITLE
启动dubbo服务提供者start.sh出现Starting the dubbo-demo-provider ....Ncat: Connection refused.

### ISSUE THREAD

**Issue by yxz1025** [apache/incubator-dubbo#381]
.Ncat: Connection refused.
.Ncat: Idle timeout expired (1000 ms).

**Comment by niweicumt** [comment]
没有更详细的信息吗

**Comment by yxz1025** [comment]
没有了 之后就启动成功了 每次启动都是同样的问题 但是本地启动是不会有问题的

**Comment by XiaoDongJi** [comment]
Starting the demo-provider ....Ncat: Connection refused
centos7 启动报这个，应该是脚本不兼容，不知道怎么处理

**Comment by czbxyls** [comment]
issue：https://github.com/apache/incubator-dubbo/issues/799

echo status | nc -i 1 $SERVER_HOST $SERVER_PORT | grep -c OK 改为
(echo status;sleep 1) | nc $SERVER_HOST $SERVER_PORT | grep -c OK

**Comment by beiwei30** [comment]
fix in 5d7b25a22cdf0f4d60dce445f454014a62bd71ee
