### ISSUE TITLE
some small problems

### ISSUE THREAD

**Issue by wuhulala** [apache/incubator-dubbo#3812]
1.  dubbo-test module  `pom.xml` --  `2.7.1-SNAPSHOT`  is wrong?
2. `org.apache.dubbo.metadata.store.MetadataReport` contants `META_DATA_SOTRE_TAG`  grammer error
3. `dubbo-dependencies-bom/pom.xml` 
![image](https://user-images.githubusercontent.com/10361981/55633604-54062580-57ef-11e9-9f18-32a545658e87.png)

**Comment by ralf0131** [comment]
This issue has been fixed from 2.7.2 onwards.
