### ISSUE TITLE
pull request 的时候 CI失败 怎么排查出现的问题

### ISSUE THREAD

**Issue by vio-lin** [apache/incubator-dubbo#3828]
pull request 的时候 CI没有通过请问下怎么排查。
看中间的log 看过两遍没有Filure 或者 Error
并且log 太长不好定位 出错误的位置。也没找到有什么操作文档

**Comment by CrazyHZM** [comment]
是哪个pr，我来看一下

**Comment by vio-lin** [comment]
> 是哪个pr，我来看一下
https://github.com/apache/incubator-dubbo/pull/3825  这个pr。 感谢

**Comment by CrazyHZM** [comment]
> > 是哪个pr，我来看一下
> > #3825  这个pr。 感谢

检查dubbo-demo-protobuf模块的时候出错了，你可以点击Details->   选择一个环境的运行结果->右上角的Raw log    来查看全部日志

**Comment by CrazyHZM** [comment]
如果没有其他问题我就暂时关闭这个issuse了

**Comment by vio-lin** [comment]
找到原因了。 邮箱推送不生效 导致消息知道的好慢  感谢
