### ISSUE TITLE
dubbo的@Service注解不支持占位符

### ISSUE THREAD

**Issue by huihuidaxia** [apache/incubator-dubbo#383]
```java
@Reference(version = "${dubbo.xxoo.version}")
```
并不能被正确替换，需要`com.alibaba.dubbo.config.spring.AnnotationBean`实现`org.springframework.context.EmbeddedValueResolverAware`接口已解决占位符问题

**Comment by ralf0131** [comment]
Hi, please check the latest code, this issue has been fixed.
