### ISSUE TITLE
dubbo 2.7.1 只订阅功能失效

### ISSUE THREAD

**Issue by liuyuehaifeng** [apache/incubator-dubbo#3836]
### Environment

* Dubbo version: 2.7.1
* Operating System version: win 7
* Java version: 1.8

### Steps to reproduce this issue

1. 在 <dubbo:registry ... register="true" />情况下，运行应用，待注册完成后，停止应用。
2. 在 <dubbo:registry ... register="false" />情况下，再次运行应用，发现service仍然会注册在zk上

经过排查，dubbo 2.7.1的服务提供者，默认是持久的注册到zk上（2.6.*是临时的）。
除了“只订阅”功能失效，还有其他问题：
当修改service信息后，url也随之变化，结果同一个service在zk上存在多条注册记录。

目前，只能通过设置 <dubbo:service dynamic="true">来实现临时注册；请问还有全局的设置方法吗？
另外，请问为什么要永久的注册到zk上，而不是临时呢？

**Comment by liuyuehaifeng** [comment]
通过 <dubbo:provider dynamic="true">来设置，但是最终会被 ServiceConfig.dynamic(false)覆盖掉，所以只能通过<dubbo:service dynamic="true">来设置？

**Comment by carryxyh** [comment]
Same issue here:
https://github.com/apache/incubator-dubbo/issues/3785

Will be fixed in next release.

**Comment by liuyuehaifeng** [comment]
ok
