### ISSUE TITLE
dubbo 泛化调用 webservice接口BUG

### ISSUE THREAD

**Issue by dingwenxiang0** [apache/incubator-dubbo#384]
泛化GenericService内的方法名叫 $invoke.  $符号没办法通过xml解析。

**Comment by ralf0131** [comment]
Hi, would you please provide more details?

**Comment by carryxyh** [comment]
There has no feedback for this issue.
I think it can be closed.

&READY-TO-CLOSE&

**Comment by zonghaishang** [comment]
Feel free to reopen it.
