### ISSUE TITLE
Need a script to check dependencies license

### ISSUE THREAD

**Issue by htynkn** [apache/incubator-dubbo#3840]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

As discussed in https://lists.apache.org/thread.html/e3112c832415850779af2fe04aa7325d8d776144f3939cc63f5eab08@%3Cdev.dubbo.apache.org%3E

In order to make sure all dependencies license is suitable for dubbo, we need a quick way (such as a convenient script) to check dependencies license.

**Comment by htynkn** [comment]
Also need think about situation like: https://github.com/apache/incubator-dubbo/issues/3790

**Comment by cvictory** [comment]
The pr have been merged。
