### ISSUE TITLE
dubbo消费者调用服务提供者的时候，将引用的对象更改后有没有办法传递给消费者

### ISSUE THREAD

**Issue by panfeng-Hn** [apache/incubator-dubbo#3842]
比如：有一个服务消费者通过dubbo调用了另一个服务提供者的方法，传入了一个对象，然后服务提供者的方法里面更改了这个对象，但是方法执行完成后消费者那边这个对象没有被改变。只能返回这个对象服务消费者才能拿到这个更改后的对象

**Comment by tjling** [comment]
![QQ截图20190411161759](https://user-images.githubusercontent.com/3849525/55941760-7b3c7700-5c75-11e9-9e89-98b27dc072c0.jpg)

**Comment by panfeng-Hn** [comment]
好的，谢谢
