### ISSUE TITLE
How about adding a slack channel for open discussion

### ISSUE THREAD

**Issue by eonezhang** [apache/incubator-dubbo#3860]
I think this would be a great step for developers all over the world to discuss issues or proposals more smoothly.

**Comment by carryxyh** [comment]
We recommend that you use the mailing-list to communicate. Where can we also communicate with developers around the world.

**Comment by chenlushun** [comment]
I think gitter is also a good choice, but not many people use it now.

**Comment by eonezhang** [comment]
gocha,
