### ISSUE TITLE
dubbo spring boot version question

### ISSUE THREAD

**Issue by CjqDy** [apache/incubator-dubbo#3870]
### Environment

* Dubbo version: 2.6.5
* Operating System version: win10
* Java version: 1.8_x

### Steps to reproduce this issue
consumer 使用 spring boot 依赖于 2.1.3.RELEASE版本启动没有问题
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.1.3.RELEASE</version>
    <relativePath/> 
</parent>
但是基于父子结构 ，用spring-boot-dependencies替换spring-boot-starter-parent
版本号还是2.1.3.RELEASE
启动时报
Exception in thread "main" java.lang.AbstractMethodError: org.springframework.boot.context.config.ConfigFileApplicationListener.supportsSourceType(Ljava/lang/Class;)Z
 
看源码ConfigFileApplicationListener确实没有实现supportsSourceType接口
接着spring-boot-dependencies版本换成 1.5.9.RELEASE，该版本实现了supportsSourceType接口
就能正常启动了

奇怪的是
spring-boot-starter-parent也是依赖于spring-boot-dependencies，为啥spring-boot-starter-parent可以正常启动，而spring-boot-dependencies却不可以？

希望大家帮我理理这个问题，感谢

**Comment by ralf0131** [comment]
I think this issue does not related to Dubbo.
