### ISSUE TITLE
为什么SPI的文件中的配置都是都是重复的

### ISSUE THREAD

**Issue by githubcheng2978** [apache/incubator-dubbo#3873]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: xxx
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Res
![02EB46E4-E55A-49F8-A293-33D347108BCE](https://user-images.githubusercontent.com/22095448/56109517-7e8c7700-5f83-11e9-816b-6adffb494127.png)
ult

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by carryxyh** [comment]
用2.7版本看下。这个问题应该是在2.6.3 2.6.4版本有，已经被修复掉了。

**Comment by githubcheng2978** [comment]
好的，已经被去掉了，但是我debug 源码的时候，出来另外一个问题：ProtocolListenerWrapper 和ProtocolListenerWrapper 这个两个顺序无法控制，我想问下，如果想实现aop 这个应该会有一个先后顺序的吧？
