### ISSUE TITLE
Integrate with SOFARegistry

### ISSUE THREAD

**Issue by ujjboy** [apache/incubator-dubbo#3874]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

SOFARegistry is a production-level, low-latency, high-availability service registry. Can we integrate with it?

**Comment by ralf0131** [comment]
Hi, 
Please feel free to go ahead and send the pull request :)
