### ISSUE TITLE
dubbo TagRouter does not work with dubbo:parameter

### ISSUE THREAD

**Issue by sanjy523892105** [apache/incubator-dubbo#3875]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.1
* Operating System version: win10
* Java version: jdk1.8.0_101

### Steps to reproduce this issue

1. 使用 [dubbo-demo-xml](https://github.com/apache/incubator-dubbo/tree/master/dubbo-demo/dubbo-demo-xml) 项目，或者其他测试项目
2. 启动两个provider示例，一个在 `<dubbo:service/>` 中加上`tag="groupA"` 我们叫他 `p1`，另一个不加tag 我们叫他 `p2`.
3. 在`<dubbo:reference>`标签中添加`<dubbo:parameter key="dubbo.tag" value="groupA"/>` 之后将consumer 示例启动
---
1. use [dubbo-demo-xml](https://github.com/apache/incubator-dubbo/tree/master/dubbo-demo/dubbo-demo-xml), or other demo .
2. prepare two providers, one set `tag="groupA"` at `<dubbo:service/>` called `p1` , another with no tag called `p2`. start them.
3. start a consumer instance ,after set `<dubbo:parameter key="dubbo.tag" value="groupA"/>` inside of `<dubbo:reference>`.

### Expected Result

因为拥有相同的tag声明，consumer本应该会调用到`p1`示例.
consumer would connect `p1`  because of the same tag definition

### Actual Result

但consumer依然可能连接到`p2`示例.
consumer also connects `p2`.

---
如果把 步骤3 的标签改为在调用代码中使用`RpcContext.getContext().setAttachment("dubbo.tag","groupA")`,是可以正常工作的。请问这两种方式有什么区别呢？

通过分析源码发现 在 [RegistryDiscovery](https://github.com/apache/incubator-dubbo/blob/1706807a1c9221fb13a24a8b318a56c699eea67d/dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java#L431) 中将consumer 端的parameter 整合到providerUrl 中。 请问为什么需要这步操作？

**Comment by chickenlj** [comment]
I test and both these two ways can work:
`RpcContext.getContext().setAttachment("dubbo.tag","groupA")` or `<dubbo:parameter key="dubbo.tag" value="groupA"/>`

**Comment by chickenlj** [comment]
Sorry `<dubbo:parameter key="dubbo.tag" value="groupA"/>` does have some problem, I just ran the wrong sample.
