### ISSUE TITLE
does dubbo support random port?

### ISSUE THREAD

**Issue by eonezhang** [apache/incubator-dubbo#3881]
as the title described. does dubbo already have this feature?

**Comment by foreveryang321** [comment]
already have this feature.
```properties
dubbo.protocol.name=dubbo
dubbo.protocol.port=-1
```

**Comment by DatPhanTien** [comment]
@foreveryang321 At the other extreme, we would like to know if the remote method invocation functionality provided by Dubbo requires extra port to be open?
With JAVA RMI protocol, we all know that the connection requires EXTRA port to be open. This port is randomly selected from the available ports. 
And clearly, we have no control over the selected port. This leads to potential issue with firewall policy on running machine.

Our question is:
1. Does Dubbo take control over the extra port assignment with RMI protocol?
2. If it is not, we will start to look to the other protocols, such as default Dubbo protocol or http. And for these protocols, does Dubbo open EXTRA port also to provide the remote method invocation functionality?
