### ISSUE TITLE
Static analysis suggestion

### ISSUE THREAD

**Issue by Moriadry** [apache/incubator-dubbo#3917]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

  I am wondering whether you want a code static analysis tool to avoid simple mistakes in Dubbo, I saw https://github.com/apache/incubator-dubbo/issues/1513 this suggestion, and maybe a Error Prone (https://github.com/google/error-prone) from google is a good choice. 

  Maybe it sometimes annoys us, but it can definitely help us to eliminate some serious bug.

  How do you guys think?

**Comment by jamesxuhaozhe** [comment]
well I believe FindBugs maybe a good tool that we can use. I find it widely used in almost every project in Amazon. It helped our team caught loads of simple and stupid bugs during my time in Amazon.
