### ISSUE TITLE
[Feature] Dubbo Cloud Native: To Add Service registration and discovery abstract

### ISSUE THREAD

**Issue by mercyblitz** [apache/incubator-dubbo#3942]
## Abstract

Dubbo Cloud Native requires an abstract for Service registration and discovery that will support Dubbo application as a whole service registering to a registry instead of Dubbo service interfaces.

## Concepts

It will introduce some new concepts:

- Dubbo Service name(a.k.a Dubbo Application name)
The name of Dubbo application is unique in the current application and the registry, which could be configured by the externalized property `dubbo.application.name` or set by `ApplicationConfig` directly.

- Dubbo Service instance
The minimum Dubbo registration unit must include:
  - service name: a.k.a Dubbo Application name that current service instance belongs to
  - hostname: The IP or hostname of the current service instance
  - service port: The port Dubbo services export
  - metadata: the metadata of the current instance, e.g, management port.

- Dubbo Service registry
Being different from the traditional Dubbo registry, Dubbo Application registry only accepts current Dubbo applications' registration, is like Spring Cloud Registry, and the metadata of Dubbo services will reside in their self-application.

- Dubbo Service discovery
It provides a mechanism to discovery Dubbo applications and Dubbo Service interfaces.

**Comment by chickenlj** [comment]
## 应用粒度注册

### 服务注册与发现
![image](https://user-images.githubusercontent.com/18097545/57497422-37876c80-730a-11e9-98b9-784cd2a6ea35.png)


### 解决微服务拆分的问题

如应用app1一拆为二：app1、app3，面向application的服务发现无法监听新增的app3，可能导致地址无法推送、服务接口调用失败。

**解决方案：**中心化存储中增加interface -> application映射关系，消费端同时监听interfaces、services下的两级目录

- 对于Dubbo面向接口的服务发现与调用，为了做到让用户侧无需感知应用拆分，额外保存interfaces数据
- 对于微服务面向应用，用户需明确感知应用拆分
![image](https://user-images.githubusercontent.com/18097545/57497413-2dfe0480-730a-11e9-8cf6-9fe9306699ee.png)


### 实例节点元数据

```json
{
  endpoints: [{protocol, ip, port}, {protocol, ip, port}]
  // 实例环境标
  weight:100,
  version:v1,
  environment:test
}
```

### MetadataService

1. 接口定义（初步设想）
```java
public interface DubboMetadataService {
    String VERSION = "1.0.0";

    String getVersion(); //如果要做版本隔离：metadataservice定义就需要注册到注册中心，或者就需要遍历每个实例的getVersion()

    List<String> getExportedUrls();

    List<String> getReferedUrls();

    String getExportedURLs(String serviceInterface, String group, String version);

    String getExportedURLs(String serviceInterface);
}
```

2. 暴露

   - 与标准Dubbo、REST协议共用端口，多协议暴露的情况下，metadataservice在每个端口都暴露？
   - MetaddataService元数据可开放配置项，但是不往注册中心注册。

   - 使用标准Protocol、ProxyFactory暴露服务，参考DubboMonitorFactory关于MonitorService的做法

3. 监听

- 实例按版本号分组，版本号是根据provider端的元数据（interface、method签名等）自动计算出来的，并在每次实例重启时注册到注册中心实例的元数据中。
- Online/offline 某个接口的解决方法？

## 使用方式

关键信息：**消费的application列表、application和reference的包含关系、registry注册模式**

- Dubbo内互调，注册中心额外维护interface -> application映射关系。
  ```xml
  <dubbo:reference interface="org.xxx.DemoService" />
  ```
- 微服务互通，指定provider应用名
  ```xml
  <dubbo:reference interface="org.xxx.DemoService" service="app-name"/>
  ```

迁移与改造

```xml
<!-- 迁移需要定义两个registry，默认是老的注册模型，使用新模型加mode=application参数 -->
<dubbo:registry address="zookeeper://127.0.0.1:2181"/>
<dubbo:registry address="zookeeper://127.0.0.1:2181?mode=application"/>

<!-- 终态。某个版本开始默认以新的模型做服务注册发现 -->
<dubbo:registry address="zookeeper://127.0.0.1:2181"/>
```

## 元数据存储
ApplicationModel

## 注册中心

- 注册，应用级事件，在元数据、端口监听完成后，写入到注册中心一次；多注册中心则注册多份
- 监听，在应用级监听，每个注册中心都做监听；监听应在refer之前，refer过程采集接口元数据



**定义一套新的应用级别的服务发现接口，用于实现面向应用的Registry和DiscoveryClient，驱动老的Regsitry接口与MetadataService的对接，以实现复用老的URL运转流程**



**裸的API方式需要一个统一的启动入口，以实现应用级别的服务暴露与注册**，Spring的事件入口，如ContextRefreshedEvent？代理到API入口
