### ISSUE TITLE
[Issue] Qos port can't be disabled by externalized property

### ISSUE THREAD

**Issue by mercyblitz** [apache/incubator-dubbo#3958]
Dubbo's Qos port can't be disabled by `dubbo.application.qos-enable=false`

**Comment by Moriadry** [comment]
Does it because we lost the QOS_ENABLE parameter in RegistryProtocol.getRegisteredProviderUrl method ? a little guess

**Comment by tswstarplanet** [comment]
@mercyblitz I test the configuration using incubator-dubbo-spring-boot-project, and I find it can disable the Qos using dubbo.application.qos-enable=false.

**Comment by tswstarplanet** [comment]
I use the sample in the incubator-dubbo-spring-boot-project to test

**Comment by wangwengeek** [comment]
我看官网 qos最下面又变成这样配置了试了一下管用
dubbo.application.qosEnable=true
dubbo.application.qosPort=33333
dubbo.application.qosAcceptForeignIp=false

**Comment by chickenlj** [comment]
I also cannot reproduce the problem, `dubbo.application.qos-enable=false` works for boot-starter.

**Comment by chickenlj** [comment]
But I think we should unify the the property name used in boot-starter and the core framework.
