### ISSUE TITLE
Merge rpc-native-thrift-for-apache-dubbo into incubator-dubbo

### ISSUE THREAD

**Issue by ralf0131** [apache/incubator-dubbo#3960]
Merge the code in https://github.com/dubbo/rpc-native-thrift-for-apache-dubbo into incubator-dubbo

Guide to add a new module to incubator-dubbo https://github.com/apache/incubator-dubbo-website/issues/350

**Comment by IanCao** [comment]
Assigned to me

**Comment by chickenlj** [comment]
Please see the comments I left on your pull request.
