### ISSUE TITLE
[Help] when I extened a new serialization SPI，how to decide contentType

### ISSUE THREAD

**Issue by vio-lin** [apache/incubator-dubbo#3982]
- [ X] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [X ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

I add one new  serialization and there can't find any useage of method Serialization.getContentType() in project.
So  what string should i return. And if there are some rules of this string value.

**Comment by Leishunyu** [comment]
I think that if it is a json type, use text/***, if it is a binary type, use x-application/***, what do you think?

**Comment by vio-lin** [comment]
I see.
