### ISSUE TITLE
dubbo and nacos 在2.7.1里存在的问题 是在下版本优化还是该版本解决

### ISSUE THREAD

**Issue by CjqDy** [apache/incubator-dubbo#4004]

**Comment by ralf0131** [comment]
What specific issue are you saying? Any issue found should be fixed in the next release.

**Comment by CjqDy** [comment]
@ralf0131  #490  and  I have also feedback in the group before, saying that there is some problem with the current 2.7.1 version adaptation nacos.

**Comment by CjqDy** [comment]
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([127.0.0.1:8848]) tried: failed to req API:http://127.0.0.1:8848/nacos/v1/ns/instance. code:400 msg: dom not found: 

today ,others also  has this problem

detail in  apache/incubator-dubbo-spring-boot-project    issue:490

**Comment by kele6413430** [comment]
I also have this problem now,so i can not raise up the version from 2.7.0 to 2.7.1

**Comment by CjqDy** [comment]
I only upgraded the version of dubbo and nacos-client to 2.7.1, but the version of nacos-server is not upgraded. Upgrade to 1.0.0.
Mainly when NameProxy calls callServer, the HttpClient.request request parameter changes and cannot be registered normally.
