### ISSUE TITLE
Dubbo2.7.1 服务shutdown后zk中的注册信息没有自动下线

### ISSUE THREAD

**Issue by spiritme1984** [apache/incubator-dubbo#4013]
我打算把项目中的dubbo版本由2.5.3升级至2.7.1，依赖升级后程序能够正常启动，但是发现在关闭服务后，注册中心zk中的 /dubbo/xxxService/providers下仍然存在该关闭服务的提供者信息。在2.5.3版本中没有这个问题（当服务关闭后，zk中会自动下线该提供者信息），以下是我的对应依赖版本：
        dubbo2.7.1
        curator 2.10.0
        zookeeper 3.4.6

项目中只是把dubbo升级2.5.3 ->2.7.1 , 其他的那两个依赖包版本没有变动。

**Comment by Leishunyu** [comment]
2.7.1 zk的服务节点是永久节点 这个问题已经在2.7.2中修复,或者通过在service中配置    <dubbo:service interface="org.apache.dubbo.demo.DemoService" ref="demoService" dynamic="true"/>

**Comment by spiritme1984** [comment]
试了，加了dynamic="ture"好像管用。。。啥时候发布2.7.2？

**Comment by Leishunyu** [comment]
> 试了，加了dynamic="ture"好像管用。。。啥时候发布2.7.2？
不出意外
应该这个月会发布的

**Comment by spiritme1984** [comment]
好的，谢谢！~ 希望能早点发布。。
