### ISSUE TITLE
consumer不能instanceof自定义异常

### ISSUE THREAD

**Issue by 51Bigod** [apache/incubator-dubbo#4016]
在官方文档上也没有找到配置自定义ExceptionFilter的方式。
使用版本2.5.10
请问是旧版本的问题吗，还是提供了其他配置方式

**Comment by Leishunyu** [comment]
You can use it , 
create META-INF/dubbo/org.apache.dubbo.rpc.Filter
xxxx=xxxxxFilter

**Comment by Leishunyu** [comment]
http://dubbo.apache.org/zh-cn/docs/dev/impls/filter.html

**Comment by 51Bigod** [comment]
非常感谢！
