### ISSUE TITLE
if the async bug fixed?

### ISSUE THREAD

**Issue by rongmin** [apache/incubator-dubbo#4019]
hi, all, pls refer to this url:
https://sanniangmiao.iteye.com/blog/2358446
just want to know if the current version of dubbo 2.7.x has fixed this bug?

**Comment by kexianjun** [comment]
I'll check it latter.

**Comment by chickenlj** [comment]
> hi, all, pls refer to this url:
> https://sanniangmiao.iteye.com/blog/2358446
> just want to know if the current version of dubbo 2.7.x has fixed this bug?

Yes, this issue has been fixed for a while, from a specific 2.6.x version, and in all 2.7.x version.

**Comment by kexianjun** [comment]
> > hi, all, pls refer to this url:
> > https://sanniangmiao.iteye.com/blog/2358446
> > just want to know if the current version of dubbo 2.7.x has fixed this bug?
> 
> Yes, this issue has been fixed for a while, from a specific 2.6.x version, and in all 2.7.x version.

I have checked, sure it has been fixed.

**Comment by rongmin** [comment]
thanks for your sincere reply
