### ISSUE TITLE
dubbo2.7 用隐式传参方式做异步调用时，调用future.get()会卡死

### ISSUE THREAD

**Issue by kele6413430** [apache/incubator-dubbo#4028]
* Dubbo version: 2.7.0
* Operating System version: any
* Java version: 1.8

1.  Because @Reference anonnation has bug on async  in the method scope ,so I  use the attachment to set the async .So luck, it  works on 2.6.2 before I raise the version up to 2.7

public static <T> Future<T> execute(Supplier<T> supplier) {
        RpcContext.getContext().setAttachment(Constants.ASYNC_KEY, "true");
        supplier.get();
        return RpcContext.getContext().getFuture();
    }
2. then I raise the version up to 2.7.
    It is sad that  I have 2 rpc method use async attachment continuously in one http interface
    but all of  future of the  methods   have no  result 
    future.get()  execute in while loop forever  
    the code is below 

![image](https://user-images.githubusercontent.com/16238117/57568017-10b55d00-7414-11e9-8aba-c6a01348ed03.png)
3、 I have read the FutureAdapter object ,the result is null,but the future has obtained the reponse 

![image](https://user-images.githubusercontent.com/16238117/57568041-61c55100-7414-11e9-9c35-d76eda8bf8ad.png)

**Comment by kexianjun** [comment]
I do'nt get your point, can you confirm it's caused by this [3678](https://github.com/apache/incubator-dubbo/issues)

**Comment by kele6413430** [comment]
> I do'nt get your point, can you confirm it's caused by this [3678](https://github.com/apache/incubator-dubbo/issues)

中文说吧，就是我连续调用了两个rpc接口，都是用隐式传参的方式去异步调用的，第一个是2.6的服务，第二个是2.7的服务，我发现得到的Future对象的result永远是null，所以调用get方法时会无限阻塞主线程

**Comment by kele6413430** [comment]
I have  found the problem now.
I use a TracingFilter for brave zipkin which register a callBack on the DefaultFuture, so the callBack in FutureAdater is overried, then real response will not be set in the CompletableFuture.

**Comment by yipixiaofeiyang** [comment]
> I have found the problem now. I use a TracingFilter for brave zipkin which register a callBack on the DefaultFuture, so the callBack in FutureAdater is overried, then real response will not be set in the CompletableFuture.

最后咋解决的?
