### ISSUE TITLE
Dispatcher can only be specified on provider side, and it in turn determines the dispatcher type on consumer side.

### ISSUE THREAD

**Issue by chickenlj** [apache/incubator-dubbo#4036]
Currently, the only way to specify the dispatcher type is to use the `protocol` element on the provider side.

```xml
<dubbo:protocol dispatcher="all/direct/message/..." />
```

**Comment by kexianjun** [comment]
same as #3955

**Comment by chickenlj** [comment]
> same as #3955

Thanks, I am closing this one, let's collaborate on #3955 and try to solve it in the next release.
