### ISSUE TITLE
fix NPE in SimpleMonitorService.write

### ISSUE THREAD

**Issue by takeseem** [apache/incubator-dubbo#404]
[SimpleMonitorService.write](https://github.com/alibaba/dubbo/blob/master/dubbo-simple/dubbo-monitor-simple/src/main/java/com/alibaba/dubbo/monitor/simple/SimpleMonitorService.java#L192)

consumer可能==null
<pre>
                    consumer = statistics.getParameter(CONSUMER);
                    int i = consumer.indexOf(':');
</pre>

fix
<pre>
                    int i = consumer == null ? -1 : consumer.indexOf(':');
</pre>

**Comment by teaey** [comment]
同学，能留个邮箱么

**Comment by takeseem** [comment]
@teaey takeseem@gmail.com

**Comment by ralf0131** [comment]
This should not be an issue any more. Feel free to reopen if you still encounter this.
