### ISSUE TITLE
dubbo 的 spring2.5的。现在spring一般都用4了。 这个有影响吗?

### ISSUE THREAD

**Issue by 65725738** [apache/incubator-dubbo#406]
最新的dubbo 2.5.4-SNAPSHOT  spring也是3.2的

**Comment by qct** [comment]
你可以自己换掉， 在dubbo里exclude掉2.5的，自己引入新的

**Comment by takeseem** [comment]
<pre>
			<dependency>
				<groupId>com.alibaba</groupId>
				<artifactId>dubbo</artifactId>
				<version>2.5.4-SNAPSHOT</version>
				<exclusions>
					<exclusion>
						<groupId>org.springframework</groupId>
						<artifactId>spring</artifactId>
					</exclusion>
					<exclusion>
						<artifactId>log4j</artifactId>
						<groupId>log4j</groupId>
					</exclusion>
					<exclusion>
						<artifactId>commons-logging</artifactId>
						<groupId>commons-logging</groupId>
					</exclusion>
					<exclusion>
						<artifactId>netty</artifactId>
						<groupId>org.jboss.netty</groupId>
					</exclusion>
				</exclusions>
			</dependency>

		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context-support</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-jdbc</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-webmvc</artifactId>
		</dependency>
		

		<dependency>
			<groupId>com.alibaba</groupId>
			<artifactId>dubbo</artifactId>
		</dependency>
		<dependency>
			<groupId>com.101tec</groupId>
			<artifactId>zkclient</artifactId>
		</dependency>
</pre>

**Comment by qct** [comment]
@takeseem 直接贴代码，比我嘴炮强多了  哈哈哈。

**Comment by wdragon1983** [comment]
@takeseem   排除这个没问题吗? 这个只是不用 spring2。用spring4 。 但是不知道spring4是否兼容sping2.
还有一个问题。你排出的netty。dubbo用的是netty3. netty这东西，是肯定不兼容的。不要说3，4,5不兼容。就是 大版本4 下面的都不一定兼容。包都改的面目全非。

**Comment by Sutonline** [comment]
@takeseem 请问spring4使用dubbo注册的rmi协议可以成功吗？ 目前不论是手动将RmiInvocationWrapper_Stub.class重新打包，或者使用spring-remote，在tomcat启动的时候都会报class not found exception。求告知~

**Comment by takeseem** [comment]
@Sutonline 最近3年，一直用spring4,包含rmi的，没遇到过这个问题。
我们是自己从master编译的dubbo（上个商业项目是16年4月clone编译的）
