### ISSUE TITLE
方法级别上没有扩展注解支持

### ISSUE THREAD

**Issue by yockii** [apache/incubator-dubbo#41]
目前提供者、消费者都可以使用@Service及@Reference来注解标注，但是方法上没有提供。比如某些方法是需要缓存的、设定重试次数、负载方式等。

**Comment by diecui1202** [comment]
@mercyblitz Pls. take a look at this.

**Comment by cvictory** [comment]
duplicate with:  https://github.com/apache/incubator-dubbo/issues/2298.

I have commit a pr : https://github.com/apache/incubator-dubbo/pull/2603

we can close it firstly, just focus on https://github.com/apache/incubator-dubbo/issues/2298

**Comment by cvictory** [comment]
&READY-TO-CLOSE&
