### ISSUE TITLE
dubbo admin 禁用或者启用服务提供者以后报404错误

### ISSUE THREAD

**Issue by LesterDong** [apache/incubator-dubbo#411]
不知道怎么贴图。。。具体就是在服务提供者列表将提供者启用或者禁用以后，最后跳转的页面就是 HTTP Status 404 - /governance/providers

**Comment by EdwardLee03** [comment]
@LesterDong  dubbo-admin 使用 Tomcat 容器部署吗？
如果使用 Tomcat 部署，记得在 tomcat/webapps/ 目录下将 dubbo-admin-xxx.war 包解压后名称改为 ROOT/

具体安装步骤参考 [Dubbo管理员文档的管理控制台安装](https://dubbo.gitbooks.io/dubbo-admin-book/install/admin-console.html)

#297  原因：dubbo admin 只能 用ROOT目录部署，这是基于webx开发的
