### ISSUE TITLE
[Dubbo-etcd3-bug]The client loses the listener when the network is reconnected.

### ISSUE THREAD

**Issue by zonghaishang** [apache/incubator-dubbo#4115]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.1
* Operating System version: mac
* Java version: 1.8

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by cvictory** [comment]
@zonghaishang  How about this issue?  If you don't have time to fix it, I will modify the milestone to 2.7.3.

**Comment by zonghaishang** [comment]
fixed: https://github.com/zonghaishang/dubbo/commit/7bacc825343bcc37c2d04327cf736518d86b49a0

What is the release deadline for the 2.7.2 release?

**Comment by ralf0131** [comment]
I am starting to review this. @cvictory

**Comment by ralf0131** [comment]
This issue has been fixed from 2.7.2 onwards.
