### ISSUE TITLE
Unkown dubbo-parent 2.4.10 pom

### ISSUE THREAD

**Issue by lenvonsam** [apache/incubator-dubbo#414]
i just download dubbo-dubbo-2.4.11 release project, then go to dubbo/dubbo-admin folder, exec mvn:clean ,mvn jetty:run, finally  show the error
![image](https://cloud.githubusercontent.com/assets/10168476/24336626/4093a160-12c5-11e7-9cc5-e755375ed377.png)

can anyone help me solve this problem? thx

**Comment by qct** [comment]
please check out 2.5.3

**Comment by ralf0131** [comment]
Please check out the latest version 2.6.1
