### ISSUE TITLE
Dubbo多生产者执行效率

### ISSUE THREAD

**Issue by zhpebox** [apache/incubator-dubbo#415]
整个应用系统在配置多个生产者的执行效率小于单个生产者的执行效率，
是否是因为多个生产者的情况下，
Dubbo需要计算选择最优生产者的过程消耗了一些时间。

**Comment by takeseem** [comment]
背景不清楚，无法帮到你！

我的理解：多个相比单个服务提供者，多个增加了处理能力，因他们的网络、序列化、反射开销都一样，多个相当于增加了计算能力。

**Comment by kimmking** [comment]
整个应用系统在配置多个生产者的执行效率小于单个生产者的执行效率，

@zhpebox  这句是怎么来的。是否有数据支撑。

**Comment by takeseem** [comment]
这不是一个好提问！上下文缺失，结论也没有依据
