### ISSUE TITLE
dubbo.properties多注册中心怎么配置？

### ISSUE THREAD

**Issue by gMan1990** [apache/incubator-dubbo#419]
http://dubbo.io/User+Guide-zh.htm#UserGuide-zh-%E5%B1%9E%E6%80%A7%E9%85%8D%E7%BD%AE
> 如果classpath根目录下存在多个dubbo.properties，比如多个jar包中有dubbo.properties，Dubbo会任意加载，并打印Error日志，后续可能改为抛异常。

> 将XML配置的标签名，加属性名，用点分隔，多个属性拆成多行：
比如：dubbo.application.name=foo等价于<dubbo:application name="foo" />
比如：dubbo.registry.address=10.20.153.10:9090等价于<dubbo:registry address="10.20.153.10:9090" />
如果XML有多行同名标签配置，可用id号区分，如果没有id号将对所有同名标签生效：
比如：dubbo.protocol.rmi.port=1234等价于<dubbo:protocol id="rmi" name="rmi" port="1099" /> (协议的id没配时，缺省使用协议名作为id)
比如：dubbo.registry.china.address=10.20.153.10:9090等价于<dubbo:registry id="china" address="10.20.153.10:9090" />

比如我配置dubbo.registry.china1.address，dubbo.registry.china2.address，怎么不生效？
还有这个问题也帮我看下：https://github.com/dangdangdotcom/dubbox/issues/261

**Comment by gMan1990** [comment]
好像看到个代码：com.alibaba.dubbo.config.AbstractInterfaceConfig#checkRegistry()
里面只会获取String address = ConfigUtils.getProperty("dubbo.registry.address");

**Comment by multiplyzero** [comment]
配置了 dubbo.registry.china1.address，dubbo.registry.china2.address
在xml上要有对应的id 如
<dubbo:registry id="china1" />
<dubbo:registry id="china2" />
这样 才会生效

**Comment by multiplyzero** [comment]
@gMan1990

**Comment by yunhaibin** [comment]
@gMan1990 参考以下配置方式

```xml
<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:dubbo="http://code.alibabatech.com/schema/dubbo"
    xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-2.5.xsd
    http://code.alibabatech.com/schema/dubbo http://code.alibabatech.com/schema/dubbo/dubbo.xsd
    ">
     
    <!-- 当前应用信息配置 -->
    <dubbo:application name="demo-provider" />
    
    <!-- 连接注册中心配置 -->
    <dubbo:registry id="reg1" address="127.0.0.1:4545" />
    
    <dubbo:registry id="reg2" address="127.0.0.1:4546" />
    
    <dubbo:registry id="reg3" address="127.0.0.1:4547" default="false" />
     
    <!-- 暴露服务协议配置 -->
    <dubbo:protocol name="dubbo" port="20880" />
    
    <!-- 暴露服务配置 -->
    <dubbo:service interface="com.alibaba.dubbo.config.spring.api.DemoService" ref="demoService" registry="reg2" />
     
    <bean id="demoService" class="com.alibaba.dubbo.config.spring.impl.DemoServiceImpl" />
 
</beans>
```

**Comment by gMan1990** [comment]
@yunhaibin 写在xml里的我知道，但dubbo.properties怎么写不知道，你看我帖子内容

**Comment by ralf0131** [comment]
@multiplyzero 's suggestion should work.
