### ISSUE TITLE
非Spring框架如何使用dubbo

### ISSUE THREAD

**Issue by Croyson** [apache/incubator-dubbo#420]
我们团队使用的框架是scala 写的 finatra ,如何使用dubbo提供的服务

**Comment by Qunzer** [comment]
换个角度，试试：thrift

**Comment by Croyson** [comment]
但是公司其他团队用的dubbo  ，thrift 可以跟dubbo对接吗

**Comment by googlefan** [comment]
dubbo  不是有thrift 模块么？ 不过我也没用过，不太清楚，我想应该是可以对吧

2017-03-31 16:37 GMT+08:00 Croyson <notifications@github.com>:

**Comment by superleo-cn** [comment]
我们使用scala + dubbo 一年了。 dubbo的hession2对Scala数据类型非常不好，发布吃了不少苦头，差点整个Facade都打算退回到Java了，核心Service只用Scala。后来研究发现了Kryo+Chill能比较完美的解决这个问题，推荐你试试。

**Comment by lovepoem** [comment]
﹉>我们使用scala + dubbo 一年了。 dubbo的hession2对Scala数据类型非常不好，发布吃了不少苦头，差点整个Facade都打算退回到Java了，核心Service只用Scala。后来研究发现了Kryo+Chill能比较完美的解决这个问题，推荐你试试。
--

I think you can refine a base dependency for scala-dubbo . As a project,we can put into the github.com/dubbo

**Comment by readmagic** [comment]
我也碰到了同样的问题，正在寻找答案，公司大部分业务用了playframework2，如果能使用dubbo在服务间通讯，那是极好的
