### ISSUE TITLE
[provider side]support returning implicit results

### ISSUE THREAD

**Issue by ludvik** [apache/incubator-dubbo#43]
This is a ticket to extend DUBBO's implicit parameter mechanism described in current DUBBO documentation: 
http://alibaba.github.io/dubbo-doc-static/User+Guide-zh.htm#UserGuide-zh-%E9%9A%90%E5%BC%8F%E4%BC%A0%E5%8F%82

In-short, the pattern of the above document is:
**[consumer side] set attachments ----> [provider side] get attachments**

this ticket is intended to extend this mechanism to:
**[provider side(before return)] set attachments --> [consumer side] get attachments**

**provider side**

```
public class XxxServiceImpl implements XxxService {

    public void xxx() { // 服务方法实现(service implementation)
        // ....
        // 返回之前 （before return）
        RpcContext.getContext().setAttachment("userToken", "0001"); 
    }
}
```

**consumer side**

```
xxxService.xxx();
String userToken = RpcContext.getContext().getAttachment("userToken"); 
```

**Comment by diecui1202** [comment]
Could you share us the scenario about using RpcContext attachment to return results?

**Comment by ralf0131** [comment]
Hi, I think the scenario is described in #68

**Comment by diecui1202** [comment]
@ludvik This feature is provided in 2.6.3, which is on the releasing vote thread.

%READY-TO-CLOSE&
