### ISSUE TITLE
dubbo-registry-host.cache中好多\u0000，导致频繁full gc

### ISSUE THREAD

**Issue by ilyaml218** [apache/incubator-dubbo#432]
cache文件中好多\u0000\u0000\u0000\u0000\u0000
导致频繁full gc

**Comment by linghushaoxia** [comment]
dubbo-registry-host.cache,本质上是一个properties，dubbo使用java.util.Properties进行处理，所以问题细化为，properties文件为什么出现\u0000。
1、\u0000
\u0000，是unicode编码中最小的一个值，使用Properties.store方法，把Properties写到磁盘时,java会把要写入的文件转码为 ISO 8859-1。
注释如下，
void java.util.Properties.store(OutputStream out, String comments) throws IOException
Writes this property list (key and element pairs) in this Properties table to the output stream in a format suitable for loading into a Properties table using the load(InputStream) method. 

Properties from the defaults table of this Properties table (if any) are not written out by this method. 

This method outputs the comments, properties keys and values in the same format as specified in store(Writer), with the following differences: 

The stream is written using the ISO 8859-1 character encoding. 
Characters not in Latin-1 in the comments are written as \uxxxx for their appropriate unicode hexadecimal value xxxx. 
Characters less than \u0020 and characters greater than \u007E in property keys or values are written as \uxxxx for the appropriate hexadecimal value xxxx. 
可以看到,字符的unicode编码小于\u00020或者大于\u007E,会被保存为十六进制的\uxxxx的形式。换言之，可以表示的字符是32-126之间的值，u0020是空格,u007E是~，这些是典型的ASCII码定义的可见字符。u0000表示NUL,这个字符是不可见的，不是null，也不是空格，就是逻辑意义上的空，并且在字符串里面可以存在[参考unicode表](https://unicode-table.com/cn/#control-character)。这说明，在你的应用中,dubbo保存properties文件时,java发现了\u0000这个编码存在。
到了这里，问题进一步细化为，在什么情况下,\u0000会被写入字符串中
我粗略想了想，列出如下猜想
1)编码不一致
保存时java会强制进行转换,将输出流以 ISO 8859-1重新编码，这个需要结合你的系统环境，来判断
2)存在人为修改.cache文件
如果使用编辑器编辑过.cache文件，编辑器可能会更改编码，导致读取的时候，就可能出问题，后续保存也会跟着出问题

2、\u0000导致的FULL GC
按照道理讲,\u0000只是一个字符，它本身导致FULL GC的可能性不大,但是这个是在注册中心服务的缓存，这会产生什么问题呢？请求堆积。dubbo如果无法正常读取properties，就无法知道服务端的具体地址，此时客户端的请求，可能会堆积，这是猜测，猜测。
根据以上的分析，希望你结合自己的应用，提供更详细的信息，来分析问题。

**Comment by wuwen5** [comment]
@ilyaml218 想和你确认两个问题
1.注册中心是否为redis.
2.是否存在多服务共享dubbo cache目录 （例如挂载盘）。

**Comment by woshidagouxiong** [comment]
我也遇到了这个问题了，DubboSaveRegistryCache-thread-1 出现OOM，dump文件中有一个2G多的char[]，都是\u0000
注：一个server多个服务都没有配置cache file，使用默认路径

**Comment by ralf0131** [comment]
Can you provide an example to reproduce this issue?

**Comment by ilyaml218** [comment]
@woshidagouxiong 您好，cache文件出现很多\u0000的原因没找到。分析了多次内存文件，通过下面的方法解决了自己项目的full gc问题。1. 把full gc模块的内存扩大一倍； 2. 减少full gc模块中的定时任务数量及执行频率； 3. 删除原有cache文件，为不同服务配置不同的cache ；

**Comment by renlei413326889** [comment]
一台机器启动多个dubbo服务，没有为每个服务指定不同的cache文件
<dubbo:registry file="dubboregistry/xxx.properties"/> ,所有服务都默认共用了一个cache导致

**Comment by diecui1202** [comment]
Feel free to reopen if necessary.

**Comment by qixiaobo** [comment]
> 我也遇到了这个问题了，DubboSaveRegistryCache-thread-1 出现OOM，dump文件中有一个2G多的char[]，都是\u0000
> 注：
> 
> 1. 一个server多个服务都没有配置cache file，使用默认路径
> 2. 注册中心是zookeeper

me 2

**Comment by ralf0131** [comment]
@qixiaobo Could you please provide an example to reproduce this problem?
