### ISSUE TITLE
缓存结果后怎么触发删除缓存

### ISSUE THREAD

**Issue by qiaohhgz** [apache/incubator-dubbo#437]
缓存结果后怎么触发删除缓存

**Comment by yunhaibin** [comment]
你指的是什么缓存？能否具体一点？

**Comment by qiaohhgz** [comment]
dubbo的结果缓存，消费端配置cache属性（有三种模式选择）当配置后第二次请求不会请求服务端会直接返回数据，但是当数据发生变化时没有地方提供刷新缓存或重新请求服务端的配置或方法

**Comment by yunhaibin** [comment]
@qiaohhgz dubbo自身的缓存机制只适用于部分业务的热数据，不适合需要实时数据的场景，没有刷新缓存的机制，看你的业务场景，建议还是用Nosql数据库做缓存吧

**Comment by qiaohhgz** [comment]
好的，那dubbo的消费者可否集成spring cache做数据缓存

**Comment by yunhaibin** [comment]
可以，你只要在消费者端更新数据时清除缓存即可，清除后发现没有缓存数据再去提供者获取最新数据，但是如果是多服务集群的话这个就不行了，这种缓存方式适合单机单消费服务

**Comment by qiaohhgz** [comment]
现在就是多服务集群有什么好的地方加吗

**Comment by yunhaibin** [comment]
建议直接用redis或者memcache等Nosql数据库吧

**Comment by qiaohhgz** [comment]
好的谢谢

**Comment by yunhaibin** [comment]
不客气^_^
