### ISSUE TITLE
dubbo 多端口暴露服务问题

### ISSUE THREAD

**Issue by blinkingso** [apache/incubator-dubbo#442]
两个项目即是生产者又是消费者时  暴露服务的端口一个20880 一个20890 其中一个会没有消费者（20890的服务无法被引用）  是什么原因？
代码地址：https://github.com/blinkingso/dubbo-project

**Comment by kimmking** [comment]
代码里只看到一个20890

**Comment by blinkingso** [comment]
dubbo-consumer那个项目暴露一个DependencyService(20890端口)给dubbo-provider中的UserSerivce(20880默认端口)调用 
然后dubbo-consumer再去调用dubbo-provider中的UserService  现在的代码启动不报错，调用UserService时报DependencyService空指针（没引用成功）

**Comment by kimmking** [comment]
dubbo-provider 是空的

**Comment by diecui1202** [comment]
Long time no feedback. Feel free to reopen if necessary.
