### ISSUE TITLE
加载Spring配置文件报错    No bean named 'dataSource' is defined

### ISSUE THREAD

**Issue by mixiaobing** [apache/incubator-dubbo#444]
ClassPathXmlApplicationContext context = new ClassPathXmlApplicationContext(  new String[]{"applicationContext.xml"});  方式加载Spring配置文件报错

<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:context="http://www.springframework.org/schema/context" xmlns:jdbc="http://www.springframework.org/schema/jdbc"  
	xmlns:jee="http://www.springframework.org/schema/jee" xmlns:tx="http://www.springframework.org/schema/tx"
	xmlns:aop="http://www.springframework.org/schema/aop" xmlns:task="http://www.springframework.org/schema/task" 
	xmlns:jpa="http://www.springframework.org/schema/data/jpa" xsi:schemaLocation="
		http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.2.xsd
		http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-3.2.xsd
		http://www.springframework.org/schema/jdbc http://www.springframework.org/schema/jdbc/spring-jdbc-3.2.xsd
		http://www.springframework.org/schema/jee http://www.springframework.org/schema/jee/spring-jee-3.2.xsd
		http://www.springframework.org/schema/tx http://www.springframework.org/schema/tx/spring-tx-3.2.xsd
		http://www.springframework.org/schema/aop http://www.springframework.org/schema/aop/spring-aop-2.5.xsd
		http://www.springframework.org/schema/data/jpa http://www.springframework.org/schema/data/jpa/spring-jpa-1.2.xsd
		http://www.springframework.org/schema/task http://www.springframework.org/schema/task/spring-task-3.2.xsd"
	default-lazy-init="true">

	<description>Spring Configuration</description>
	
	<import resource="classpath*:/spring-dubbo-provider.xml"/>
	
    
	<context:property-placeholder ignore-unresolvable="true" location="classpath*:/apm.properties" />
	
		
	<bean id="springContextHolder" class="apm.common.utils.SpringContextHolder" lazy-init="false"/>

	
	<bean id="entityManagerFactory" class="org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean"> 
		<property name="dataSource" ref="dataSource"/>
		<property name="jpaVendorAdapter" ref="hibernateJpaVendorAdapter"/> 
		<property name="packagesToScan" value="apm.modules.**.entity"/>
		<property name="persistenceProvider">
            <bean class="org.hibernate.ejb.HibernatePersistence"/>
        </property>
        <property name="jpaDialect">
            <bean class="org.springframework.orm.jpa.vendor.HibernateJpaDialect"/>
        </property>
		<property name="jpaProperties">
			<props>
				<prop key="hibernate.ejb.naming_strategy">org.hibernate.cfg.ImprovedNamingStrategy</prop>
				<prop key="hibernate.cache.region.factory_class">org.hibernate.cache.ehcache.EhCacheRegionFactory</prop>
				<prop key="net.sf.ehcache.configurationResourceName">${hibernate.ehcache.configFile}</prop>
				<prop key="hibernate.cache.use_second_level_cache">true</prop>
				<prop key="hibernate.cache.use_query_cache">true</prop>
				<prop key="hibernate.search.default.directory_provider">filesystem</prop>
				<prop key="hibernate.search.default.indexBase">${hibernate.search.default.indexBase}</prop>
				<prop key="hibernate.show_sql">${hibernate.show_sql}</prop>
				
			</props>
		</property>
	</bean>
	
	
	<bean id="hibernateJpaVendorAdapter" class="org.springframework.orm.jpa.vendor.HibernateJpaVendorAdapter">
	    <property name="generateDdl" value="${jpa.generateDdl}"/>
	    <property name="database" value="${jpa.database}"/>
	    <property name="databasePlatform" value="org.hibernate.dialect.MySQL5InnoDBDialect"/>
	    <property name="showSql" value="${jpa.showSql}"/>
	</bean>
	
	
 	<jpa:repositories base-package="apm.modules.**.dao"  transaction-manager-ref="transactionManager"
 		entity-manager-factory-ref="entityManagerFactory"/>
   
	
	<bean id="transactionManager" class="org.springframework.orm.jpa.JpaTransactionManager">
		<property name="entityManagerFactory" ref="entityManagerFactory"/>
	</bean>
	<tx:advice id="txAdvice" transaction-manager="transactionManager">
		<tx:attributes>
            <tx:method name="get*" propagation="REQUIRED" read-only="true"/>
			<tx:method name="save*" propagation="REQUIRED" read-only="true"/>
			<tx:method name="insert*" propagation="REQUIRED" read-only="true"/>
			<tx:method name="add*" propagation="REQUIRED" read-only="true"/>
            <tx:method name="find*" propagation="REQUIRED" read-only="true"/>
            <tx:method name="list*" propagation="REQUIRED" read-only="true"/>
			<tx:method name="update*" propagation="REQUIRED" read-only="true"/>
			<tx:method name="delete*" propagation="REQUIRED" read-only="true"/>
			<tx:method name="remove*" propagation="REQUIRED" read-only="true"/>
            <tx:method name="*" propagation="REQUIRED"/>
		</tx:attributes>
	</tx:advice>

	
	<tx:annotation-driven transaction-manager="transactionManager" proxy-target-class="true"/>

    
    <bean id="messageSource" class="org.springframework.context.support.ReloadableResourceBundleMessageSource">
        <property name="basenames">
            <list>
                
                <value>classpath:i18n/messages</value>
                <value>classpath:i18n/ValidationMessages</value>
            </list>
        </property>
        <property name="useCodeAsDefaultMessage" value="true"/>
        <property name="defaultEncoding" value="UTF-8"/>
        <property name="cacheSeconds" value="60"/>
    </bean>
	
	
	<bean id="validator" class="org.springframework.validation.beanvalidation.LocalValidatorFactoryBean" />

	
    <bean id="conversionService" class="org.springframework.format.support.FormattingConversionServiceFactoryBean"/>
    
    
    <bean id="domainClassConverter" class="org.springframework.data.repository.support.DomainClassConverter">
        <constructor-arg ref="conversionService"/>
    </bean>
    
    
    <bean id="openOfficeConnection" class="com.artofsolving.jodconverter.openoffice.connection.SocketOpenOfficeConnection" destroy-method="disconnect">
        <constructor-arg index="0">
            <value>127.0.0.1</value>
        </constructor-arg>
        <constructor-arg index="1">
            <value>8100</value>
        </constructor-arg>
    </bean> 
    
	
	<bean id="cacheManager" class="org.springframework.cache.ehcache.EhCacheManagerFactoryBean">
		<property name="configLocation" value="classpath:${ehcache.configFile}" />
	</bean>

	
 	<beans profile="production">
 		
 	    
		<bean id="dataSource" class="com.alibaba.druid.pool.DruidDataSource" init-method="init" destroy-method="close"> 
		    
		    <property name="driverClassName" value="${jdbc.driver}" />
		    
			
			<property name="url" value="${jdbc.url}" />
			<property name="username" value="${jdbc.username}" />
			<property name="password" value="${jdbc.password}" />
			
			
			<property name="initialSize" value="${jdbc.pool.minIdle}" />
			<property name="minIdle" value="${jdbc.pool.minIdle}" />
			<property name="maxActive" value="${jdbc.pool.maxActive}" />
			
			
			<property name="maxWait" value="60000" />
			
			
			<property name="timeBetweenEvictionRunsMillis" value="60000" />
			
			
			<property name="minEvictableIdleTimeMillis" value="300000" />
			
			<property name="validationQuery" value="SELECT 'x'" />
			<property name="testWhileIdle" value="true" />
			<property name="testOnBorrow" value="false" />
			<property name="testOnReturn" value="false" />
			
			
			<property name="removeAbandoned" value="true" /> 
			
			<property name="removeAbandonedTimeout" value="1800" /> 
			
			<property name="logAbandoned" value="true" /> 
			
			
			
			
		    <property name="filters" value="stat" /> 
		</bean>
		
		
	
		
		
	</beans>
	
</beans>

**Comment by kimmking** [comment]
你激活了profile了吗？

这不是dubbo的问题，是spring基础用法的问题。

**Comment by linghushaoxia** [comment]
看了你的配置，你是单进程方式，启动应用。如kimmking的回答，你没有激活profile,又没有默认的beans
下面给出激活profile的几种方式
### 1)作为SpringMVC中的DispatcherServlet的初始化参数
### 2)作为Web 应用上下文中的初始化参数
### 3)作为JNDI的入口
### 4)作为环境变量
### 5)作为虚拟机的系统参数
### 6)使用@AtivceProfile来进行激活
不同的方式，使用在不同的场合，单进程应用，适合使用4和5来进行激活
怎么做呢？
环境变量进行配置，spring.profiles.active=test（或者其他的）
系统参数，可以在启动脚本中加入 -Dspring.profiles.active=test

**Comment by chickenlj** [comment]
如kimmking、linghushaxia回答的，请检查spring使用方式。我将关闭这个issue
