### ISSUE TITLE
provider怎么获取consumer端的用户session信息

### ISSUE THREAD

**Issue by liuyunfeng2017** [apache/incubator-dubbo#448]
provider怎么获取consumer端的用户session信息

**Comment by kimmking** [comment]
作为参数，或者rpcContext里的变量，传递过来。

**Comment by liuyunfeng2017** [comment]
@kimmking 用上下文的话，那每调用一次就要设置一次，有没有全局的，因为我只需要传用户ID和类型

**Comment by kevin-wang001** [comment]
provider怎么传递参数给consumer？

**Comment by carryxyh** [comment]
Provider can not send param to consumer so far.

&READY-TO-CLOSE&

**Comment by zonghaishang** [comment]
Temporarily closed, can open again if there is a problem
