### ISSUE TITLE
Data length too large: 9598962, max payload: 8388608

### ISSUE THREAD

**Issue by zhw1992** [apache/incubator-dubbo#453]
这个该怎么解决了

**Comment by kimmking** [comment]
限制改为100M：
在请求的url后面加上payload=104857600

**Comment by hollyshi** [comment]
可以考虑分批操作，比如查询返回数据量过大，需要考虑分批取。盲目加大payload感觉不是很好，毕竟数据量太大网络传输也会慢的吧

**Comment by carryxyh** [comment]
@zhw1992 
Is this problem solved now?
If no more feedback, we will close the issue soon.
