### ISSUE TITLE
dubbo-admin 2.5.4-SNAPSHOT build err

### ISSUE THREAD

**Issue by MahdiCat** [apache/incubator-dubbo#456]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building dubbo-admin 2.5.4-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.alibaba:dubbo:jar:2.5.4-SNAPSHOT is missing, no depend
ency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.593 s
[INFO] Finished at: 2017-06-09T17:00:44+08:00
[INFO] Final Memory: 6M/17M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project dubbo-admin: Could not resolve depende
ncies for project com.alibaba:dubbo-admin:war:2.5.4-SNAPSHOT: Could not find art
ifact com.alibaba:dubbo:jar:2.5.4-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyReso
lutionException

**Comment by chenlushun** [comment]
看下这个版本，对2.x版本的dubbo做了一些改进， https://github.com/linux-china/dubbo3  @MahdiCat

**Comment by kimmking** [comment]
目前maven中央库版本是253，自己编译请全部都编译，版本才能对的上。

直接在dubbo目录mvn install -DskipTests

**Comment by MahdiCat** [comment]
I had found the right way yestday. But fogot to give answer here.
Thank to kimmking. Right answer.

**Comment by yutaolian** [comment]
jdk是多少1.8的话切换成1.7
