### ISSUE TITLE
如何把rest协议的json组件改为fastjson

### ISSUE THREAD

**Issue by jqncc** [apache/incubator-dubbo#460]
如题，想项目统一各功能的组件，json统一为fastsjon
fastjson也是实现了jax-rs provider的，所以想把默认的jackson替换掉应该怎么做呢？？

**Comment by kimmking** [comment]
这是一个比较难做的事情，dubbox的rest依赖于resteasy，resteasy默认依赖的是jackson，
所以，你需要换resteasy的依赖，目前了解的情况是，需要改resteasy源码。

**Comment by jqncc** [comment]
resteasy是自动扫描的,应该实现他的provider然后把jackson-provider依赖包去掉就行

**Comment by jqncc** [comment]
自己实现
`
@Provider
@Consumes({ "application/*+json","text/json" })
@Produces({ "application/*+json","text/json" })
public class FastJsonJaxrsProvider extends FastJsonProvider {

    public FastJsonJaxrsProvider() {
        super();
        getFastJsonConfig().setSerializerFeatures(SerializerFeature.DisableCircularReferenceDetect,
                SerializerFeature.WriteNullListAsEmpty);
    }

    public void writeTo(Object obj, Class<?> type, Type genericType, Annotation[] annotations, MediaType mediaType,
            MultivaluedMap<String,Object> httpHeaders, OutputStream entityStream)
            throws IOException, WebApplicationException {
        super.writeTo(obj, type, genericType, annotations, mediaType, httpHeaders, entityStream);
        // dubbox client使用 httpclient发送请求时设置了Content-Length导致"Content-Length header already present"异常
        // httpHeaders.remove("Content-Length");
    }
}
`

再META-INF/services下加入SPI文件javax.wr.rs.ext.Providers

**Comment by chickenlj** [comment]
This feature relies on the underlying rest framework.

So cannot be fixed in dubbo.
