### ISSUE TITLE
dubbo目前的支持优雅停机吗？

### ISSUE THREAD

**Issue by SuperDubbo** [apache/incubator-dubbo#465]
网上很多都说dubbo在服务端和客户端配置参数：-Ddubbo.service.shutdown.wait=30000，该参数为停机等待时间，但是结果也不生效，还是马上停机了。 
  <dubbo:application name="abc_dubbo">
        <dubbo:parameter key="shutdown.timeout" value="60000" /> 
    </dubbo:application>

这个支持吗?
我看了一下dubbo的dubbo.xsd的application的下面并没有dubbo:parameter标签啊

**Comment by JackyWoo** [comment]
1 dubbo.service.shutdown.wait需要写在配置文件中dubbo.properties

2 配置了dubbo.service.shutdown.wait的意义是首先停止接收任务，并等待现有任务执行完成，最多等待 XX时间。如果当时没有正在执行的任务，也会立刻停机。

以下是gracefulShutdown代码：

```
public static void gracefulShutdown(Executor executor, int timeout) {
        if (!(executor instanceof ExecutorService) || isShutdown(executor)) {
            return;
        }
        final ExecutorService es = (ExecutorService) executor;
        try {
            es.shutdown(); // Disable new tasks from being submitted
        } catch (SecurityException ex2) {
            return ;
        } catch (NullPointerException ex2) {
            return ;
        }
        try {
            if(! es.awaitTermination(timeout, TimeUnit.MILLISECONDS)) {
                es.shutdownNow();
            }
        } catch (InterruptedException ex) {
            es.shutdownNow();
            Thread.currentThread().interrupt();
        }
        if (!isShutdown(es)){
            newThreadToCloseExecutor(es);
        }
    }
```

ps： gracefully shutdown的功能我也没用过，你可以尝试试试

**Comment by SuperDubbo** [comment]
在dubbo.xml中配置不了dubbo.service.shutdown.wait或dubbo.service.shutdown.wait.seconds吗？

**Comment by JackyWoo** [comment]
provider标签里有个wait， 你试试管用不

**Comment by SuperDubbo** [comment]
你看看官方文档http://dubbo.io/User+Guide-zh.htm#UserGuide-zh-%3Cdubbo%3Aprovider%2F%3E
Provider标签下面并没有wait呀@JackyWoo @kimmking

**Comment by JackyWoo** [comment]
我看代码里边有的，你可以先试试

**Comment by SuperDubbo** [comment]
![image](https://user-images.githubusercontent.com/20811216/27473645-799c4d60-5832-11e7-9759-1eee9f061686.png)
貌似是这个才对吧

**Comment by taige** [comment]
dubbo的原生graceful shutdown是有bug的，仅释放了一些资源但没有尝试等待服务线程结束。
可以采用这个fix：https://github.com/taige/dubbo/commit/c8c1df022cd0412ee660544028032d5c342cb219

**Comment by qinliujie** [comment]
now it can only be configed in property file or jvm argument, we will improve it later

**Comment by caneo** [comment]
xml配置<dubbo:registry>
<dubbo:registry>中存在wait标签：表示在注册中心配置的优雅停机的超时时间
在provider.xml中新增：
<dubbo:registry address="multicast://224.5.6.7:1234" wait="100000"/>

**Comment by chaoKing** [comment]
The timeout for getting graceful downtime in dubbo is obtained from the method ConfigUtils.getServerShutdownTimeout, which is to get value of dubbo.service.shutdown.wait (new key) or dubbo.service.shutdown.wait.seconds (old key).

Configure the dubbo:registry configuration wait tag in xml, and the spring tag resolution will configure dubbo.service.shutdown.wait.
So configure the wait tag directly in the dubbo:registry.
E.g:
Added in the configuration file:
<dubbo:registry wait="1000"/>
