### ISSUE TITLE
dubbo-admin启动报错

### ISSUE THREAD

**Issue by a13707331174** [apache/incubator-dubbo#468]
Line 30 in XML document from ServletContext resource [/WEB-INF/webx.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 30; columnNumber: 44; cvc-complex-type.2.4.a: 发现了以元素 'services:property' 开头的无效内容。应以 '{property}' 之一开头。
我用的是jdk1.8

**Comment by a13707331174** [comment]
有人吗

**Comment by a13707331174** [comment]
。

**Comment by yutaolian** [comment]
jdk把本最好是1.7

**Comment by elijarvis** [comment]
把代码clone到本地，重新打个war就可以用

**Comment by wenjiahao** [comment]
1.8不行   1.7能用

**Comment by kentxp** [comment]
jdk的版本问题  翻翻以前的issues 有人说过  升级pom一个jar包

**Comment by elijarvis** [comment]
用最新的代码，jdk 1.8亲测可用

**Comment by cassia233** [comment]
自己打包后还是不能用. jdk8
``` ERROR context.ContextLoader - Context initialization failed
org.springframework.beans.factory.BeanDefinitionStoreException: IOException parsing XML document from ServletContext resource [/WEB-INF/applicationContext.xml]; nested exception is java.io.FileNotFoundException: Could not open ServletContext resource [/WEB-INF/applicationContext.xml]

**Comment by liaozan** [comment]
@cassia233 同样的问题，新手求问。。解决了吗

**Comment by ralf0131** [comment]
Please check the latest code. It should be fixed.
