### ISSUE TITLE
关于异步调用和attachment传递的问题

### ISSUE THREAD

**Issue by pocrd** [apache/incubator-dubbo#469]
1. dubbo在进行异步业务调用的时候会使用attachment来传递这个异步标志位
2. RpcContext中的attachment清除是在第一次完成对外的dubbo-rpc调用之后
上面两个现状导致了以下问题(以下A,B,C,D为不同dubbo服务中的接口)
1. 一旦A调用B的时候使用了异步调用，那么当B调用C和D的时候，先调用的C会默认使用异步调用。
2. 当A调用B并显示传递若干attachment，此时B再依次调用C和D，调用C的时候会继承所有A传递给B的attachment，而调用D的时候没有这些attachment
请问以上状况是否是设计目标- -，或者是bug
如果是我理解上的错误，请见谅

**Comment by carryxyh** [comment]
This problem will not occur in the new async way(new aysnc way code is in master).

&READY-TO-CLOSE&
