### ISSUE TITLE
dubbo 2.5.3 与mybatis-spring 冲突

### ISSUE THREAD

**Issue by bingowen** [apache/incubator-dubbo#476]
dubbo未配置
```
<exclusion>
     <artifactId>spring</artifactId>
     <groupId>org.springframework</groupId>
</exclusion>
```
启动报Error creating bean with name 'sqlSessionFactory' defined in class path resource [spring-mybatis.xml]
当增加exclusion spring配置后，dubbo provider无法通过dubbo:annotation扫描注册服务，只能一个个服务进行注册。
是存在的bug还是我配置出了问题？

**Comment by wuwen5** [comment]
```xml
    <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>dubbo</artifactId>
                <version>${dubbo.version}</version>
                <exclusions>
                    <exclusion>
                        <artifactId>spring</artifactId>
                        <groupId>org.springframework</groupId>
                    </exclusion>
                </exclusions>
            </dependency>
```

**Comment by shuaiqingli** [comment]
试试在启动前添加参数的方式： System.setProperty("dubbo.spring.config", "dubbo-provider.xml,spring.xml,spring-mybatis.xml");

**Comment by chickenlj** [comment]
启动报Error creating bean with name 'sqlSessionFactory' defined in class path resource [spring-mybatis.xml]

这个错误的根本起因是？ @bingowen

**Comment by bingowen** [comment]
@chickenlj 这个问题在原有的官方常见问题里面有，但是现在改版了，一时间也没找到，意思就是mybatis所使用的spring与dubbo使用的spring两者冲突了。maven的dubbo加上<exclusion>
     <artifactId>spring</artifactId>
     <groupId>org.springframework</groupId>
</exclusion>就能排除这个spring的引入，此时不报错，但是自动扫描注册dubbo服务无法正常工作。个人理解的意思大概这样，不知道是否能理解？

**Comment by bingowen** [comment]
@shuaiqingli  你的意思是调整引入的顺序？这个试过，没问题依然

**Comment by diecui1202** [comment]
@bingowen u can upgrade dubbo to 2.6.2 and try it. Feel free to reopen it.
