### ISSUE TITLE
显示调用ReferenceConfig.destory()方法缺陷

### ISSUE THREAD

**Issue by lemon2004122034** [apache/incubator-dubbo#478]
程序中需要显示的调用ReferenceConfig.destory()销毁consumer时，其对应的ChildListener并没有被删除，通过分析代码发现 zkClient.removeChildListener(toUrlPath(url), zkListener)导致。
原因是因为：toUrlPath(url) 返回的内容和订阅时注册的url不一致。
订阅时监听的url分别为 ：
.../XXXSERVICE/providers;
.../XXXSERVICE/configurators;
.../XXXSERVICE/routers；
而取消订阅时URL为：
.../XXXService?application=xxx&category=providers,configurators,routers

故进而导致销毁的consumer并不会清除对应的ChildListener；

**Comment by jerry8086** [comment]
我们在泛化引用销毁consumer时也碰到了这个问题， @chickenlj 想问下这个问题有具体修复计划吗？

**Comment by ralf0131** [comment]
Hi, would you mind send a pull request?

**Comment by beiwei30** [comment]
I also verified generic invocation, it works too.
