### ISSUE TITLE
Dubbo以webservice协议发布接口时不支持最新的CXF系列jar包

### ISSUE THREAD

**Issue by yuanye342601** [apache/incubator-dubbo#484]
目前在用springboot重新构建一个老项目，但是发现spirngboot不支持老版本的CXF包，而新版本又不能被dubbo支持，请问有没有解决方法？

**Comment by maliqiang** [comment]
@yuanye342601 我也遇到了，暂时还没找到解决办法。

**Comment by mercyblitz** [comment]
@yuanye342601 提供一下版本信息

**Comment by yuanye342601** [comment]
@mercyblitz  dubbo版本就是最新的2.5.3，CXF系列包，新版本是指3.x.x，老版本是指2.x.x，springBoot试过各种版本均不支持老版本CXF

**Comment by Xiaobaxi** [comment]
@yuanye342601 尝试升级到3.1.6吧，我们这边已经升级上去了，没有什么问题。
不过我们遇到的是生成出来的wsdl更加严谨了，如果第三方通过wsdl去解析的话，需要处理一下

**Comment by yuanye342601** [comment]
@Xiaobaxi 3.1.6？dubbo的版本么？

**Comment by Xiaobaxi** [comment]
@yuanye342601 是测试没有问题的cxf版本，还可以再往上升级的

**Comment by rongmin** [comment]
@Xiaobaxi    求详细pom依赖配置。

**Comment by diecui1202** [comment]
Feel free to reopen if necessary.
