### ISSUE TITLE
服务发布方同时发布多个协议服务，reference没有显示指定protocol的话，默认采用哪个？

### ISSUE THREAD

**Issue by guoxu0514** [apache/incubator-dubbo#496]
服务发布方同时发布多个协议服务，reference没有显示指定protocol的话，默认采用哪个？

比如发布dubbo与jsonrpc协议，负载均衡如果是随机，通过看源码，貌似是多个协议随机调用？

**Comment by wuwen5** [comment]
服务发布方可以指定一个default协议.

<table>
<tr>
<td class="confluenceTd"> &lt;dubbo:provider&gt; </td>
<td class="confluenceTd"> default </td>
<td class="confluenceTd">&nbsp;</td>
<td class="confluenceTd"> boolean </td>
<td class="confluenceTd"> 可选 </td>
<td class="confluenceTd"> false </td>
<td class="confluenceTd"> 配置关联 </td>
<td class="confluenceTd"> 是否为缺省协议，用于多协议 </td>
<td class="confluenceTd"> 1.0.16以上版本 </td>
</tr>
</table>

**Comment by wuwen5** [comment]
如果没记错应该是这样，可以尝试下
```xml
<dubbo:protocol name="dubbo" port="20880" default="true"/>
<dubbo:protocol name="jsonrpc" port="8080" server="jetty" />
```

**Comment by guoxu0514** [comment]
@wuwen5 你这个是服务发布是否的配置，<dubbo:provider> 是设置服务发布的默认协议

**Comment by guoxu0514** [comment]
@liangfei0201 @oldratlee

**Comment by guoxu0514** [comment]
@chickenlj

**Comment by wuwen5** [comment]
多协议，最终体现就是多个invoker.

> 1.存在多个服务提供者的情况下，首先根据Loadbalance进行选择，如果选择的provider处于可用状态，则进行后续调用
> 2.如果第一步选择的服务提供者不可用，则从剩余服务提供者列表中继续选择，如果可用，进行后续调用
> 3.如果所有的服务提供者都不可用，重新遍历整个列表（优先从没有选过的列表中选择），判断是否有可用的服务提供者（选择过程中，不可用的服务提供者可能会恢复到可用状态），如果有，则进行后续调用
> 4.如果第三步没有选择出可用的服务提供者，会选第一步选出的invoker中的下一个（如果不是最后一个），避免碰撞.

>LoadBalance负责从多个Invoker中选出具体的一个用于本次调用.

**Comment by guoxu0514** [comment]
@wuwen5 你的意思就是reference没有指定protocol，那就随机从可用列表里随机选择，多协议就是随机调用，是吧

**Comment by wuwen5** [comment]
是的，取决于```Loadbalance```的策略，默认是随机```RandomLoadBalance```.

**Comment by guoxu0514** [comment]
@wuwen5 好的，谢谢

**Comment by guoxu0514** [comment]
@wuwen5 刚看到，原来您是dubbo-jsonrpc的contributor，jackson反序列化的时候有个问题。  如果服务发布方版本升级新增字段，服务订阅方不作升级，就会有反序列化的异常

**Comment by wuwen5** [comment]
@guoxu0514  jsonrpc模块不够完善，其实最好的方式是与json的实现解耦，让用户自由选择json序列化的实现框架。

你说的这个问题只是在生产消费都是java平台的时候才有吧？ 如果都是java建议指定dubbo协议（高性能），jsonrpc只是提供给非java语言调用的。不过好像确实没有一个全局的配置可以指定一个默认协议，目前看只能```<dubbo:reference/>```中指定。

**Comment by chickenlj** [comment]
@guoxu0514  消费端在没有明确指定protocol的情况下，consumer端是没有做区分的。也就是说Provider端的多协议实例是平等的

**Comment by shenzhuan** [comment]
http://git.oschina.net/catshen/zscat_sw
