### ISSUE TITLE
文档用到 http://code.alibabatech.com 都需要更新下

### ISSUE THREAD

**Issue by nashtsai** [apache/incubator-dubbo#500]
文档用到 http://code.alibabatech.com 都需要更新下

http://dubbo.io/user-guide/reference-xmlconf/introduction.html 里面 schema 连接还是 http://code.alibabatech.com/schema/dubbo/dubbo.xsd

建议 dubbo docs and dubbo site 也放在 github

**Comment by chickenlj** [comment]
文档建设中，敬请期待

**Comment by foquanlin** [comment]
http://code.alibabatech.com/schema/dubbo/dubbo.xsd
链接失效,导致项目报错,为毛这么严重的问题一直没解决?

**Comment by he644017879** [comment]
这个东西要哪个版本才会解决

**Comment by huadong** [comment]
多少年的问题了，都成为apache的孵化项目，这个还是阿里巴巴所有的域名：alibabatech.com！太丢人了！

**Comment by ralf0131** [comment]
@nashtsai 

* Dubbo docs: https://github.com/apache/incubator-dubbo-docs
* Dubbo website: https://github.com/apache/incubator-dubbo-website

@foquanlin 

http://code.alibabatech.com/schema/dubbo/dubbo.xsd the link has been fixed, I will be available under 2.6.2, or you can try out it 2.6.2-SNAPSHOT on the master branch.

**Comment by ralf0131** [comment]
All the broken links should be fixed in the latest official documentation.
