### ISSUE TITLE
dubbo管理台能否做到手动停止服务

### ISSUE THREAD

**Issue by why7282** [apache/incubator-dubbo#507]
场景如下：
服务端多节点部署，在发版的时候想一个一个发，但是又不想直接kill进程导致正在处理中的业务中断，
故想到dubbo能否有个管理台先把机器表示为下线，然后等看日志发现没处理业务了我再kill进程，这样
能做到不间断发版。

解决：
dubbo先在有针对这种无缝升级而不影响边界业务的处理方案吗？

**Comment by justein** [comment]
是否可以考虑使用 优雅停机？
2017-08-10 

james_gosling 



发件人：why7282 <notifications@github.com>
发送时间：2017-08-10 13:55
主题：[alibaba/dubbo] dubbo管理台能否做到手动停止服务 (#507)
收件人："alibaba/dubbo"<dubbo@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

场景如下：
服务端多节点部署，在发版的时候想一个一个发，但是又不想直接kill进程导致正在处理中的业务中断，
故想到dubbo能否有个管理台先把机器表示为下线，然后等看日志发现没处理业务了我再kill进程，这样
能做到不间断发版。
解决：
dubbo先在有针对这种无缝升级而不影响边界业务的处理方案吗？

**Comment by why7282** [comment]
优雅停机是否有用？ 还有就是优雅停机会不会仍然会存在边界业务问题。不知道dubbo目前在设置优雅停机的命令上是否成熟？所有是想有没有功能提前标识为节点将要下线，客户端就不在调用，等没有调用了在真正关闭节点。

**Comment by chickenlj** [comment]
我们目前推荐使用的策略是优雅停机。然而当前优雅停机本身在实现上有一点bug，我们会在近期的发版中进行修复和优化

**Comment by why7282** [comment]
也就是并没有实现，比如通过管理台，或者说去zookeeper表示服务的下线状态，来让客户端不在调用该节点？

**Comment by why7282** [comment]
按理，有那种手动控制节点的上下线状态的需求非常常见，有计划通过什么方式去实现么？

**Comment by chickenlj** [comment]
我理解的你是要通过服务治理平台实现某台机器的下线。对应服务的《动态配置》功能可以实现
http://dubbo.io/user-guide/demos/%E9%85%8D%E7%BD%AE%E8%A7%84%E5%88%99.html

**Comment by why7282** [comment]
这 服务治理平台  动态配置的功能，我尝试了，控制下线或者覆盖规则，相应的节点并没有下线，依旧能有请求分配到该节点。 是这个治理功能只是规划了，还是去具体实现么？

**Comment by chickenlj** [comment]
功能是已经实现了的，不过限制指定consumer（ip）的动态配置功能可能存在bug

**Comment by why7282** [comment]
好谢谢。不过我还是没成功。 看能怎么联系你们交流下吗。

**Comment by cnhans** [comment]
<dubbo:application ...>
    <dubbo:parameter key="shutdown.timeout" value="60000" /> 
</dubbo:application>

这个无法配置的，application里面无法配置参数。

**Comment by ralf0131** [comment]
Please check this doc: http://dubbo.apache.org/#!/docs/user/demos/graceful-shutdown.md
