### ISSUE TITLE
集群上限、扩展瓶颈

### ISSUE THREAD

**Issue by mulunfeng** [apache/incubator-dubbo#509]
不知dubbo对集群支持的最大上限多少，是否做过压测，服务提供者、与消费者的上限，因为服务量大了之后每一次部署都要推送服务列表给消费者，消费者需要比较与本地缓存的区别，消耗大量的性能。

**Comment by chickenlj** [comment]
目前还没有这方面的公开数据。
根据经验，瓶颈可能首先会出现在注册中心或网络带宽；关闭dubbo注册中心的本地文件缓存功能可以显著减少被通知方(consumer)的性能损耗。
在集群规模提升的情况下，也建议减少单个工程的服务数量
