### ISSUE TITLE
优雅停机期间日志不能正常输出

### ISSUE THREAD

**Issue by wonderlq** [apache/incubator-dubbo#514]
tomcat+dubbo 优雅停机期间，貌似日志组件被销毁了，只能System.out输出日志，请问有什么方法能用logger方式输出？

**Comment by ralf0131** [comment]
Can you provide an example output?

**Comment by ralf0131** [comment]
Hi, 

In Dubbo 2.6.3 we have improved the elegant shutdown, the issue you described should been fixed. Please try it out with 2.6.3. Feel free to reopen this issue if it still exists.
