### ISSUE TITLE
LruCache 代码的没有设置accessOrder属性，这个是个FIFO缓存，不是LRU缓存

### ISSUE THREAD

**Issue by liushun89** [apache/incubator-dubbo#517]
dubbo/dubbo-filter/dubbo-filter-cache/src/main/java/com/alibaba/dubbo/cache/support/lru/LruCache.java

这个源码有点问题，里边的LinkedHashMap没有设置accessOrder，所以这个是是个FIFO的实现，与类名不符啊

**Comment by helloworldwt** [comment]
我这边也发现这个问题了。目前LruCache实现实际行为是FIFO的 @liushun89

**Comment by helloworldwt** [comment]
@liushun89 确实是FIFO缓存。这个地方使用LRU缓存更好一些吧，因为缓存的size是有限的，把经常访问的API调用结果缓存起来，能提高缓存的命中率，提升系统的性能。

**Comment by ralf0131** [comment]
This issue has already been fixed.
