### ISSUE TITLE
DUBBO服务IP异常

### ISSUE THREAD

**Issue by cnhaicao** [apache/incubator-dubbo#524]
![image](https://user-images.githubusercontent.com/28727462/29301456-e1c007e2-81ae-11e7-8381-dc63074c8335.png)

DUBBO服务启动后在zookeeper上看到的服务地址是上图那样的IP，请问这是怎么回事，

服务IP形如；0.0.0.xxx好奇怪，一直不知道是什么原因。

**Comment by chickenlj** [comment]
检查一下hosts文件配置？

**Comment by lizhou828** [comment]
我也有同样的问题
![default](https://user-images.githubusercontent.com/5133759/30364121-7474bdd8-9895-11e7-82ba-d42eee5e0847.png)

**Comment by ralf0131** [comment]
Please check:

1. your hosts file configuration.
2. your network interface. 

where Dubbo will get host ip from.

**Comment by diecui1202** [comment]
Feel free to reopen if necessary.
