### ISSUE TITLE
dubbo监控看不懂

### ISSUE THREAD

**Issue by panhongliang** [apache/incubator-dubbo#530]
![x334q 2flehnn21 vdgb le](https://user-images.githubusercontent.com/12706175/29343204-2d09524a-8262-11e7-90aa-1230f98c6f86.png)

Success:533 --> 274什么意思？还有别的几个都是什么意思

**Comment by wufengbin** [comment]
不是有可以切换语言吗？

**Comment by donlianli** [comment]
因为调用次数是分开统计的，客户端会统计一遍，服务器会统计一遍。所以一般客户端统计的次数会大于服务器端。533->274 表示客户端有533次的成功调用，服务器端有274的成功调用。看这数据，你监控数据有丢失或者时间不一致

**Comment by luxcm** [comment]
@panhongliang 你的统计数据是怎么做出来的？为什么我的没有？
