### ISSUE TITLE
使用Http协议方式，如何使用json序列化方式

### ISSUE THREAD

**Issue by liuluo129** [apache/incubator-dubbo#54]
文档上写的使用http协议时，默认使用json序列化，但是实际上请求头和响应头的content-type都是application/x-java-serialized-object，请求体和响应体也是类似java序列化的方式，想知道怎么才能使用json序列化方式呢

**Comment by diecui1202** [comment]
Hi, @liuluo129 Now you can try rest protocol: https://github.com/apache/incubator-dubbo-docs/blob/master/dubbo-user-book/rest.md
