### ISSUE TITLE
Consumer发起请求后20秒左右Provider才开始处理

### ISSUE THREAD

**Issue by chixuan777** [apache/incubator-dubbo#540]
Hi
我们使用最新的dubbo+spring3+tomcat7
我们有provider A，B
01秒A向B发出请求，但是B 20秒才开始进行处理（都是通过dubbo的filter来记录时间，有一定的误差）
03秒的时候，A正好有个线程dump的操作，记录03秒发起请求的consumer的状态是这样的
![1](https://user-images.githubusercontent.com/9463689/29559123-c27e46fc-8760-11e7-8c57-2e99ec0a0cf8.png)
我们也检查了系统网络，系统日志，业务日志，tomcat日志，都没有发现异常，A B的压力也都不大
请问对于排查这个问题有什么建议么？
为什么会有tomcat load class的操作呢？

**Comment by stoneapple** [comment]
关注下创建服务代理的耗时，这部分不算执行时间的

**Comment by carryxyh** [comment]
@chixuan777 
Hi, is this problem solved so far?
If it is, we will close this issue.

**Comment by carryxyh** [comment]
No person feedback about this issue this two days, I think it should be closed.
Maybe reopen if sth feedback.

&READY-TO-CLOSE&
