### ISSUE TITLE
rpc的dubbo协议的默认传输层框架是什么？http协议的servlet默认使用的是什么？

### ISSUE THREAD

**Issue by guliziduo** [apache/incubator-dubbo#556]
dubbo协议的传输层框架默认是netty还是mina；官方protocol配置说默认是netty，dubbo://介绍时又说是mina。
http协议Servlet层使用的jetty还是自己的servlet;官方protocol配置说默认是servlet，http://介绍时又说是jetty。

**Comment by www1350** [comment]
@SPI("netty")
public interface Transporter {

**Comment by www1350** [comment]
DubboProtocol 的export最后调用的是ExtensionLoader.getExtensionLoader(Transporter.class).getAdaptiveExtension();默认是@SPI("netty")
public interface Transporter作为ExchangeServer

HttpProtocol的@SPI("jetty")
public interface HttpBinder 作为HttpServer

**Comment by www1350** [comment]
你说的是推荐配置吧。

**Comment by guliziduo** [comment]
非常感谢你的解答。不看源代码可能发现不了这个问题，因为官方介绍dubbo协议时，说的默认使用mina1.1.7 + hessian3.2.1 



在 2017-09-01 15:04:36，"王文伟" <notifications@github.com> 写道：


DubboProtocol 的export最后调用的是ExtensionLoader.getExtensionLoader(Transporter.class).getAdaptiveExtension();默认是@SPi("netty")
public interface Transporter作为ExchangeServer

HttpProtocol的@SPi("jetty")
public interface HttpBinder 作为HttpServer

**Comment by ralf0131** [comment]
The default transporter for DubboProtocol is `netty`.
The default Http server for HttpProtocol is `jetty`.

**Comment by tomchan2015** [comment]
2020年了
[中文官网](https://dubbo.apache.org/zh/docs/v2.7/user/references/protocol/dubbo/)还是：
缺省协议，使用基于 mina 1.1.7 和 hessian 3.2.1 的 tbremoting 交互。
[英文](https://dubbo.apache.org/en/docs/v2.7/user/references/protocol/dubbo/)是：
The default protocol is Dubbo protocol ,based on netty 3.2.5.Final and Hessian2 3.2.1-fixed-2(Alibaba embed version).

所以什么时候能更新一下中文的？
