### ISSUE TITLE
conflict between @Service and @transactional 还需要其他设置？

### ISSUE THREAD

**Issue by ffff121** [apache/incubator-dubbo#557]
hi:
      我在 dubbo the version 2.5.4-SNAPSHOT master 分支看到提交号为 3945b83956debcf2127606ef6d88a6d29a080094 已经解决了@Service and @transactional冲突问题. 但我在使用的时候，provider生成到SpringProxy这个类命名的地址下，我使用的是spring boot 1.5.2.RELEASE. 下面是我的代码，是否还需要设置其他配置:

```javascript
@Service(protocol = "dubbo", timeout = 20000, retries = -1)
@Transactional
public class GoodServiceImpl implements GoodService {
....
}
```

```javascript
<dependency>
     <groupId>com.alibaba</groupId>
     <artifactId>dubbo</artifactId>
     <version>2.5.4-SNAPSHOT</version>
	<exclusions>
            <exclusion>
                 <artifactId>spring</artifactId>
		 <groupId>org.springframework</groupId>
	    </exclusion>
	</exclusions>
</dependency>
```

- `[DUBBO] Register: dubbo://192.168.2.17:28801/org.springframework.aop.SpringProxy?.....
`

**Comment by thinkhlin** [comment]
我也是遇到这种情况了，我的没写@Transactional

**Comment by ffff121** [comment]
@thinkhlin 你代码里可能有其他的注解，导致这个问题，比如@cachable之类的

**Comment by thinkhlin** [comment]
@ffff121 昨天我还特意试了下，我单独使用@Service注解，没有其他注解的情况下是正常的，然后我只加上了@Transactional后就出现这个情况了。没有其他注解了。

**Comment by thinkhlin** [comment]
@ffff121 是我自身的问题，只需要将事务管理的proxyTargetClass = true即可，即加上了这个注解就行了@EnableTransactionManagement(proxyTargetClass = true)

**Comment by ffff121** [comment]
@thinkhlin 那我也试试你的方法，我觉得也是我少配置了什么东西，因为我用的是spring boot，在spring boot的application.properties里我配置了spring.aop.proxyTargetClass=true，但不起作用。按你说的，是不是@transaction需要单独配置proxyTargetClass=true，我今天试试，再更新这里

**Comment by ffff121** [comment]
@thinkhlin 多谢！这几天太忙，刚抽出时间，试了一下，代码如下：
```
@Configuration
@EnableTransactionManagement(proxyTargetClass = true)
public class TransactionConfig {
}
```
```
@Transactional
@Service(protocol = "dubbo", timeout = 20000, retries = -1)
public class GoodServiceImpl implements GoodService {
...
}
```
这样就可以正常启动了。
ps：之前我在spring boot 的application.properties中设置spring.aop.proxyTargetClass=true并不起作用，我初步分析，spring.aop.proxyTargetClass=true属性是设置业务代码的方式。也许spring 的transaction并不起作用，需要额外设置参数

**Comment by ffff121** [comment]
@thinkhlin 启动不报错了，但是最后服务还是注册到了
```[DUBBO] Register: dubbo://192.168.2.17:28801/org.springframework.aop.SpringProxy?.....```
这个类上面，依然不行

**Comment by ffff121** [comment]
试了各种办法，升级了spring boot到2.0也不行。。。

**Comment by ffff121** [comment]
现在暂时只能用之前的办法，将rpc层和业务层分开

**Comment by mokci** [comment]
这个是 dubbo 和 spring aop的小冲突。
在 dubbo 的 AnnotationBean.class 第 300(isMatchPackage)行处并没有判断你的Service 是不是被spring aop 使用了JdkDynamicAopProxy   那么bean.getClass().getName()  的值将是： com.sun.proxy.$Proxy**  。这样就和你配置进去的包名不匹配，它就不会将这个@Service 注册到注册中心 。

`    private boolean isMatchPackage(Object bean) {
        if (annotationPackages == null || annotationPackages.length == 0) {
            return true;
        }
        String beanClassName = bean.getClass().getName();
        for (String pkg : annotationPackages) {
            if (beanClassName.startsWith(pkg)) {
                return true;
            }
        }
        return false;
    }`


解决办法：修改该类。修改方式参考新浪的Motan ，它就把这个处理的很好。ps：两个太像了。
Motan的[AnnotationBean.class](https://github.com/weibocom/motan/blob/master/motan-springsupport/src/main/java/com/weibo/api/motan/config/springsupport/AnnotationBean.java)

**Comment by mokci** [comment]
AnnotationBean 没法注册 代理bean。

参考：代理bean 无法用@Service 注入 #614 
或者自己修改：可以参考新浪的motan [AnnotationBean.class](https://github.com/weibocom/motan/blob/master/motan-springsupport/src/main/java/com/weibo/api/motan/config/springsupport/AnnotationBean.java)

**Comment by ffff121** [comment]
@mokci 多谢

**Comment by ralf0131** [comment]
Is your issue solved?

**Comment by ralf0131** [comment]
As mentioned in #614 , 

proxy bean support with annotation scan, was fixed in dubbox[1].

We need to port the fix to dubbo.

[1] dangdangdotcom@1b33f19

**Comment by charish00** [comment]
这个其实是BeanPostProcessor的执行顺序的问题，我的做法是把dubbo sevice的代理放到了spring生命周期的refresh阶段做了。这个需要修改部分源码

**Comment by beiwei30** [comment]
https://github.com/apache/incubator-dubbo/issues/2215#issuecomment-463097233 这个问题已经解决了。请尝试最新版本。
