### ISSUE TITLE
dubbo启动的时候将虚拟机IP当成本地IP

### ISSUE THREAD

**Issue by Debri** [apache/incubator-dubbo#560]
dubbo将我本地电脑安装的虚拟机的ip地址当成了我的公网IP，以虚拟机的IP地址加上服务名注册到了zookeeper上，nodejs能够订阅到服务但是无法调用

**Comment by bianlizuozishu** [comment]
1.配置host:127.0.0.1 计算机名字

**Comment by bianlizuozishu** [comment]
2.禁用虚拟机的网卡

**Comment by lovepoem** [comment]
这种读本地ip的问题，多网卡时候，确实不好解决。一般是server的环境变量上加一个变，如：SERVER_IP=192.168.10.1.在consumer自动时候，读环境变量的数值,将配置的ip注册到zk

**Comment by qiudaozhang** [comment]
这个问题到底如何解决呢？
