### ISSUE TITLE
服务如何rebalance

### ISSUE THREAD

**Issue by dubby1994** [apache/incubator-dubbo#562]
服务消费者和服务提供者长连，那如果我增加一个新的服务提供者，这个服务提供者怎么被消费呢？难道注册中心只负责推送服务新实例的消息，由服务消费者自己决定要不要长连这个新的服务实例吗？还是洗牌，重新来一次负载均衡，所有的都重新建立长连的？

**Comment by Authorlove** [comment]
你是说一致性hash选址吗？

**Comment by ralf0131** [comment]
Hi, if you new provider comes online, the address will be pushed to consumer, the consumer will do the load balance according to your load balance strategy. If the consumer decide to choose the new provider, it will establish connection to the new provider. 

Load balance will be done each time, but connection establishment will only be done once.
