### ISSUE TITLE
Stub Proxy 失效Bug

### ISSUE THREAD

**Issue by 710270532** [apache/incubator-dubbo#565]
项目里只有dubbo-consumer.xml文件使用stub配置，stub配置为 stub="ture"，有效。项目如果增加dubbo-provider.xml，相同配置stub失效。

**Comment by ralf0131** [comment]
Hi, can you provide to reproduce your issue?

Stub can only be used in consumer side: http://dubbo.apache.org/#!/docs/user/demos/local-stub.md?lang=zh-cn

**Comment by diecui1202** [comment]
Feel free to reopen if necessary.
