### ISSUE TITLE
ubuntu下广播模式本地ip获取问题

### ISSUE THREAD

**Issue by feye** [apache/incubator-dubbo#575]
Ubuntu 下 host = InetAddress.getLocalHost().getHostAddress(); 获取到的地址是127.0.0.1，这是一个不合法的本地地址。
后面代码尝试去连接注册地址，在广播模式下地址是不可连接的，所以就出错了。
希望能修复这个问题。
com.alibaba.dubbo.config.ServiceConfig  ===>    doExportUrlsFor1Protocol

**Comment by ralf0131** [comment]
It has been fixed in #1620 and will be available since 2.6.2
