### ISSUE TITLE
com.alibaba.dubbo.common.bytecode.proxy0

### ISSUE THREAD

**Issue by nerososft** [apache/incubator-dubbo#604]
com.alibaba.dubbo.common.bytecode.proxy0 这个可以通过某种方式invok么？

target = applicationContext.getBean(targetName);这样的话taget是：com.iot.nero.api_gateway.demo.service.impl.HelloWorld@6a9d7ace
class com.iot.nero.api_gateway.demo.service.impl.HelloWorld

target = Consumer.singleton().getBean(targetName);这样的话target是：
com.alibaba.dubbo.common.bytecode.proxy0@3cb7d279
class com.alibaba.dubbo.common.bytecode.proxy0

**Comment by ralf0131** [comment]
Could you please describe why you want to do so?

**Comment by nerososft** [comment]
api gateway

**Comment by diecui1202** [comment]
@nerososft Maybe you can try generic invoke.

**Comment by beiwei30** [comment]
this is just a dynamic proxy for remote service.
