### ISSUE TITLE
计划官方支持 Spring boot么？ 目前的配置很不友好

### ISSUE THREAD

**Issue by xiaolongyuan** [apache/incubator-dubbo#616]

**Comment by beiwei30** [comment]
很快会支持的，可能在下面几个维护版本中发布。目前的配置，你是指官方的 spring 配置吗？

**Comment by xiaolongyuan** [comment]
Thanks .

我消费者方用的还是 spring xml 集成方式  因为觉得 使用 @Reference 不爽
生产方 用的 dubbo的 @Service 注解

希望未来都可以 用 spring boot 解决

**Comment by liuanxin** [comment]
https://github.com/teaey/spring-boot-starter-dubbo 这个就是 dubbo 的作者之一的项目. 基于 spring boot 一共也就四个类就实现了

**Comment by kukaqin** [comment]
支持spring boot 很容易，我们自己也扩展了

**Comment by Comven** [comment]
spring-boot-starter-dubbo中使用@Reference这个注解的确不是很方便，而且例如check=false这个设置就没有用，如果服务发布方没有启动很容出现空指针

**Comment by shenzhuan** [comment]
http://git.oschina.net/catshen/zscat_sw 这个整合的不错

**Comment by liuanxin** [comment]
@Comven 那是 dubbo 自己内部的问题导致的, 本地测试的时候可以用一种折中的办法处理.  https://github.com/alibaba/dubbo/issues/195

**Comment by xiaolongyuan** [comment]
官方有解决方案不就更好么 对吧

**Comment by liuanxin** [comment]
官方会更乐于见到有已经实现的成熟方案, pull request 进去就行了.

开源社区的意义也就在这里. 而不是等着人天天呼吁发 issue

**Comment by CodingOX** [comment]
期待官方实现！

**Comment by lovepoem** [comment]
https://github.com/apache/incubator-dubbo-spring-boot-project is the official version
