### ISSUE TITLE
Dubbo的最佳实践是什么

### ISSUE THREAD

**Issue by DayuZhu** [apache/incubator-dubbo#617]
Dubbo按照 官方提供的最佳实践是    com.alibaba.dubbo.container.Main.main(args);  来启动 ； 那么每个dubbo服务中的lib依赖是不是都得单独打包还是说可以共用一个

**Comment by xiaolongyuan** [comment]
。。。

怎么还有这种想法呢  肯定不共用啊

**Comment by DayuZhu** [comment]
我就纠结 是用可运行jar 还是放容器里运行

**Comment by xiaolongyuan** [comment]
spring boot  jar就行了

**Comment by zistrong** [comment]
provider启动一个java进程就行了。 为啥还要放到javaee容器中。
