### ISSUE TITLE
Service注解能支持Inherited吗

### ISSUE THREAD

**Issue by iBase4J** [apache/incubator-dubbo#618]
Service注解能支持Inherited吗

**Comment by shenzhuan** [comment]
升级到2.8.4就可以了 http://git.oschina.net/catshen/zscat_sw  已经验证了

**Comment by lj7711622** [comment]
[Service.java](https://github.com/alibaba/dubbo/blob/dubbo-2.5.5/dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/annotation/Service.java)
现在已经支持了吧

**Comment by ralf0131** [comment]
Yes, it is already supported.
