### ISSUE TITLE
dubbo netty会考虑升级为4以上版本吗

### ISSUE THREAD

**Issue by zhangyinyue** [apache/incubator-dubbo#622]

**Comment by seasail** [comment]
该考虑升级至4.*版本了

**Comment by Leviathans** [comment]
这个升级还是挺大的

**Comment by wuwen5** [comment]
https://github.com/QianmiOpen/dubbo-remoting-netty4
仅供参考，几年前尝试做的. 可以与当前dubbo版本直接使用。
当时与netty3压测对比 无明显优势，所以就搁置没关注了。感兴趣可以一起看下.

**Comment by seasail** [comment]
@wuwen5，我看了下你提供的路径，当时验证的是4.0版本，而Netty4.1版本也有比较大的变化，与3.*版本相比，提升非常大。

**Comment by GeemChen** [comment]
@zhangyinyue 目前最新已经更新netty4

**Comment by seasail** [comment]
@GeemChen 查了pom，没看到有升级至netty4

**Comment by ralf0131** [comment]
The latest version 2.6.1 now supports netty4.
