### ISSUE TITLE
maven install时一直提示无法解析项目jar包

### ISSUE THREAD

**Issue by xiongminglang** [apache/incubator-dubbo#625]
ailed to execute goal on project dubbo: Could not resolve dependencies for project com.alibaba:dubbo:jar:2.5.4: The following artifacts could not be resolved: com.alibaba:dubbo-config-api:jar:2.5.4, com.alibaba:dubbo-config-spring:jar:2.5.4, com.alibaba:dubbo-remoting-netty:jar:2.5.4, com.alibaba:dubbo-remoting-mina:jar:2.5.4, com.alibaba:dubbo-remoting-grizzly:jar:2.5.4, com.alibaba:dubbo-remoting-p2p:jar:2.5.4, com.alibaba:dubbo-remoting-http:jar:2.5.4, com.alibaba:dubbo-rpc-default:jar:2.5.4, com.alibaba:dubbo-rpc-injvm:jar:2.5.4, com.alibaba:dubbo-rpc-rmi:jar:2.5.4, com.alibaba:dubbo-rpc-hessian:jar:2.5.4, com.alibaba:dubbo-rpc-http:jar:2.5.4, com.alibaba:dubbo-rpc-webservice:jar:2.5.4, com.alibaba:dubbo-rpc-thrift:jar:2.5.4, com.alibaba:dubbo-rpc-memcached:jar:2.5.4, com.alibaba:dubbo-rpc-redis:jar:2.5.4, com.alibaba:dubbo-registry-default:jar:2.5.4, com.alibaba:dubbo-registry-multicast:jar:2.5.4, com.alibaba:dubbo-registry-zookeeper:jar:2.5.4, com.alibaba:dubbo-registry-redis:jar:2.5.4, com.alibaba:dubbo-monitor-default:jar:2.5.4, com.alibaba:dubbo-container-spring:jar:2.5.4, com.alibaba:dubbo-container-jetty:jar:2.5.4, com.alibaba:dubbo-container-log4j:jar:2.5.4, com.alibaba:dubbo-container-logback:jar:2.5.4: Failure to find com.alibaba:dubbo-config-api:jar:2.5.4 in http://maven.aliyun.com/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of alimaven has elapsed or updates are forced

我尝试手动安装jar包.提示拒绝访问

**Comment by chickenlj** [comment]
是在本地执行maven命令报错吧？在什么目录执行的什么命令出的问题？

**Comment by erstens** [comment]
+1

**Comment by Xiaobaxi** [comment]
setting文件中的mirrors配置需要正确，删除仓库，重新下载一下试试

**Comment by ralf0131** [comment]
Hi, please try the latest code. Feel free to reopen it if it still exists.
