### ISSUE TITLE
使用redis作为注册服务器时，密码设置无效

### ISSUE THREAD

**Issue by cralcui** [apache/incubator-dubbo#63]
使用redis作为注册服务器时，密码设置无效
好像是 com.alibaba.dubbo.registry.redis.RedisRegistry中没有处理密码

**Comment by htynkn** [comment]
Refer to #665. Feature added by 4c95cfe9424377c827d0b181d042f40105042cf7

**Comment by ralf0131** [comment]
This issue has been fixed.
