### ISSUE TITLE
dubbo用户手册连接错误

### ISSUE THREAD

**Issue by wannshan** [apache/incubator-dubbo#642]
https://dubbo.gitbooks.io/dubbo-user-book/demos/registry-only.html
4.6节，只订阅 和4.7节，只注册，连接内容颠倒了。

**Comment by ralf0131** [comment]
Can you send a pull request to https://github.com/apache/incubator-dubbo-docs ?

**Comment by ralf0131** [comment]
Hi, this issue has already be fixed. Please check the latest code.
