### ISSUE TITLE
本地存根和本地伪装无法使用

### ISSUE THREAD

**Issue by liuluo129** [apache/incubator-dubbo#65]
文档上写的本地存根和本地伪装在调用失败的时候会进行一些处理，但是我在测试环境使用的时候把全部服务端关掉之后，就无法使用了，再次调用会抛出异常，信息如下：
```
com.alibaba.dubbo.rpc.RpcException: Forbid consumer 10.0.0.182 access service com.common.service.LogService from registry zookeeper1:2181 use dubbo version 2.4.10, Please check registry access list (whitelist/blacklist).
    at com.alibaba.dubbo.registry.integration.RegistryDirectory.doList(RegistryDirectory.java:586)
    at com.alibaba.dubbo.rpc.cluster.directory.AbstractDirectory.list(AbstractDirectory.java:73)
    at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.list(AbstractClusterInvoker.java:259)
    at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:218)
    at com.alibaba.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:72)
    at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:52)
    at com.alibaba.dubbo.common.bytecode.proxy0.addScheduleLog(proxy0.java)
```
看源码发现RegistryDirectory类中forbidden属性已经变成true了，原因在于没有服务端的时候，会接收到通知，RegistryDirectory类会调用refreshInvoker方法，如下：
```java
private void refreshInvoker(List<URL> invokerUrls){
        if (invokerUrls != null && invokerUrls.size() == 1 && invokerUrls.get(0) != null
                && Constants.EMPTY_PROTOCOL.equals(invokerUrls.get(0).getProtocol())) {
            this.forbidden = true; // 禁止访问
            this.methodInvokerMap = null; // 置空列表
            destroyAllInvokers(); // 关闭所有Invoker
```
这个时候在去调用stub和mock都会抛出异常。所以我怀疑这个特性根本无法使用，但是文档上写的可以在生产中使用，有使用过这特特性的同学吗

**Comment by sdw2330976** [comment]
遇到同样的问题v2.5.3 有解决的吗

**Comment by bbiao** [comment]
2.5.3还是有这个问题

**Comment by wuzhefang** [comment]
是不是重启一下服务端，刷新一下服务列表就好了？

**Comment by JKAK47** [comment]
dubbo的本地伪装有谁成功实现过。按照dubbo官方文档设置。然后关于服务提供方服务。服务调用方调用接口也是会失败的。

**Comment by JKAK47** [comment]
2.5.3 还是有这个不能本地伪装的问题存在

**Comment by kitikousei** [comment]
在AbstractRegistry中有一段这样的代码
 for (Map.Entry<String, List<URL>> entry : result.entrySet()) {
            String category = entry.getKey();
            List<URL> categoryList = entry.getValue();
            categoryNotified.put(category, categoryList);
            saveProperties(url);
            listener.notify(categoryList);
        }
这里的result内容如下
[providers=[empty://192.168.1.137/com.xxx.xxService?application=myconsume&category=providers&default.check=false&default.mock=true&dubbo=2.5.5&interface=com.xxx.xxService&methods=register&pid=27046side=consumer], configurators=[empty://192.168.1.137/com.xxx.xxService?application=myconsume&category=configurators&default.check=false&default.mock=true&dubbo=2.5.5&interface=com.xxx.xxService&methods=register&pid=27046&side=consumer], routers=[empty://192.168.1.137/com.xxx.xxService?application=myconsume&category=routers&default.check=false&default.mock=true&dubbo=2.5.5&interface=com.xxx.xxService&methods=register&pid=27046&side=consumer]]
在jdk1.7中第一次循环取的是providers。后面的逻辑会去刷新forbidden字段（refreshInvoker方法）。此时是forbidden设置为false，第二次循环会设置为true，第三次会设置成false。此时可以本地伪装。
但是在jdk1.8中第一次循环去的是configurators。后面的逻辑会去刷新forbidden字段（refreshInvoker方法）。此时是forbidden设置为true，第二次循环会设置为false，第三次会设置成true。此时就本地伪装就没法调用。

**Comment by diecui1202** [comment]
Local stub works only when providers >= 1. Local mock's bug has fixed, please check https://github.com/apache/incubator-dubbo/blob/fd7bab3cdf2650168e9eca625fd5311ffc7b1f5a/dubbo-cluster/src/main/java/com/alibaba/dubbo/rpc/cluster/support/wrapper/MockClusterInvoker.java#L142

Feel free to reopen it or open a new issue if you have any other questions.
