### ISSUE TITLE
用户手册基准测试工具包地址失效了

### ISSUE THREAD

**Issue by shitongtong** [apache/incubator-dubbo#652]
用户手册基准测试工具包中：
下载 [benchmark压缩包](http://code.alibabatech.com/wiki/download/attachments/7669075/dubbo.benchmark-2.0.14.tar.gz)，并解压
这里[benchmark压缩包](http://code.alibabatech.com/wiki/download/attachments/7669075/dubbo.benchmark-2.0.14.tar.gz)地址失效了

**Comment by ralf0131** [comment]
Hi, please check this doc: https://github.com/apache/incubator-dubbo-docs/blob/master/dubbo-user-book/benchmark-tool.md

**Comment by lovepoem** [comment]
>Hi, please check this doc: https://github.com/apache/incubator-dubbo-docs/blob/master/dubbo-user-book/benchmark-tool.md

as @ralf0131 metioned,you can use the new method to get tar.gz archives
