### ISSUE TITLE
what’s the plan to support jetty version 9?

### ISSUE THREAD

**Issue by yjqg6666** [apache/incubator-dubbo#655]
When would be supported? Would the dubboX dangdangdotcom/dubbox merged back to dubbo?

**Comment by chickenlj** [comment]
I remember jetty9 requires jdk1.8+, we'll consider upgrade jetty in the 2.5.8

**Comment by yjqg6666** [comment]
@chickenlj  It's true. So version 2.5.8 will also support 1.8 officially?

**Comment by ralf0131** [comment]
Dubbo 2.x should support Java 6+, so the highest version that can be upgrade to should be Jetty 8:  

https://www.eclipse.org/jetty/about.html

**Comment by chickenlj** [comment]
http://www.eclipse.org/jetty/previousversions.html

I think we can upgrade to the latest version listed here, http://www.eclipse.org/jetty/previousversions.html
