### ISSUE TITLE
dubbo-admin2.5.5提供者禁用之后，点击启用无效

### ISSUE THREAD

**Issue by jmbkeyes** [apache/incubator-dubbo#658]
在服务治理 > 提供者页面，将一个服务禁用之后，点击启用。提示成功，但实际还是禁用状态
![image](https://user-images.githubusercontent.com/12583734/30513394-fc3605b4-9b34-11e7-9db2-8a6da91296b1.png)

**Comment by chickenlj** [comment]
dubbo会保证至少有一个可用的provider，如果一条禁用规则会导致无可用provider则不会生效。你只有两个provider，所以禁用不会生效

**Comment by jmbkeyes** [comment]
我的问题是**"禁用之后，无法再启用"**

**Comment by ganjx** [comment]
“dubbo会保证至少有一个可用的provider” 这种逻辑不是很合理，对于禁用来说，就是想禁用全部，现在就实现不了。

**Comment by ganjx** [comment]
对于禁用如果禁用很多节点的情况下，常常会启用不了。在使用dubbokeeper感觉不错。

**Comment by maodie007** [comment]
确实有禁用后无法启用的问题

**Comment by DayuZhu** [comment]
2.5.6 好使啊 你想全部禁用 不如屏蔽consumer

**Comment by lovepoem** [comment]
@jmbkeyes 
It is recommended to use the latest version of dubbo-ops
