### ISSUE TITLE
There is a potential deadlock in DubboProtocol#getSharedClient

### ISSUE THREAD

**Issue by aCoder2013** [apache/incubator-dubbo#677]
Synchronized on `String#intern` is a bad practice, interning a string will make it a global object .Which means if you synchronized the same interned strings in different parts of your code , some shit'll happen ,eg : deadlock

https://github.com/alibaba/dubbo/blob/9cf27a36848c22fbfd00877449fbe0eaf53e040c/dubbo-rpc/dubbo-rpc-default/src/main/java/com/alibaba/dubbo/rpc/protocol/dubbo/DubboProtocol.java#L333

**Comment by chickenlj** [comment]
If we put all export/refer actions into a single serial process, we can get rid locks.
We've decided to solve this problem that way.

**Comment by beiwei30** [comment]
dead lock will not happen since this is the only place to use `str.intern()` in dubbo code base, but to be safe, I decide to change it to:

```java
        synchronized ((key + ".lock").intern()) {
            ...
       }
```

to solve the potential issue.

**Comment by aCoder2013** [comment]
@beiwei30 how about a lock pool, so basically this pool always return the same lock instance with the same key, and use something like access time to collect unused instance

**Comment by beiwei30** [comment]
@aCoder2013 a lock pool certainly works, but it make no difference with str.intern() if recycling is not considered, furthermore, it should occupy more memory. Are we facing overhead design here? :)

**Comment by aCoder2013** [comment]
@beiwei30  interning a string will make it a global object, but each service can have its own lock pool .
I didn't read all  the source code here ,do we need to consider memory consumption？

**Comment by beiwei30** [comment]
@aCoder2013 how about this:

```java

    ConcurrentMap<String, Object> locks = new ConcurrentHashMap<String, Object>();

    /**
     * Get shared connection
     */
    private ExchangeClient getSharedClient(URL url) {
        String key = url.getAddress();
        ReferenceCountExchangeClient client = referenceClientMap.get(key);
        if (client != null) {
            if (!client.isClosed()) {
                client.incrementAndGetCount();
                return client;
            } else {
                referenceClientMap.remove(key);
            }
        }
        locks.putIfAbsent(key, new Object());
        synchronized (locks.get(key)) {
            if (referenceClientMap.containsKey(key)) {
                return referenceClientMap.get(key);
            }
            
            ExchangeClient exchangeClient = initClient(url);
            client = new ReferenceCountExchangeClient(exchangeClient, ghostClientMap);
            referenceClientMap.put(key, client);
            ghostClientMap.remove(key);
            locks.remove(key);
            return client;
        }
    }
```

**Comment by aCoder2013** [comment]
LGTM！

**Comment by beiwei30** [comment]
:)
