### ISSUE TITLE
Invoker在返回RpcResult时添加的attachements没有传给consumer的proxy.

### ISSUE THREAD

**Issue by chenwmw** [apache/incubator-dubbo#68]
主要想法是模仿http cookie实现servlet session的思路，通过attachement来传递session ID，藉此达到支持Session的目的，目前加在RpcInvocation attachement中的sessionID能成功的传递给provider端的Invoker，但是在调用结果封装对象RpcResult attachements的sessionID却不能穿会给consumer端的proxy factory.

**Comment by jxctx88** [comment]
同问，这个问题有解决吗？

**Comment by takeseem** [comment]
14年我们用来传递一个系统跟踪id，除了rmi协议需修复外，走dubbo协议是ok的

**Comment by jxctx88** [comment]
你说的应该是consumer传递给provider，我们说的是proider反传给consumer

**Comment by takeseem** [comment]
这个倒是真的，没有反传过。

**Comment by ralf0131** [comment]
dup with #448
