### ISSUE TITLE
Dubbo2.5.3在windows下不能使用公网IP注册服务

### ISSUE THREAD

**Issue by xiaosilent** [apache/incubator-dubbo#69]
近日新增了一个服务，必须在Windows Server2003的环境下运行，因此需要在Windows下注册dubbo服务，服务器为单网卡连接路由器，分配内网IP：192.168.1.3，路由器有公网IP假设为8.8.8.8，注册到另一IDC的Zookeeper下(4.4.4.4)，自动使用内网IP 192.168.1.3注册成功，但consumer肯定无法在4.4.4.4的内网下调用到8.8.8.8下的内网的服务，因此需要将服务注册成公网ip。

看了使用者指南的“主机绑定”部分，指出 
方法1：可以通过修改 /etc/host 文件(经测试在8.8.8.8下开了一个linux主机用修改hosts文件的办法成功注册为公网ip)，但我试着修改了c:\windows\system32\drivers\etc\hosts 文件，仍然是注册为内网ip
方法2：老实说，没看懂示例中的地址为何要那样写（
<dubbo:protocol host="http://10.20.160.198/wiki/display/dubbo/205.182.23.201">）,我把host写成ip，会抛出bindException，canot assign requested address:bind
方法3：在classpath中添加dubbo.properties文件，结局和方法2一样

求教如何在windows下成功用公网ip注册服务。。。

**Comment by deo-prime** [comment]
如果主机的网卡配置是内网IP地址，除非消费者也在这个内网，否则是无法访问到提供者的。你的方法二出错是因为你的公网IP不是本机，只不过是因为公网IP通过路由器配置绑定在你这台主机上。我也尝试过使用hostname，然后让客户端配置hosts解析，但是不知道为什么提供者通过这样开放的服务只能在本机访问到，其他主机都访问不到。

**Comment by gMan1990** [comment]
@xiaosilent 我和你同样的问题，买的云服务器，telnet是通的，我用直连的方式都不行。/尴尬

**Comment by ralf0131** [comment]
Please check: https://github.com/apache/incubator-dubbo/wiki/FAQ, in the "How to register ip correctly in docker" section.

Under windows you can use:

```
SET DUBBO_IP_TO_REGISTRY=8.8.8.8
```
