### ISSUE TITLE
Generic invoke only support "dubbo protocol"?

### ISSUE THREAD

**Issue by fred201710** [apache/incubator-dubbo#705]
生产者使用泛化实现时，消费者不能调用此服务,使用hessian协议调用时报错，使用dubbo协议调用时正常。报错信息如下：
com.alibaba.dubbo.common.bytecode.NoSuchMethodException: Not found method "$invoke" in class *.*.UserManageService.
	com.alibaba.dubbo.common.bytecode.Wrapper1.invokeMethod(Wrapper1.java)
	com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:46)
	com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:72)
	com.alibaba.dubbo.rpc.protocol.AbstractProxyProtocol$2.doInvoke(AbstractProxyProtocol.java:93)
	com.alibaba.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:144)
	com.alibaba.dubbo.rpc.filter.GenericImplFilter.invoke(GenericImplFilter.java:173)
	com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	com.alibaba.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:53)
	com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75)
	com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	com.alibaba.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:48)
	com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	com.alibaba.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:74)
	com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53)
	com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:77)
	com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:227)
	com.alibaba.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:72)
	com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:52)
	com.alibaba.dubbo.common.bytecode.proxy1.findUser(proxy1.java)
看一下源代码，好像是除dubbo协议都不支持。在GenericImplFilter类中把方法名转成$invoke,把原方法名和参数转成现在参数了，而其它协议在生成代理时都是按服务接口生成的没有$invoke这个方法。还有串化方面，只有对dubbo泛化的类GenericDataInput,GenericDataOutput,GenericObjectInput,GenericObjectOutput.

**Comment by chickenlj** [comment]
泛化调用/实现目前对dubbo以外的协议支持是存在问题的，我认为泛化应该提供对其他协议的支持。
现在不支持算是代码实现上的问题
