### ISSUE TITLE
AbstractConfig内存泄露

### ISSUE THREAD

**Issue by pingchungg** [apache/incubator-dubbo#71]
AbstractConfig中使用addShutdownHook函数造成AbstractConfig对象无法被回收.造成ClassLoader对象也无法被回收.

**Comment by xinghui322** [comment]
确实会造成内存泄露。http://stackoverflow.com/a/6950607

**Comment by wendal** [comment]
原来是老bug了，唉

**Comment by ralf0131** [comment]
Hi, I am planing to look at this issue.

**Comment by diecui1202** [comment]
@ralf0131 Any progress ?

**Comment by LiZhenNet** [comment]
> @ralf0131 Any progress ?

I have push a request to fix it。

**Comment by ralf0131** [comment]
@LiZhenNet Not yet, sorry for being late. I should have some time to review it this week.
