### ISSUE TITLE
dubbo-admin如何查看同一服务的多个分组？

### ISSUE THREAD

**Issue by jinsust** [apache/incubator-dubbo#731]
如题，为了区分正式环境和测试环境，对服务提供方配置了group(dubbo, test); 

但dubbo-admin默认只显示dubbo分组里的服务, 更改dubbo-admin的group配置为test的话，又不显示之前dubbo组里的服务信息了

怎样能查看多个分组的服务信息？

**Comment by lovepoem** [comment]
不同环境应该配置不同的集群，zk数据分离

**Comment by yiway** [comment]
但是同样的环境，也存在“当一个接口有多种实现时，需要用 group 区分”的情况，那这怎么办呢？

**Comment by serrena** [comment]
是不是可以考虑通过version来区分？

**Comment by nzomkxia** [comment]
目前版本中 服务查询页面可以显示服务分组信息：https://github.com/apache/incubator-dubbo-ops

**Comment by hellothejava** [comment]
搭建的0.3.0还是必须配置单个group，虽然有页面有group列，但是是空值，那个版本支持多个组？
