### ISSUE TITLE
未来规划

### ISSUE THREAD

**Issue by lilanlong** [apache/incubator-dubbo#745]
现在dubbo开始维护了，未来有什么计划呀。

**Comment by chickenlj** [comment]
当前还是以维护版本为主，主要focus在遗留issue修复、优化上；  
2.5.7版本之后将会以新特性和优化为主；  
我个人觉得围绕RPC、分布式服务调用的整个生态体系的各种框架、工具链的完善也是一个重要的工作方向

有什么建议吗

**Comment by liguoxijob** [comment]
dubbo有对接口做一层安全保护吗？比如接口的调用鉴权

**Comment by gundamff** [comment]
与spring cloud集成怎么样?

**Comment by CodingOX** [comment]
1. 修改在SpringBoot集成后的bug。
2. 生态打造很张重要。SpringCloud之所以能这么火，不是性能而是生态，生态跟上了，中小型公司才更有底气去使用。

**Comment by chickenlj** [comment]
@CodingOX 2.5.7版本即将发布，将会提供相对完善的注解配置方式，后续马上会提供spring-boot-starter集成方案
