### ISSUE TITLE
zookeeper添加acl失效

### ISSUE THREAD

**Issue by chrischeng03** [apache/incubator-dubbo#758]
zookeeper作为注册中心后，如果zookeeper添加acl后，注册失败，提升没有权限

**Comment by deo-prime** [comment]
同样遇到了这个问题.

**Comment by deo-prime** [comment]
客户端使用curator后就好了~

**Comment by notlate** [comment]
zk如果添加了权限，那么dubbo作为client也要把用户名 密码带过去注册zk

**Comment by carryxyh** [comment]
> zk如果添加了权限，那么dubbo作为client也要把用户名 密码带过去注册zk

Solve this problem like this.

&READY-TO-CLOSE&
