### ISSUE TITLE
dubbo-admin-2.5.6启动日志报错 ERROR 但控制台可访问

### ISSUE THREAD

**Issue by DayuZhu** [apache/incubator-dubbo#766]
![default](https://user-images.githubusercontent.com/18682988/31875013-bdfd5324-b7fe-11e7-8bcd-4fef28663d5c.png)

**Comment by chickenlj** [comment]
堆栈已经描述的很清楚了，依赖包检查发现dubbo-common、dubbo两个依赖包，应该和你本地工程引用的问题

**Comment by DayuZhu** [comment]
dubbo目录下 运行mvn install -Dmaven.test.skip=true 时 将子项也打在war里
![qq 20171025105751](https://user-images.githubusercontent.com/18682988/32036793-82f83dc2-ba54-11e7-9a37-167d81d146db.png)
用 mvn package  -Dmaven.test.skip=true 打war就OK了 @chickenlj
