### ISSUE TITLE
dubbo可不可以支持相同接口，指定调用服务系统

### ISSUE THREAD

**Issue by egemmer** [apache/incubator-dubbo#802]
使用dubbo时，有2个系统实现相同接口，在调用服务的时候能路由到想要调的系统。比如通知结果，有2个系统都实现了获得通知的服务，核心去调的时候根据业务类型调用指定的系统服务。

**Comment by chickenlj** [comment]
根据你描述的场景，适合使用[服务分组](https://dubbo.gitbooks.io/dubbo-user-book/content/demos/service-group.html)进行区分不同实现

**Comment by egemmer** [comment]
服务分组能够区分接口不同实现的场景，但是必须配置文件写死，不能调用的时候动态选择group实现。如果能在调用的时候动态选择group，dubbo将带来更大的灵活性

**Comment by lichao321** [comment]
可以使用代理的方式动态调用

**Comment by stoneapple** [comment]
这个问题可以通过动态路由来实现，提供方不同系统配置不同的<dubbo:parameter> 消费方在自定义路由里面根据你的业务类型判断需要走到哪个系统，这个是动态的

**Comment by ralf0131** [comment]
@chickenlj I've noticed that you added `good first issue` and `help wanted`. What should be done here?
