### ISSUE TITLE
etcd support on 2.7

### ISSUE THREAD

**Issue by lujs890616** [apache/incubator-dubbo#808]
1. 注册中心是否考虑增加etcd的方案？
1. 2.5.7会适配大部分的注解实现，预计什么时候发布？

**Comment by oldratlee** [comment]
@lujs890616 标题不合适吧？并且和内容不一致。

**Comment by chickenlj** [comment]
@lujs890616  
1. 我们在考虑适配一些流行的注册中心或动态配置等框架，也包括剔除一些过期的框架如grizzly等，但可能不会在近期的维护版本中
2. 2.5.7本周内会发布

**Comment by lovepoem** [comment]
关注：
https://github.com/coreos/jetcd  
etcd java客户端，Java 8 or above is required  支持到etcd 3.2.9

https://github.com/coreos/zetcd

A ZooKeeper "personality" for etcd

**Comment by lovepoem** [comment]
https://github.com/alibaba/dubbo/issues/983

**Comment by zonghaishang** [comment]
@lujs890616 我已经实现了etcd注册中心，3月份后计划开源

**Comment by ralf0131** [comment]
Hi, please checkout this project: https://github.com/dubbo/dubbo-registry-etcd

**Comment by ralf0131** [comment]
Etcd registry will be introduced in 2.7.1.
