### ISSUE TITLE
Service，Reference注解什么时候支持占位符替换

### ISSUE THREAD

**Issue by wangzhangxing** [apache/incubator-dubbo#830]
诸如版本号之类的参数，硬编码不方便啊

**Comment by stoneapple** [comment]
I also need this feature

**Comment by ralf0131** [comment]
Please check the latest version, I has been added recently.

**Comment by hylyLLL** [comment]
> I am providing a Service-SDK to our partner, and it requires a dynamic version specified by the partner's application. The best way is to provide the version via properties.
> 
> `@com.alibaba.dubbo.config.annotation.Service(version = "${service.version}")`
> 
> but it will fail and report:
> `Caused by: java.lang.IllegalStateException: Invalid version="${service.version}" contain illegal charactor, only digit, letter, '-', '_' and '.' is legal.`

你好，请问现在有解决方式了吗？

**Comment by Wolf-ZR** [comment]
2.6.3想通过占位符分组，有什么解决办法没
