### ISSUE TITLE
dubbo:annotation注解扫描到被代理的对象时，无法发布服务

### ISSUE THREAD

**Issue by yiyiwangru** [apache/incubator-dubbo#840]
private boolean isMatchPackage(Object bean) {
        if (annotationPackages == null || annotationPackages.length == 0) {
            return true;
        }
        String beanClassName = bean.getClass().getName();
        for (String pkg : annotationPackages) {
            if (beanClassName.startsWith(pkg)) {
                return true;
            }
        }
        return false;
 }
这里的代码获取到的是代理对象，取到的beanClassName是代理类，不能获取到真实类型。
可以参考新浪的motan [AnnotationBean.class](https://github.com/weibocom/motan/blob/master/motan-springsupport/src/main/java/com/weibo/api/motan/config/springsupport/AnnotationBean.java)

**Comment by chickenlj** [comment]
请使用[2.5.7版本](https://github.com/alibaba/dubbo/releases/tag/dubbo-2.5.7)，重写后此问题已修复

**Comment by yiyiwangru** [comment]
还是不可以呢 我看了源码 里面有没有处理啊 还是没变 调试也还是取到的代理类  @chickenlj

**Comment by mercyblitz** [comment]
@yiyiwangru 测试代码？

**Comment by yiyiwangru** [comment]
这是位于包com.mei.service.facade下面的服务类
@Service(validation = "true")
public class UserInfoServiceFacade implements UserInfoService {
	@Autowired
	private IUserInfoService userInfoService;
	
	...
}

这是扫描注解
<dubbo:annotation package="com.mei.service.facade"/>

这是在服务类上配置的一个切面
<bean class="com.mei.common.aspect.DubboServiceAspect" />

这样的情况下没办法发布服务 @mercyblitz @chickenlj

**Comment by chickenlj** [comment]
@yiyiwangru  你给出的代码还是老版本的使用方式，请参照[2.5.7新版本的使用方式](https://github.com/alibaba/dubbo/releases)

**Comment by yiyiwangru** [comment]
@chickenlj 具体要怎么使用呢？你给的链接里面的配置说明的链接打不开呢

**Comment by ralf0131** [comment]
Please check the latest official documentation: http://dubbo.apache.org/books/dubbo-user-book/configuration/annotation.html
