### ISSUE TITLE
Dubbo异常解析机制

### ISSUE THREAD

**Issue by DoubleSmile** [apache/incubator-dubbo#854]
Dubbo在异常解析的时候，例如A->B->C，C工程抛出了异常(RemoteException)最终在A工程的错误信息中显示，这样就导致A工程的开发以为是自己直接调用的服务出现了异常。
调用服务一旦多了之后这样很不利于排除，感觉可以优化一下将抛出异常的直接调用方带上工程的相关信息(applicationName等)

**Comment by banyeliangzhong** [comment]
可以对RemoteException改造一下，加上调用的服务，方法以及服务提供短的ip:port,并且对dubbo接收到异常处理这一块也做一下改造，通过java异常的cause by的方式，将下一层的异常包装到当前调用阶段的新的异常对象里面，然后再丢给上一层的消费者，这样在最上层的消费组就可以拿到整个异常链路，并且知道是哪个服务器以及那个服务哪个方法

**Comment by carryxyh** [comment]
I think this feature should be delegated to the APM framework. Dubbo itself should pay more attention to the remote call.

How do u think about it?

**Comment by carryxyh** [comment]
If no more feedback for this issue, we will close is soon.
:)

**Comment by zonghaishang** [comment]
If there is a problem, you can reopen it.
