### ISSUE TITLE
dubbo现在还会考虑对分布式事务的支持吗？

### ISSUE THREAD

**Issue by 1991wangliang** [apache/incubator-dubbo#858]

**Comment by shipengyan** [comment]
@1991wangliang 估计不会有，不然影响商业化的分布式事务了

**Comment by shipengyan** [comment]
表示期待

**Comment by 1991wangliang** [comment]
那我就自己推荐一个吧，https://github.com/codingapi/tx-lcn 开源的分布式事务框架

**Comment by chickenlj** [comment]
欢迎大家推荐一致性方案的开源实现，虽然目前我们没有计划去做具体实现的支持。
说不定我们可以做个汇总，最终将稳定、流行的实现纳入周边支持

**Comment by GuldanChen** [comment]
我也想参与dubbo的开发

**Comment by diecui1202** [comment]
@GuldanChen Welcome to Dubbo community. Refer this contributor guide: https://github.com/apache/incubator-dubbo/wiki/New-contributor-guide

Also, you can start from issues labeled with `good first issue` and `help wanted`. It's a good way to start, believe you and try it.
