### ISSUE TITLE
关于webservice context path的问题

### ISSUE THREAD

**Issue by Eakel** [apache/incubator-dubbo#86]
webservice/hessain加上context path和servlet匹配前缀的时候， 发布的地址与注册的地址不一致，具体情况如下：
webapp的contextpath 是app，protocol是webservice，server=servlet，在web.xm的 Servlet Bridge 配置如下：

```
<!-- Dubbo Servlet Bridge  -->
<servlet>
    <servlet-name>dubbo</servlet-name>
    <servlet-class>com.alibaba.dubbo.remoting.http.servlet.DispatcherServlet</servlet-class>
    <load-on-startup>1</load-on-startup>
</servlet>
<servlet-mapping>
    <servlet-name>dubbo</servlet-name>
    <url-pattern>/service/*</url-pattern>
</servlet-mapping>
```

发布后，webservice的地址：http://xxx.xxx.xxx.xxx:8080/app/service/xxxxService
而注册到注册中心的地址为：http://xxx.xxx.xxx.xxx:8080/xxxService

hessain发布也有类似的情况，也就是说，采用webservice/hessain的时候，context只能是ROOT，servlet只能匹配/*。这种情况与开始者的设计初衷是一致的吗？

**Comment by jumpbyte** [comment]
@Eakel 协议的上下文路径<dubbo:protocol contextpath="contextPath" />必须与servlet应用的上下文路径相同，你的protocol配置contextpath了吗

**Comment by diecui1202** [comment]
Long time no feedback, will close it. Feel free to reopen if necessary.
