### ISSUE TITLE
服务宕机问题？三个节点，同时间宕机，且当时服务请求并发量很小

### ISSUE THREAD

**Issue by keepongjl** [apache/incubator-dubbo#860]
具体看日志，上面的日志和dubbo的优雅关机日志一样。
公司内部多次出现这种情况
![image](https://user-images.githubusercontent.com/32863148/32831008-ee205a5c-ca31-11e7-9891-524a8201b1ea.png)
因为公司业务问题，所以将ip地址替换了，还望见谅

**Comment by keepongjl** [comment]
好多微服务都出现了这个问题，但是一直没有找到具体原因，三个节点同事宕机，日志和优雅关机一样，所以排除是人为的原因，当时考虑出现这种情况的原因有：
1、zk注册问题
2、system.exit()
3、ctrl+c关闭（脚本问题）
有没有遇见过同样的情况，望指点迷津，感谢

**Comment by rentian870423** [comment]
关注，同样的问题也出现过多次，并且每次的情况不同，不止楼主的服务器是否为 Linux服务器， Linux服务内存吃紧的情况下，会自动kill掉内存使用较高的进程。我这边第一次出现这个问题，感觉是这个导致的，后续几次目前还在排查。

**Comment by chickenlj** [comment]
> 关注，同样的问题也出现过多次，并且每次的情况不同，不止楼主的服务器是否为 Linux服务器， Linux服务内存吃紧的情况下，会自动kill掉内存使用较高的进程。我这边第一次出现这个问题，感觉是这个导致的，后续几次目前还在排查。

我认为这个问题还是应该从部署环境、业务逻辑上来排查，本身和dubbo相关的可能性相对较小。再比如排查GC、定期dump文件等。

**Comment by keepongjl** [comment]
忘了说了下，一般都是重启后一两天内宕机，如果没有发生宕机情况就不会再出现宕机情况，如果发生了宕机之后再重启的话，一般来说就不会再出现问题

**Comment by keepongjl** [comment]
@rentian870423 应该不是服务器内存吃紧，我们公司的服务器是suselinux，部署的是三台机器，应该不是内存吃急

**Comment by diecui1202** [comment]
Feel free to reopen if necessary.
