### ISSUE TITLE
2.5.7版本新特性

### ISSUE THREAD

**Issue by huzhongchun0918** [apache/incubator-dubbo#865]
请问2.5.7版本修复的注册中心缓存，泛化调用解析这个两个问题，具体是指什么问题呢？相关的代码修改在哪里？

**Comment by chickenlj** [comment]
#755 #685 
请参考下这两个issue，另外关于dubbo版本发布内容，可以通过跟踪milestone内容

**Comment by EdwardLee03** [comment]
@huzhongchun0918  https://github.com/alibaba/dubbo/milestone/5?closed=1
