### ISSUE TITLE
关于修复参数有泛型时类型转化出错的疑问

### ISSUE THREAD

**Issue by huzhongchun0918** [apache/incubator-dubbo#866]
https://github.com/alibaba/dubbo/pull/755
这个修复中加的代码，在什么样的情况下会调用？自己没能模拟出来，还请提供个例子，，

**Comment by chickenlj** [comment]
[generic provider](https://github.com/dubbo/dubbo-feature-test/blob/master/provider-test/src/main/resources/dubbo-generic.xml)
[generic consumer](https://github.com/dubbo/dubbo-feature-test/blob/master/consumer-test/src/main/resources/dubbo-generic.xml)

你把序列化协议改成fastjson，试一下看

**Comment by diecui1202** [comment]
Long time no feedback, will close it.
