### ISSUE TITLE
dubbo基于zookeeper注册服务的疑问

### ISSUE THREAD

**Issue by tongmintsai** [apache/incubator-dubbo#869]
场景描述如下：
1、采用zookeeper作为注册中心
2、服务提供者正常提供服务

操作如下：
1、通过连接zookeeper，删除掉服务提供者的目录
2、服务提供者就被这样干掉了，心跳检测机制也未能重新注册回服务

望解答这种如何处理

**Comment by tongmintsai** [comment]
dubbo版本2.5.3

**Comment by RayDuHarry** [comment]
单纯在服务端删掉服务提供者，不会触发自动注册。
需要重启zookeeper，触发zk客户端的Reconnect的事件才能进行恢复注册。

**Comment by tongmintsai** [comment]
:(，服务的注册列表无故被删除了，没法恢复了

**Comment by RayDuHarry** [comment]
只要应用没有重启过，zookeeper重启之后，dubbo收到zk客户端的Reconnect事件会自动进行恢复的。可以看看FailbackRegistry.java。我测试过重启zk之后会进行recover恢复。

**Comment by chickenlj** [comment]
> 操作如下：
> 1、通过连接zookeeper，删除掉服务提供者的目录
> 2、服务提供者就被这样干掉了，心跳检测机制也未能重新注册回服务

主动清空zookeeper这种场景，是不支持自动恢复的

**Comment by duguyixiaono1** [comment]
@chickenlj 我们服务也遇到过类似问题，网络抖动，zk重连，recover将registerurl添加到failedRegistered，retry重试，创建zk节点NodeExistsException（应该是这样），但是，之后zk节点无故丢失，服务全部不可用，有类似的问题吗？有什么建议？
