### ISSUE TITLE
在处理dubbo请求的线程中，如何随时获取请求的invocation信息

### ISSUE THREAD

**Issue by lastboy1228** [apache/incubator-dubbo#871]
一旦当前处理线程发起了一个dubbo子请求，之后当前线程用RpcContext.getContext()获取到的各种信息就变成了子请求的信息。
如果发生了injvm调用，原处理线程和子请求处理线程还是同一个线程。在这个线程处理主请求、子请求的不同阶段里，如何获取到恰当的invocation？

**Comment by zonghaishang** [comment]
1. 在发生子请求前，调用一次RpcContext.getContext()， 是父请求的invocation
2. 在子请求发生后，调用一次拿到RpcContext.getContext()，是子请求的invocation
3. 你自己保存一次到两个变量就OK了

**Comment by carryxyh** [comment]
@ralf0131 
NEED-CLOSE
