### ISSUE TITLE
JDK1.8下,对provider的方法重载支持是不是有Bug?

### ISSUE THREAD

**Issue by DreamL** [apache/incubator-dubbo#878]
不作为dubbo的provider是没有问题,具体代码和异常如下:
interface:
`boolean down(OutputStream os, Map<String, String> tfsNameAndFileName, String suffix)`
`boolean down(OutputStream os, List<String> tfsNames, String suffix) `

impl对以上2个接口提供任意实现,使用dubbo的@Service注解 项目启动时报以下异常:

**java.lang.RuntimeException: java.io.IOException: invalid constant type: 15**
` at javassist.bytecode.ConstPool.readOne(ConstPool.java:1023) ~[javassist-3.7.ga.jar:?]`

导致应用启动失败,然后再引起(以下不确定是否dubbo的问题):
`信息: Illegal access: this web application instance has been stopped already.  Could not load org.apache.mina.common.ExceptionMonitor.  The eventual following stack trace is caused by an error thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access, and has no functional impact.`

`java.lang.NoClassDefFoundError: org/apache/mina/common/ExceptionMonitor
Caused by: java.lang.ClassNotFoundException: org.apache.mina.common.ExceptionMonitor`

网上搜索有说升级javassist包,已尝试,未解决. 感谢关注.

**Comment by zonghaishang** [comment]
1. 应该是你使用的bubbo版本比较低吧 , 应为javassist依赖asm , 建议asm 升级到5.0.4, javassist 升级到 3.18.0 以上， 应该就OK了.
asm: http://mvnrepository.com/artifact/org.ow2.asm/asm
javassist: http://mvnrepository.com/artifact/org.javassist/javassist

**Comment by DreamL** [comment]
@zonghaishang 感谢回复,最近在忙其他的一直没来关注,不好意思.
刚才按您说的检查项目, 发现项目中未包含asm依赖,请问是哪里的依赖, 
我在javassist的pom中并未看到这个依赖配置. 另外javassist的版本是3.18.1
dubbo版本是本次重新维护前的最后一个版本:2.4.11

**Comment by ralf0131** [comment]
From your error log, I can see javassist version 3.7 is used, please make sure you are using latest javassist version.
