### ISSUE TITLE
docker中封装dubbo不能使用nc命令，请大神指点

### ISSUE THREAD

**Issue by yxstar** [apache/incubator-dubbo#879]
docker中封装dubbo不能使用nc命令监测dubbo状态，dubbo日志中也会一直报错。使用telnet命令可以。请问大神怎么解决啊？
如下：
# echo "status"|nc -i 1 127.0.0.1 29020  
Ncat: Idle timeout expired (1000 ms).

# telnet 127.0.0.1 29020 
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
dubbo>status
OK

**Comment by 356082462** [comment]
我们是加了一个等待时间解决的，观察服务端日志：服务端在发送响应时，客户端已经把连接关闭了。

**Comment by yxstar** [comment]
nc -i 参数吗？

**Comment by yxstar** [comment]
# echo "status"|nc -i 10 127.0.0.1 29103
Ncat: Idle timeout expired (10000 ms).
10秒还是不行

**Comment by 356082462** [comment]
echo "status",sleep 1 |nc -i 1 127.0.0.1 29020

**Comment by tnndwc** [comment]
试试：(echo "status";sleep 0.2;exit)|telnet IP PORT 2> /dev/null

**Comment by yxstar** [comment]
@tnndwc 谢谢大神
