### ISSUE TITLE
Zookeeper每隔10小时连接断开问题分析与解决

### ISSUE THREAD

**Issue by RayDuHarry** [apache/incubator-dubbo#886]
最近看到不少dubbo使用zookeeper作为注册中心，与注册中心的链接断开的案例。也发布一个案例与分析解决过程，希望对大家有所帮助。
   应用使用dubbo框架， Zookeeper作为服务注册中心，同时通过Dubbo中使用的Cxf组件对外提供WebService服务。    应用启动后，基本上每隔10个小时，都会出现与Zookeeper连接断开，服务重新注册；dubbo的服务提供者与服务消费者连接断开。最终发现罪魁祸首竟然是CXF。真相如何，请看分析报告。
   分析过程请见如下链接。
http://mp.weixin.qq.com/s?__biz=MzIwOTc1MzE4MQ==&mid=2247483678&idx=1&sn=a93b072d91c2b37cd556999a0142fde8&chksm=976e442ca019cd3a75cd4cb643189ca13789be02bff23b95e52e01b5dde2a1b904032db8f955#rd

**Comment by ralf0131** [comment]
Thanks for reporting, this issue is a CXF issue, so I am closing this ticket.
