### ISSUE TITLE
thrift://在策略成熟度里面没提及，可用于生产环境吗？

### ISSUE THREAD

**Issue by jialechan** [apache/incubator-dubbo#89]
thrift://在策略成熟度里面没提及，可用于生产环境吗？

想试试

**Comment by diecui1202** [comment]
We have provided a extension name 'native-thrift', check https://github.com/dubbo/dubbo-rpc-native-thrift for more infos.

I think it can be used online, @lovepoem Is that right?

Feel free to reopen it. &READY-TO-CLOSE&
