### ISSUE TITLE
SpringBoot配置Provider 并使用@com.alibaba.dubbo.config.annotation.Service配置服务，报错找不到application

### ISSUE THREAD

**Issue by xuyanzhuo** [apache/incubator-dubbo#892]
官方例子：
@com.alibaba.dubbo.config.annotation.Service(timeout = 5000, **application = "provider-test"**)
public class AnnotateServiceImpl implements AnnotateService {

    @Override
    public String sayHello() {
        return "Hello";
    }
}

@Configuration
// @ImportResource(locations = {"classpath:*.xml"}) //去掉xml,改用springboot的@bean方式配置
public class DubboConfiguration {

	@Bean
	public ApplicationConfig applicationConfig() {
		ApplicationConfig applicationConfig = new ApplicationConfig();
		applicationConfig.setName(**"provider-test"**);//application-name
		return applicationConfig;
	}
      //...........省略其他配置
}

@SpringBootApplication
@DubboComponentScan(basePackages = "com.alibaba.dubbo.test.service.impl")
public class ProviderTestApp { ///..省略此部分代码....}

启动报错如下：
2017-11-21 14:11:43.098  WARN 11844 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.alibaba.dubbo.config.spring.ServiceBean#0': Cannot resolve reference to bean 'provider-test' while setting bean property 'application'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'provider-test' available

问题：如果使用springboot的@Configuration来配置dubbo自身的属性导致使用@com.alibaba.dubbo.config.annotation.Service(timeout = 5000, **application = "provider-test"**)
中的application一直获取不到，报错~~~
求解答~~

**Comment by xuyanzhuo** [comment]
@chickenlj 求解答

**Comment by mercyblitz** [comment]
写法有问题
```
@Bean
public ApplicationConfig applicationConfig() {
	ApplicationConfig applicationConfig = new ApplicationConfig();
	applicationConfig.setName(**"provider-test"**);//application-name
	return applicationConfig;
}
```
 这个代码的 Bean 名称为“ applicationConfig”，
`@Service#application()` 指定的是Bean 名称，调整一下这个属性值为 “applicationConfig”

**Comment by chickenlj** [comment]
> 这个代码的 Bean 名称为“ applicationConfig”，
> @Service#application() 指定的是Bean 名称，调整一下这个属性值为 “applicationConfig”

@xuyanzhuo 如小马哥所说，要显示设置bean名称，而name属性是指当前应用名称
