### ISSUE TITLE
dubbo-admin各位有集群方案吗？

### ISSUE THREAD

**Issue by 356082462** [apache/incubator-dubbo#894]
在admin中有这么一段代码，而所有在admin中的大部分操作都是基于这段代码生成的ID进行操作的，如果要做admin的集群需要保证集群中的每个节点的ID值保存一致。

做admin集群这个是目前面临的最大问题，我想问问大家是怎么解决这个问题的。

代码：ids.put(ID.incrementAndGet(), url)

**Comment by takeseem** [comment]
我们只是通过nginx做了个保证admin挂一台还有另一台。不知道这个对这种方案有问题没

**Comment by 356082462** [comment]
@takeseem 如果直接用dubbo-admin。假设有A和B两个admin，你先访问的是A，从A拿到一个ID为100的服务，这个时候你要操作这个服务，但是这个时候A挂了，Nginx将你的请求转发给B，B因为之前没有登陆过，需要重新登陆，之后的操作步骤需要重新开始，这样看是没有问题的。但是浏览器中之前的页面没有关闭掉，继续操作的话，还是会有操作错服务的风险。
