### ISSUE TITLE
Does Dubbo have plan to support circuit breaker?

### ISSUE THREAD

**Issue by meiping05** [apache/incubator-dubbo#896]
比如整合Hystrix，以及Hystrix Dashboard

**Comment by mercyblitz** [comment]
这个会纳入考虑，不过Hystrix 并非最优的选择

**Comment by meiping05** [comment]
@mercyblitz 有其他熔断器可以推荐一下,目前正在整合这块

**Comment by takeseem** [comment]
同求

**Comment by maodie007** [comment]
先关注下，同样需求！

**Comment by jjqiubj** [comment]
同求

**Comment by stoneapple** [comment]
@mercyblitz 目前hystrix的熔断是直接将服务完全拒绝掉，有一种场景，如果服务提供方有一半是不可用的，这个时候如果真的设置了熔断，可能会造成这个服务的请求直接被拒绝掉了。有没有一种机制，能将熔断粒度细化到服务提供者维度，就是说如果某一个提供者一直报错，我把这个提供者熔断掉。

**Comment by Jaskey** [comment]
熔断简直太重要了，无论是服务级别熔断，还是实例级别熔断，都很重要。特别是后者，现在使用dubbo, 在RPC服务中一台provider机器慢下来，会拖垮整个consumer集群

**Comment by wannshan** [comment]
dubbo现在不是支持实例级别熔断吗？mock="return null"

**Comment by chickenlj** [comment]
Would you like to start a discussion on dev@dubbo.apache.org <mailto:dev@dubbo.apache.org> ? Just send your requirement of circuit break to this email, and i am sure that the community will have a discuss on it. And also, i am doing research on this feature recently, and I’d like you guys to start this discussion.

Best regards,
Jun Liu

**Comment by raduihys** [comment]
@wannshan 这个不是熔断，这个只是服务降级功能而已。

**Comment by wannshan** [comment]
@raduihys 不反对。不过熔断结果就是服务降级。

**Comment by wanhuhou** [comment]
我们开发了一个熔断器，只熔断有问题的机器

**Comment by wanhuhou** [comment]
配置在消费端，根据时间内错误率将机器从本地服务列表中移出，时间窗口检测，机器恢复正常，在放进去

**Comment by diecui1202** [comment]
@meiping05 Hope this article can help you. http://dubbo.apache.org/zh-cn/blog/dubbo-integrate-with-hystrix.html

Feel free to reopen.
