### ISSUE TITLE
LeastActiveLoadBalance负载均衡

### ISSUE THREAD

**Issue by wannshan** [apache/incubator-dubbo#904]
74行  int offsetWeight = random.nextInt(totalWeight);//这里totalWeight是没有经过warmup降权的值的和
78    offsetWeight -= getWeight(invokers.get(leastIndex), invocation);//这个是经过warmup降权的。

当服务刚启动，经过warmup降权后的getWeight返回的值，可能经过leastCount次循环后，还是offsetWeight >0
造成选不到invoker
for (int i = 0; i < leastCount; i++) {
                int leastIndex = leastIndexs[i];
                offsetWeight -= getWeight(invokers.get(leastIndex), invocation);
                if (offsetWeight <= 0)
                    return invokers.get(leastIndex);
}

**Comment by ralf0131** [comment]
Hi, could you please send a pull request?

**Comment by carryxyh** [comment]
If the offsetWeight doesn't decrease lower than 0 after loop, it maybe mean that all the least active invokers are in warmup, then the LeastActiveLoadBalance will select a random one from these same active invokers.
Or, continue to loop until the value of offsetWeight drops below 0?

**Comment by wannshan** [comment]
Change the line  
int weight = invoker.getUrl().getMethodParameter(invocation.getMethodName(), Constants.WEIGHT_KEY, Constants.DEFAULT_WEIGHT); // Weight
TO
int weight = getWeight(invoker, invocation); // have warm up  value

**Comment by wannshan** [comment]
may be  taotalWeightWithWarmUp   will be better ,after all not after  but warming....

**Comment by carryxyh** [comment]
That make sense.
Would u pls review this into my pr? And I will fix it soon.

**Comment by carryxyh** [comment]
Hi, I submit a new issue here:
https://github.com/apache/incubator-dubbo/issues/2540
Focus on this issue, pls.
