### ISSUE TITLE
Extension of  LoadBalance (a small suggestion for loadbalance policy when there's less than 2 providers)

### ISSUE THREAD

**Issue by smallh0a1n1d0s** [apache/incubator-dubbo#934]
暴露1个或者2个服务时,无法扩展到SPI->LoadBalance....能否将逻辑抽象到abstractLoadBalance，毕竟1个的默认选择，和2个的退化轮询也属于选择负载的方向，也能方便重写性扩展，有助于筛选参数和自定义筛选invokers。这样C端扩展点也将会更灵活

**Comment by chickenlj** [comment]
That's a good point, we'll discuss the feasibility

**Comment by ananas-hebo** [comment]
确实碰到了这样的问题。
在通过loadbalance做会话保持，当两个节点时，会话保持不了。

**Comment by smallh0a1n1d0s** [comment]
是的，因为没到扩展逻辑就返回了，是为替大众用户思考的呢，少一次代理负载的逻辑，但是对于freeStyle的小伙伴们受限了，让我们奔放吧

**Comment by diecui1202** [comment]
After discussing with @chickenlj , we decide to remove 140-142 lines, as the following shows: 

```java
private Invoker<T> doSelect(LoadBalance loadbalance, Invocation invocation, List<Invoker<T>> invokers, List<Invoker<T>> selected) throws RpcException {
        if (invokers == null || invokers.isEmpty())
            return null;
        if (invokers.size() == 1)
            return invokers.get(0);
        // If we only have two invokers, use round-robin instead.
        //if (invokers.size() == 2 && selected != null && !selected.isEmpty()) {
        //    return selected.get(0) == invokers.get(0) ? invokers.get(1) : invokers.get(0);
        //}
        if (loadbalance == null) {
            loadbalance = ExtensionLoader.getExtensionLoader(LoadBalance.class).getExtension(Constants.DEFAULT_LOADBALANCE);
        }
        Invoker<T> invoker = loadbalance.select(invokers, getUrl(), invocation);

        //If the `invoker` is in the  `selected` or invoker is unavailable && availablecheck is true, reselect.
        if ((selected != null && selected.contains(invoker))
```

Because the `selected` param is only not null when retry or in ForkingClusterInvoker. And the reselect function will finally select a avaliable invoker. 

So these 3 lines code seems unnecessary.

**Comment by diecui1202** [comment]
Since https://github.com/apache/incubator-dubbo/pull/1759 has been merged, so this issue can be closed.

**Comment by smallh0a1n1d0s** [comment]
@diecui1202  @chickenlj Pretty Good,But the only  one invoker exists ,and  we  also can't  expand  our  intentions.

**Comment by diecui1202** [comment]
Could you tell us the scenario that need to expand when only 1 invoker exists.

**Comment by smallh0a1n1d0s** [comment]
Assuming that the three normal services can maintain the business, notify the container platform to rebuild the service or notify the alarm platform when the payload encounters only one or no invoker alive
