### ISSUE TITLE
dubbo启动脚本中nc命令不稳定

### ISSUE THREAD

**Issue by ycfang** [apache/incubator-dubbo#936]
启动脚本的nc命令不稳定，经常无法获取dubbo的状态，使用telnet的成功率会更高
COUNT=`(sleep 1;echo "^M";sleep 1;echo status;sleep 1)|telnet 127.0.0.1 $SERVER_PORT | grep -c OK`

**Comment by Loveless070** [comment]
这个想法不错,,,,,,另外我想问你一些事情,,,那个启动脚本中,,有些地方 用的 ps -f ,,有些地方用的 ps -ef ,,,,,,,那些 ps -f 命令有什么意义吗,,,,比如 ps -f | grep java | grep -v grep | grep "$DEPLOY_DIR" | awk '{print $2}' | wc -l 
我试了几次 这个命令 并不能获取什么 东西,,,,ps -ef 可以

**Comment by diecui1202** [comment]
@ycfang @Loveless070 Could you fix this and start a PR ?
