### ISSUE TITLE
AbstractClient reconnect() should be synchronized under concurrency scene

### ISSUE THREAD

**Issue by chenliuyang1989** [apache/incubator-dubbo#944]
高并发重连出错，需要加锁，
eg：线程1关闭原有连接，重建连接
        并发线程2会关闭线程1新建的连接，重接新的连接。导致线程1发送数据失败
        并发线程3又会关闭线程2新建立的连接，重建新的连接，导致线程2发送数据失败。
问题：高并发重连时不加锁会出现频繁的连接关闭重建，

线上出错日志见附件
![default](https://user-images.githubusercontent.com/4150132/33326002-b4ee8f62-d48e-11e7-8b0b-70d7efa6c0db.jpg)

**Comment by chenliuyang1989** [comment]
This is my ReImplementation of reconnect method ：
   public void reconnect() throws RemotingException {
        this.reConnectLock.lock();

        try {
            if(!this.isConnected()) {
                this.disconnect();
                this.resetConnectStatus();
                this.connect();
                return;
            }
        } finally {
            this.reConnectLock.unlock();
        }

    }

**Comment by chenliuyang1989** [comment]
do you have plan when to fix the bug?

**Comment by ralf0131** [comment]
Hi, would you mind send a pull request?

**Comment by zonghaishang** [comment]
fixed, refer: https://github.com/apache/incubator-dubbo/pull/2135

**Comment by zonghaishang** [comment]
@chenliuyang1989  Which version of dubbo you use?
