### ISSUE TITLE
dubbo admin动态配置项启用后无法删除

### ISSUE THREAD

**Issue by lichenglingl** [apache/incubator-dubbo#98]
dubbo版本：2.5.4，注册中心为zookeeper 3.4.6
步骤 1.在admin中新增一个动态配置项sayHello.timeout=3500，默认状态为已禁用。
        2. 启用上述动态配置项，返回成功，且状态更新为启用。
        3. 删除上述动态配置项，返回成功，但是上述动态配置项依旧存在。

查看zookeeper数据发现上述动态配置项为
override%3A%2F%2F0.0.0.0%2Fcom.alibaba.dubbo.demo.DemoService%3Fcategory%3Dconfigurators%26dynamic%3Dfalse%26sayHello.timeout%3D3500
解码后为
override://0.0.0.0/com.alibaba.dubbo.demo.DemoService?category=configurators&dynamic=false&sayHello.timeout=3500

查看admin日志，发现删除的记录为Unregister: 
override://0.0.0.0/com.alibaba.dubbo.demo.DemoService?category=configurators&dynamic=false&enabled=true&sayHello.timeout=3500

其中存在&enabled=true的差异，导致上述动态配置项删除不掉。

**Comment by jack161641** [comment]
这个适用于版本更新后的新建的动态配置项的删除，如在版本更新前动态配置已存在于zookeeper中，需要手工清理zookeeper配置项

**Comment by nzomkxia** [comment]
目前新版本的dubbo ops已经具备此项功能，请试一下是否还存在这个问题：https://github.com/apache/incubator-dubbo-ops
