### ISSUE TITLE
Users and developers around the world are using or contributing to dubbo, we are trying to make here a pure english community 

### ISSUE THREAD

**Issue by chickenlj** [apache/incubator-dubbo#981]
Recently, we have received issues & suggests from users/developers around the world , and this makes us very exciting and inspiring. To communicate without barriers, i think we should try making  here a pure English community. 

Whenever you have an issue or create pull request, try using english. It really doesn't matter 
whether your issue have a grammatical mistake or a misspell, we only thank you for your report 
and contribution.

And also, we may have translated the title or content of recent issues, please don't mind.

**Comment by beiwei30** [comment]
+1

**Comment by ralf0131** [comment]
+1

**Comment by ralf0131** [comment]
The release notes should also be globalized. https://github.com/alibaba/dubbo/releases

**Comment by chickenlj** [comment]
@ralf0131  Got it. I'll translate the release notes soon.

**Comment by diecui1202** [comment]
strongly recommend

**Comment by tuser4198** [comment]
+1

**Comment by cpyong** [comment]
+1

**Comment by DeadLion** [comment]
cool

**Comment by ralf0131** [comment]
Is there a feature that we can PIN this issue to the top of the issues?

**Comment by stoneapple** [comment]
good idea
