### ISSUE TITLE
support consul on 2.7

### ISSUE THREAD

**Issue by xiakun1201** [apache/incubator-dubbo#983]
ZK cluster is too heavy，i strongly recommend consul after trying it，i think dubbo should support consul.

**Comment by chickenlj** [comment]
@MrXiaKun We recommend use english, so everyone can get involved.

**Comment by chickenlj** [comment]
What do you exactly mean by too heavy? 
As far as i know, these two solutions both based on strong consistency protocol. Consul made a specifically abstraction for Service Discovery(which means we can do less work when using consul as Service Registry),  but do these changes makes any performance difference?

**Comment by kirbylynx** [comment]
I guess consul has higher availability performance than zookeeper.

**Comment by takeseem** [comment]
我认为他的意思是用zk来开发太难了。

- zk实际本身对资源的消耗是非常少的，无论是客户端还是服务器

I gues zookeeper too heavy, he meant to use zookeeper to develop too hard.
- zk actual consumption of resources is very small, whether it is client or server

**Comment by mthhk** [comment]
这个is为什么关闭了呢？
对于一些有consul，但是无zk的场景，想用dubbo就有些难受。

**Comment by byronzoz** [comment]
建议把consul支持起来

**Comment by xiangkaiy** [comment]
Does dubbo support consul now?

**Comment by ettingshausen** [comment]
> Does dubbo support consul now?  

@xiangkaiy
https://github.com/apache/dubbo-samples/tree/master/java/dubbo-samples-consul
